Repository apache/trafficserver, pull requests merged in 2018-10, with the labels that each got.

#4339 Fix a TM crash on alarms
  lib/records/I_RecCore.h
Labels: Manager

#4341 clang-format
  proxy/http/HttpTransact.cc
Labels: Cleanup

#4330 Fix build for arm architecture on Debian
  src/traffic_ctl/Makefile.inc
  src/traffic_top/Makefile.inc
Labels: Build

#4329 Fix build for mips64el architecture on Debian
  include/tscore/ink_queue.h
Labels: Build

#4340 Fixes spelling in spec summary
  tools/package/trafficserver.spec
Labels: Cleanup

#4327 Fix build for kfreebsd architecture on Debian
  proxy/Plugin.cc
  proxy/http/remap/RemapConfig.cc
  src/tscore/ink_memory.cc
Labels: Build

#4342 Update the include dir paths for new layout
  .vscode/c_cpp_properties.json
Labels: Tools

#4350 Fix for ASAN buffer overrun for IpMap::contains in HttpTransact::OSDNSLookup
  proxy/http/HttpTransact.cc
Labels: Cleanup

#4352 client_bytes should be initialized as 0
  src/traffic_server/FetchSM.h
Labels: TS API

#4360 Fix mysql_remap plugin build with MySQL 8
  plugins/experimental/mysql_remap/mysql_remap.cc
Labels: Plugins

#4364 Added debugging information on parent proxy
  proxy/http/HttpTransact.cc
Labels: Parent Proxy

#4363 CMake: Add lib/records, unit_tests.
  CMakeLists.txt
Labels: Cleanup

#4309 Orders k-v pairs to avoid making too many files
  tests/gold_tests/redirect/redirect_actions.test.py
Labels: Cleanup, Tests

#4359 Set log code when closing half open connections.
  proxy/http/HttpSM.cc
Labels: Logging

#4367 s3_auth_v4: update default region map
  plugins/s3_auth/aws_auth_v4.cc
Labels: Plugins

#4312 Disable the HttpSM half open logic if the underlying transport is TLS
  proxy/http/Http1ClientSession.h
  proxy/http/Http1ClientTransaction.cc
  proxy/http/Http1ClientTransaction.h
Labels: Backport

#4319 Fix another ProxySession and NetVC shutdown race crash
  proxy/ProxyClientSession.cc
  proxy/http/Http1ClientSession.cc
Labels: Backport

#4299 Inherit parent config file root-required attribute
  mgmt/FileManager.cc
  mgmt/Rollback.h
Labels: Configuration

#4368 s3_auth_v4: update default region map
  plugins/s3_auth/aws_auth_v4.cc
Labels: Plugins

#4355 make the lua context static for parsing logging.config
  proxy/logging/LogConfig.cc
Labels: Logging, Lua

#4316 Reset the inactivity timeout to the transaction timeout…
  proxy/http/HttpSM.cc
Labels: Backport

#4313 HTTP/2 priority fixes to match common browser patterns
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2DependencyTree.h
  proxy/http2/test_Http2DependencyTree.cc
Labels: Backport

#4371 Fix a TM crash on alarms
  lib/records/I_RecCore.h
Labels: Manager

#4337 Fix Segmentation fault in ShowCache::handleCacheEvent #4328
  iocore/cache/CachePages.cc
Labels: Cache

#4369 Doc: Fix doc build to work with Sphinx 1.8.
  doc/Makefile.am
  doc/ext/local-config.py.in
  doc/ext/plantuml_fetch.sh
  doc/ext/traffic-server.py
  doc/uml/Makefile.am
Labels: Documentation

#4343 ArgParser: enable default command and help message update
  doc/developer-guide/internal-libraries/ArgParser.en.rst
  include/tscore/ArgParser.h
  src/traffic_layout/traffic_layout.cc
  src/tscore/ArgParser.cc
Labels: Core

#4242 header_rewrite: Adds basic string concatenation
  doc/admin-guide/plugins/header_rewrite.en.rst
  plugins/header_rewrite/Examples/Geo
  plugins/header_rewrite/Makefile.inc
  plugins/header_rewrite/condition.h
  plugins/header_rewrite/conditions.cc
  plugins/header_rewrite/conditions.h
  plugins/header_rewrite/factory.cc
  plugins/header_rewrite/header_rewrite.cc
  plugins/header_rewrite/header_rewrite_test.cc
  plugins/header_rewrite/parser.cc
  plugins/header_rewrite/parser.h
  plugins/header_rewrite/value.cc
  plugins/header_rewrite/value.h
Labels: Plugins

#4314 Remove the ignore_keep_alive method entirely
  proxy/ProxyClientTransaction.h
  proxy/http/Http1ClientTransaction.h
  proxy/http/HttpTransact.cc
  proxy/http2/Http2Stream.h
Labels: Backport

#4373 Cache: update internal counters to be std::atomic.
  iocore/cache/Cache.cc
  iocore/cache/CacheHosting.cc
  iocore/cache/CachePagesInternal.cc
  iocore/cache/P_CacheVol.h
Labels: Cache

#4374 TCL: remove TCL dependency from RecHttp
  lib/records/RecHttp.cc
Labels: Cleanup, Core

#4380 Fix lost pending_actions causing actions on stale objects.
  iocore/net/P_UnixNetVConnection.h
  proxy/http/HttpSM.cc
Labels: Crash

#4040 Add configs for groups list
  doc/admin-guide/files/records.config.en.rst
  iocore/net/P_SSLConfig.h
  iocore/net/SSLClientUtils.cc
  iocore/net/SSLConfig.cc
  iocore/net/SSLUtils.cc
  mgmt/RecordsConfig.cc
Labels: TLS

#4308 remap.config .include files trigger reloads
  proxy/http/remap/RemapConfig.cc
  proxy/http/remap/RemapConfig.h
  src/traffic_server/traffic_server.cc
Labels: Configuration

#4381 Add details for documentation for hook addition functions.
  doc/developer-guide/api/functions/TSHttpHookAdd.en.rst
Labels: Documentation

#4366 Docs: Remove the EXTERNAL_TYPES logic
  doc/conf.py
  doc/ext/traffic-server.py
Labels: Cleanup, Documentation

#4386 docs: reference to overridable config not parsed
  doc/admin-guide/plugins/regex_remap.en.rst
Labels: Documentation

#4358 client_bytes should be initialized as 0, it is exclusevely used by ge…
  src/traffic_server/FetchSM.h
Labels: TS API

#4306 Convert traffic_cache_tool to use ArgParser
  src/traffic_cache_tool/CacheDefs.h
  src/traffic_cache_tool/CacheTool.cc
  src/traffic_cache_tool/Command.cc
  src/traffic_cache_tool/Command.h
  src/traffic_cache_tool/Makefile.inc
Labels: Cache, Commands

#4393 Removes reference to non-existent example
  include/tscpp/api/Url.h
Labels: Cleanup

#4395 Cleanup: Remove MgmtHashTable.h
  mgmt/utils/Makefile.am
  mgmt/utils/MgmtHashTable.h
Labels: Cleanup

#4351 Add some feeble amount of encapsulation to the Thread class.
  iocore/eventsystem/I_Thread.h
Labels: Core

#4389 Rename stats for HTTP/2 current client connections
  proxy/http2/HTTP2.cc
Labels: HTTP/2, Metrics

#4387 Replace the overridable lookup with an unordered_map
  src/traffic_server/InkAPI.cc
Labels: TS API

#4396 Allows unknown configuration variables when specified on the commandline
  plugins/conf_remap/conf_remap.cc
Labels: Plugins

#4401 Removes errant mid-sentence extra space from message
  configs/body_factory/default/response#bad_response
Labels: Cleanup

#4404 Doc: Repair various warnings, mostly from header_rewrite and ArgParser.
  doc/admin-guide/plugins/header_rewrite.en.rst
  doc/conf.py
  doc/developer-guide/internal-libraries/ArgParser.en.rst
Labels: Documentation

#4376 Ats magick
  configure.ac
  plugins/Makefile.am
  plugins/experimental/magick/Makefile.inc
  plugins/experimental/magick/README
  plugins/experimental/magick/keys/rsa256-private.key
  plugins/experimental/magick/keys/rsa256-public.key
  plugins/experimental/magick/magick.cc
  plugins/experimental/magick/sign.sh
  plugins/experimental/magick/test.sh
  plugins/experimental/magick/ts.png
  plugins/experimental/magick/verify.sh
Labels: Plugins

#4407 Fix traffic_via problem with string length
  src/traffic_via/tests/[u c s f p eS;tNc  p s ]
  src/traffic_via/tests/[uIcRs f p eN;t cCHp s ]
  src/traffic_via/tests/[uIcRs f p eN;t cCNp s ]
  src/traffic_via/tests/[uScMsSf pSeN;t cCMp sS]
  src/traffic_via/tests/[uScRs f p eN;t cCHp s ]
  src/traffic_via/tests/long rubbish via code2
  src/traffic_via/tests/rubbish
  src/traffic_via/traffic_via.cc
Labels: Commands

#4357 TCL: Remove TCL dependency from iocore
  iocore/net/SSLCertLookup.cc
  iocore/utils/I_Machine.h
  iocore/utils/Machine.cc
Labels: Core

#4383 TCL: Remove TCL dependency from RecCore
  lib/records/P_RecCore.cc
  lib/records/P_RecCore.h
  lib/records/RecConfigParse.cc
  lib/records/RecCore.cc
  lib/records/RecRawStats.cc
Labels: Cleanup

#4397 Remove deprecated HTTP/2 metrics
  proxy/http2/HTTP2.cc
Labels: HTTP/2, Incompatible, Metrics

#4399 QUIC Read new session ticket msg and send it back
  iocore/net/quic/QUICTLS.h
  iocore/net/quic/QUICTLS_boringssl.cc
  iocore/net/quic/QUICTLS_openssl.cc
  iocore/net/quic/test/test_QUICHandshakeProtocol.cc
Labels: QUIC

#4405 QUIC Client session reused with new session ticket msg
  iocore/net/quic/QUICConfig.cc
  iocore/net/quic/QUICConfig.h
  iocore/net/quic/QUICGlobals.cc
  iocore/net/quic/QUICGlobals.h
  iocore/net/quic/QUICTLS.h
  iocore/net/quic/QUICTLS_openssl.cc
  mgmt/RecordsConfig.cc
Labels: QUIC, TLS

#4354 Fix logging log file roll issue (#2544).
  proxy/logging/LogFile.cc
Labels: Logging

#4289 Do not follow redirects after cache hit
  doc/admin-guide/files/records.config.en.rst
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
Labels: Cache, HTTP

#4406 ts_file: Add 'view' method to get a view of the path.
  include/tscore/ts_file.h
Labels: Cleanup, Core

#4384 Fix gzip(compress) plugin not linked correctly with zlib
  plugins/compress/Makefile.inc
Labels: Build

#4408 QUIC: Changes QUICErrorUPtr to QUICConnectionUPtr to terminate the connection
  iocore/net/P_QUICNetVConnection.h
  iocore/net/QUICNetVConnection.cc
  iocore/net/quic/QUICDebugNames.cc
  iocore/net/quic/QUICFrameDispatcher.cc
  iocore/net/quic/QUICFrameDispatcher.h
  iocore/net/quic/QUICFrameHandler.h
  iocore/net/quic/QUICHandshake.cc
  iocore/net/quic/QUICHandshake.h
  iocore/net/quic/QUICIncomingFrameBuffer.cc
  iocore/net/quic/QUICIncomingFrameBuffer.h
  iocore/net/quic/QUICLossDetector.cc
  iocore/net/quic/QUICLossDetector.h
  iocore/net/quic/QUICPathValidator.cc
  iocore/net/quic/QUICPathValidator.h
  iocore/net/quic/QUICStream.cc
  iocore/net/quic/QUICStream.h
  iocore/net/quic/QUICStreamManager.cc
  iocore/net/quic/QUICStreamManager.h
  iocore/net/quic/QUICTypes.h
  src/traffic_quic/quic_client.cc
Labels: QUIC

#4394 TCL: Remove TCL dependency from Alarms
  mgmt/Alarms.cc
  mgmt/Alarms.h
  mgmt/api/CoreAPI.cc
Labels: Cleanup

#4412 Cachekey plugin doc minor typos fixed.
  doc/admin-guide/plugins/cachekey.en.rst
Labels: Documentation, Plugins

#4420 Removes this unused old/duplicated define
  include/tscore/Diags.h
Labels: Cleanup, Logging

#4392 Update logic to watch config files even if they are not default
  mgmt/FileManager.cc
  mgmt/FileManager.h
  mgmt/Rollback.cc
  mgmt/Rollback.h
  src/traffic_manager/AddConfigFilesHere.cc
  src/traffic_manager/traffic_manager.cc
Labels: Configuration

#4403 TCL: Remove TCL dependency from TSControl and EventControl
  mgmt/api/EventControlMain.cc
  mgmt/api/EventControlMain.h
  mgmt/api/TSControlMain.cc
Labels: Cleanup, Manager

#4422 TCL: Rmove TCL dependency from HostStatus
  proxy/HostStatus.h
  src/traffic_server/HostStatus.cc
Labels: Cleanup, Core

#4426 YAML: Move ts_meta to external C++ library.
  include/tscpp/util/ts_meta.h
  src/tscore/Makefile.am
  src/tscpp/util/Makefile.am
  src/tscpp/util/unit_tests/test_ts_meta.cc
Labels: Core

#4419 QUIC: Ignore empty msg when handshake success
  iocore/net/quic/QUICTLS_openssl.cc
Labels: QUIC

#4431 TCL: All ink_hash_table in proxy converted to use STL
  proxy/ControlMatcher.cc
  proxy/ControlMatcher.h
  proxy/InkAPIInternal.h
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ClientSession.h
  src/traffic_server/InkAPI.cc
Labels: Cleanup, Core

#4433 YAML: LibSWOC upgrade for TextView.
  include/tscpp/util/TextView.h
  src/tscpp/util/unit_tests/test_TextView.cc
Labels: Core

#4429 Fix build for 32bits armhf arch. Partialy closes #4361
  include/tscore/ink_atomic.h
  src/traffic_cache_tool/Makefile.inc
Labels: Build

#4413 TCL: Remove TCL depedency from mgmt
  mgmt/BaseManager.cc
  mgmt/BaseManager.h
  mgmt/FileManager.cc
  mgmt/FileManager.h
  mgmt/WebMgmtUtils.cc
  mgmt/WebMgmtUtils.h
Labels: Cleanup, Core

#4430 TCL: Rmove TCL dependency from UrlRewrite
  proxy/ReverseProxy.h
  proxy/http/remap/UrlRewrite.cc
  proxy/http/remap/UrlRewrite.h
Labels: Cleanup, Core

#4344 Add test for ticket reuse with proxy.config.ssl.server.ticket_key.filename
  tests/bootstrap.py
  tests/gold_tests/autest-site/init.cli.ext
  tests/gold_tests/autest-site/trafficserver.test.ext
  tests/gold_tests/tls/file.ticket
  tests/gold_tests/tls/tls_ticket.test.py
Labels: Tests

#4385 Update documentation for SSL VERIFY hooks.
  doc/developer-guide/api/types/TSHttpHookID.en.rst
  doc/developer-guide/plugins/hooks-and-transactions/ssl-hooks.en.rst
  include/ts/apidefs.h.in
  iocore/net/SSLClientUtils.cc
  iocore/net/SSLNetVConnection.cc
  proxy/InkAPIInternal.h
  proxy/http/HttpDebugNames.cc
  src/traffic_server/InkAPITest.cc
Labels: Cleanup, Documentation

#4438 QUIC: Add write_early_data to generate 0rtt km
  iocore/net/quic/QUICTLS.h
  iocore/net/quic/QUICTLS_openssl.cc
Labels: QUIC

#4447 Fixes memory leak in header_rewrite when GeoIP is used
  plugins/header_rewrite/header_rewrite.cc
Labels: Bug

#4441 Corrects the wording of the usage messages for traffic_ctl host subcommand
  src/traffic_ctl/host.cc
Labels: Commands

#4448 YAML: TextView upgrade revisited.
  src/tscpp/util/TextView.cc
Labels: Core

#4449 YAML: Inline BufferWriter formatting functions.
  include/tscore/CryptoHash.h
  proxy/http/HttpConnectionCount.cc
  proxy/http/HttpConnectionCount.h
  proxy/http/HttpDebugNames.cc
  proxy/http/HttpDebugNames.h
  src/tscore/CryptoHash.cc
Labels: Core

#4414 Cleaning up TLS server verify options
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/files/ssl_server_name.yaml.en.rst
  doc/admin-guide/security/index.en.rst
  doc/developer-guide/api/functions/TSVConnReenable.en.rst
  doc/developer-guide/plugins/example-plugins/tls_bridge.en.rst
  iocore/net/I_NetVConnection.h
  iocore/net/P_SSLConfig.h
  iocore/net/P_SSLNetVConnection.h
  iocore/net/P_SSLSNI.h
  iocore/net/SSLClientUtils.cc
  iocore/net/SSLConfig.cc
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLSNIConfig.cc
  iocore/net/SSLUtils.cc
  iocore/net/YamlSNIConfig.cc
  iocore/net/YamlSNIConfig.h
  mgmt/RecordsConfig.cc
  src/traffic_server/InkAPI.cc
  tests/gold_tests/tls/ssl/signed-bar.key
  tests/gold_tests/tls/ssl/signed-bar.pem
  tests/gold_tests/tls/ssl/signed-foo.key
  tests/gold_tests/tls/ssl/signed-foo.pem
  tests/gold_tests/tls/ssl/signer.key
  tests/gold_tests/tls/ssl/signer.pem
  tests/gold_tests/tls/tls_verify.test.py
  tests/gold_tests/tls/tls_verify2.test.py
Labels: Configuration, Documentation, Tests

#4285 Change atscppapi::TransformationPlugin to use atscppapi::Continuation instead of TSCont.
  example/cppapi/delay_transformation_plugin/DelayTransformationPlugin.cc
  include/tscpp/api/TransformationPlugin.h
  src/tscpp/api/TransformationPlugin.cc
Labels: CPP API

#4451 Fixes leak when no OCSP URL is available
  iocore/net/OCSPStapling.cc
Labels: Bug

#4445 Converts loop and callees in SSLInitServerContext to std::string
  iocore/net/SSLUtils.cc
Labels: Bug, OnDocs

#4424 YAML: LibSWOC IntrusiveDList update.
  doc/developer-guide/internal-libraries/intrusive-list.en.rst
  include/tscore/IntrusiveHashMap.h
  include/tscore/IpMap.h
  include/tscpp/util/IntrusiveDList.h
  include/tscpp/util/Makefile.am
  src/tscore/IntrusivePtrTest.cc
  src/tscore/IpMap.cc
  src/tscore/Makefile.am
  src/tscpp/util/Makefile.am
  src/tscpp/util/unit_tests/test_IntrusiveDList.cc
Labels: Core, OnDocs

#3693 register stats in traffic_server if running in standalone mode
  src/traffic_server/traffic_server.cc
Labels: Manager, Metrics

#4444 Uses stack-based buffer for record lookup during logging
  proxy/logging/LogAccess.cc
Labels: Bug, OnDocs

#4465 Fixes memory leaks in compress plugin
  plugins/compress/compress.cc
Labels: Bug

#4388 Split current active client connections stats into HTTP/1.1 and HTTP/2
  doc/admin-guide/monitoring/statistics/core/http-connection.en.rst
  proxy/ProxyClientSession.cc
  proxy/ProxyClientSession.h
  proxy/http/Http1ClientSession.cc
  proxy/http/Http1ClientSession.h
  proxy/http2/HTTP2.cc
  proxy/http2/HTTP2.h
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ClientSession.h
Labels: HTTP, HTTP/2, Metrics

#4475 Add test for ticket reuse with proxy.config.ssl.server.ticket_key.fil…
  tests/bootstrap.py
  tests/gold_tests/autest-site/init.cli.ext
  tests/gold_tests/autest-site/trafficserver.test.ext
  tests/gold_tests/tls/file.ticket
  tests/gold_tests/tls/tls_ticket.test.py
Labels: Tests

#4474 clang-format
  proxy/http2/HTTP2.cc
Labels: Cleanup

#4476 heap use after free
  proxy/http/HttpTransact.cc
Labels: Backport, Crash

#4452 Fix leak in stapling_refresh_response
  iocore/net/OCSPStapling.cc
Labels: Bug

#4421 TCL: Remove TCL dependency from proxy/logging
  proxy/logging/Log.cc
  proxy/logging/Log.h
  proxy/logging/LogField.cc
Labels: Cleanup, Logging, OnDocs

#4461 Fixes memory leaks in header_rewrite
  plugins/header_rewrite/condition.h
  plugins/header_rewrite/header_rewrite.cc
  plugins/header_rewrite/ruleset.cc
  plugins/header_rewrite/ruleset.h
  plugins/header_rewrite/statement.h
  plugins/header_rewrite/value.cc
  plugins/header_rewrite/value.h
Labels: Bug

#4464 Fixes more leaks when no OCSP URL is available
  iocore/net/OCSPStapling.cc
Labels: Bug

#4478 Do not attempt clang-analyzer builds on 7.1.x branch
  .clang-analyzer
  ci/jenkins/bin/clang-analyzer.sh
Labels: CI

#4482 Fix leak in stapling_refresh_response
  iocore/net/OCSPStapling.cc
Labels: Backport

#4483 Fixes more leaks when no OCSP URL is available
  iocore/net/OCSPStapling.cc
Labels: Backport

#4485 Fixes memory leaks in header_rewrite
  plugins/header_rewrite/condition.h
  plugins/header_rewrite/header_rewrite.cc
  plugins/header_rewrite/ruleset.cc
  plugins/header_rewrite/ruleset.h
  plugins/header_rewrite/statement.h
  plugins/header_rewrite/value.h
Labels: Backport

#4484 Fixes memory leaks in header_rewrite
  plugins/header_rewrite/condition.h
  plugins/header_rewrite/header_rewrite.cc
  plugins/header_rewrite/ruleset.cc
  plugins/header_rewrite/ruleset.h
  plugins/header_rewrite/statement.h
  plugins/header_rewrite/value.h
Labels: Backport

#3749 ats_fastcgi experimental plugin
  ci/rat-regex.txt
  plugins/experimental/fastcgi/README.md
  plugins/experimental/fastcgi/src/Makefile
  plugins/experimental/fastcgi/src/Profiler.h
  plugins/experimental/fastcgi/src/Readme
  plugins/experimental/fastcgi/src/ats_fastcgi.cc
  plugins/experimental/fastcgi/src/ats_fastcgi.h
  plugins/experimental/fastcgi/src/ats_fcgi_client.cc
  plugins/experimental/fastcgi/src/ats_fcgi_client.h
  plugins/experimental/fastcgi/src/bin/php-fastcgi.sh
  plugins/experimental/fastcgi/src/config/ats_mod_fcgi.config
  plugins/experimental/fastcgi/src/config/fastcgi.config
  plugins/experimental/fastcgi/src/configuru.hpp
  plugins/experimental/fastcgi/src/connection_pool.cc
  plugins/experimental/fastcgi/src/connection_pool.h
  plugins/experimental/fastcgi/src/fcgi_config.cc
  plugins/experimental/fastcgi/src/fcgi_config.h
  plugins/experimental/fastcgi/src/fcgi_protocol.h
  plugins/experimental/fastcgi/src/request_queue.cc
  plugins/experimental/fastcgi/src/request_queue.h
  plugins/experimental/fastcgi/src/server.cc
  plugins/experimental/fastcgi/src/server.h
  plugins/experimental/fastcgi/src/server_connection.cc
  plugins/experimental/fastcgi/src/server_connection.h
  plugins/experimental/fastcgi/src/server_intercept.cc
  plugins/experimental/fastcgi/src/server_intercept.h
Labels: Plugins

#4455 allow regex_revalidate per remap rule, remove direct ink includes
  doc/admin-guide/plugins/regex_revalidate.en.rst
  plugins/regex_revalidate/regex_revalidate.c
Labels: Core

#4497 Fix chained server cert verify
  iocore/net/SSLClientUtils.cc
  mgmt/RecordsConfig.cc
  tests/gold_tests/tls/tls_verify.test.py
  tests/gold_tests/tls/tls_verify2.test.py
Labels: TLS, Tests

#4502 Fix for #4413 - avoid ASAN crash on use after free for file name.
  mgmt/FileManager.cc
Labels: Bug

#4498 Fixes plugin builds using tsxs on MacOS
  tools/tsxs.in
Labels: Backport

#4503 Reverting fadddccd53c4e8f41553fef6ca0630f0124ed4a0 and fixing up b6f4227fe3f4b9ce344f159ac505258228fa8aeb
  iocore/net/I_NetProcessor.h
  iocore/net/P_SSLNetVConnection.h
  iocore/net/P_UnixNetVConnection.h
  iocore/net/UnixNetProcessor.cc
  iocore/net/UnixNetVConnection.cc
  proxy/http/HttpSM.cc
Labels: Cleanup

#4189 Plugins: Cleanup up dependencies on core headers - background_fetch
  plugins/background_fetch/background_fetch.cc
  plugins/background_fetch/configs.cc
  plugins/background_fetch/configs.h
  plugins/background_fetch/rules.cc
Labels: Cleanup, Plugins

#4499 Small doc typo fix
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#4507 Handle inactivity timeout event in state_http_server_open
  proxy/http/HttpSM.cc
Labels: Crash

#4427 Add vconn reenable event
  doc/developer-guide/api/functions/TSVConnReenable.en.rst
  doc/developer-guide/plugins/hooks-and-transactions/index.en.rst
  doc/developer-guide/plugins/hooks-and-transactions/ssl-hooks.en.rst
  include/ts/ts.h
  iocore/net/SSLNetVConnection.cc
  src/traffic_server/InkAPI.cc
  tests/gold_tests/tls/tls_hooks_verify.test.py
  tests/tools/plugins/ssl_verify_test.cc
Labels: Documentation, Plugins, TLS, TS API, Tests

#4512 Use references for indexes of range-based for loops when this avoids expensive copies.
  iocore/net/P_SSLUtils.h
  iocore/net/SSLSNIConfig.cc
  plugins/experimental/fastcgi/src/ats_fastcgi.cc
  plugins/experimental/fastcgi/src/ats_fcgi_client.cc
  src/traffic_cache_tool/CacheDefs.h
  src/tscore/ArgParser.cc
  src/tscore/runroot.cc
Labels: Cleanup

#4488 preventing crashing when calling TSSslContextFindByName with a nullptr or a 0 length string
  src/traffic_server/InkAPI.cc
Labels: TS API

#4457 Clean up client certificate specification and add tests
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/files/ssl_server_name.yaml.en.rst
  iocore/net/P_SSLConfig.h
  iocore/net/SSLConfig.cc
  iocore/net/SSLSNIConfig.cc
  iocore/net/YamlSNIConfig.cc
  iocore/net/YamlSNIConfig.h
  proxy/http/HttpConfig.cc
  proxy/http/HttpSM.cc
  tests/gold_tests/autest-site/microserver.test.ext
  tests/gold_tests/tls/ssl/signed2-bar.pem
  tests/gold_tests/tls/ssl/signed2-foo.pem
  tests/gold_tests/tls/ssl/signer2.key
  tests/gold_tests/tls/ssl/signer2.pem
  tests/gold_tests/tls/tls_client_cert.test.py
  tests/tools/microServer/uWServer.py
Labels: Documentation, Incompatible, TLS, Tests

#4454 CacheTool: Cleanup TS_INLINE.
  src/traffic_cache_tool/CacheDefs.cc
  src/traffic_cache_tool/CacheDefs.h
Labels: Cleanup

#4513 Adding cdnicrit claim support for uri signing service
  plugins/experimental/uri_signing/jwt.c
  plugins/experimental/uri_signing/jwt.h
Labels: Plugins

#4500 Augment cryptic diag message when log line fails to print
  proxy/logging/LogBuffer.cc
  proxy/logging/LogField.cc
  proxy/logging/LogField.h
  proxy/logging/LogFormat.cc
Labels: Logging

#4486 Reload records client certs
  doc/admin-guide/files/records.config.en.rst
  iocore/net/SSLConfig.cc
  mgmt/RecordsConfig.cc
  tests/gold_tests/tls/tls_client_cert.test.py
Labels: Configuration, TLS, Tests

#4515 Make sure ua_session is not nullptr
  proxy/http2/Http2ConnectionState.cc
Labels: HTTP/2

#4522 Rewrite TunnelHashMap in modern standard
  iocore/net/P_SSLUtils.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLSNIConfig.cc
  iocore/net/SSLUtils.cc
  proxy/http/HttpSM.cc
Labels: Cleanup, Core

#4524 Convert ctx_store in SSLCertLookUp to use STL vector
  iocore/net/SSLCertLookup.cc
Labels: Cleanup
