Repository apache/trafficserver, pull requests merged in 2018-05, with the labels that each got.

#3549 Only check for final C++ standards in configure
  build/ax_cxx_compile_stdcxx.m4
Labels: Build

#3555 Test: autest exercising cache-control directives
  tests/gold_tests/cache/cache-control.test.py
  tests/gold_tests/cache/gold/cache_and_req_body-hit.gold
  tests/gold_tests/cache/gold/cache_and_req_body-miss.gold
  tests/gold_tests/cache/gold/cache_hit_stale.gold
  tests/gold_tests/cache/gold/cache_no_cache.gold
  tests/gold_tests/cache/gold/cache_no_cc.gold
Labels: Cache, Tests

#3556 Convert 'gzip' Au test case to 'compress'.
  tests/gold_tests/pluginTest/compress/compress.config
  tests/gold_tests/pluginTest/compress/compress.gold
  tests/gold_tests/pluginTest/compress/compress.test.py
  tests/gold_tests/pluginTest/compress/compress2.config
  tests/gold_tests/pluginTest/compress/compress_observer.py
  tests/gold_tests/pluginTest/compress/greplog.sh
  tests/gold_tests/pluginTest/gzip/gzip_userver.gold
Labels: Tests

#3554 Ignore temporary clang files
  .gitignore
Labels: Build

#3520 Downgrade 'previously indexed' cert warning to debug
  iocore/net/SSLCertLookup.cc
Labels: TLS

#3547 Remove the default tab size in editorconfig, and create C/C++ section
  .editorconfig
Labels: Build

#3558 Update initialization to activate openssl async_job properly
  iocore/net/P_SSLUtils.h
  iocore/net/SSLNetProcessor.cc
  iocore/net/SSLUtils.cc
Labels: TLS

#3550 Corrects marshaling of source ip and port
  proxy/logging/LogAccessHttp.cc
Labels: Logging

#3519 Add cache scan feature
  cmd/traffic_cache_tool/CacheDefs.cc
  cmd/traffic_cache_tool/CacheDefs.h
  cmd/traffic_cache_tool/CacheScan.cc
  cmd/traffic_cache_tool/CacheScan.h
  cmd/traffic_cache_tool/CacheTool.cc
  cmd/traffic_cache_tool/Makefile.am
Labels: Cache, Tools

#3564 Parent Selection -- Host Marking -- Handle pRec == nullptr and wrap-a…
  proxy/ParentConsistentHash.cc
Labels: Parent Proxy

#3568 Test: autest for traffic_layout verify runroot and expected error
  tests/gold_tests/runroot/runroot_error.test.py
  tests/gold_tests/runroot/runroot_use.test.py
  tests/gold_tests/runroot/runroot_verify.test.py
Labels: Tests

#3562 Downgrade 'previously indexed' cert warning to debug
  iocore/net/SSLCertLookup.cc
Labels: TLS

#3569 traffic-replay: python request needs schema
  tests/tools/traffic-replay/NonSSL.py
Labels: Tests

#3566 Fix parsing of runroot from ink_args of 7.1.x
  lib/ts/ink_args.cc
Labels: Core

#3545 Add log field for error code of GOAWAY/RST_STREAM frame
  doc/admin-guide/logging/formatting.en.rst
  proxy/ProxyClientSession.cc
  proxy/ProxyClientSession.h
  proxy/ProxyClientTransaction.cc
  proxy/ProxyClientTransaction.h
  proxy/http/HttpTransact.h
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2ConnectionState.h
  proxy/logging/Log.cc
  proxy/logging/LogAccess.cc
  proxy/logging/LogAccess.h
  proxy/logging/LogAccessHttp.cc
  proxy/logging/LogAccessHttp.h
Labels: HTTP/2, Logging

#3563 Parent Selection -- Balance treatment of primary and secondary parent…
  proxy/ParentSelection.cc
Labels: Parent Proxy

#3572 CMakelist: Updates for gzip -> compress, libtsconfig.
  CMakeLists.txt
Labels: Cleanup

#3579 Cache-Tool: initialize tmp in CacheScan
  cmd/traffic_cache_tool/CacheScan.cc
Labels: Cleanup

#3571 Cache-Tool: coverity Fixes
  cmd/traffic_cache_tool/CacheDefs.cc
  cmd/traffic_cache_tool/CacheDefs.h
  cmd/traffic_cache_tool/CacheScan.cc
  cmd/traffic_cache_tool/File.h
Labels: Coverity

#3576 Coverity ID 1390803: Fixes unreachable code in OCSP
  iocore/net/OCSPStapling.cc
Labels: TLS

#3581 Coverity 1390802: Fix resource leak in CacheDefs.cc
  cmd/traffic_cache_tool/CacheDefs.cc
Labels: Coverity

#3594 Changes the check on toPath, which will be NULL when there is no path
  proxy/http/remap/UrlRewrite.cc
Labels: HTTP

#3590 Fixes uninitialized argument value use in HttpTransact::issue_revalidate
  proxy/http/HttpTransact.cc
Labels: HTTP

#3598 Fix a nullptr dereference
  proxy/hdrs/HttpCompat.cc
Labels: Core

#3591 Fix clang-analyzer identified memory leak in test code
  proxy/logging/LogFilter.cc
Labels: Cleanup

#3589 Fix potential nullptr derefernece in ink_inet.cc
  lib/ts/ink_inet.cc
Labels: Cleanup

#3592 Fix clang-analyzer issue in HdrTest::test_mime.
  proxy/hdrs/HdrTest.cc
Labels: Tests

#3596 Fix Dereference of null pointer in HashMap
  lib/ts/Map.h
Labels: Core

#3607 Cleaned up the syntax test
  tests/gold_tests/headers/syntax.test.py
Labels: Tests

#3610 Clang6: Fix garbage return value in CacheTool.cc.
  cmd/traffic_cache_tool/CacheTool.cc
Labels: Cleanup

#3603 Prevent memcpy overlapping buffers when assigning a CryptoHash to itself
  lib/ts/CryptoHash.h
Labels: Core

#3595 Fix out-of-bounds access in append_string function.
  tools/jtest/jtest.cc
Labels: Tests

#3613 Remove unused code
  iocore/net/SSLSessionCache.cc
  iocore/net/SSLSessionCache.h
Labels: Cleanup

#3605 Testing: Update to Catch 2.2.2
  lib/ts/ink_inet.h
  lib/ts/unit-tests/test_BufferWriterFormat.cc
  lib/ts/unit-tests/test_IpMap.cc
  lib/ts/unit-tests/test_TextView.cc
  tests/include/catch.hpp
Labels: Tests

#3602 Clang6: Fix nullptr use in AtomicList.
  lib/ts/List.h
Labels: Cleanup

#3612 Fixed off-by-one error in select_best_srv.
  iocore/hostdb/P_HostDBProcessor.h
Labels: DNS

#3601 Add TLSv1.3 cipher suites for OpenSSL-1.1.1
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  proxy/config/records.config.default.in
Labels: TLS

#3587 Move Cachekey plugin to stable plugins.
  doc/admin-guide/plugins/index.en.rst
  plugins/Makefile.am
  plugins/cachekey/Makefile.inc
  plugins/cachekey/README.md
  plugins/cachekey/cachekey.cc
  plugins/cachekey/cachekey.h
  plugins/cachekey/common.cc
  plugins/cachekey/common.h
  plugins/cachekey/configs.cc
  plugins/cachekey/configs.h
  plugins/cachekey/pattern.cc
  plugins/cachekey/pattern.h
  plugins/cachekey/plugin.cc
  plugins/cachekey/tests/pattern_test.cc
Labels: Build, Plugins

#3615 No need to walk the buckets for cache scan
  cmd/traffic_cache_tool/CacheTool.cc
Labels: Tools

#3619 Fix Coverity ID 1022023
  proxy/http/HttpTransact.cc
Labels: Coverity

#3627 Fixes coverity issues 1390794 and 1390798.
  proxy/HostStatus.cc
Labels: Coverity, Parent Proxy

#3629 Doc: document proxy.config.ssl.server.multicert.exit_on_load_fail
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#3632 Coverity 1021693: Initialized m_remap to nullptr in HttpSM.h
  proxy/http/HttpSM.h
Labels: Coverity

#3634 Fix memory leak in traffic_cache_tool.
  cmd/traffic_cache_tool/File.cc
Labels: Coverity

#3628 Added a first cut of this share file for Visual Code users
  .vscode/c_cpp_properties.json
Labels: Tools

#3570 Removes the traffic_shell.pl script
  tools/traffic_shell.pl
Labels: Tools

#3637 Coverity 1390953
  proxy/http/HttpTransact.cc
Labels: Coverity

#3620 Coverity 1021989
  lib/ts/RbTree.cc
Labels: Coverity

#3588 clang6 fix in DNS.cc
  lib/ts/ink_inet.h
Labels: DNS

#3633 Clang: fix ats_scoped_fd in CacheTool.cc
  CMakeLists.txt
  cmd/traffic_cache_tool/CacheTool.cc
  lib/ts/Makefile.am
  lib/ts/unit-tests/test_scoped_resource.cc
Labels: Cleanup

#3626 coverity: free on return - Stripe::updateHeaderFooter()
  cmd/traffic_cache_tool/CacheDefs.cc
Labels: Coverity

#3636 Removes the epic plugin
  CMakeLists.txt
  plugins/Makefile.am
  plugins/experimental/epic/Makefile.inc
  plugins/experimental/epic/epic.cc
Labels: Plugins

#3630 Fixed past-the-end error in collapsed connection plugin.
  plugins/experimental/collapsed_connection/collapsed_connection.cc
Labels: Coverity

#3608 Suppress clang-analyzer's erroneous complaint about use-after-free.
  proxy/logging/LogHost.cc
Labels: Logging

#3635 cachekey: Update CMakelists.txt for cachekey promotion.
  CMakeLists.txt
Labels: Cleanup

#3623 Coverity 1021954
  proxy/http/HttpTunnel.cc
Labels: Coverity

#3609 Remove traffic_cop
  CMakeLists.txt
  README
  cmd/Makefile.am
  cmd/traffic_cop/Makefile.am
  cmd/traffic_cop/traffic_cop.cc
  cmd/traffic_ctl/config.cc
  cmd/traffic_manager/Makefile.am
  cmd/traffic_manager/MgmtHandlers.cc
  cmd/traffic_manager/MgmtHandlers.h
  cmd/traffic_manager/traffic_manager.cc
  configure.ac
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/installation/index.en.rst
  doc/admin-guide/introduction.en.rst
  doc/admin-guide/logging/understanding.en.rst
  doc/appendices/command-line/traffic_cop.en.rst
  doc/appendices/faq.en.rst
  doc/developer-guide/api/types/TSRecordUpdateType.en.rst
  doc/developer-guide/config-vars.en.rst
  doc/developer-guide/core-architecture/rpc.en.rst
  doc/manpages.py
  lib/records/I_RecDefs.h
  lib/records/RecLocal.cc
  lib/ts/BaseLogFile.cc
  lib/ts/apidefs.h.in
  mgmt/RecordsConfig.cc
  mgmt/WebMgmtUtils.cc
  proxy/Main.cc
  proxy/ReverseProxy.cc
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  proxy/http/remap/UrlRewrite.cc
  proxy/http/remap/UrlRewrite.h
  rc/trafficserver.conf.in
  rc/trafficserver.in
  rc/trafficserver.service.in
  rc/trafficserver.xml.in
  tests/gold_tests/basic/basic-cop.test.py
Labels: Cleanup, Cop

#3622 Clang: fix CacheTool null parameter reference.
  cmd/traffic_cache_tool/CacheDefs.h
  cmd/traffic_cache_tool/CacheTool.cc
  cmd/traffic_cache_tool/File.h
  lib/ts/BufferWriter.h
  lib/ts/HashMD5.cc
  lib/ts/ink_assert.h
  lib/ts/ink_hrtime.cc
  lib/ts/ink_platform.h
  mgmt/api/NetworkMessage.cc
  tools/jtest/jtest.cc
Labels: Cleanup

#3631 coverity 1022110 fix null check
  proxy/InkAPITest.cc
Labels: Coverity

#3639 CID 1383617: Add null check
  proxy/http/HttpSM.cc
Labels: Coverity

#3625 Coverity 1267857: Null return value check in check_request_validity.
  proxy/http/HttpTransact.cc
Labels: Coverity

#3325 Adding proxy.config.http.allow_half_open
  doc/admin-guide/files/records.config.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  lib/ts/apidefs.h.in
  mgmt/RecordsConfig.cc
  plugins/experimental/ts_lua/ts_lua_http_config.c
  proxy/InkAPI.cc
  proxy/InkAPITest.cc
  proxy/http/Http1ClientTransaction.cc
  proxy/http/Http1ClientTransaction.h
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
Labels: HTTP, Network

#3640 coverity: bulkfile ignored sign
  cmd/traffic_cache_tool/File.cc
Labels: Coverity

#3624 coverity-1022121 Fix null check
  iocore/cache/CacheHosting.cc
Labels: Coverity

#3641 Clang: fix ats_scoped_fd problem.
  cmd/traffic_cache_tool/CacheTool.cc
Labels: Cleanup

#3647 Removes a bogus check that tricks clang-analyzer to think it's null
  proxy/InkAPI.cc
Labels: TS API, clang-analyzer

#3648 Fix jtest append_string() buffer overrun.
  tools/jtest/jtest.cc
Labels: Bug, clang-analyzer

#3653 Fix typo "mutext" to "mutex" in comment
  example/blacklist_1/blacklist_1.c
Labels: Cleanup, Documentation, good first issue

#3662 Fix assertion in quic_client
  cmd/traffic_quic/quic_client.cc
Labels: QUIC

#3660 Get rid of small memory leak in compress plugin.
  plugins/compress/compress.cc
Labels: Plugins

#3652 Fixes some markdown for the CIDR condition
  doc/admin-guide/plugins/header_rewrite.en.rst
Labels: Documentation

#3659 Changes to compile on Fedora 28 with gcc 8.1.1
  cmd/traffic_via/traffic_via.cc
  configure.ac
  lib/ts/mkdfa.c
  plugins/experimental/url_sig/url_sig.c
  plugins/healthchecks/healthchecks.c
  proxy/InkAPITest.cc
  proxy/ParentSelection.cc
  proxy/shared/DiagsConfig.cc
  tools/jtest/jtest.cc
Labels: Build, Cleanup

#3670 Fix issue with test_MemArena.cc which wasn't caught by the PR builds.
  lib/ts/unit-tests/test_MemArena.cc
Labels: Cleanup, Tests

#3671 Sets things up to find appropriate compilers for C++17
  ci/jenkins/bin/autest.sh
  ci/jenkins/bin/environment.sh
  ci/jenkins/bin/github.sh
Labels: Build, CI

#3655 Remove some more traffic_cop remenants
  rc/trafficserver.in
  rc/trafficserver.service.in
Labels: Cleanup

#3667 Force using C++17 as the default standard
  build/ax_cxx_compile_stdcxx.m4
  configure.ac
Labels: Build

#3680 CMakelists.txt: Remove traffic_cop remnants.
  CMakeLists.txt
Labels: Cleanup

#3642 CID 1383925: Fix null check
  proxy/http/HttpSM.cc
Labels: Coverity

#3681 More fixes to the CI builds for C++17
  ci/jenkins/bin/autest.sh
  ci/jenkins/bin/clang-analyzer.sh
  ci/jenkins/bin/coverity.sh
  ci/jenkins/bin/environment.sh
Labels: Build, CI

#3682 Fixes an assert that breaks clang-analyzer
  lib/ts/BufferWriter.h
Labels: Core, clang-analyzer

#3679 Upgrades target autest version to 1.5.3
  tests/bootstrap.py
Labels: Tests

#3684 Undoes some damage from clang-tidy on C sources
  plugins/experimental/mysql_remap/lib/dictionary.h
  plugins/experimental/mysql_remap/lib/iniparser.h
Labels: Cleanup, Plugins

#3677 Removed internal C++14 and C++17 features in ink_std_compat.h
  CMakeLists.txt
  iocore/hostdb/HostDB.cc
  lib/ts/BufferWriter.h
  lib/ts/BufferWriterForward.h
  lib/ts/Makefile.am
  lib/ts/ink_memory.h
  lib/ts/ink_std_compat.h
  plugins/tcpinfo/tcpinfo.cc
Labels: Build, Cleanup

#3686 Enhance background_fetch plugin for better squid logging
  plugins/background_fetch/background_fetch.cc
Labels: Plugins

#3644 Remove TSHttpSsnSSLConnectionGet which seems redundant.
  plugins/experimental/sslheaders/sslheaders.cc
  proxy/InkAPI.cc
  proxy/api/ts/ts.h
Labels: Cleanup, TLS, TS API

#3688 Adds a couple of more include dirs to vscode
  .vscode/c_cpp_properties.json
Labels: Tools

#3687 Removes all the metrics.config related stuff
  .gitignore
  CMakeLists.txt
  cmd/traffic_manager/AddConfigFilesHere.cc
  cmd/traffic_manager/Makefile.am
  cmd/traffic_manager/metrics.cc
  cmd/traffic_manager/metrics.h
  cmd/traffic_manager/test_metrics.cc
  cmd/traffic_manager/traffic_manager.cc
  doc/admin-guide/files/index.en.rst
  doc/admin-guide/files/metrics.config.en.rst
  doc/manpages.py
  lib/bindings/Makefile.am
  lib/bindings/metrics.cc
  lib/bindings/metrics.h
  proxy/config/Makefile.am
  proxy/config/metrics.config.default
  tests/README.md
  tests/gold_tests/autest-site/trafficserver.test.ext
Labels: Metrics

#3685 Fixed memory leak in transform add test, found with clang-analyzer
  proxy/InkAPITest.cc
Labels: clang-analyzer

#3666 Updates a test to work on BSD systems
  tests/gold_tests/headers/general-connection-failure-502.gold
  tests/gold_tests/headers/general-connection-failure-502.test.py
Labels: Tests

#3690 Promote the Escalate plugin to stable
  doc/admin-guide/plugins/escalate.en.rst
  doc/admin-guide/plugins/index.en.rst
  plugins/Makefile.am
  plugins/escalate/Makefile.inc
  plugins/escalate/escalate.cc
Labels: Build, Plugins

#3691 Restores the expected non-tab indentations
  .editorconfig
  ci/jenkins/bin/autest.sh
  ci/jenkins/bin/build.sh
  ci/jenkins/bin/clang-analyzer.sh
  ci/jenkins/bin/environment.sh
  ci/jenkins/bin/github.sh
  ci/jenkins/bin/in_tree.sh
  ci/jenkins/bin/out_of_tree.sh
  ci/jenkins/bin/snapshot.sh
  ci/jenkins/git-jenkins-setup.sh
  ci/jenkins/git-jenkins-update.sh
Labels: CI

#3559 This adds a new callback to remap APIs: TSRemapConfigReload
  doc/developer-guide/api/functions/TSRemap.en.rst
  proxy/ReverseProxy.cc
  proxy/api/ts/remap.h
  proxy/http/remap/RemapConfig.cc
  proxy/http/remap/RemapPluginInfo.cc
  proxy/http/remap/RemapPluginInfo.h
Labels: TS API

#3692 Promotes cache_promote plugin to stable
  CMakeLists.txt
  doc/admin-guide/plugins/index.en.rst
  plugins/Makefile.am
  plugins/cache_promote/Makefile.inc
  plugins/cache_promote/README
  plugins/cache_promote/cache_promote.cc
Labels: Plugins

#3689 Doc: Minor tweaks to clear up doc build errors.
  doc/admin-guide/monitoring/statistics/core-statistics.en.rst
  doc/admin-guide/plugins/compress.en.rst
  doc/admin-guide/plugins/index.en.rst
  doc/appendices/command-line/traffic_layout.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
Labels: Cleanup, Documentation

#3697 Editor: Fix CMakeLists.txt to handle escalate plugin promotion.
  CMakeLists.txt
Labels: Cleanup

#3696 Fix linkage of traffic_manager with WCCP due to removal of metric library.
  cmd/traffic_manager/Makefile.am
Labels: Cleanup

#3650 Add a -F option to disable freelist in ProxyAllocator
  doc/appendices/command-line/traffic_server.en.rst
  iocore/eventsystem/I_ProxyAllocator.h
  iocore/eventsystem/ProxyAllocator.cc
  lib/ts/Allocator.h
  lib/ts/ink_args.cc
  lib/ts/ink_args.h
  lib/ts/ink_queue.cc
  lib/ts/ink_queue.h
  lib/ts/test_freelist.cc
  proxy/Main.cc
  proxy/http2/test_HPACK.cc
Labels: Core

#3699 Make sure we core dump when we need to
  lib/ts/signals.cc
Labels: Core

#3698 For TS remap API functions, elaborate on mutual exclusion in the documentation.
  doc/developer-guide/api/functions/TSRemap.en.rst
Labels: Documentation

#3700 WCCP: Fix issues with gcc8.
  lib/wccp/WccpEndPoint.cc
  lib/wccp/WccpLocal.h
  lib/wccp/WccpMsg.cc
Labels: Cleanup, WCCP

#3673 [QUIC] Limits the size when store frame into buffer
  iocore/net/QUICNetVConnection.cc
  iocore/net/quic/QUICFrame.cc
  iocore/net/quic/QUICFrame.h
  iocore/net/quic/test/test_QUICFrame.cc
Labels: QUIC

#3675 [QUIC] Fixs the compiler error with c++17
  iocore/net/quic/QUICAckFrameCreator.cc
  iocore/net/quic/QUICCongestionController.cc
  iocore/net/quic/QUICLossDetector.cc
  iocore/net/quic/QUICLossDetector.h
Labels: Build, QUIC

#3703 Replaces the old metrics.config with a simple C++ class
  cmd/traffic_manager/traffic_manager.cc
  mgmt/DerivativeMetrics.cc
  mgmt/DerivativeMetrics.h
  mgmt/Makefile.am
Labels: Metrics

#3706 Adding missing string_view include, hopefully makes Coverity happy
  lib/ts/ink_memory.h
Labels: Core

#3702 Log the full ATS version to traffic.out on startup.
  proxy/Main.cc
Labels: Logging

#3695 CacheTool:Fix Unmarshal code and check for loops while scanning
  cmd/traffic_cache_tool/CacheScan.cc
  cmd/traffic_cache_tool/CacheScan.h
Labels: Cache, Tools

#3704 Support for clang-analyzer to use Fedora 29 packages
  ci/jenkins/bin/clang-analyzer.sh
Labels: Build, clang-analyzer

#3709 Doc: remove cluster references in traffic_ctl
  doc/appendices/command-line/traffic_ctl.en.rst
Labels: Documentation

#3705 Fixed clang-analyzer issue with null pointer in BufferWriter
  lib/ts/BufferWriter.h
Labels: clang-analyzer

#3717 Adding delay to fix race conditions in continuation tests
  tests/gold_tests/continuations/double.test.py
  tests/gold_tests/continuations/double_h2.test.py
  tests/gold_tests/continuations/openclose.test.py
  tests/gold_tests/continuations/openclose_h2.test.py
Labels: Tests

#3711 support TSHttpSsnIdGet() in lua plugin
  doc/admin-guide/plugins/lua.en.rst
  plugins/lua/ts_lua_http.c
Labels: Lua, Plugins

#3718 Fixes compiler flags used for compress plugin
  plugins/compress/Makefile.inc
Labels: Plugins

#3722 Fixed clang-analyzer issue with memory leak in LogHostList
  proxy/logging/LogBuffer.h
  proxy/logging/LogHost.cc
  proxy/logging/LogHost.h
Labels: clang-analyzer

#3721 Fixed clang-analyzer issue with memory leak in LogObject
  proxy/logging/LogObject.cc
Labels: clang-analyzer

#3710 Remove prepended "_" from public member of VIO
  iocore/cache/CacheWrite.cc
  iocore/cache/P_CacheInternal.h
  iocore/eventsystem/I_VIO.h
  iocore/eventsystem/P_VIO.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/UnixNetVConnection.cc
  proxy/CoreUtils.cc
  proxy/InkIOCoreAPI.cc
  proxy/PluginVC.cc
  proxy/Prefetch.cc
  proxy/Transform.cc
  proxy/http2/Http2Stream.cc
Labels: Cleanup

#3726 TS-2365: Fix crash in tls dynamic record size
  iocore/net/P_SSLNetVConnection.h
  iocore/net/P_SSLUtils.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLUtils.cc
Labels: TLS

#3714 Two more places to check if attempting half_closed connection logic is feasible
  proxy/ProxyClientSession.cc
  proxy/http/HttpSM.cc
Labels: HTTP, HTTP/2

#3729 Fix dicarding active lock in CPPAPI Async Timer.
  lib/cppapi/AsyncTimer.cc
Labels: CPP API

#3713 Add zombie-event option to debug leaked Http2ClientSessions.
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  proxy/http2/HTTP2.cc
  proxy/http2/HTTP2.h
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2ConnectionState.h
Labels: HTTP/2

#3741 [QUIC] Splits retransmit stream frame if needed
  iocore/net/quic/QUICFrame.cc
  iocore/net/quic/QUICFrame.h
  iocore/net/quic/QUICPacketRetransmitter.cc
  iocore/net/quic/test/test_QUICFrame.cc
Labels: QUIC

#3740 Switch to a safer snprintf(), makes compilers more happy
  plugins/experimental/mysql_remap/lib/iniparser.c
Labels: Plugins

#3738 Removes stray debug message on environments with getpeerid
  mgmt/utils/MgmtSocket.cc
Labels: Cleanup

#3719 Removes unused raft library
  CMakeLists.txt
  Makefile.am
  NOTICE
  lib/raft/raft.h
  lib/raft/raft.proto
  lib/raft/raft_impl.h
  lib/raft/raft_test.cc
  lib/raft/test_makefile
Labels: Cleanup

#3708 Adds log field for "reason" returned with status error codes
  doc/admin-guide/logging/formatting.en.rst
  proxy/logging/Log.cc
  proxy/logging/LogAccess.cc
  proxy/logging/LogAccess.h
  proxy/logging/LogAccessHttp.cc
  proxy/logging/LogAccessHttp.h
  proxy/logging/LogAccessTest.cc
  proxy/logging/LogAccessTest.h
Labels: Logging

#3733 Make ATS buildable with BoringSSL again
  iocore/net/P_OCSPStapling.h
  iocore/net/SSLUtils.cc
  lib/ts/HashMD5.cc
  proxy/InkAPI.cc
Labels: Build, TLS

#3750 Only increment currently_open count if FD is really open
  iocore/net/UnixNetProcessor.cc
  iocore/net/UnixNetVConnection.cc
Labels: Network

#3735 Fix traffic_crashlog zombie issue
  cmd/traffic_crashlog/traffic_crashlog.cc
  proxy/Crash.cc
  proxy/Main.cc
  proxy/Main.h
Labels: Logging

#3753 doc: Fixes some broken macro usages
  doc/admin-guide/layer-4-routing.en.rst
  doc/developer-guide/plugins/new-protocol-plugins.en.rst
Labels: Documentation

#3751 In the non-transparent case handle EADDRNOTAVAIL as a normal connect fail
  proxy/http/HttpSM.cc
Labels: Network

#3758 header age not critical to HSTS header test result.
  tests/gold_tests/headers/hsts.200.gold
Labels: Tests

#3756 Only increment currently_open if socket connects (take 2)
  iocore/net/UnixNetVConnection.cc
Labels: Network

#3759 Log the errno from the connect failure.
  proxy/http/HttpSM.cc
Labels: Logging, Network

#3757 Allow disable throttling.
  doc/admin-guide/files/records.config.en.rst
  iocore/net/P_UnixNet.h
Labels: Network
