Repository apache/trafficserver, pull requests merged in 2018-09, with the labels that each got.

#4186 clang-format: Another one that slipped through.
  lib/cppapi/Transaction.cc
Labels: Cleanup

#4195 Runroot: Fix storage.config and host.db issues when using runroot
  iocore/cache/Store.cc
  lib/records/RecConfigParse.cc
Labels: Core

#4192 Add exit code checks in clang-format.sh
  ci/jenkins/bin/clang-format.sh
Labels: CI

#4178 Fix another ProxySession and NetVC shutdown race crash
  proxy/ProxyClientSession.cc
  proxy/http/Http1ClientSession.cc
Labels: Core, Crash

#4196 Back-port to 8.0.x - Log Collation Memory Leak
  proxy/logging/LogHost.cc
Labels: Logging

#4184 Update to changelog generation tool to not require milestone to be closed
  tools/changelog.pl
Labels: Tools

#4199 Remove unneeded aio header file
  iocore/net/SSLSessionCache.h
Labels: Build, Cleanup

#4198 Cleanup, and adds support for new luajit option
  ci/jenkins/bin/clang-analyzer.sh
  ci/jenkins/bin/environment.sh
  ci/jenkins/bin/github.sh
Labels: CI

#4194 Remove ssl_cert_loader. Certifier is more complete version.
  plugins/Makefile.am
  plugins/experimental/ssl_cert_loader/Makefile.inc
  plugins/experimental/ssl_cert_loader/domain-tree.cc
  plugins/experimental/ssl_cert_loader/domain-tree.h
  plugins/experimental/ssl_cert_loader/ssl-cert-loader.cc
  plugins/experimental/ssl_cert_loader/ssl_cert_loader.cfg
  plugins/experimental/ssl_cert_loader/ssl_start.cfg
Labels: Cleanup, Plugins

#4200 Revert "Fixes MacOS linker issue with release build"
  iocore/net/Makefile.am
Labels: Build

#4142 Lock continuation before calling event handler.
  iocore/hostdb/HostDB.cc
Labels: Core

#4055 Remove ignore_keep_alive method entirely
  proxy/ProxyClientTransaction.h
  proxy/http/Http1ClientTransaction.h
  proxy/http/HttpTransact.cc
  proxy/http2/Http2Stream.h
Labels: HTTP, HTTP/2

#4215 HostStatus debug logging segfault fix.
  src/traffic_server/HostStatus.cc
Labels: Backport, Bug, Parent Proxy

#4217 Fix a regression in the traffic_ctl host status subcommand.
  proxy/HostStatus.h
  src/traffic_ctl/host.cc
  src/traffic_server/HostStatus.cc
Labels: Backport, Regression

#4193 G++ 8.1.1: Fix complaint about lack of storage definitiona for class static constant
  proxy/http/remap/UrlRewrite.h
Labels: Cleanup

#4133 Disables the double test for inconsistent execution
  tests/gold_tests/continuations/double.test.py
Labels: Tests

#4213 Disable the HttpSM half open logic if the underlying transport is TLS
  proxy/http/Http1ClientSession.h
  proxy/http/Http1ClientTransaction.cc
Labels: HTTP, TLS

#4207 Correct interpretation of proxy.config.ssl.client.verify.server
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/files/ssl_server_name.yaml.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  iocore/net/SSLNetVConnection.cc
  lib/ts/apidefs.h.in
  plugins/lua/ts_lua_http_config.c
  proxy/http/HttpConfig.cc
  proxy/http/HttpSM.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/InkAPITest.cc
Labels: Configuration, Documentation, TLS

#4175 TextView: Better support for std::string assignment.
  lib/ts/TextView.h
Labels: Core

#4177 IntrusiveDList: Add ptr_ref_cast to make inheritance easier
  doc/developer-guide/internal-libraries/intrusive-list.en.rst
  lib/ts/IntrusiveDList.h
  lib/ts/unit-tests/test_IntrusiveDList.cc
Labels: Cleanup

#4226 HttpSessionManager: Fix potential infinite loop problem.
  proxy/http/HttpSessionManager.cc
Labels: Core

#4229 Clarifies code comment for DL_Emergency
  lib/ts/Diags.h
Labels: Cleanup

#4176 TextView: Add support for use as "Source" in STL containers.
  lib/ts/TextView.h
Labels: Core

#4231 Fix storage.config path issue for runroot
  iocore/cache/Store.cc
Labels: Startup

#4233 Fix link error on macOS
  src/tscore/Makefile.am
Labels: Build

#4203 Allow enabling MPTCP on a listening socket through the records.config
  doc/admin-guide/files/records.config.en.rst
  lib/records/I_RecHttp.h
  lib/records/RecHttp.cc
  mgmt/LocalManager.cc
Labels: Network

#4225 Fixed error getting h2 HEADERS frame after stream is closed
  proxy/http2/Http2ConnectionState.cc
Labels: Crash, HTTP/2

#4230 Heap use after free
  proxy/http/HttpTransact.cc
Labels: HTTP

#4234 Corrects path to test file in docs
  doc/developer-guide/internal-libraries/intrusive-list.en.rst
Labels: Cleanup, Documentation

#4152 revoke promise when provider is gone
  include/tscpp/api/Async.h
Labels: CPP API

#4145 Adds configurable behavior on redirect to loopback
  doc/admin-guide/files/records.config.en.rst
  iocore/utils/I_Machine.h
  iocore/utils/Machine.cc
  mgmt/RecordsConfig.cc
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpTransact.cc
  tests/gold_tests/redirect/redirect.test.py
  tests/gold_tests/redirect/redirect_actions.test.py
  tests/gold_tests/redirect/redirect_post.test.py
Labels: HTTP

#4239 Corrects path in multiple documents
  Makefile.am
  NOTICE
  doc/developer-guide/api/functions/TSTypes.en.rst
  doc/developer-guide/config-vars.en.rst
  doc/developer-guide/internal-libraries/buffer-writer.en.rst
  proxy/issues.txt
Labels: Cleanup

#4238 Runroot: Update doc according to the storage.config change
  doc/admin-guide/files/storage.config.en.rst
  doc/appendices/command-line/traffic_layout.en.rst
Labels: Documentation

#4241 Runroot: Fix a issue caused by restructured headers
  src/traffic_layout/file_system.cc
Labels: Build

#4243 Follow up for #3724 - fix out of tree builds.
  CMakeLists.txt
  build/plugins.mk
  configure.ac
  iocore/aio/Makefile.am
  iocore/cache/Makefile.am
  iocore/dns/Makefile.am
  iocore/eventsystem/Makefile.am
  iocore/hostdb/Makefile.am
  iocore/net/Makefile.am
  iocore/utils/Makefile.am
  lib/records/Makefile.am
  lib/tsconfig/Makefile.am
  mgmt/Makefile.am
  mgmt/api/Makefile.am
  mgmt/utils/Makefile.am
  plugins/experimental/memcache/Makefile.inc
  proxy/Makefile.am
  proxy/hdrs/Makefile.am
  proxy/http/Makefile.am
  proxy/http/remap/Makefile.am
  proxy/http2/Makefile.am
  proxy/logging/Makefile.am
  proxy/shared/Makefile.am
  src/traffic_cache_tool/Makefile.inc
  src/traffic_crashlog/Makefile.inc
  src/traffic_ctl/Makefile.inc
  src/traffic_layout/Makefile.inc
  src/traffic_logcat/Makefile.inc
  src/traffic_logstats/Makefile.inc
  src/traffic_manager/Makefile.inc
  src/traffic_server/Makefile.inc
  src/traffic_top/Makefile.inc
  src/traffic_wccp/Makefile.inc
  src/traffic_wccp/wccp_client.cc
  src/tscore/Makefile.am
  src/wccp/Makefile.am
Labels: Cleanup

#4244 git ignore - location of autogenerated headers changed
  .gitignore
Labels: Cleanup

#4247 Removes the deprecated plugin coallapsed_connection
  CMakeLists.txt
  plugins/Makefile.am
  plugins/experimental/collapsed_connection/Makefile.inc
  plugins/experimental/collapsed_connection/MurmurHash3.cc
  plugins/experimental/collapsed_connection/MurmurHash3.h
  plugins/experimental/collapsed_connection/P_collapsed_connection.h
  plugins/experimental/collapsed_connection/README
  plugins/experimental/collapsed_connection/collapsed_connection.cc
  plugins/experimental/collapsed_connection/default.config
  plugins/experimental/collapsed_connection/state.dot
Labels: Plugins

#4139 Adds 308 origin response stat metric
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpTransact.cc
Labels: HTTP, Metrics

#4248 PR-3724: Fix additional linkage issues.
  example/Makefile.am
  plugins/experimental/webp_transform/Makefile.inc
Labels: Cleanup

#4219 Adding missing image file for Proxy Protocol documentation.
  doc/static/images/admin/proxy-protocol.png
Labels: Documentation

#4261 Adds a few missing packages needed by autest
  ci/docker/yum/Dockerfile
Labels: Build

#4265 CMakeLists.txt: Change to be generic and not need updates so often.
  CMakeLists.txt
Labels: Cleanup

#4259 Corrects typo in argument name
  doc/developer-guide/api/functions/TSMimeHdrFieldGet.en.rst
Labels: Documentation

#4164 Reset the inactivity timeout when reusing connections
  proxy/http/HttpSM.cc
Labels: Core, Network

#4266 Run automake and autoconf everytime on a docs build
  ci/jenkins/bin/docs.sh
Labels: Build, Documentation

#4257 Update base version of AuTest to 1.6.0
  tests/bootstrap.py
  tests/gold_tests/autest-site/init.cli.ext
Labels: Tests

#4268 Test: Convert test_X509HostnameValidator.cc to Catch
  src/tscore/Makefile.am
  src/tscore/unit_tests/test_X509HostnameValidator.cc
Labels: Cleanup, Tests

#4272 Test: Convert test_Map.cc to Catch
  .gitignore
  src/tscore/Makefile.am
  src/tscore/unit_tests/test_Map.cc
Labels: Cleanup, Tests

#4274 Documentation for plugin certifier
  doc/admin-guide/plugins/certifier.en.rst
  doc/admin-guide/plugins/index.en.rst
Labels: Documentation

#4275 Documentation for traffic dump
  doc/admin-guide/plugins/index.en.rst
  doc/admin-guide/plugins/traffic_dump.en.rst
Labels: Documentation

#4206 ts_file: Simple sketch of std::filesystem for internal use.
  include/tscore/ts_file.h
  src/tscore/Makefile.am
  src/tscore/ts_file.cc
  src/tscore/unit_tests/test_ts_file.cc
Labels: Core

#4269 Test: Convert test_List.cc to Catch
  .gitignore
  src/tscore/Makefile.am
  src/tscore/unit_tests/test_List.cc
Labels: Cleanup, Tests

#4276 Use the default log rotation enabled value and remove old comments in logging.yaml and link to docs
  configs/logging.yaml.default
  proxy/logging/YamlLogConfig.cc
Labels: Logging

#4271 Updated the rpm spec file to have the correct files and fixed permissions
  tools/package/trafficserver.spec
Labels: Build

#4227 ArgParser: 'ArgParser' Class for command line arguments parsing
  doc/developer-guide/internal-libraries/ArgParser.en.rst
  doc/developer-guide/internal-libraries/index.en.rst
  include/tscore/ArgParser.h
  src/tscore/ArgParser.cc
  src/tscore/Makefile.am
  src/tscore/unit_tests/test_ArgParser.cc
Labels: Cleanup, Core

#4280 Fix clang format problems
  include/tscore/ts_file.h
  iocore/net/I_NetVConnection.h
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
Labels: Cleanup

#4282 Hopefully a final clang-format fix after CI problems.
  src/tscore/ArgParser.cc
Labels: Cleanup

#4267 Set log code when closing half open connections.
  proxy/http/HttpSM.cc
Labels: HTTP

#4270 Test: Convert test_arena.cc to Catch
  .gitignore
  src/tscore/Makefile.am
  src/tscore/unit_tests/test_arena.cc
Labels: Cleanup, Tests

#4273 Test: Convert test_Vec.cc to Catch
  .gitignore
  src/tscore/Makefile.am
  src/tscore/unit_tests/test_Vec.cc
Labels: Cleanup, Tests

#4284 Fixed ts_file test for out of tree builds
  src/tscore/unit_tests/test_ts_file.cc
Labels: Tests

#4283 Test: Convert test_Http2DependencyTree.cc to Catch
  proxy/http2/Makefile.am
  proxy/http2/unit_tests/test_Http2DependencyTree.cc
Labels: Tests

#4287 Test: Fix issues with new Catch unit tests
  src/tscore/unit_tests/test_Map.cc
  src/tscore/unit_tests/test_Vec.cc
  src/tscore/unit_tests/test_arena.cc
Labels: Tests

#4281 Fix docs typo
  doc/admin-guide/files/records.config.en.rst
Labels: Cleanup, Documentation

#4279 Ensure NOFILES ulimit is set high
  rc/trafficserver.in
Labels: Startup

#4290 Remove unnecessary line in src/Makefile.am
  src/Makefile.am
Labels: Build, Cleanup

#4301 Fix doc building warnings for recent plugin docs
  doc/admin-guide/plugins/certifier.en.rst
  doc/admin-guide/plugins/traffic_dump.en.rst
Labels: Documentation

#4296 Fix libjansson & libcjose static or dynamic detection
  configure.ac
Labels: Build

#4260 Removes logging of secrets
  plugins/s3_auth/s3_auth.cc
Labels: Plugins, Security

#4300 Expand the post chunked tests.
  tests/gold_tests/h2/http2.test.py
Labels: HTTP/2, Tests

#4310 Add warning of body_factory templates are not loaded due to missing dot file
  proxy/http/HttpBodyFactory.cc
Labels: Configuration

#4307 Add a search path for Tcl
  build/tcl.m4
Labels: Build

#4305 Generally random code cleanup
  proxy/http/remap/RemapPluginInfo.h
  proxy/http/remap/RemapProcessor.h
  src/traffic_server/traffic_server.cc
Labels: Cleanup

#4320 Runroot: make runroot accept defective yaml file
  include/tscore/I_Layout.h
  src/tscore/Layout.cc
Labels: Core

#4311 Fix typo of the nofiles ulimit to a sane number
  rc/trafficserver.in
Labels: Configuration

#4288 Rewrite traffic_layout with ArgParser
  doc/admin-guide/files/storage.config.en.rst
  doc/appendices/command-line/traffic_layout.en.rst
  include/tscore/runroot.h
  src/traffic_layout/engine.cc
  src/traffic_layout/engine.h
  src/traffic_layout/file_system.cc
  src/traffic_layout/file_system.h
  src/traffic_layout/info.cc
  src/traffic_layout/info.h
  src/traffic_layout/traffic_layout.cc
  src/tscore/runroot.cc
  tests/gold_tests/runroot/runroot_error.test.py
  tests/gold_tests/runroot/runroot_init.test.py
  tests/gold_tests/runroot/runroot_manager.test.py
  tests/gold_tests/runroot/runroot_remove.test.py
  tests/gold_tests/runroot/runroot_use.test.py
  tests/gold_tests/runroot/runroot_verify.test.py
Labels: Commands

#4322 Remove Bitops - apparently not used anywhere
  include/tscore/Bitops.h
  src/tscore/Bitops.cc
  src/tscore/Makefile.am
Labels: Cleanup

#4323 Removed headers that are not used
  proxy/TimeTrace.h
  src/traffic_cache_tool/CacheStore.h
Labels: Cleanup

#4324 Adds Robots exclusion file
  doc/robots.txt
Labels: Documentation

#4331 Make build failures also mark the CA builds as failed
  ci/jenkins/bin/clang-analyzer.sh
Labels: CI

#4332 Fixes build issues related to Clang Analyzer only
  src/tscore/MemArena.cc
Labels: Core

#4334 Converts ink_autoconf.h to #pragma once
  configure.ac
Labels: Cleanup

#4333 Runroot: verify functionality update and other minor fixes
  doc/appendices/command-line/traffic_layout.en.rst
  src/traffic_layout/Makefile.inc
  src/traffic_layout/engine.cc
  src/traffic_layout/file_system.cc
  src/traffic_layout/file_system.h
  src/traffic_layout/traffic_layout.cc
  tests/gold_tests/autest-site/setup.cli.ext
Labels: Configuration

#4253 Add the capability to mark origins down with traffic_ctl.
  proxy/http/HttpTransact.cc
Labels: Core
