Repository apache/trafficserver, pull requests merged in 2018-08, with the labels that each got.

#4049 Removes carriage returns from MT_hashtable.h
  lib/ts/MT_hashtable.h
Labels: Cleanup

#4045 Mark log collation as deprecated
  doc/admin-guide/files/logging.yaml.en.rst
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/logging/destinations.en.rst
  doc/admin-guide/logging/formatting.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/monitoring/logging/log-collation.en.po
  proxy/logging/LogConfig.cc
Labels: Logging

#4019 Ensure that continuation lock is held before calling handler.
  iocore/eventsystem/Continuation.cc
  iocore/eventsystem/I_Continuation.h
  iocore/eventsystem/Makefile.am
  iocore/eventsystem/UnixEThread.cc
  iocore/net/UnixNetAccept.cc
  iocore/net/UnixNetVConnection.cc
  proxy/http/HttpConfig.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpTunnel.cc
  src/traffic_server/InkAPI.cc
Labels: Core, Crash

#4020 Add logic to clean up vios on HttpSM shutdown
  proxy/http/Http1ClientSession.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpSM.h
  proxy/http/HttpServerSession.cc
  proxy/http2/Http2ClientSession.cc
Labels: Core, Crash, HTTP

#4024 Fix logic to support ASYNC_pause_job
  iocore/net/P_SSLNetVConnection.h
  iocore/net/SSLNetVConnection.cc
Labels: TLS

#4044 Adjust tests to work with more versions of curl.
  tests/gold_tests/h2/gold/priority_0_stderr.gold
  tests/gold_tests/h2/http2.test.py
Labels: HTTP/2, Tests

#4048 Cached object should not be removed when write is aborted
  proxy/http/HttpCacheSM.h
Labels: HTTP

#4050 Optimize: make NetAccept::init_accept_loop has the logic similar to NetAccept::init_accept_per_thread
  iocore/net/P_NetAccept.h
  iocore/net/UnixNetAccept.cc
  iocore/net/UnixNetProcessor.cc
Labels: Network

#4051 Doc: Document TSContCall
  doc/developer-guide/api/functions/TSContCall.en.rst
Labels: Documentation, Plugins

#4052 Removes reference to non-existent ssl_multicert option 'exit_on_load_error'
  doc/admin-guide/files/ssl_multicert.config.en.rst
Labels: Cleanup, Documentation

#3900 ts/Extendible and AcidPtr classes
  doc/developer-guide/internal-libraries/AcidPtr.en.rst
  doc/developer-guide/internal-libraries/Extendible.en.rst
  doc/developer-guide/internal-libraries/index.en.rst
  lib/ts/AcidPtr.cc
  lib/ts/AcidPtr.h
  lib/ts/Extendible.h
  lib/ts/Makefile.am
  lib/ts/unit-tests/test_AcidPtr.cc
  lib/ts/unit-tests/test_Extendible.cc
Labels: Parent Proxy

#4028 proxy.config.http.connect_attempts_timeout tracks TTBF instead of connect
  iocore/net/I_NetProcessor.h
  iocore/net/P_SSLNetVConnection.h
  iocore/net/P_UnixNetVConnection.h
  iocore/net/UnixNetProcessor.cc
  iocore/net/UnixNetVConnection.cc
  proxy/http/HttpSM.cc
Labels: Network

#4014 fix outputlog, diagslog rolling size overflow
  lib/ts/Diags.cc
Labels: Logging

#4058 Remove Http2ConnectionState::continued_buffer
  proxy/http2/Http2ConnectionState.h
Labels: Backport, HTTP/2

#4053 Test for proxy.config.http.connect_attempts_timeout
  tests/gold_tests/timeout/timeout.gold
  tests/gold_tests/timeout/timeout.test.py
Labels: Network, Tests

#4042 Fixed url_sig error when storing base64ed params in penultimate segment.
  plugins/experimental/url_sig/url_sig.c
Labels: Plugins

#4067 Bug fix for timeout test
  tests/gold_tests/timeout/timeout.test.py
Labels: Tests

#3966 Add BWF support for SourceLocation.
  lib/ts/SourceLocation.cc
  lib/ts/SourceLocation.h
  lib/ts/unit-tests/test_History.cc
Labels: Core

#3967 BufferWriter: Add print overloads to FixedBufferWriter
  lib/ts/BufferWriter.h
Labels: Core

#4063 BWF: Add "FirstOf" for better handling of printing alternates for null strings.
  doc/developer-guide/internal-libraries/buffer-writer.en.rst
  lib/ts/bwf_std_format.h
  lib/ts/unit-tests/test_BufferWriterFormat.cc
Labels: Core

#4069 Setup better defaults for service file logic
  rc/trafficserver.in
  rc/trafficserver.service.in
Labels: Configuration

#4076 traffic_manager: fix --tsArgs to work.
  src/traffic_manager/traffic_manager.cc
Labels: Backport, Manager

#4074 Cancel inactive event before marking it as nullptr in PluginVC::process_timeout()
  proxy/PluginVC.cc
  proxy/PluginVC.h
Labels: Core

#4078 In conf_remap plugin, print name of non-existent or non-overriddable …
  plugins/conf_remap/conf_remap.cc
Labels: Logging

#4080 Add diags log message when cache wraps.
  iocore/cache/CacheWrite.cc
Labels: Backport, Logging

#4079 Enable ECDH explicitly only if OpenSSL version is v1.0.2 or lower
  iocore/net/SSLUtils.cc
Labels: Backport, TLS

#4070 Renames TSHttpTxnSetHttpRetStatus to TSHttpTxnStatusSet
  example/remap/remap.cc
  example/secure_link/secure_link.c
  lib/cppapi/Transaction.cc
  plugins/authproxy/authproxy.cc
  plugins/experimental/geoip_acl/geoip_acl.cc
  plugins/experimental/hipes/hipes.cc
  plugins/experimental/memcached_remap/memcached_remap.cc
  plugins/experimental/mp4/mp4.cc
  plugins/experimental/mysql_remap/mysql_remap.cc
  plugins/experimental/uri_signing/uri_signing.c
  plugins/experimental/url_sig/url_sig.c
  plugins/header_rewrite/operators.cc
  plugins/lua/ts_lua_http.c
  plugins/regex_remap/regex_remap.cc
  plugins/s3_auth/s3_auth.cc
  proxy/api/ts/ts.h
  src/traffic_server/InkAPI.cc
  tests/tools/plugins/custom204plugin.cc
Labels: TS API

#4081 Fix typo in header_normalize plugin.
  plugins/experimental/header_normalize/header_normalize.cc
Labels: Cleanup, Plugins

#4084 Fixed http/2 issue with Http2Stream being updated after it was destroyed
  proxy/http2/Http2Stream.cc
Labels: Backport, Crash, HTTP/2

#4083 Links server_push_preload plugin against libatscppapi
  plugins/experimental/server_push_preload/Makefile.inc
Labels: Build, Plugins

#4085 Fix typo in header_normalize plugin.
  plugins/experimental/header_normalize/header_normalize.cc
Labels: Backport, Cleanup, Plugins

#4072 Release ssl in QUICTLS (destructor)
  iocore/net/quic/QUICTLS.cc
  iocore/net/quic/test/test_QUICHandshakeProtocol.cc
Labels: QUIC

#4073 Fix Http/2 priority crashes.
  proxy/http2/Http2DependencyTree.h
  proxy/http2/test_Http2DependencyTree.cc
Labels: Crash, HTTP/2

#4082 Lock continuation to avoid handleEvent assert.
  iocore/hostdb/HostDB.cc
Labels: Core, DNS, HostDB

#4087 Doc: Add documentation for experimental plugin "multiplexer".
  doc/admin-guide/plugins/index.en.rst
  doc/admin-guide/plugins/multiplexer.en.rst
Labels: Documentation, Plugins

#4046 Collapses LogAccess and LogAccessHttp into LogAccess
  CMakeLists.txt
  proxy/ProxyClientSession.cc
  proxy/ProxyClientSession.h
  proxy/http/HttpBodyFactory.cc
  proxy/http/HttpSM.cc
  proxy/logging/Log.cc
  proxy/logging/Log.h
  proxy/logging/LogAccess.cc
  proxy/logging/LogAccess.h
  proxy/logging/LogAccessHttp.cc
  proxy/logging/LogAccessHttp.h
  proxy/logging/LogAccessTest.h
  proxy/logging/Makefile.am
  src/traffic_logcat/Makefile.inc
  src/traffic_logstats/Makefile.inc
Labels: Cleanup, Logging

#4091 logstats conditionally disable format check
  doc/appendices/command-line/traffic_logstats.en.rst
  src/traffic_logstats/logstats.cc
Labels: Logging, Tools

#3950 access_control plugin
  doc/admin-guide/plugins/access_control.en.rst
  doc/admin-guide/plugins/index.en.rst
  plugins/Makefile.am
  plugins/experimental/access_control/.gitignore
  plugins/experimental/access_control/Makefile.inc
  plugins/experimental/access_control/README.md
  plugins/experimental/access_control/access_control.cc
  plugins/experimental/access_control/access_control.h
  plugins/experimental/access_control/common.cc
  plugins/experimental/access_control/common.h
  plugins/experimental/access_control/config.cc
  plugins/experimental/access_control/config.h
  plugins/experimental/access_control/headers.cc
  plugins/experimental/access_control/headers.h
  plugins/experimental/access_control/pattern.cc
  plugins/experimental/access_control/pattern.h
  plugins/experimental/access_control/plugin.cc
  plugins/experimental/access_control/unit-tests/test_access_control.cc
  plugins/experimental/access_control/unit-tests/test_utils.cc
  plugins/experimental/access_control/utils.cc
  plugins/experimental/access_control/utils.h
Labels: Plugins, Security

#4092 Fix Http/2 priority crashes.
  proxy/http2/Http2DependencyTree.h
  proxy/http2/test_Http2DependencyTree.cc
Labels: Backport, Crash, HTTP/2

#4093 Fixes the renamed RenameTSHttpTxnSetHttpRetStatus() API
  plugins/experimental/access_control/plugin.cc
Labels: Plugins

#4088 Make sure len is smaller than MAX_ENTRY before we use it as the index
  proxy/logging/LogObject.cc
Labels: Cleanup

#4100 Doc: Update comments in InkAPI.cc in the header and for member converters.
  src/traffic_server/InkAPI.cc
Labels: Cleanup

#4106 make sure len is smaller than MAX_ENTRY before we use it as the index
  proxy/logging/LogObject.cc
Labels: Backport, Logging

#4101 cachekey: handle empty regex group captures
  plugins/cachekey/pattern.cc
Labels: Backport, Plugins

#4104 Ensure continuation lock on read and write signal
  iocore/net/UnixNetVConnection.cc
Labels: Crash, Network

#4105 Deal with the case when the hostdb cont may not have a mutex
  iocore/hostdb/HostDB.cc
Labels: Crash, HostDB

#4065 process early data during handshake
  iocore/net/quic/QUICPacket.cc
  iocore/net/quic/QUICPacket.h
  iocore/net/quic/QUICPacketReceiveQueue.cc
Labels: Network, QUIC

#3995 cachekey: capture cache key elements from headers
  doc/admin-guide/plugins/cachekey.en.rst
  plugins/cachekey/cachekey.cc
  plugins/cachekey/cachekey.h
  plugins/cachekey/common.h
  plugins/cachekey/configs.cc
  plugins/cachekey/configs.h
  plugins/cachekey/pattern.cc
  plugins/cachekey/pattern.h
Labels: Plugins

#4111 Replace TRY_MUTEX_LOCK_FOR with equivalent TRY_MUTEX_LOCK
  iocore/eventsystem/I_Lock.h
  iocore/eventsystem/UnixEThread.cc
  iocore/hostdb/HostDB.cc
  iocore/net/SSLNetVConnection.cc
  iocore/net/UnixNetVConnection.cc
  iocore/net/UnixUDPNet.cc
Labels: Cleanup

#4126 Fix typo in RecUtils
  lib/records/P_RecUtils.h
  lib/records/RecRawStats.cc
  lib/records/RecUtils.cc
Labels: Cleanup

#4122 Make sure "traffic_ctl config reload" only reloads configs that changed
  lib/records/P_RecCore.cc
  lib/records/RecUtils.cc
Labels: Commands, Configuration

#4098 adding a Mutex to the continuation
  plugins/stats_over_http/stats_over_http.c
Labels: Plugins

#4116 Increase limit on open files allowed as a service
  rc/trafficserver.service.in
Labels: Configuration

#3901 MemArena: Add make method to construct objects in the arena.
  doc/conf.py
  doc/developer-guide/internal-libraries/MemArena.en.rst
  lib/ts/MemArena.cc
  lib/ts/MemArena.h
  lib/ts/unit-tests/test_MemArena.cc
Labels: Core

#4108 fixing spelled enumeration
  lib/cppapi/Transaction.cc
  lib/cppapi/include/atscppapi/Transaction.h
Labels: CPP API

#4115 TextView: Add overload for strcasecmp for string_view & TextView.
  lib/ts/TextView.cc
  lib/ts/TextView.h
  lib/ts/unit-tests/test_TextView.cc
  plugins/xdebug/xdebug.cc
Labels: Cleanup

#3955 IntrusiveHashMap: Refresh TSHashTable for C++ eleventy.
  CMakeLists.txt
  doc/conf.py
  doc/developer-guide/internal-libraries/index.en.rst
  doc/developer-guide/internal-libraries/intrusive-hash-map.en.rst
  lib/ts/IntrusiveHashMap.h
  lib/ts/Makefile.am
  lib/ts/unit-tests/test_IntrusiveHashMap.cc
Labels: Core

#4131 Completes code comment for redirect configs
  mgmt/RecordsConfig.cc
  proxy/http/HttpConfig.cc
Labels: Cleanup

#4132 Completes documentation regarding redirects
  doc/admin-guide/files/records.config.en.rst
Labels: Cleanup, Documentation

#4146 Cleanup: remove unused and unimplemented functions from ink_string.h
  lib/ts/ink_string.h
Labels: Cleanup

#4149 Clang-format: Redo clang-format error that slipped through.
  lib/cppapi/include/atscppapi/Transaction.h
Labels: Cleanup

#4151 Corrects IPv4 multicast ip address check
  lib/ts/ink_inet.h
Labels: Core, Network

#4156 Move handleEvent back into the header file.
  iocore/eventsystem/Continuation.cc
  iocore/eventsystem/I_Continuation.h
Labels: Cleanup

#4155 REVERTED: Revert "Ensure continuation lock on read and write signal"
  iocore/net/UnixNetVConnection.cc
Labels: Revert

#4154 QUIC: fix memleaking in test_QUICFrame
  iocore/net/quic/QUICPacketReceiveQueue.cc
  iocore/net/quic/test/test_QUICFrame.cc
Labels: QUIC

#4161 Fixes memleaking in handshake
  iocore/net/quic/QUICHandshake.cc
Labels: QUIC

#4147 Fix crash in Http2ClientSession::release_netvc
  proxy/ProxyClientSession.cc
  proxy/ProxyClientSession.h
  proxy/http/Http1ClientSession.h
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ClientSession.h
Labels: Core, Crash

#4163 Doc: Remove deprecated configs from examples of traffic_ctl
  doc/appendices/command-line/traffic_ctl.en.rst
Labels: Documentation

#4129 Update IPAllow infrastructure.
  CMakeLists.txt
  iocore/net/I_SessionAccept.h
  iocore/net/Makefile.am
  iocore/net/SessionAccept.cc
  proxy/IPAllow.cc
  proxy/IPAllow.h
  proxy/ProxyClientSession.cc
  proxy/ProxyClientSession.h
  proxy/ProxyClientTransaction.h
  proxy/http/HttpSM.cc
  proxy/http/HttpSessionAccept.cc
  proxy/http/HttpTransact.cc
  proxy/http2/Http2SessionAccept.cc
Labels: Cleanup

#4114 Clear up evnets and timers for a H2 stream before destroying its mutex
  proxy/http2/Http2Stream.cc
Labels: HTTP/2

#4170 Fix for when multiplexer gets a 0 byte read event
  plugins/experimental/multiplexer/chunk-decoder.cc
Labels: Plugins

#4169 Multiplexer fixes
  plugins/experimental/multiplexer/fetcher.h
Labels: Plugins

#4138 Follows 308 Permanent Redirect
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  tests/gold_tests/redirect/redirect.test.py
Labels: HTTP

#4124 Removes references to STAT_PROCESSOR
  lib/records/I_RecDefs.h
  lib/records/RecUtils.cc
Labels: Cleanup

#4041 Log collation mem leaks (x2).
  proxy/logging/LogHost.cc
Labels: Logging

#4127 Allows to run Spinx builds on portions of the docs
  .gitignore
  doc/ext/local-config.py.in
Labels: Documentation

#4174 Fix crash in Http2ClientSession::release_netvc
  proxy/ProxyClientSession.cc
  proxy/ProxyClientSession.h
  proxy/http/Http1ClientSession.h
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ClientSession.h
Labels: Backport, Core

#4173 Clear up evnets and timers for a H2 stream before destroying its mutex
  proxy/http2/Http2Stream.cc
Labels: Backport, HTTP/2

#4165 Update the header_rewrite doc for clarification on CLIENT-URL:HOST
  doc/admin-guide/plugins/header_rewrite.en.rst
Labels: Documentation

#4031 Revert "Add TLSv1.3 cipher suites for OpenSSL-1.1.1"
  configs/records.config.default.in
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
Labels: TLS

#4181 Removed checking the return value for TSContCall() in the multiplexer plugin
  plugins/experimental/multiplexer/post.cc
Labels: Plugins

#4037 Add configs for TLSv1.3 ciphersuites
  build/crypto.m4
  configure.ac
  doc/admin-guide/files/records.config.en.rst
  iocore/net/P_SSLConfig.h
  iocore/net/SSLClientUtils.cc
  iocore/net/SSLConfig.cc
  iocore/net/SSLUtils.cc
  lib/ts/ink_config.h.in
  mgmt/RecordsConfig.cc
Labels: TLS

#4102 fix for cpp api Transaction::redirectTo
  lib/cppapi/Transaction.cc
Labels: CPP API

#3810 Handy tool to decode via header
  tools/traffic_via.pl
Labels: Commands

#4183 Default config change with proxy.config.http.negative_revalidating_enabled
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#4123 Enables proxy.config.http.negative_revalidating_enabled by default
  mgmt/RecordsConfig.cc
Labels: Configuration

#3956 PROXY Protocol transformed to Forwarded HTTP header - backport to 8.0.x - WIP - DO NOT MERGE
  doc/admin-guide/configuration/index.en.rst
  doc/admin-guide/configuration/proxy-protocol.en.rst
  doc/admin-guide/files/records.config.en.rst
  doc/static/images/admin/proxy-protocol.png
  iocore/net/Connection.cc
  iocore/net/I_NetProcessor.h
  iocore/net/I_NetVConnection.h
  iocore/net/Makefile.am
  iocore/net/P_NetVConnection.h
  iocore/net/P_SSLConfig.h
  iocore/net/P_UnixNetVConnection.h
  iocore/net/ProxyProtocol.cc
  iocore/net/ProxyProtocol.h
  iocore/net/SSLConfig.cc
  iocore/net/SSLNetVConnection.cc
  iocore/net/UnixNetAccept.cc
  iocore/net/UnixNetProcessor.cc
  lib/records/I_RecHttp.h
  lib/records/RecHttp.cc
  lib/ts/IpMapConf.h
  mgmt/LocalManager.cc
  mgmt/RecordsConfig.cc
  proxy/PluginVC.cc
  proxy/PluginVC.h
  proxy/ProtocolProbeSessionAccept.cc
  proxy/ProtocolProbeSessionAccept.h
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpProxyServerMain.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
Labels: Core, WIP
