Repository apache/trafficserver, pull requests merged in 2019-12, with the labels that each got.

#6227 Remove never implemented regex descriptions
  doc/admin-guide/plugins/header_rewrite.en.rst
Labels: Documentation

#6224 Fixed build issue with clang5 and Extendible
  include/tscore/Extendible.h
Labels: Core

#6231 Adjust the refcounts to avoid Mutex leak
  iocore/eventsystem/I_Lock.h
  src/traffic_server/InkIOCoreAPI.cc
Labels: Core

#6217 cache_range_requests plugin optional support for special IMS header
  doc/admin-guide/plugins/cache_range_requests.en.rst
  doc/admin-guide/plugins/index.en.rst
  plugins/cache_range_requests/README
  plugins/cache_range_requests/README.md
  plugins/cache_range_requests/cache_range_requests.cc
  tests/gold_tests/pluginTest/cache_range_requests/cache_range_requests.test.py
  tests/gold_tests/pluginTest/cache_range_requests/cache_range_requests_ims.test.py
  tests/gold_tests/pluginTest/cache_range_requests/gold/frange.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/full.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/inner.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/last.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/pselect.stdout.gold
Labels: Plugins

#6242 Fixes sphinx build warning with the strategies.yaml document in the admin-guide
  doc/admin-guide/files/strategies.yaml.en.rst
Labels: Documentation

#5987 Removing traffic_cop reference in admin guide introduction
  doc/admin-guide/introduction.en.rst
  doc/static/images/admin/process.jpg
Labels: Documentation

#6001 New TS maintenance commands: verify_global_plugin and verify_remap_plugin
  .gitignore
  doc/appendices/command-line/traffic_server.en.rst
  doc/release-notes/whats-new.en.rst
  include/tscore/ts_file.h
  proxy/Plugin.cc
  proxy/Plugin.h
  proxy/http/remap/RemapPluginInfo.h
  src/traffic_server/traffic_server.cc
  src/tscore/ts_file.cc
  src/tscore/unit_tests/test_ts_file.cc
  tests/gold_tests/command_argument/verify_global_plugin.test.py
  tests/gold_tests/command_argument/verify_remap_plugin.test.py
  tests/tools/plugins/conf_remap_stripped.cc
  tests/tools/plugins/missing_mangled_definition.c
  tests/tools/plugins/missing_mangled_definition.cc
  tests/tools/plugins/missing_mangled_definition.h
  tests/tools/plugins/missing_ts_plugin_init.cc
Labels: Feature, Tests

#6226 Fix sni.yaml fqdn to match complete name string
  iocore/net/SSLSNIConfig.cc
  tests/gold_tests/tls/tls_client_verify.test.py
Labels: TLS, Tests

#6251 Some tweaks to reloading-plugins.en.rst
  doc/developer-guide/design-documents/reloading-plugins.en.rst
Labels: Documentation

#6248 Add support for the old lua formatted ease of use conventions and the numeric log rolling values
  proxy/logging/YamlLogConfig.cc
Labels: Backport, Logging

#6247 Add some stats collections to cache_promote.
  doc/admin-guide/plugins/cache_promote.en.rst
  plugins/cache_promote/cache_promote.cc
Labels: Plugins

#5972 Avoid unnecesarry copy on POST request over HTTP/2
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2Stream.cc
  proxy/http2/Http2Stream.h
Labels: Cleanup, HTTP/2

#6236 remap_stats: restore handling of remap/hostname to remove memory leak
  plugins/experimental/remap_stats/remap_stats.cc
Labels: Leak, Plugins

#6233 auto delete rolled log file fixes
  include/tscore/Diags.h
  include/tscore/ts_file.h
  iocore/cache/test/main.cc
  iocore/net/quic/test/event_processor_main.cc
  iocore/net/quic/test/main.cc
  proxy/http3/test/main.cc
  proxy/http3/test/main_qpack.cc
  proxy/logging/Log.cc
  proxy/logging/LogConfig.cc
  proxy/logging/LogConfig.h
  proxy/logging/LogObject.cc
  proxy/logging/LogObject.h
  proxy/logging/Makefile.am
  proxy/logging/RolledLogDeleter.cc
  proxy/logging/RolledLogDeleter.h
  proxy/logging/YamlLogConfig.cc
  proxy/logging/unit-tests/test_LogUtils.h
  proxy/logging/unit-tests/test_RolledLogDeleter.cc
  proxy/shared/DiagsConfig.cc
  proxy/shared/DiagsConfig.h
  src/traffic_server/InkAPI.cc
  src/tscore/Diags.cc
  tests/gold_tests/logging/log_retention.test.py
  tests/tools/plugins/test_log_interface.cc
Labels: Logging

#6258 Initial revision of .lgtm.yml config file
  .lgtm.yml
Labels: Build, Security

#6260 Fix TS_USE_DIAGS usage for --disable-diags option
  include/tscore/Diags.h
Labels: Build

#6193 Fixes various crashers loading/reloading parent.config
  src/tscore/HostLookup.cc
Labels: Crash, Parent Proxy, WIP

#6270 LGTM: fix a comparison that is always false.
  proxy/http/remap/NextHopSelectionStrategy.cc
Labels: Bug, lgtm

#6271 LGTM: fixes a shadowed variable in ParentSelection::PreprocessParents().
  proxy/ParentSelection.cc
Labels: Bug, Parent Proxy, lgtm

#6264 Change HTTP/2 error rate log to warning
  proxy/http2/Http2ClientSession.cc
Labels: HTTP/2

#6266 LGTM: Fix wrong type of arguments to formatting function
  proxy/http/HttpPages.cc
Labels: lgtm

#6265 LGTM: Add header guards
  plugins/authproxy/utils.h
  plugins/experimental/geoip_acl/acl.h
  plugins/experimental/sslheaders/sslheaders.h
  plugins/experimental/uri_signing/config.h
  plugins/experimental/uri_signing/cookie.h
  plugins/experimental/uri_signing/jwt.h
  plugins/experimental/uri_signing/normalize.h
  plugins/experimental/uri_signing/parse.h
  plugins/experimental/uri_signing/timing.h
  src/traffic_layout/info.h
Labels: Build, lgtm

#6274 Remove -j from lgtm build
  .lgtm.yml
Labels: lgtm

#6149 For per-transaction config override, crossing the const-correctness event horizon.
  iocore/cache/Cache.cc
  iocore/cache/CacheRead.cc
  iocore/cache/I_Cache.h
  iocore/cache/P_CacheInternal.h
  mgmt/MgmtDefs.h
  proxy/CacheControl.cc
  proxy/CacheControl.h
  proxy/http/HttpCacheSM.cc
  proxy/http/HttpCacheSM.h
  proxy/http/HttpConnectionCount.cc
  proxy/http/HttpConnectionCount.h
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  proxy/http/HttpTransactCache.cc
  proxy/http/HttpTransactCache.h
  proxy/http/HttpTransactHeaders.cc
  proxy/http/HttpTransactHeaders.h
  src/traffic_server/InkAPI.cc
Labels: Configuration

#6244 Copy the Client SNI Server Name out of the openssl SSL object.
  iocore/net/P_SSLNetVConnection.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLUtils.cc
  proxy/http/HttpSM.cc
Labels: Crash

#6222 For combo_handler plugin, add an optional whitelist of allowed values for Content-Type.
  doc/admin-guide/plugins/combo_handler.en.rst
  plugins/esi/README.combo
  plugins/esi/combo_handler.cc
  tests/gold_tests/pluginTest/combo_handler/combo_handler.test.py
  tests/gold_tests/pluginTest/combo_handler/combo_handler_files/tr1.gold
  tests/gold_tests/pluginTest/combo_handler/combo_handler_files/tr2.gold
Labels: Plugins

#6279 Update the admin-guide hierachical caching and remap.config documentation.
  doc/admin-guide/configuration/hierarchical-caching.en.rst
  doc/admin-guide/files/remap.config.en.rst
Labels: Documentation

#6025 Remove remnants of obsolete remap thread.
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  proxy/http/HttpSM.cc
  proxy/http/remap/RemapProcessor.cc
  proxy/http/remap/RemapProcessor.h
  src/traffic_server/traffic_server.cc
Labels: Cleanup

#6280 Assure no SM survives plugin factory deactivation.
  proxy/ReverseProxy.cc
  proxy/http/remap/PluginFactory.cc
  proxy/http/remap/UrlRewrite.cc
Labels: Bug, Core

#6282 LGTM: Fix unused imports
  contrib/python/compare_RecordsConfigcc.py
  plugins/experimental/uri_signing/python_signer/uri_signer.py
Labels: lgtm

#6284 Removes the remaining references to TSQA
  doc/developer-guide/testing/blackbox-testing.en.rst
  example/plugins/c-api/intercept/intercept.cc
  src/traffic_layout/info.cc
  tests/README.md
Labels: Cleanup

#6286 These features are in 9.0.x release notes
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#6257 Moving / adding the Roadmap to the release notes
  doc/release-notes/images/git-versions.png
  doc/release-notes/images/roadmap.png
  doc/release-notes/index.en.rst
  doc/release-notes/roadmap.en.rst
Labels: Documentation

#6290 Fixes a few Sphinx build warnings
  doc/admin-guide/plugins/header_rewrite.en.rst
  doc/appendices/command-line/traffic_server.en.rst
Labels: Documentation

#6281 Perf: replace dynamic_cast with static_cast in this_thread()
  iocore/eventsystem/P_UnixEThread.h
Labels: Core, Performance

#6285 Set wrap around after checking all the parents
  proxy/ParentConsistentHash.cc
  proxy/ParentSelection.h
Labels: Parent Proxy

#6296 Fix rst errors for collapsed forwarding plugin
  doc/admin-guide/plugins/collapsed_forwarding.en.rst
Labels: Backport, Documentation

#6297 Add links to RWW sections
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation
