Repository apache/trafficserver, pull requests merged in 2019-05, with the labels that each got.

#5367 Check QUIC availability with SSL_MODE_QUIC_HACK
  configure.ac
Labels: QUIC

#5399 Removes code related to removed configuration
  tests/README.md
  tests/gold_tests/autest-site/trafficserver.test.ext
Labels: Tests

#5411 Update README.md
  tests/README.md
  tests/gold_tests/logging/all_headers.test.py
Labels: Tests

#5413 TS C++ API: add member function TSSslConnection InterceptPlugin::getSslConnection()
  include/tscpp/api/InterceptPlugin.h
  src/tscpp/api/InterceptPlugin.cc
Labels: CPP API

#5370 Fixed clang-analyzer issues in cookie_remap
  plugins/experimental/cookie_remap/Makefile.inc
  plugins/experimental/cookie_remap/strip.cc
Labels: clang-analyzer

#5228 Implement prefetched OCSP stapling responses
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/files/ssl_multicert.config.en.rst
  doc/admin-guide/security/index.en.rst
  include/ts/ts.h
  iocore/net/OCSPStapling.cc
  iocore/net/P_OCSPStapling.h
  iocore/net/P_SSLConfig.h
  iocore/net/P_SSLUtils.h
  iocore/net/SSLConfig.cc
  iocore/net/SSLUtils.cc
  mgmt/RecordsConfig.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/InkAPITest.cc
  tests/gold_tests/autest-site/conditions.test.ext
  tests/gold_tests/tls/ssl/ca.ocsp.key
  tests/gold_tests/tls/ssl/ca.ocsp.pem
  tests/gold_tests/tls/ssl/ocsp_response.der
  tests/gold_tests/tls/ssl/responder.ocsp.key
  tests/gold_tests/tls/ssl/responder.ocsp.pem
  tests/gold_tests/tls/ssl/server.ocsp.key
  tests/gold_tests/tls/ssl/server.ocsp.pem
  tests/gold_tests/tls/tls_ocsp.test.py
Labels: TLS

#5416 Move setsockopt from UnixNetProcessor to Server::setup_fd_for_listen
  iocore/net/Connection.cc
  iocore/net/I_NetProcessor.h
  iocore/net/UnixNetProcessor.cc
  proxy/http/HttpProxyServerMain.cc
Labels: Network

#5396 Rewrite the assert statement to avoid Socks Proxy triggering the assertions
  proxy/http/HttpSM.cc
Labels: SOCKS

#5398 Load the Socks configuration after the host state persistence data is loaded
  iocore/net/I_NetProcessor.h
  iocore/net/P_UnixNetProcessor.h
  iocore/net/UnixNetProcessor.cc
  proxy/shared/UglyLogStubs.cc
  src/traffic_server/traffic_server.cc
Labels: Parent Proxy, SOCKS

#5432 Doc: Update TSConfig... functions.
  doc/developer-guide/api/functions/TSConfig.en.rst
  doc/developer-guide/api/functions/TSConfigDataGet.en.rst
  doc/developer-guide/api/functions/TSConfigGet.en.rst
  doc/developer-guide/api/functions/TSConfigRelease.en.rst
  doc/developer-guide/api/functions/TSConfigSet.en.rst
  src/traffic_server/InkAPITest.cc
Labels: Documentation

#5424 Fix ContFlags for gcc 9.
  include/tscore/ContFlags.h
Labels: Cleanup

#5427 gcc9 - fix class Connection.
  iocore/net/P_Connection.h
Labels: Cleanup

#5428 gcc9 - fix CryptoHash.h
  include/tscore/CryptoHash.h
Labels: Cleanup

#5426 First pass of documentation for URL rewrite.
  doc/developer-guide/core-architecture/index.en.rst
  doc/developer-guide/core-architecture/url_rewrite_architecture.en.rst
  doc/uml/url_rewrite.plantuml
Labels: Documentation

#5281 Change Au test condition for minimal OpenSSL version to use traffic_layout info --versions
  tests/gold_tests/autest-site/conditions.test.ext
Labels: Tests

#5362 fix 3939 collision
  iocore/cache/CacheWrite.cc
Labels: Cache

#5420 Adds update header only test case
  iocore/cache/Makefile.am
  iocore/cache/test/test_Update_header.cc
Labels: Cache, Tests

#5421 Check nullptr before call netvc->do_io_close in SSLNextProtocolAccept::mainEvent
  iocore/net/SSLNextProtocolAccept.cc
Labels: TLS

#5423 This fixes parsing where the [ ] section gets merged into values
  plugins/header_rewrite/header_rewrite.cc
  plugins/header_rewrite/header_rewrite_test.cc
  plugins/header_rewrite/parser.cc
  plugins/header_rewrite/parser.h
  plugins/header_rewrite/ruleset.cc
  plugins/header_rewrite/value.cc
Labels: Plugins

#5433 gcc9 - Fix Errata.h, NumericType.h.
  lib/tsconfig/Errata.h
  lib/tsconfig/NumericType.h
Labels: Cleanup

#5435 gcc9 - fix HTTPVersion.
  proxy/hdrs/HTTP.h
Labels: Cleanup

#5434 gcc9 - Fix I_Store.h
  iocore/cache/I_Store.h
Labels: Cleanup

#5438 Add wait_for_cache to make all_headers test more resilient
  tests/gold_tests/logging/all_headers.test.py
Labels: Tests

#5440 Removes unused TSConfig usage in ssl_sni_whitelist example
  example/ssl_sni_whitelist/ssl_sni_whitelist.cc
  example/ssl_sni_whitelist/ssl_sni_whitelist.config
Labels: Cleanup

#5439 Removes unused TSConfig usage in ssl_sni example
  example/ssl_sni/ssl_sni.cc
  example/ssl_sni/ssl_sni.config
Labels: Cleanup

#5442 Removes unused TSConfig usage in verify_cert example
  example/verify_cert/verify_cert.cc
Labels: Cleanup

#5443 Address intermittent failures of all_headers Au test (see Issue # 5437).
  tests/gold_tests/logging/all_headers.test.py
  tests/gold_tests/logging/all_headers_sanitizer.py
  tests/gold_tests/logging/all_headers_sanitizer.sh
  tests/gold_tests/logging/gold/test_all_headers.gold
Labels: Tests

#5447 Fixed nullptr check in cookie remap
  plugins/experimental/cookie_remap/strip.cc
Labels: Plugins

#5417 Change HostStatus to use only one stat per host.
  doc/appendices/command-line/traffic_ctl.en.rst
  iocore/cache/test/stub.cc
  proxy/HostStatus.h
  proxy/ParentSelection.cc
  src/traffic_ctl/host.cc
  src/traffic_server/HostStatus.cc
Labels: Parent Proxy

#5441 Improve test resilience by waiting for TS ports to be ready.
  tests/gold_tests/headers/cache_and_req_body.test.py
  tests/gold_tests/headers/cachedIMSRange.test.py
Labels: Tests

#5414 Add API and fix logic for TS_SSL_VERIFY_*_HOOK.
  doc/developer-guide/api/functions/TSVConnSslVerifyCTXGet.en.rst
  doc/developer-guide/plugins/hooks-and-transactions/ssl-hooks.en.rst
  include/ts/apidefs.h.in
  include/ts/ts.h
  iocore/net/P_SSLNetVConnection.h
  iocore/net/SSLClientUtils.cc
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLUtils.cc
  src/traffic_server/InkAPI.cc
  tests/gold_tests/tls/tls_hooks_client_verify.test.py
  tests/tools/plugins/ssl_client_verify_test.cc
Labels: Documentation, TLS, TS API, Tests

#5448 Fixed syntax issue with clang
  plugins/experimental/ssl_session_reuse/src/ats_ssl_plugin.cc
Labels: Build

#5410 Add docs for QUIC configuration
  doc/admin-guide/files/records.config.en.rst
Labels: QUIC

#5446 Fixes use-after-free in PVCTestDriver::start_tests
  proxy/PluginVC.cc
Labels: PluginVC

#5445 Rewrite SocksProxy based on states
  src/traffic_server/SocksProxy.cc
Labels: SOCKS

#5415 MemSpan: Update to templated style, fix gcc9 compile error.
  include/tscore/BufferWriter.h
  include/tscore/MemArena.h
  include/tscpp/util/MemSpan.h
  lib/records/I_RecCore.h
  lib/records/P_RecMessage.h
  lib/records/RecHttp.cc
  lib/records/RecMessage.cc
  mgmt/BaseManager.cc
  mgmt/BaseManager.h
  mgmt/LocalManager.cc
  mgmt/MgmtDefs.h
  mgmt/ProcessManager.cc
  proxy/logging/LogConfig.cc
  proxy/logging/LogConfig.h
  src/traffic_cache_tool/CacheDefs.cc
  src/traffic_cache_tool/CacheDefs.h
  src/traffic_cache_tool/CacheScan.cc
  src/traffic_cache_tool/CacheScan.h
  src/traffic_server/HostStatus.cc
  src/traffic_server/traffic_server.cc
  src/tscore/BufferWriterFormat.cc
  src/tscore/MemArena.cc
  src/tscore/unit_tests/test_BufferWriterFormat.cc
  src/tscore/unit_tests/test_MemArena.cc
  src/tscpp/util/unit_tests/test_MemSpan.cc
Labels: Cleanup

#5453 Doc: Clean up some errors and formatting in traffic_ctl documentation.
  doc/appendices/command-line/traffic_ctl.en.rst
Labels: Cleanup, Documentation

#5452 Clang Analyzer: Fix IpMap.cc false positives. #2
  src/tscore/IpMap.cc
Labels: clang-analyzer

#5462 gcc9: fixed issue with always printing a null char*
  proxy/http/HttpSM.cc
Labels: Build

#5387 Fixes typos in various documentation files
  doc/admin-guide/plugins/geoip_acl.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/files/parent.config.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/files/records.config.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/plugins/geoip_acl.en.po
  doc/locale/ja/LC_MESSAGES/developer-guide/api/functions/TSVConnReenable.en.po
  plugins/experimental/metalink/test/location
  plugins/experimental/slice/ContentRange.h
  plugins/experimental/slice/server.cc
  proxy/CacheControl.cc
  proxy/CacheControl.h
  proxy/ControlMatcher.cc
  proxy/IPAllow.h
  proxy/ParentSelection.cc
  proxy/ParentSelection.h
  proxy/PluginVC.h
  proxy/hdrs/HdrHeap.cc
  proxy/hdrs/HdrHeap.h
  proxy/hdrs/HdrToken.h
  proxy/hdrs/HttpCompat.cc
  proxy/hdrs/MIME.cc
  proxy/http/ForwardedConfig.cc
  proxy/http/Http1ClientSession.cc
  proxy/http/Http1ClientTransaction.cc
  proxy/http/HttpBodyFactory.h
  proxy/http/HttpCacheSM.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpConnectionCount.h
  proxy/http/HttpPages.cc
  proxy/http/HttpPages.h
  proxy/http/HttpSM.cc
  proxy/http/HttpSM.h
  proxy/http/HttpServerSession.h
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransactCache.cc
  proxy/http/HttpTransactHeaders.cc
  proxy/http/HttpTunnel.cc
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2ConnectionState.h
  proxy/http2/Http2Stream.h
  proxy/logging/LogAccess.cc
  proxy/logging/LogFile.cc
  proxy/logging/LogFilter.h
  proxy/logging/LogFormat.cc
  proxy/logging/LogObject.cc
  proxy/logging/LogStandalone.cc
  proxy/logging/LogUtils.cc
  src/traffic_logstats/logstats.cc
  tests/gold_tests/autest-site/trafficserver.test.ext
  tests/gold_tests/headers/hsts.test.py
  tests/gold_tests/headers/http408.test.py
Labels: Cleanup

#5464 clang-analyzer: Fix API test logic and fixed clang-analyzer issue
  src/traffic_server/InkAPITest.cc
Labels: Tests, clang-analyzer

#5467 Add be32toh and htobe32 for macOS
  include/tscore/ink_endian.h
Labels: Core

#5455 Convert ssl_preaccept plugin to use command-line arguments
  example/ssl_preaccept/ssl_preaccept.cc
  example/ssl_preaccept/ssl_preaccept.config
Labels: Cleanup

#5463 clang-analyzer: Fixed err value being uninitialized
  iocore/net/SSLNetVConnection.cc
Labels: clang-analyzer

#5472 gcc9: Added default assignment operator
  proxy/HostStatus.h
Labels: Build

#5477 Removes proxy.config.http.server_tcp_init_cwnd
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/plugins/lua.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/files/records.config.en.po
  doc/locale/ja/LC_MESSAGES/developer-guide/api/functions/TSHttpOverridableConfig.en.po
  include/ts/apidefs.h.in
  iocore/net/Connection.cc
  iocore/net/I_NetProcessor.h
  iocore/net/I_NetVConnection.h
  iocore/net/P_UnixNetVConnection.h
  mgmt/RecordsConfig.cc
  plugins/lua/ts_lua_http_config.c
  proxy/PluginVC.cc
  proxy/PluginVC.h
  proxy/http/Http1ClientSession.cc
  proxy/http/Http1ClientSession.h
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpProxyServerMain.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/InkAPITest.cc
Labels: Cleanup, Configuration, Network

#5479 Fix checking progress of read/write vio
  iocore/net/quic/QUICBidirectionalStream.h
Labels: QUIC

#5484 Don't read frames after sending GOAWAY with an error code
  proxy/http2/Http2ClientSession.cc
Labels: Backport, HTTP/2

#5489 gcc9: set default value for printing debug message
  plugins/header_rewrite/conditions.cc
Labels: Build

#5493 QUIC: Fix test for pervious changes
  iocore/net/quic/Mock.h
  iocore/net/quic/test/test_QUICFlowController.cc
  iocore/net/quic/test/test_QUICFrame.cc
  iocore/net/quic/test/test_QUICStream.cc
  iocore/net/quic/test/test_QUICStreamManager.cc
Labels: QUIC

#5482 Document proxy.config.ssl.server.honor_cipher_order
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#5492 clang-analyzer: fix bogus use after free with Ptr in LogFieldInt constructor.
  proxy/logging/LogFilter.cc
Labels: clang-analyzer

#5490 clang-analyzer: Fix uninitialized variable in make_to_lower_case.
  iocore/net/SSLCertLookup.cc
Labels: clang-analyzer

#5497 gcc9: sprintf and strncat fixes in plugins
  example/thread_pool/psi.c
  plugins/s3_auth/s3_auth.cc
Labels: Build

#5500 Added Docker support for Fedora 29 and Fedora 30
  ci/docker/Makefile
Labels: Build, CI

#5495 Correct the clear range when cache restart
  iocore/cache/Cache.cc
Labels: Cache

#5478 Fixes some cache-tests build issues
  ci/jenkins/bin/cache-tests.sh
Labels: CI

#5460 Fixed clang-analyzer issue calling schedule_imm with the continuation possibly being a nullptr
  proxy/http2/Http2Stream.cc
Labels: clang-analyzer

#5458 Updates the Docker image with latest dependencies
  ci/docker/yum/Dockerfile
Labels: Build

#5508 Grab lock before invoke
  src/traffic_server/traffic_server.cc
Labels: Crash

#5502 This is already documented in the proper traffic_ctl page
  doc/admin-guide/monitoring/alarms.en.rst
Labels: Documentation

#5507 AcidPtr: Tweaks tests to be a bit more robust.
  src/tscore/unit_tests/test_AcidPtr.cc
Labels: Cleanup, Tests

#5509 clang analzyer - fix false positive in Vol::handle_recover_from_data.
  iocore/cache/Cache.cc
Labels: clang-analyzer

#5512 Http3: close connection when buffer release
  proxy/http3/Http3ClientTransaction.cc
Labels: QUIC

#5499 Host status refactor 8.0.x backport
  doc/admin-guide/files/parent.config.en.rst
  doc/appendices/command-line/traffic_ctl.en.rst
  iocore/net/I_NetProcessor.h
  iocore/net/P_UnixNetProcessor.h
  iocore/net/UnixNetProcessor.cc
  mgmt/LocalManager.cc
  mgmt/LocalManager.h
  mgmt/api/CoreAPI.cc
  mgmt/api/CoreAPI.h
  mgmt/api/CoreAPIRemote.cc
  mgmt/api/INKMgmtAPI.cc
  mgmt/api/NetworkMessage.cc
  mgmt/api/TSControlMain.cc
  mgmt/api/include/mgmtapi.h
  proxy/HostStatus.h
  proxy/ParentSelection.cc
  proxy/ParentSelection.h
  proxy/shared/UglyLogStubs.cc
  src/traffic_ctl/Makefile.inc
  src/traffic_ctl/host.cc
  src/traffic_server/HostStatus.cc
  src/traffic_server/traffic_server.cc
Labels: Backport

#5516 Make code compilable with BoringSSL
  iocore/net/SSLSessionTicket.h
  iocore/net/SSLUtils.cc
  plugins/experimental/access_control/utils.cc
Labels: TLS

#5510 TextView: clean up on strcasecmp, strcmp, and memcmp.
  include/tscpp/util/TextView.h
  src/tscpp/util/TextView.cc
  tests/tools/plugins/test_cppapi.cc
Labels: Cleanup

#5454 Doc: Clean up JA3 plugin docs.
  doc/admin-guide/plugins/ja3_fingerprint.en.rst
Labels: Cleanup, Documentation

#5518 Adds a missing dependency, bump autest version
  tests/bootstrap.py
Labels: Tests

#5521 Check for OpenSSSL v1.1.1, for now, for this test
  tests/gold_tests/tls/tls_hooks_client_verify.test.py
Labels: Tests

#5425 Updates the VSCode include dirs
  .vscode/c_cpp_properties.json
Labels: Tools

#5528 Allow number of settings per H2 session to be configurable
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  proxy/http2/HTTP2.cc
  proxy/http2/HTTP2.h
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2ConnectionState.h
Labels: HTTP/2

#5524 clang analyzer: Fix false positive "use after free" in IpMap.cc
  src/tscore/IpMap.cc
Labels: clang-analyzer

#5525 clang analyzer: suppress nullptr derefence report in mime_hdr_sanity_check
  proxy/hdrs/MIME.cc
Labels: clang-analyzer

#5529 clang analyzer: Suppress nullptr dereference error in SSLNetVConnection::update_rbio
  iocore/net/SSLNetVConnection.cc
Labels: clang-analyzer

#5526 Remove f_callback_on_accept
  iocore/net/I_NetProcessor.h
  iocore/net/UnixNetAccept.cc
  iocore/net/UnixNetProcessor.cc
  proxy/shared/UglyLogStubs.cc
Labels: Cleanup, clang-analyzer

#5530 Removes disable_configuration_modification, making it always on
  doc/admin-guide/files/records.config.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/files/records.config.en.po
  lib/records/P_RecCore.cc
  lib/records/P_RecCore.h
  lib/records/RecLocal.cc
  lib/records/RecProcess.cc
  mgmt/RecordsConfig.cc
  mgmt/api/TSControlMain.cc
Labels: Cleanup, Configuration, Proposal

#4240 Inherited Extendible
  doc/developer-guide/internal-libraries/AcidPtr.en.rst
  doc/developer-guide/internal-libraries/Extendible.en.rst
  include/tscore/Extendible.h
  src/tscore/Extendible.cc
  src/tscore/Makefile.am
  src/tscore/unit_tests/test_AcidPtr.cc
  src/tscore/unit_tests/test_Extendible.cc
Labels: Core

#5537 Fixed an ownership issue in autest
  tests/gold_tests/autest-site/trafficserver.test.ext
Labels: Tests

#5547 Make sure autest has all minimal config files
  ci/rat-regex.txt
  tests/gold_tests/autest-site/min_cfg/logging.yaml
  tests/gold_tests/autest-site/min_cfg/plugin.config
  tests/gold_tests/autest-site/min_cfg/socks.config
  tests/gold_tests/autest-site/min_cfg/splitdns.config
  tests/gold_tests/autest-site/min_cfg/ssl_server_name.yaml
Labels: Tests

#5551 Fix test to not break on custom layouts
  tests/gold_tests/runroot/runroot_verify.test.py
Labels: Tests

#5552 Add options to sort to reduce os differences in all_headers test
  tests/gold_tests/logging/all_headers.test.py
  tests/gold_tests/logging/all_headers_sanitizer.sh
  tests/gold_tests/logging/gold/test_all_headers.gold
Labels: Tests

#5558 Removed headers that don't exist in the dir to fix clang-tidy
  src/tscore/Makefile.am
Labels: Build

#5554 Updates Dockerfile, and adds a comment to autest bootstrap
  ci/docker/yum/Dockerfile
  tests/bootstrap.py
Labels: CI

#5536 More fixes and cleanup of CI scripts
  ci/jenkins/bin/autest.sh
  ci/jenkins/bin/clang-analyzer.sh
  ci/jenkins/bin/gh-mirror.sh
  ci/jenkins/bin/snapshot.sh
Labels: Build, CI

#5561 Check DH_get_2048_256() should inclue <openssl/dh.h>
  build/crypto.m4
Labels: Build, TLS

#5564 Doc: Remove origin KA note from removed setting
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#5565 Add cstdio in TextBuffer for vsnprintf
  src/tscore/TextBuffer.cc
Labels: Core

#5566 Doc: Add documentation for a few C API functions, clean up doc build errors
  doc/admin-guide/performance/index.en.rst
  doc/admin-guide/plugins/background_fetch.en.rst
  doc/admin-guide/security/index.en.rst
  doc/appendices/glossary.en.rst
  doc/developer-guide/api/functions/TSHttpHdrUrlGet.en.rst
  doc/developer-guide/api/functions/TSHttpTxnClientReqGet.en.rst
  doc/developer-guide/api/functions/TSHttpTxnIsCacheable.en.rst
  doc/developer-guide/api/functions/TSTypes.en.rst
  doc/developer-guide/api/functions/TSUrlHostGet.en.rst
  doc/developer-guide/api/functions/TSVConnSslVerifyCTXGet.en.rst
  doc/developer-guide/api/types/TSMgmtTypes.en.rst
  doc/developer-guide/config-vars.en.rst
  doc/developer-guide/internal-libraries/Extendible.en.rst
  doc/developer-guide/internal-libraries/scalar.en.rst
  doc/developer-guide/plugins/hooks-and-transactions/ssl-hooks.en.rst
Labels: Documentation

#5543 Added loop detection via code and squid logging code
  doc/appendices/command-line/traffic_via.en.rst
  doc/appendices/faq.en.rst
  proxy/hdrs/HTTP.h
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  proxy/http/HttpTransactHeaders.cc
  proxy/logging/Log.cc
  src/traffic_via/traffic_via.cc
  tools/traffic_via/traffic_via.pl
Labels: HTTP

#5556 Minor wording changes in ssl_server_name.yaml docs
  doc/admin-guide/files/ssl_server_name.yaml.en.rst
Labels: Documentation

#5567 Doc: Fix typo in TSMimeHdrFieldCreate
  doc/developer-guide/api/functions/TSMimeHdrFieldCreate.en.rst
Labels: Cleanup, Documentation

#5570 Clean up: Remove proxy.config.http.parent_proxy_routing_enable variable
  configs/records.config.default.in
  doc/admin-guide/configuration/hierarchical-caching.en.rst
  doc/admin-guide/files/records.config.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/configuration/hierachical-caching.en.po
  lib/perl/lib/Apache/TS/AdminClient.pm
  mgmt/RecordsConfig.cc
  proxy/ParentSelection.cc
  src/traffic_server/InkAPITest.cc
Labels: Cleanup

#5544 Add an ignore_self_detect flag to parent.config so that the local cache host may be a member of a peering cache group.
  doc/admin-guide/files/parent.config.en.rst
  iocore/cache/test/stub.cc
  proxy/HostStatus.h
  proxy/ParentConsistentHash.cc
  proxy/ParentRoundRobin.cc
  proxy/ParentSelection.cc
  proxy/ParentSelection.h
  proxy/http/HttpTransact.cc
  src/traffic_server/HostStatus.cc
Labels: Parent Proxy

#5466 Set HTTP version on server side header conversion
  proxy/http2/HTTP2.cc
Labels: HTTP/2, OnDocs

#5571 Removes the abort() from header_rewrite, and try to deal with errors
  plugins/header_rewrite/header_rewrite.cc
  plugins/header_rewrite/matcher.h
Labels: Crash, Plugins

#5531 Allow number of settings per H2 session to be configurable
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  proxy/http2/HTTP2.cc
  proxy/http2/HTTP2.h
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2ConnectionState.h
Labels: Backport, HTTP/2

#5575 Fix order a little bit, based on F30 availability
  tests/Pipfile
Labels: Tests

#5569 New API: TSSslClientContextsNamesGet and TSSslClientContextFindByName
  doc/developer-guide/api/functions/TSSslClientContext.en.rst
  example/Makefile.am
  example/client_context_dump/client_context_dump.cc
  include/ts/ts.h
  src/traffic_server/InkAPI.cc
  tests/gold_tests/autest-site/setup.cli.ext
  tests/gold_tests/pluginTest/client_context_dump/client_context_dump.test.py
  tests/gold_tests/pluginTest/client_context_dump/gold/client_context_dump.gold
  tests/gold_tests/pluginTest/client_context_dump/ssl/one.com.pem
  tests/gold_tests/pluginTest/client_context_dump/ssl/two.com.pem
Labels: TLS, TS API

#5586 Ignore Pipfile.lock file
  .gitignore
Labels: Tests

#5589 Adds support for set-destination SCHEME/URL to take string expansions
  plugins/header_rewrite/operators.cc
Labels: Plugins
