Repository apache/trafficserver, pull requests merged in 2020-09, with the labels that each got.

#7155 PluginFactory - Remove unused code.
  proxy/http/remap/PluginFactory.h
Labels: Cleanup

#7153 Add metric tracking async job pauses
  doc/admin-guide/monitoring/statistics/core/ssl.en.rst
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLStats.cc
  iocore/net/SSLStats.h
Labels: TLS

#7135 Replace ACTION_RESULT_NONE with nullptr
  iocore/eventsystem/I_Action.h
  iocore/net/I_UDPConnection.h
  iocore/net/P_UnixUDPConnection.h
  iocore/net/UnixNetProcessor.cc
  iocore/net/UnixUDPConnection.cc
Labels: Cleanup, Crash

#7119 URL::parse fixes for empty paths
  doc/developer-guide/api/functions/TSUrlHostGet.en.rst
  include/ts/ts.h
  plugins/header_rewrite/operators.cc
  proxy/hdrs/URL.cc
  proxy/hdrs/URL.h
  proxy/hdrs/unit_tests/test_URL.cc
  proxy/http/remap/RemapConfig.cc
  proxy/http2/unit_tests/test_HTTP2.cc
  tests/gold_tests/autest-site/microDNS.test.ext
  tests/gold_tests/pluginTest/header_rewrite/gold/set-redirect.gold
  tests/gold_tests/pluginTest/header_rewrite/header_rewrite_url.test.py
  tests/gold_tests/pluginTest/header_rewrite/rules/set_redirect.conf
  tests/gold_tests/remap/gold/remap-zero-200.gold
  tests/gold_tests/remap/regex_map.test.py
Labels: HTTP

#7154 Fixes H2 toggling using ssl_server_name.yaml
  iocore/net/SSLSNIConfig.cc
Labels: Bug

#7156 Fixes garbled logs when using %<vbn> log tag
  proxy/logging/LogAccess.cc
Labels: Backport, Bug, Logging

#7131 Don't make an error on duplicated RETIRE_CONNECTION frames
  iocore/net/quic/QUICAltConnectionManager.cc
  iocore/net/quic/QUICAltConnectionManager.h
Labels: QUIC

#7158 Fix lua plugin mem leak problem
  plugins/lua/ts_lua_mgmt.c
Labels: Lua, Plugins

#7157 rc: fixes systemd unit file stopping
  rc/trafficserver.service.in
Labels: Bug

#7160 Fix memory leaks in multiplexer plugin
  plugins/multiplexer/ats-multiplexer.cc
Labels: Leak, Plugins

#7161 Traffic Dump documentation for post_process.py
  doc/admin-guide/plugins/traffic_dump.en.rst
Labels: Documentation

#7159 MicroDNS Extension: handle different 'default' types
  tests/gold_tests/autest-site/microDNS.test.ext
Labels: AuTest

#7168 Fix #7167, make pep8 failure
  tools/autopep8.sh
Labels: Build

#7169 AuTest: Properly handle experimental plugins. (#6971)
  tests/gold_tests/autest-site/trafficserver_plugins.test.ext
  tests/gold_tests/body_factory/http204_response_plugin.test.py
  tests/gold_tests/command_argument/verify_global_plugin.test.py
  tests/gold_tests/command_argument/verify_remap_plugin.test.py
  tests/gold_tests/cont_schedule/schedule.test.py
  tests/gold_tests/cont_schedule/schedule_on_pool.test.py
  tests/gold_tests/cont_schedule/schedule_on_thread.test.py
  tests/gold_tests/cont_schedule/thread_affinity.test.py
  tests/gold_tests/continuations/double.test.py
  tests/gold_tests/continuations/double_h2.test.py
  tests/gold_tests/continuations/openclose.test.py
  tests/gold_tests/continuations/openclose_h2.test.py
  tests/gold_tests/logging/log_retention.test.py
  tests/gold_tests/null_transform/null_transform.test.py
  tests/gold_tests/pluginTest/cert_update/cert_update.test.py
  tests/gold_tests/pluginTest/client_context_dump/client_context_dump.test.py
  tests/gold_tests/pluginTest/cppapi/cppapi.test.py
  tests/gold_tests/pluginTest/test_hooks/hook_add.test.py
  tests/gold_tests/pluginTest/test_hooks/test_hooks.test.py
  tests/gold_tests/pluginTest/tsapi/tsapi.test.py
  tests/gold_tests/shutdown/emergency.test.py
  tests/gold_tests/shutdown/fatal.test.py
  tests/gold_tests/slow_post/slow_post.test.py
  tests/gold_tests/tls/tls_hooks_client_verify.test.py
  tests/gold_tests/tls/tls_hooks_verify.test.py
  tests/gold_tests/tls/tls_keepalive.test.py
  tests/gold_tests/tls_hooks/tls_hooks.test.py
  tests/gold_tests/tls_hooks/tls_hooks10.test.py
  tests/gold_tests/tls_hooks/tls_hooks11.test.py
  tests/gold_tests/tls_hooks/tls_hooks12.test.py
  tests/gold_tests/tls_hooks/tls_hooks13.test.py
  tests/gold_tests/tls_hooks/tls_hooks14.test.py
  tests/gold_tests/tls_hooks/tls_hooks15.test.py
  tests/gold_tests/tls_hooks/tls_hooks16.test.py
  tests/gold_tests/tls_hooks/tls_hooks17.test.py
  tests/gold_tests/tls_hooks/tls_hooks18.test.py
  tests/gold_tests/tls_hooks/tls_hooks2.test.py
  tests/gold_tests/tls_hooks/tls_hooks3.test.py
  tests/gold_tests/tls_hooks/tls_hooks4.test.py
  tests/gold_tests/tls_hooks/tls_hooks6.test.py
  tests/gold_tests/tls_hooks/tls_hooks7.test.py
  tests/gold_tests/tls_hooks/tls_hooks8.test.py
  tests/gold_tests/tls_hooks/tls_hooks9.test.py
  tests/tools/plugins/Makefile.inc
  tests/tools/plugins/null_transform.c
  tests/tools/plugins/request_buffer.c
Labels: AuTest

#7166 Fix #7164 Changing Warning to Debug and creating a stat
  iocore/hostdb/HostDB.cc
  iocore/hostdb/P_HostDBProcessor.h
Labels: HostDB

#7162 Removes references to non-existent function handle_conditional_headers
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransactHeaders.h
Labels: Cleanup

#7150 Additions to enable loading qat_engine
  iocore/net/P_SSLNetVConnection.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLUtils.cc
Labels: TLS

#7172 Fix leaks in BaseLogFiles.cc
  src/tscore/BaseLogFile.cc
Labels: ASAN, Leak

#7149 Traffic Dump: Record HTTP/2 priority.
  doc/developer-guide/api/functions/TSHttpTxnClientStreamIdGet.en.rst
  doc/developer-guide/api/functions/TSHttpTxnClientStreamPriorityGet.en.rst
  include/ts/apidefs.h.in
  include/ts/ts.h
  plugins/experimental/traffic_dump/session_data.cc
  plugins/experimental/traffic_dump/session_data.h
  plugins/experimental/traffic_dump/transaction_data.cc
  plugins/experimental/traffic_dump/transaction_data.h
  src/traffic_server/InkAPI.cc
  tests/gold_tests/pluginTest/traffic_dump/gold/200_http10.gold
  tests/gold_tests/pluginTest/traffic_dump/traffic_dump.test.py
  tests/gold_tests/pluginTest/traffic_dump/verify_replay.py
  tests/tools/lib/replay_schema.json
Labels: Plugins

#7181 TS_API for Note,Status,Warning,Alert,Fatal
  doc/developer-guide/api/functions/TSDebug.en.rst
  include/ts/ts.h
  include/tscore/Diags.h
  src/traffic_server/InkAPI.cc
Labels: Debug, Logging, Plugins, rel-9.0.0

#7178 AuTest: Reuse venv if it exists already
  tests/test-env-check.sh
Labels: AuTest

#7184 Add virtual destructor to QUICRTTProvider.
  iocore/net/quic/QUICTypes.h
Labels: Cleanup

#7180 Remove duplicate code
  iocore/net/UnixNet.cc
Labels: Cleanup

#7189 TextView: Add additional constructor tests.
  src/tscpp/util/unit_tests/test_TextView.cc
Labels: Tests

#7186 autopep8: avoid running on non-committed files.
  tests/gold_tests/autest-site/cli_tools.test.ext
  tests/gold_tests/autest-site/conditions.test.ext
  tests/gold_tests/autest-site/curl_header.test.ext
  tests/gold_tests/autest-site/init.cli.ext
  tests/gold_tests/autest-site/ip.test.ext
  tests/gold_tests/autest-site/microserver.test.ext
  tests/gold_tests/autest-site/setup.cli.ext
  tests/gold_tests/autest-site/traffic_replay.test.ext
  tests/gold_tests/autest-site/trafficserver_plugins.test.ext
  tools/autopep8.sh
  tools/git/pre-commit
Labels: Build

#7183 Emits log when OCSP fails to connect to server
  iocore/net/OCSPStapling.cc
  iocore/net/SSLNetProcessor.cc
Labels: SSL

#7134 Do not lose original inactivity timeout on disable
  iocore/net/P_UnixNet.h
Labels: Core

#7175 Fix TSHttpTxnServerPacket* API's to correctly update existing server connections
  src/traffic_server/InkAPI.cc
Labels: Network, TS API

#7063 Add an autest testcase for HTTP3
  tests/gold_tests/autest-site/trafficserver.test.ext
  tests/gold_tests/timeout/active_timeout.test.py
Labels: AuTest, HTTP/3, QUIC

#7188 Update sni outbound policy to allow directly setting the outbound SNI.
  doc/admin-guide/files/records.config.en.rst
  proxy/http/HttpSM.cc
Labels: Configuration, Plugins, SSL

#7193 Make custom xdebug HTTP header name available to other plugins.
  plugins/xdebug/xdebug.cc
Labels: Plugins

#7152 Updates the list of supported / linked Docs versions
  doc/static/languages.json
Labels: OnDocs

#7191 Emits log when OCSP fails to connect to server
  iocore/net/OCSPStapling.cc
  iocore/net/SSLNetProcessor.cc
Labels: Backport

#7194 Remove unused HttpUpdate mechanism
  proxy/http/HttpDebugNames.cc
  proxy/http/HttpProxyServerMain.cc
  proxy/http/HttpUpdateSM.cc
  proxy/http/HttpUpdateSM.h
  proxy/http/HttpUpdateTester.cc
  proxy/http/Makefile.am
Labels: Cleanup

#7182 Remove obsolete cdn_ HttpTransact vars
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
Labels: Cleanup, Core

#7197 Fix the active_timeout test to work without quic enabled
  tests/gold_tests/timeout/active_timeout.test.py
Labels: AuTest

#7198 KWF useless member function HttpSM::kill_this_async_hook().
  proxy/http/HttpSM.cc
  proxy/http/HttpSM.h
  proxy/http/remap/unit-tests/nexthop_test_stubs.cc
  src/traffic_quic/traffic_quic.cc
Labels: Cleanup, HttpSM

#7199 Rename ambiguous log variable
  example/plugins/cpp-api/logger_example/LoggerExample.cc
Labels: Build, Cleanup

#7207 Add duplicate header field processing when creating outgoing response
  proxy/http/HttpTransact.cc
Labels: Bug, HTTP

#7173 Adds new plugin: statichit
  plugins/Makefile.am
  plugins/experimental/statichit/Makefile.inc
  plugins/experimental/statichit/README.md
  plugins/experimental/statichit/statichit.cc
Labels: Plugins

#7202 Strip whitespaces after field-name and before the colon in headers from the origin
  proxy/hdrs/MIME.cc
  tests/gold_tests/headers/field_name_space.test.py
  tests/gold_tests/headers/gold/field_name_space.gold
Labels: Bug, RFC

#7210 Docs cleanup
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/plugins/access_control.en.rst
  doc/developer-guide/cache-architecture/architecture.en.rst
  plugins/experimental/statichit/statichit.cc
Labels: Documentation

#7206 If the weight is 0, the SRV record should be selected from the highest priority group
  iocore/hostdb/P_HostDBProcessor.h
Labels: HostDB

#7208 Add support for TS API for Note, Status, Warning, Alert
  doc/admin-guide/plugins/lua.en.rst
  plugins/lua/ts_lua_misc.c
Labels: Lua, Plugins

#6806 Support external log rotation tools via SIGUSR2
  include/tscore/Diags.h
  proxy/logging/Log.cc
  proxy/logging/Log.h
  proxy/logging/LogFile.cc
  proxy/logging/LogFile.h
  proxy/logging/LogObject.cc
  proxy/logging/LogObject.h
  src/traffic_manager/traffic_manager.cc
  src/traffic_server/traffic_server.cc
  src/tscore/Diags.cc
  tests/gold_tests/autest-site/trafficserver.test.ext
  tests/gold_tests/logging/sigusr2.test.py
  tests/gold_tests/logging/ts_process_handler.py
Labels: Logging

#7177 Create an explicit runroot.yaml for AuTests
  tests/gold_tests/autest-site/autest_runroot_layout.yml
  tests/gold_tests/autest-site/trafficserver.test.ext
Labels: AuTest

#7213 Follow redirection responses when refreshing stale cache objects.
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  tests/gold_tests/redirect/gold/redirect_stale.gold
  tests/gold_tests/redirect/redirect_stale.test.py
Labels: Cache

#7215 Log config reload: use new config for initialization
  proxy/logging/Log.cc
  proxy/logging/Log.h
  proxy/logging/LogBuffer.cc
  proxy/logging/LogBuffer.h
  proxy/logging/LogConfig.cc
  proxy/logging/LogObject.cc
  proxy/logging/LogObject.h
  proxy/logging/RolledLogDeleter.cc
  proxy/logging/YamlLogConfig.cc
  proxy/logging/unit-tests/test_RolledLogDeleter.cc
  tests/gold_tests/logging/log_retention.test.py
Labels: Logging

#7224 Fix renamed setting in default config
  configs/records.config.default.in
Labels: Configuration

#7225 Increment ssl_error_syscall only if not EOF
  doc/admin-guide/monitoring/statistics/core/ssl.en.rst
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLStats.cc
  iocore/net/SSLStats.h
Labels: Cleanup, Metrics, TLS

#7142 New option to dead server to not retry during dead period
  doc/admin-guide/files/records.config.en.rst
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
Labels: Feature, Incompatible
