Repository apache/trafficserver, pull requests merged in 2020-05, with the labels that each got.

#6723 Document ip_allow in sni.yaml
  doc/admin-guide/files/sni.yaml.en.rst
Labels: Documentation

#6712 Commenting EventIO methods
  iocore/net/P_UnixNet.h
Labels: Documentation

#6542 Rework stats over http so that it supports both a config file and the original path parameter
  doc/admin-guide/plugins/stats_over_http.en.rst
  plugins/stats_over_http/stats_over_http.c
Labels: Plugins

#6729 Fix a bug that current_active_client_connections doesn't decrease
  proxy/http2/Http2ConnectionState.cc
Labels: HTTP/2

#6728 Fix ink_endian.h to include an appropriate header file
  include/tscore/ink_endian.h
Labels: Core

#6721 HttpSM cleaning up non-sense pointer indirection
  proxy/http/HttpSM.cc
Labels: Cleanup, HTTP

#6726 Lua plugin: add ts.server_response.is_cacheable()
  doc/admin-guide/plugins/lua.en.rst
  plugins/lua/ts_lua_server_response.c
Labels: Lua

#6734 Update expired test certificates for cert_update
  tests/gold_tests/pluginTest/cert_update/ssl/client1.pem
  tests/gold_tests/pluginTest/cert_update/ssl/client2.pem
  tests/gold_tests/pluginTest/cert_update/ssl/server1.pem
  tests/gold_tests/pluginTest/cert_update/ssl/server2.pem
Labels: AuTest

#6682 Lua Plugin - Extend the crypto API with SHA-256 and HMAC functions.
  doc/admin-guide/plugins/lua.en.rst
  plugins/lua/ts_lua_crypto.c
  plugins/lua/ts_lua_string.c
  plugins/lua/ts_lua_string.h
Labels: Lua, Plugins

#6424 SSL: Introduce proxy.config.ssl.server.session_ticket.number
  doc/admin-guide/files/records.config.en.rst
  iocore/net/P_SSLCertLookup.h
  iocore/net/SSLUtils.cc
  mgmt/RecordsConfig.cc
Labels: OnDocs, TLS

#6735 Remove unused index for SSL application specific data
  iocore/net/SSLUtils.cc
Labels: Cleanup, TLS

#6739 Fix typos in comments
  iocore/eventsystem/I_EThread.h
  lib/records/RecConfigParse.cc
Labels: Cleanup

#6741 Remove using namespace std
  cmd/traffic_top/stats.h
  iocore/cache/CacheTest.cc
Labels: Build

#6745 Doc: Remove build warning
  doc/admin-guide/plugins/slice.en.rst
  doc/developer-guide/api/functions/TSTypes.en.rst
Labels: Documentation

#6744 Doc: Add example for ipv4/6 on dns nameserver
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#6740 Cleans up doubled words in documentation
  doc/Doxyfile
  doc/admin-guide/configuration/transparent-proxy/build.en.rst
  doc/admin-guide/files/cache.config.en.rst
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/logging/formatting.en.rst
  doc/admin-guide/plugins/access_control.en.rst
  doc/admin-guide/plugins/cachekey.en.rst
  doc/admin-guide/plugins/esi.en.rst
  doc/admin-guide/plugins/geoip_acl.en.rst
  doc/admin-guide/plugins/header_rewrite.en.rst
  doc/admin-guide/plugins/lua.en.rst
  doc/admin-guide/plugins/prefetch.en.rst
  doc/admin-guide/plugins/slice.en.rst
  doc/admin-guide/storage/index.en.rst
  doc/appendices/glossary.en.rst
  doc/developer-guide/api/functions/TSHttpTxnMilestoneGet.en.rst
  doc/developer-guide/api/functions/TSIOBufferReader.en.rst
  doc/developer-guide/api/functions/TSRemap.en.rst
  doc/developer-guide/api/functions/TSTypes.en.rst
  doc/developer-guide/cache-architecture/architecture.en.rst
  doc/developer-guide/cache-architecture/data-structures.en.rst
  doc/developer-guide/client-session-architecture.en.rst
  doc/developer-guide/core-architecture/heap.en.rst
  doc/developer-guide/internal-libraries/TextView.en.rst
  doc/developer-guide/internal-libraries/scalar.en.rst
  doc/developer-guide/plugins/remap-plugins.en.rst
  doc/uml/Makefile.am
Labels: Cleanup, Documentation

#6743 traffic_dump: refactor to make transactions written atomically
  .gitignore
  plugins/experimental/traffic_dump/Makefile.inc
  plugins/experimental/traffic_dump/global_variables.h
  plugins/experimental/traffic_dump/json_utils.cc
  plugins/experimental/traffic_dump/json_utils.h
  plugins/experimental/traffic_dump/sensitive_fields.h
  plugins/experimental/traffic_dump/session_data.cc
  plugins/experimental/traffic_dump/session_data.h
  plugins/experimental/traffic_dump/traffic_dump.cc
  plugins/experimental/traffic_dump/transaction_data.cc
  plugins/experimental/traffic_dump/transaction_data.h
  plugins/experimental/traffic_dump/unit_tests/test_json_utils.cc
  plugins/experimental/traffic_dump/unit_tests/test_sensitive_fields.cc
  plugins/experimental/traffic_dump/unit_tests/unit_test_main.cc
  tests/gold_tests/pluginTest/traffic_dump/gold/200.gold
  tests/gold_tests/pluginTest/traffic_dump/gold/4_byte_response_body.gold
  tests/gold_tests/pluginTest/traffic_dump/gold/two_transactions.gold
  tests/gold_tests/pluginTest/traffic_dump/traffic_dump.test.py
  tests/gold_tests/pluginTest/traffic_dump/verify_replay.py
  tests/tools/lib/replay_schema.json
Labels: Plugins

#6750 backports parent.config ignore_self_detect flag to 8.1.x
  doc/admin-guide/files/parent.config.en.rst
  iocore/cache/test/stub.cc
  proxy/ParentConsistentHash.cc
  proxy/ParentRoundRobin.cc
  proxy/ParentSelection.cc
  proxy/ParentSelection.h
  src/traffic_server/HostStatus.cc
Labels: Backport, Parent Proxy

#6742 gcc10: fixed clearing an object of non-trivial type for wccp
  src/wccp/WccpLocal.h
Labels: Build, WCCP

#6757 ASAN: Fixed one definition rule violation
  lib/records/unit_tests/unit_test_main.cc
Labels: ASAN

#6756 Correct `schedule_every_local` to schedule locally
  iocore/eventsystem/P_UnixEThread.h
Labels: event_system

#6758 Fix set manipulation in dual cert resolution
  iocore/net/SSLUtils.cc
Labels: Bug, TLS

#6761 Disable remap-stats test until we can reliably wait for metrics
  tests/gold_tests/pluginTest/remap_stats/remap_stats.test.py
Labels: AuTest

#6762 Make chunked_encoding test more reliable by killing nc process
  tests/gold_tests/chunked_encoding/case4.sh
Labels: AuTest

#6730 Add HttpTransact::get_max_age and TSHttpTxnGetMaxAge
  include/ts/ts.h
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  src/traffic_server/InkAPI.cc
Labels: TS API

#6754 Enforce Active Connection limits
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/monitoring/statistics/core/network-io.en.rst
  iocore/net/Net.cc
  iocore/net/P_Net.h
  iocore/net/UnixNet.cc
  proxy/PluginVC.cc
  proxy/http/Http1ClientSession.cc
  proxy/http2/Http2ConnectionState.cc
Labels: Capacity Tuning, Connection Timeouts, Throttling

#6751 Script to find mutexes/futexes that are contending
  tools/gdb_mutex_contention.pl
Labels: Tools

#6755 Add metrics to track default inactivity timed out connections
  doc/admin-guide/monitoring/statistics/core/network-io.en.rst
  iocore/net/I_NetVConnection.h
  iocore/net/Net.cc
  iocore/net/NetEvent.h
  iocore/net/P_Net.h
  iocore/net/P_UnixNetVConnection.h
  iocore/net/UnixNet.cc
  iocore/net/UnixNetVConnection.cc
  proxy/PluginVC.cc
  proxy/PluginVC.h
Labels: Connection Timeouts, Metrics

#6759 Promote netvc to ProxySession
  proxy/ProxySession.cc
  proxy/ProxySession.h
  proxy/http/Http1ClientSession.cc
  proxy/http/Http1ClientSession.h
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ClientSession.h
  proxy/http3/Http3Session.cc
  proxy/http3/Http3Session.h
Labels: Core

#6763 Accept handling VIO events
  proxy/ProtocolProbeSessionAccept.cc
Labels: HTTP, HTTP/2, HTTP/3, Proxy Protocol

#6764 Accept Handling VIO events SSL
  iocore/net/SSLNextProtocolAccept.cc
Labels: TLS

#6760 Do not fail multicert load if line does not create entry
  iocore/net/QUICMultiCertConfigLoader.cc
  iocore/net/SSLUtils.cc
Labels: TLS

#6768 clang-analyzer: Fix dead nested assignment issues
  iocore/dns/DNSConnection.cc
  iocore/net/Connection.cc
  iocore/net/UnixUDPNet.cc
  mgmt/api/EventControlMain.cc
  plugins/esi/esi.cc
  plugins/experimental/access_control/access_control.cc
  plugins/experimental/mp4/mp4_meta.cc
  proxy/http/remap/RemapConfig.cc
  tools/jtest/jtest.cc
Labels: clang-analyzer

#6772 Ensure inactivity timeout is not set when passed in timeout value is 0
  iocore/net/UnixNetVConnection.cc
Labels: Connection Timeouts

#6767 Lua plugin: add ts.server_response.get_maxage()
  doc/admin-guide/plugins/lua.en.rst
  plugins/lua/ts_lua_server_response.c
Labels: Lua, Plugins

#6773 Add back reading config for handshake timeout
  iocore/net/SSLConfig.cc
Labels: TLS

#6770 Weird characters in debug message
  proxy/http/remap/PluginDso.cc
Labels: Bug

#6774 Fixed `AddressSanitizer: odr-violation`
  proxy/http/remap/Makefile.am
Labels: Bug, Core, Plugins

#6779 8.1.x backport: header_rewrite: this fixes parsing where the [ ] section gets merged into values
  plugins/header_rewrite/header_rewrite.cc
  plugins/header_rewrite/header_rewrite_test.cc
  plugins/header_rewrite/parser.cc
  plugins/header_rewrite/parser.h
  plugins/header_rewrite/ruleset.cc
  plugins/header_rewrite/value.cc
Labels: Plugins

#6781 1. Set a non-zero default value for TLS Client Handshake Timeout
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
Labels: Connection Timeouts, Documentation

#6780 Use Proxy-Connection iff parent_is_proxy=true
  proxy/http/HttpTransact.cc
Labels: Parent Proxy

#6785 clang-analyzer: Fix dead nested assignment issues [8.1.x]
  iocore/dns/DNSConnection.cc
  iocore/net/Connection.cc
  iocore/net/UnixUDPNet.cc
  mgmt/api/EventControlMain.cc
  plugins/esi/esi.cc
  plugins/experimental/access_control/access_control.cc
  plugins/experimental/mp4/mp4_meta.cc
  proxy/http/remap/RemapConfig.cc
  tools/jtest/jtest.cc
Labels: clang-analyzer

#6786 HPACK: send back an error to the client when the index is invalid
  proxy/http2/HPACK.cc
Labels: HTTP/2

#6789 Adding HTTP Status code 451 for Unavailable For Legal Reasons (RFC 7725)
  include/tscpp/api/HttpStatus.h
Labels: CPP API, HTTP

#6787 HPACK: send back an error to the client when the index is invalid
  proxy/http2/HPACK.cc
Labels: HTTP/2

#6788 HPACK: send back an error to the client when the index is invalid
  proxy/http2/HPACK.cc
Labels: HTTP/2

#6790 clang-analyzer: eliminate identical conditions
  proxy/http/HttpTransact.cc
Labels: clang-analyzer

#6791 clang-analyzer: code clone in get_proxy_protocol_addr
  iocore/net/I_NetVConnection.h
  iocore/net/P_NetVConnection.h
Labels: clang-analyzer

#6753 Fix HPACK Dynamic Table Cleanup
  proxy/http2/HPACK.cc
  proxy/http2/HPACK.h
  proxy/http2/unit_tests/test_HpackIndexingTable.cc
Labels: HTTP/2

#6803 fixes issue 6765, memory leak in unit test
  proxy/http/remap/unit-tests/nexthop_test_stubs.cc
Labels: Backport, Bug, Leak

#6736 Generalize callbacks for TLS session resumption
  iocore/net/Makefile.am
  iocore/net/P_SSLNetVConnection.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLSessionTicket.cc
  iocore/net/SSLUtils.cc
  iocore/net/TLSSessionResumptionSupport.cc
  iocore/net/TLSSessionResumptionSupport.h
Labels: TLS

#6800 Add TXN_CLOSE hook to CPPAPI TransactionPlugin
  include/tscpp/api/Plugin.h
  include/tscpp/api/TransactionPlugin.h
  src/tscpp/api/GlobalPlugin.cc
  src/tscpp/api/utils_internal.cc
Labels: CPP API

#6686 Fixes to hostDB to avoid event and memory leaks
  iocore/hostdb/HostDB.cc
  iocore/hostdb/P_HostDBProcessor.h
Labels: HostDB, OnDocs

#6746 Add an optional ramcache setting to volume.config to disable it
  doc/admin-guide/files/volume.config.en.rst
  doc/admin-guide/storage/index.en.rst
  iocore/cache/Cache.cc
  iocore/cache/CacheHosting.cc
  iocore/cache/P_CacheHosting.h
  iocore/cache/P_CacheVol.h
Labels: Cache

#6814 Make post_slow_server Au test work in Docker container.
  tests/gold_tests/post_slow_server/check.sh
  tests/gold_tests/post_slow_server/post_slow_server.test.py
  tests/gold_tests/post_slow_server/server.sh
Labels: AuTest

#6816 Fixes remaining memory leaks with nexthop strategy unit tests
  proxy/http/remap/NextHopStrategyFactory.cc
  proxy/http/remap/unit-tests/nexthop_test_stubs.cc
  proxy/http/remap/unit-tests/nexthop_test_stubs.h
  proxy/http/remap/unit-tests/test_NextHopConsistentHash.cc
Labels: ASAN, Backport, Bug

#6769 ip_resolve - Make config variable overridable
  doc/admin-guide/files/records.config.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  include/ts/apidefs.h.in
  include/tscore/ink_resolver.h
  plugins/lua/ts_lua_http_config.c
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  src/shared/overridable_txn_vars.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/InkAPITest.cc
  src/tscore/ink_res_mkquery.cc
  tests/gold_tests/remap/gold/remap-DNS-ipv6-200.gold
  tests/gold_tests/remap/gold/remap-ip-resolve.gold
  tests/gold_tests/remap/remap_ip_resolve.test.py
Labels: HostDB

#6815 Doc updates for tunnel_route and ip_allow interaction.
  doc/admin-guide/files/ip_allow.yaml.en.rst
  doc/admin-guide/files/sni.yaml.en.rst
  doc/admin-guide/layer-4-routing.en.rst
Labels: Documentation

#6824 Fix test certs in client_context_dump
  tests/gold_tests/pluginTest/client_context_dump/client_context_dump.test.py
  tests/gold_tests/pluginTest/client_context_dump/ssl/one.com.pem
  tests/gold_tests/pluginTest/client_context_dump/ssl/two.com.pem
Labels: AuTest

#6827 Make chunked encoding test more resilient
  tests/gold_tests/chunked_encoding/case4.sh
  tests/gold_tests/chunked_encoding/chunked_encoding.test.py
Labels: AuTest

#6807 Add le32toh and htole32 for macOS
  include/tscore/ink_endian.h
Labels: Core

#6825 Clear handling tracked events of Http2Stream
  proxy/http2/Http2Stream.cc
Labels: Crash, HTTP/2

#6817 lua plugin: fix for incorrectly injecting global plugin stats
  plugins/lua/ts_lua.c
  tests/gold_tests/pluginTest/lua/global.lua
  tests/gold_tests/pluginTest/lua/gold/metrics.stdout.gold
  tests/gold_tests/pluginTest/lua/lua_states_stats.test.py
Labels: Lua, Plugins

#6711 cache_range_request autests: make more robust and clean up.
  tests/gold_tests/pluginTest/cache_range_requests/cache_range_requests.test.py
  tests/gold_tests/pluginTest/cache_range_requests/gold/404.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/frange.stderr.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/frange.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/full.stderr.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/full.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/inner.stderr.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/inner.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/last.stderr.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/last.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/pselect.stdout.gold
  tests/gold_tests/pluginTest/cache_range_requests/gold/pselect_none.stdout.gold
Labels: AuTest

#6820 HostDB - change HostResPreferenceOrder type to std::array.
  include/tscore/ink_resolver.h
  lib/records/RecHttp.cc
  lib/records/unit_tests/unit_test_main.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpSessionAccept.h
  src/tscore/ink_res_init.cc
  src/tscore/ink_res_mkquery.cc
Labels: DNS

#6818 Add CSV output as an option format for stats_over_http
  doc/admin-guide/plugins/stats_over_http.en.rst
  plugins/stats_over_http/stats_over_http.c
Labels: Plugins

#6813 Adding a basic ip_allow test.
  tests/gold_tests/ip_allow/gold/200.gold
  tests/gold_tests/ip_allow/gold/403.gold
  tests/gold_tests/ip_allow/gold/403_h2.gold
  tests/gold_tests/ip_allow/ip_allow.test.py
  tests/gold_tests/ip_allow/ssl/server.key
  tests/gold_tests/ip_allow/ssl/server.pem
Labels: AuTest
