Repository apache/trafficserver, pull requests merged in 2020-03, with the labels that each got.

#6462 x-remap ignoring age in gold file
  tests/gold_tests/pluginTest/xdebug/x_remap/out.gold
Labels: Tests

#6470 Remove update to unused variable
  proxy/http2/Http2ConnectionState.cc
Labels: clang-analyzer

#6166 Make sure time is consistent between calculations
  iocore/eventsystem/UnixEThread.cc
Labels: Core, event_system

#6460 Make traffic_manager be flexible when opening config files.
  mgmt/ConfigManager.cc
  mgmt/ConfigManager.h
  mgmt/FileManager.cc
  mgmt/FileManager.h
  src/traffic_manager/AddConfigFilesHere.cc
Labels: Cleanup, Configuration

#6464 cache_range_requests plugin: detect and handle TSCacheUrlSet failures…
  doc/admin-guide/plugins/cache_range_requests.en.rst
  plugins/cache_range_requests/cache_range_requests.cc
  tests/gold_tests/pluginTest/cache_range_requests/cache_range_requests_cachekey.test.py
  tests/gold_tests/pluginTest/cache_range_requests/cache_range_requests_ims.test.py
Labels: Plugins

#6421 Issue #6400 - Add config option to enable/disable dynamic plugin reload feature
  doc/admin-guide/files/records.config.en.rst
  doc/developer-guide/design-documents/reloading-plugins.en.rst
  mgmt/RecordsConfig.cc
  proxy/Plugin.cc
  proxy/Plugin.h
  proxy/http/remap/PluginDso.cc
  proxy/http/remap/PluginDso.h
  proxy/http/remap/PluginFactory.cc
  proxy/http/remap/PluginFactory.h
  proxy/http/remap/RemapConfig.cc
  proxy/http/remap/unit-tests/plugin_testing_common.cc
  proxy/http/remap/unit-tests/plugin_testing_common.h
  proxy/http/remap/unit-tests/test_PluginFactory.cc
  src/traffic_server/traffic_server.cc
Labels: Configuration, Documentation, Plugins

#6475 Remove noisy mutex warning
  iocore/eventsystem/UnixEThread.cc
Labels: Cleanup

#6474 Remove --read_core option
  doc/appendices/command-line/traffic_server.en.rst
  src/traffic_server/CoreUtils.cc
  src/traffic_server/CoreUtils.h
  src/traffic_server/Makefile.inc
  src/traffic_server/traffic_server.cc
Labels: Cleanup

#6476 Fixed logging docs typos
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/logging/rotation.en.rst
Labels: Bug, Documentation

#6471 Removes some things deprecated from older versions
  doc/developer-guide/api/functions/TSContScheduleOnPool.en.rst
  doc/developer-guide/api/types/TSThreadPool.en.rst
  include/ts/apidefs.h.in
  include/ts/ts.h
  src/traffic_server/InkAPI.cc
Labels: Cleanup

#6461 Reduce minimum config files needed for golden_tests.
  tests/gold_tests/autest-site/min_cfg/cache.config
  tests/gold_tests/autest-site/min_cfg/hosting.config
  tests/gold_tests/autest-site/min_cfg/logging.yaml
  tests/gold_tests/autest-site/min_cfg/parent.config
  tests/gold_tests/autest-site/min_cfg/plugin.config
  tests/gold_tests/autest-site/min_cfg/readme.txt
  tests/gold_tests/autest-site/min_cfg/records.config
  tests/gold_tests/autest-site/min_cfg/remap.config
  tests/gold_tests/autest-site/min_cfg/sni.yaml
  tests/gold_tests/autest-site/min_cfg/socks.config
  tests/gold_tests/autest-site/min_cfg/splitdns.config
  tests/gold_tests/autest-site/min_cfg/ssl_multicert.config
  tests/gold_tests/autest-site/min_cfg/volume.config
Labels: AuTest

#6469 Delay cleanup when cache write continues after early client response
  proxy/http/Http1ClientSession.cc
  proxy/http2/Http2ClientSession.cc
Labels: Crash, HTTP

#6477 traffic_dump: Fixing content:size collection.
  plugins/experimental/traffic_dump/post_process.py
  plugins/experimental/traffic_dump/traffic_dump.cc
  tests/gold_tests/pluginTest/traffic_dump/gold/post_with_body.gold
  tests/gold_tests/pluginTest/traffic_dump/traffic_dump.test.py
  tests/gold_tests/pluginTest/traffic_dump/verify_replay.py
Labels: Plugins

#6463 [CPPAPI] Provide access to TSRemapRequestInfo in RemapPlugins.
  include/tscpp/api/RemapPlugin.h
  src/tscpp/api/RemapPlugin.cc
Labels: CPP API, Feature

#6485 Be explicit about RTLD_LOCAL, defaults varies on platforms
  proxy/http/remap/PluginDso.cc
  proxy/http/remap/unit-tests/test_PluginFactory.cc
Labels: Cleanup, Core

#6480 Remove some outdated files.
  CRUFT.txt
  LAYOUT
  REVIEWERS
  proxy/ClassH.txt
  proxy/issues.txt
Labels: Cleanup

#6486 Issue 3546: Add "overridable" to the configuration variable description.
  CMakeLists.txt
  doc/developer-guide/config-vars.en.rst
  include/shared/overridable_txn_vars.h
  src/shared/overridable_txn_vars.cc
  src/traffic_ctl/Makefile.inc
  src/traffic_ctl/config.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/Makefile.inc
Labels: Commands, Configuration

#6488 Bikeshedding some code structures for reloadable plugins config
  proxy/Plugin.cc
  proxy/Plugin.h
  proxy/http/remap/unit-tests/plugin_testing_common.cc
Labels: Cleanup, OnDocs

#6490 Fix a compile warning
  iocore/net/quic/QUICTLS_boringssl.cc
Labels: QUIC

#6491 LGTM: Fix comparing int8_t with wider type
  src/tscpp/util/TextView.cc
Labels: Cleanup, lgtm

#6492 Add null check to fix error tunnel crash
  proxy/http/HttpTunnel.cc
Labels: Crash, HTTP

#6487 Fix session reuse plugin shutdown crashes and cleanups
  plugins/experimental/ssl_session_reuse/src/Config.h
  plugins/experimental/ssl_session_reuse/src/common.cc
  plugins/experimental/ssl_session_reuse/src/common.h
  plugins/experimental/ssl_session_reuse/src/message.h
  plugins/experimental/ssl_session_reuse/src/openssl_utils.cc
  plugins/experimental/ssl_session_reuse/src/publish.cc
  plugins/experimental/ssl_session_reuse/src/session_process.cc
  plugins/experimental/ssl_session_reuse/src/ssl_key_utils.cc
  plugins/experimental/ssl_session_reuse/src/stek.h
  plugins/experimental/ssl_session_reuse/src/subscriber.cc
  plugins/experimental/ssl_session_reuse/src/subscriber.h
Labels: Plugins

#6493 Make all_headers test more resilient to timing
  tests/gold_tests/logging/all_headers.test.py
  tests/gold_tests/logging/all_headers_sanitizer.py
Labels: Tests

#6499 Doc: traffic_manager - Add documentation for exp backoff and config.
  doc/admin-guide/files/records.config.en.rst
  doc/appendices/command-line/traffic_manager.en.rst
Labels: Documentation

#6501 Remove method that does nothing.
  include/tscpp/api/Url.h
  src/tscpp/api/Url.cc
  src/tscpp/api/utils_internal.cc
Labels: Cleanup

#6500 traffic_dump: Make the client-request node gathered in a global hook
  plugins/experimental/traffic_dump/traffic_dump.cc
Labels: Plugins

#6502 Change Proxy Header Regression tests into Catch unit tests.
  .gitignore
  include/tscore/Regression.h
  proxy/hdrs/HdrTest.cc
  proxy/hdrs/HdrTest.h
  proxy/hdrs/Makefile.am
  proxy/hdrs/unit_tests/test_Hdrs.cc
  src/traffic_server/traffic_server.cc
Labels: HTTP, Tests

#6503 Doc: connection.match default value update
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#6333 XDebug: Always append to the X- header, rather than prepend
  doc/admin-guide/plugins/xdebug.en.rst
  plugins/xdebug/xdebug.cc
Labels: Incompatible, OnDocs, Plugins

#6483 Rework server side SSL_CTX creation to better handle dual_cert mismatches
  iocore/net/P_SSLCertLookup.h
  iocore/net/P_SSLUtils.h
  iocore/net/QUICMultiCertConfigLoader.cc
  iocore/net/QUICMultiCertConfigLoader.h
  iocore/net/SSLUtils.cc
  tests/gold_tests/tls/ssl/signed-foo-ec.key
  tests/gold_tests/tls/ssl/signed-foo-ec.pem
  tests/gold_tests/tls/ssl/signed-san-ec.key
  tests/gold_tests/tls/ssl/signed-san-ec.pem
  tests/gold_tests/tls/ssl/signed-san.key
  tests/gold_tests/tls/ssl/signed-san.pem
  tests/gold_tests/tls/ssl/signer.pem
  tests/gold_tests/tls/tls_check_dual_cert_selection.test.py
Labels: TLS

#6494 Cleanup: check activity of Http2Stream by ActivityCop
  iocore/net/NetTimeout.h
  proxy/http2/Http2ConnectionState.h
  proxy/http2/Http2Stream.cc
  proxy/http2/Http2Stream.h
Labels: HTTP/2, Network

#6481 traffic_manager - Exponential backoff - Make values configurable
  mgmt/RecordsConfig.cc
  src/traffic_manager/traffic_manager.cc
Labels: Configuration, Manager

#6516 Fix SDK_API_TSSslServerContextCreate
  iocore/net/SSLUtils.cc
Labels: Tests

#6515 Check the exit value of the regression test
  ci/jenkins/bin/github.sh
  ci/jenkins/bin/regression.sh
Labels: Build

#6468 Refactor and generalize the User Arg concept, add global
  doc/developer-guide/api/functions/TSHttpArgs.en.rst
  doc/developer-guide/api/functions/TSTypes.en.rst
  doc/developer-guide/api/functions/TSUserArgs.en.rst
  doc/developer-guide/api/functions/TSVConnArgs.en.rst
  doc/developer-guide/design-documents/reloading-plugins.en.rst
  example/plugins/c-api/remap/remap.cc
  example/plugins/c-api/vconn_args/vconn_args.cc
  include/ts/apidefs.h.in
  include/ts/ts.h
  include/tscore/PluginUserArgs.h
  iocore/eventsystem/I_VConnection.h
  iocore/net/I_NetVConnection.h
  plugins/authproxy/authproxy.cc
  plugins/esi/combo_handler.cc
  plugins/experimental/ja3_fingerprint/ja3_fingerprint.cc
  plugins/experimental/remap_stats/remap_stats.cc
  plugins/experimental/traffic_dump/traffic_dump.cc
  plugins/xdebug/Cleanup.h
  proxy/InkAPIInternal.h
  proxy/ProxySession.cc
  proxy/ProxySession.h
  proxy/http/HttpSM.h
  proxy/http/HttpTransact.h
  src/traffic_server/InkAPI.cc
  src/tscpp/api/utils_internal.cc
  tests/tools/plugins/user_args.cc
Labels: Incompatible, OnDocs, Plugins

#6513 Moves hosting.config finished loading message outside of parsing loop
  iocore/cache/CacheHosting.cc
Labels: Logging

#6518 Fixes a bug where HostStatus::getHostStatus() creates too many stats.
  proxy/ParentSelection.cc
  src/traffic_server/HostStatus.cc
Labels: Backport, Bug, OnDocs, Parent Proxy

#6517 Make traffic_ctl limp along for now with large records.snap
  src/traffic_ctl/traffic_ctl.cc
Labels: Metrics, OnDocs, Tools

#6523 Removes noisy log statement from xdebug
  plugins/xdebug/xdebug.cc
Labels: Plugins

#6524 Require 1.1.1 as minimum openssl lib version for tls_check_dual_cert_selection Au test.
  tests/gold_tests/tls/tls_check_dual_cert_selection.test.py
Labels: AuTest

#6519 Adds support for configure option --enable-yaml-headers
  build/yaml-cpp.m4
  configure.ac
  lib/Makefile.am
Labels: YAML

#6505 Created remap_stats au test
  tests/gold_tests/pluginTest/remap_stats/remap_stats.test.py
Labels: AuTest

#6526 Fixes crash in SNIConfigParams::cleanup()
  iocore/net/SSLSNIConfig.cc
Labels: Configuration, Crash

#6534 Ignore MgmtMessageHdr if ProcessManager is not running
  mgmt/ProcessManager.cc
Labels: Backport

#6535 Add MIMEHdr Garbage Collection to HPACK Dynamic Table
  proxy/hdrs/HdrHeap.cc
  proxy/hdrs/HdrHeap.h
  proxy/http2/HPACK.cc
  proxy/http2/HPACK.h
Labels: Backport

#6540 Disables "virtual host not used with AWS auth v4" error in s3_auth
  plugins/s3_auth/s3_auth.cc
Labels: Plugins

#6539 Convert tscore regression tests to Catch unit tests.
  src/tscore/Makefile.am
  src/tscore/Tokenizer.cc
  src/tscore/Version.cc
  src/tscore/unit_tests/test_Extendible.cc
  src/tscore/unit_tests/test_Tokenizer.cc
  src/tscore/unit_tests/test_Version.cc
Labels: Tests

#6548 Remove unused unit test source files in src/tscore.
  src/tscore/IntrusivePtrTest.cc
  src/tscore/Makefile.am
  src/tscore/TestHttpHeader.cc
  src/tscore/load_http_hdr.cc
Labels: Cleanup

#6531 Allow lo interface in list of system stats
  plugins/experimental/system_stats/system_stats.c
Labels: Plugins

#6512 Doc: traffic_manager - Add mention for retry sleep time variance
  doc/appendices/command-line/traffic_manager.en.rst
Labels: Documentation

#6532 Add FetchSM support to dechunking in non-streaming mode with new TS API TSFetchFlagSet
  doc/developer-guide/api/functions/TSFetchCreate.en.rst
  include/ts/experimental.h
  src/traffic_server/FetchSM.cc
  src/traffic_server/FetchSM.h
  src/traffic_server/InkAPI.cc
Labels: FetchSM, HTTP, TSFetchUrl

#6550 Fixes some tls autests on macOS
  tests/gold_tests/tls/tls_client_cert.test.py
  tests/gold_tests/tls/tls_tunnel.test.py
Labels: AuTest, Tests

#6556 Removes copypasta curl text from tests and removes checks for curl
  tests/gold_tests/cache/cache-generation-disjoint.test.py
  tests/gold_tests/chunked_encoding/chunked_encoding.test.py
  tests/gold_tests/chunked_encoding/chunked_encoding_h2.test.py
  tests/gold_tests/h2/h2disable.test.py
  tests/gold_tests/h2/h2disable_no_accept_threads.test.py
  tests/gold_tests/h2/h2enable.test.py
  tests/gold_tests/h2/h2enable_no_accept_threads.test.py
  tests/gold_tests/h2/http2.test.py
  tests/gold_tests/h2/http2_priority.test.py
  tests/gold_tests/h2/nghttp.test.py
  tests/gold_tests/pluginTest/multiplexer/multiplexer.test.py
  tests/gold_tests/timeout/active_timeout.test.py
  tests/gold_tests/timeout/inactive_timeout.test.py
  tests/gold_tests/tls/tls_client_versions.test.py
Labels: AuTest

#6559 Convert unit tests for sslheaders plugin to Catch.
  plugins/experimental/sslheaders/Makefile.inc
  plugins/experimental/sslheaders/test_sslheaders.cc
  plugins/experimental/sslheaders/unit_tests/test_sslheaders.cc
  plugins/experimental/sslheaders/unit_tests/unit_test_main.cc
Labels: Tests

#6530 Convert Mime and URL unit tests in proxy/hdrs to Catch.
  proxy/hdrs/Makefile.am
  proxy/hdrs/URL.cc
  proxy/hdrs/test_mime.cc
  proxy/hdrs/unit_tests/test_URL.cc
  proxy/hdrs/unit_tests/test_mime.cc
Labels: Tests

#6563 Removed some unused declarations in HttpTransact
  proxy/http/HttpTransact.h
Labels: Cleanup

#6565 Fixed build issue with Ubuntu 16 debug
  include/tscore/PluginUserArgs.h
Labels: Build

#6506 In Au tests, poll for excretion of log file rather than waiting fixed delay.
  tests/gold_tests/h2/httpbin.test.py
  tests/gold_tests/logging/custom-log.test.py
  tests/gold_tests/logging/log-field.test.py
  tests/gold_tests/logging/log-filter.test.py
  tests/gold_tests/logging/new_log_flds.test.py
  tests/tools/condwait
Labels: AuTest

#6555 Enable logging autests on macOS, clarify why Linux is required
  tests/.gitignore
  tests/gold_tests/logging/custom-log.test.py
  tests/gold_tests/logging/log-field.test.py
  tests/gold_tests/logging/log-filter.test.py
  tests/gold_tests/logging/new_log_flds.test.py
Labels: AuTest

#6564 Convert single regression test in iocore/eventsystem/SocketManager.cc to Catch.
  iocore/eventsystem/SocketManager.cc
  iocore/eventsystem/unit_tests/test_EventSystem.cc
Labels: Tests

#6544 Convert proxy/logging unit tests to use Catch.
  proxy/logging/Makefile.am
  proxy/logging/test_LogUtils.cc
  proxy/logging/unit-tests/test_LogUtils.cc
  proxy/logging/unit-tests/test_LogUtils.h
Labels: Tests

#6553 Options to roll empty logs and log trimming (8.1.x)
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/logging/rotation.en.rst
  mgmt/RecordsConfig.cc
  proxy/logging/LogConfig.cc
  proxy/logging/LogConfig.h
  proxy/logging/LogFile.cc
  proxy/logging/LogFile.h
  proxy/logging/LogObject.cc
  proxy/logging/LogObject.h
  proxy/logging/YamlLogConfig.cc
  src/traffic_server/InkAPI.cc
Labels: Core, Logging

#6533 Do not change stream state from HALF_CLOSED_REMOTE with CONTINUATION frame
  proxy/http2/Http2Stream.cc
  tests/gold_tests/h2/gold/http2_8_stderr.gold
  tests/gold_tests/h2/gold/http2_8_stdout.gold
  tests/gold_tests/h2/http2.test.py
  tests/gold_tests/h2/rules/huge_resp_hdrs.conf
Labels: Backport

#6567 Moved printing the incoming headers for debug before remapping
  proxy/http/HttpTransact.cc
Labels: Debug

#6570 Make request/response body as an option for AuTest microserver
  tests/gold_tests/autest-site/microserver.test.ext
Labels: AuTest

#6580 Coalesce empty objects in HdrHeap
  proxy/hdrs/HdrHeap.cc
Labels: Backport

#6576 Ensure TSContSchedule API family are called from an EThread.
  doc/developer-guide/api/functions/TSContSchedule.en.rst
  doc/developer-guide/api/functions/TSContScheduleOnPool.en.rst
  doc/developer-guide/api/functions/TSContScheduleOnThread.en.rst
  src/traffic_server/InkAPI.cc
Labels: Continuations, Plugins, Schedule, Threads

#6577 When using TSContSchedule() and TSContScheduleAPI() set the calling thread as the thread affinity when not already set
  src/traffic_server/InkAPI.cc
Labels: Continuations, Plugins, Schedule, Threads

#6573 SSL: Always renew TLS Session Tickets iff TLSv1.3 is being used
  iocore/net/SSLSessionTicket.cc
Labels: TLS

#6579 Fix tunnel crash
  proxy/http/HttpTunnel.cc
Labels: Crash, OnDocs

#6558 Support body factory template suppression for internal requests
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  proxy/http/HttpBodyFactory.cc
Labels: Body Factory, Configuration, HTTP

#6587 [Doc][DevGuide][TSStatSync] Fixing documentation for SUM and COUNT types
  doc/developer-guide/api/types/TSStatSync.en.rst
Labels: Documentation, Metrics

#6554 Convert mgmt/utils unit tests to use Catch.
  .gitignore
  mgmt/utils/Makefile.am
  mgmt/utils/unit_tests/test_marshall.cc
  mgmt/utils/unit_tests/unit_test_main.cc
Labels: Tests

#6508 Include start line of HTTP messages in xdebug probe output.
  plugins/xdebug/xdebug_headers.cc
  tests/gold_tests/pluginTest/xdebug/x_remap/out.gold
Labels: Plugins

#6590 Skip compressible content type check with null strings.
  plugins/compress/configuration.cc
Labels: Bug

#6594 Remove extra new line detection in 303 gold file
  tests/gold_tests/pluginTest/header_rewrite/gold/header_rewrite-303.gold
Labels: AuTest

#6582 Fix strict round robin cur_index increment
  proxy/ParentRoundRobin.cc
Labels: Backport

#6585 url_sig: fix memory leak with urlParse and pristine flag (8.1.x)
  plugins/experimental/url_sig/url_sig.c
  tests/gold_tests/pluginTest/url_sig/url_sig.test.py
Labels: Backport

#6595 Fix httpbin autest for 8.1.x
  tests/gold_tests/h2/gold/httpbin_0_stdout.gold
  tests/gold_tests/h2/httpbin.test.py
Labels: AuTest

#6591 Cleanup: fix a inline function style
  proxy/http2/Http2Stream.h
Labels: Cleanup

#6568 Fix PUSH_PROMISE frame payload length
  .gitignore
  proxy/http2/HTTP2.h
  proxy/http2/Http2Frame.h
  proxy/http2/Makefile.am
  proxy/http2/unit_tests/main.cc
  proxy/http2/unit_tests/test_Http2Frame.cc
Labels: HTTP/2

#6597 HTTP/2 backports for 8.1.x (part 2)
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ClientSession.h
  proxy/http2/Http2Stream.cc
  proxy/http2/Http2Stream.h
Labels: Backport

#6600 Remove enable_tls option and set select ports to false. This passed …
  tests/gold_tests/h2/http2.test.py
Labels: AuTest

#6601 Fixes Issue #6321 caused when proxy.config.http.no_dns_just_forward_to_parent
  proxy/ParentSelection.cc
Labels: Backport
