Repository apache/trafficserver, pull requests merged in 2020-08, with the labels that each got.

#7072 Added support for out of tree builds with vscode
  .vscode/launch.json
  .vscode/tasks.json
Labels: Build

#7079 const-ify quic/http3 code
  iocore/net/quic/QUICAckFrameCreator.cc
  iocore/net/quic/QUICAckFrameCreator.h
  iocore/net/quic/QUICApplication.cc
  iocore/net/quic/QUICApplication.h
  iocore/net/quic/QUICFlowController.cc
  iocore/net/quic/QUICFlowController.h
  iocore/net/quic/QUICFrame.cc
  iocore/net/quic/QUICFrame.h
  iocore/net/quic/QUICFrameRetransmitter.h
  iocore/net/quic/QUICHandshake.cc
  iocore/net/quic/QUICHandshake.h
  iocore/net/quic/QUICLossDetector.cc
  iocore/net/quic/QUICLossDetector.h
  iocore/net/quic/QUICNewRenoCongestionController.cc
  iocore/net/quic/QUICNewRenoCongestionController.h
  iocore/net/quic/QUICPacket.cc
  iocore/net/quic/QUICPacket.h
  iocore/net/quic/QUICPacketReceiveQueue.cc
  iocore/net/quic/QUICPacketReceiveQueue.h
  iocore/net/quic/QUICPathValidator.cc
  iocore/net/quic/QUICPathValidator.h
  iocore/net/quic/QUICTransportParameters.h
  iocore/net/quic/QUICVersionNegotiator.cc
  iocore/net/quic/QUICVersionNegotiator.h
  iocore/net/quic/qlog/QLog.cc
  iocore/net/quic/qlog/QLog.h
  iocore/net/quic/qlog/QLogEvent.h
  iocore/net/quic/qlog/QLogFrame.h
  proxy/http3/QPACK.cc
  proxy/http3/QPACK.h
Labels: QUIC

#7085 Fixes build warnings in maxmind_acl
  plugins/experimental/maxmind_acl/mmdb.cc
Labels: Plugins

#7084 const-ify quic/http3 code
  iocore/net/quic/QUICAckFrameCreator.cc
  iocore/net/quic/QUICAckFrameCreator.h
  iocore/net/quic/QUICApplication.cc
  iocore/net/quic/QUICApplication.h
  iocore/net/quic/QUICFlowController.cc
  iocore/net/quic/QUICFlowController.h
  iocore/net/quic/QUICFrame.cc
  iocore/net/quic/QUICFrame.h
  iocore/net/quic/QUICFrameRetransmitter.h
  iocore/net/quic/QUICHandshake.cc
  iocore/net/quic/QUICHandshake.h
  iocore/net/quic/QUICLossDetector.cc
  iocore/net/quic/QUICLossDetector.h
  iocore/net/quic/QUICNewRenoCongestionController.cc
  iocore/net/quic/QUICPacket.cc
  iocore/net/quic/QUICPacket.h
  iocore/net/quic/QUICPacketReceiveQueue.cc
  iocore/net/quic/QUICPacketReceiveQueue.h
  iocore/net/quic/QUICPathValidator.cc
  iocore/net/quic/QUICPathValidator.h
  iocore/net/quic/QUICTransportParameters.h
  iocore/net/quic/QUICVersionNegotiator.cc
  iocore/net/quic/QUICVersionNegotiator.h
  iocore/net/quic/qlog/QLog.cc
  iocore/net/quic/qlog/QLog.h
  iocore/net/quic/qlog/QLogEvent.h
  iocore/net/quic/qlog/QLogFrame.h
  proxy/http3/QPACK.cc
  proxy/http3/QPACK.h
Labels: Cleanup

#7086 Doc: fix no_content_length status code
  doc/admin-guide/monitoring/error-messages.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/monitoring/error-messages.en.po
Labels: Documentation

#7080 Fix a crash on connection migration to the advertised preferred address
  iocore/net/QUICNetVConnection.cc
Labels: QUIC

#7087 Fix eval_ip compile - missing const.
  plugins/experimental/maxmind_acl/mmdb.h
Labels: Plugins

#7089 Converts files to #pragma once
  iocore/net/ProxyProtocol.h
  plugins/experimental/cookie_remap/cookiejar.h
  plugins/experimental/cookie_remap/hash.h
  plugins/experimental/cookie_remap/strip.h
  plugins/experimental/maxmind_acl/mmdb.h
  plugins/experimental/memcache/tsmemcache.h
  proxy/http3/Http3SessionAccept.h
Labels: Cleanup

#7062 Signal WRITE_COMPLETE regardless of transmission progress
  proxy/http3/Http3Transaction.cc
Labels: HTTP/3

#7078 Ran clang-tidy over the source tree
  example/plugins/cpp-api/websocket/WSBuffer.cc
  iocore/cache/Cache.cc
  iocore/cache/CacheLink.cc
  iocore/eventsystem/UnixEventProcessor.cc
  iocore/net/P_QUICNetVConnection.h
  iocore/net/P_QUICPacketHandler.h
  iocore/net/P_SSLUtils.h
  iocore/net/QUICNet.cc
  iocore/net/QUICNetVConnection.cc
  iocore/net/QUICPacketHandler.cc
  iocore/net/SSLUtils.cc
  iocore/net/UnixNetVConnection.cc
  plugins/cache_promote/lru_policy.cc
  plugins/experimental/memcache/tsmemcache.cc
  plugins/experimental/metalink/metalink.cc
  plugins/experimental/remap_stats/remap_stats.cc
  plugins/experimental/slice/Config.cc
  plugins/experimental/slice/Range.cc
  plugins/experimental/slice/slice.cc
  plugins/experimental/slice/util.cc
  plugins/experimental/ssl_session_reuse/src/publish.cc
  plugins/experimental/ssl_session_reuse/src/session_process.cc
  plugins/experimental/stream_editor/stream_editor.cc
  plugins/experimental/traffic_dump/session_data.cc
  plugins/experimental/traffic_dump/transaction_data.cc
  plugins/lua/ts_lua.c
  plugins/stats_over_http/stats_over_http.c
  proxy/ControlMatcher.cc
  proxy/ParentConsistentHash.cc
  proxy/hdrs/MIME.cc
  proxy/http/Http1Transaction.cc
  proxy/http/remap/NextHopConsistentHash.cc
  proxy/http/remap/NextHopSelectionStrategy.cc
  proxy/http/remap/NextHopStrategyFactory.cc
  proxy/http/remap/NextHopStrategyFactory.h
  proxy/logging/Log.cc
  proxy/logging/LogAccess.cc
  proxy/logging/LogFile.cc
  src/traffic_logstats/logstats.cc
  src/traffic_server/FetchSM.cc
  src/traffic_server/InkAPITest.cc
  src/tscore/ink_inet.cc
  src/tscore/ink_queue.cc
  src/tscore/ink_res_init.cc
  src/tscore/ink_res_mkquery.cc
  src/tscore/unit_tests/test_Regex.cc
  tools/jtest/jtest.cc
Labels: Cleanup

#7069 Move the direct self loop check later to HttpSM::do_http_server_open
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
Labels: Core

#7081 Updated release notes for 9.0.0 to have new QUIC 27 version
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#7091 Adds description for ssl_ticket_number in ssl_multicert docs
  doc/admin-guide/files/ssl_multicert.config.en.rst
Labels: Documentation

#7093 Fix compilation error - missing '&' operator
  plugins/experimental/maxmind_acl/mmdb.h
Labels: Build

#7083 Destroy threads after job done
  mgmt/ProcessManager.cc
  mgmt/ProcessManager.h
  src/traffic_server/traffic_server.cc
Labels: Leak, Process Management

#7098 Remove more deadcode
  doc/admin-guide/plugins/access_control.en.rst
  doc/developer-guide/testing/blackbox-testing.en.rst
  iocore/dns/P_SplitDNSProcessor.h
  iocore/dns/SplitDNS.cc
  iocore/net/Socks.cc
  mgmt/ProxyConfig.cc
  mgmt/ProxyConfig.h
  proxy/ControlMatcher.cc
  proxy/ControlMatcher.h
  proxy/ParentSelection.h
  tests/README.md
Labels: Cleanup

#7088 Skip docs builds if there are no changes in the doc dir and files it includes
  ci/jenkins/bin/docs.sh
Labels: Build

#7095 Refresh proxy protocol diagram
  doc/static/images/admin/proxy-protocol.png
Labels: Documentation

#7071 Adding autopep8 as a pre-commit hook.
  CONTRIBUTING.md
  Makefile.am
  ci/jenkins/bin/clang-format.sh
  tools/autopep8.sh
  tools/clang-format.sh
  tools/git/pre-commit
Labels: Build

#7038 Add cross references between server session sharing match and upstream connection tracking match.
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/plugins/icap.en.rst
  doc/admin-guide/plugins/memory_profile.en.rst
Labels: Documentation

#7100 Fixes uninitialized variables found by Xcode
  proxy/http/HttpBodyFactory.cc
  proxy/http/HttpTransactCache.cc
Labels: Cleanup

#7104 Don't send image/webp responses from cache to broswers that don't support it
  proxy/http/HttpTransactCache.cc
  tests/gold_tests/headers/accept_webp.test.py
  tests/gold_tests/headers/gold/accept_webp.gold
  tests/gold_tests/headers/gold/accept_webp_cache.gold
  tests/gold_tests/headers/gold/accept_webp_jpeg.gold
Labels: HTTP

#7118 Backing out my update of our jenkin's autest file.
  ci/jenkins/bin/autest.sh
Labels: AuTest

#7122 Make tls_hooks tests more likely to pass particularly for 9.0.x branch
  tests/gold_tests/tls_hooks/tls_hooks.test.py
  tests/gold_tests/tls_hooks/tls_hooks10.test.py
  tests/gold_tests/tls_hooks/tls_hooks11.test.py
  tests/gold_tests/tls_hooks/tls_hooks12.test.py
  tests/gold_tests/tls_hooks/tls_hooks13.test.py
  tests/gold_tests/tls_hooks/tls_hooks14.test.py
  tests/gold_tests/tls_hooks/tls_hooks15.test.py
  tests/gold_tests/tls_hooks/tls_hooks16.test.py
  tests/gold_tests/tls_hooks/tls_hooks17.test.py
  tests/gold_tests/tls_hooks/tls_hooks18.test.py
  tests/gold_tests/tls_hooks/tls_hooks2.test.py
  tests/gold_tests/tls_hooks/tls_hooks3.test.py
  tests/gold_tests/tls_hooks/tls_hooks4.test.py
  tests/gold_tests/tls_hooks/tls_hooks6.test.py
  tests/gold_tests/tls_hooks/tls_hooks7.test.py
  tests/gold_tests/tls_hooks/tls_hooks8.test.py
  tests/gold_tests/tls_hooks/tls_hooks9.test.py
Labels: AuTest

#7073 Expose remap config file callback
  include/ts/experimental.h
  include/ts/ts.h
  mgmt/utils/MgmtUtils.h
  plugins/experimental/maxmind_acl/mmdb.cc
  plugins/experimental/maxmind_acl/mmdb.h
  proxy/http/remap/RemapConfig.cc
  proxy/http/remap/RemapConfig.h
  src/traffic_server/InkAPI.cc
  src/traffic_server/traffic_server.cc
Labels: Configuration, TS API

#7105 Add modsecurity lua script to example
  example/plugins/lua-api/modsecurity/C.lua
  example/plugins/lua-api/modsecurity/README.md
  example/plugins/lua-api/modsecurity/ats-luajit-modsecurity.lua
  example/plugins/lua-api/modsecurity/example.conf
  example/plugins/lua-api/modsecurity/msc.lua
  example/plugins/lua-api/modsecurity/msc_config.lua
  example/plugins/lua-api/modsecurity/owasp.conf
Labels: Lua, Plugins

#7111 Cancel active/inactive timeout on closing Http2Stream
  proxy/http2/Http2Stream.cc
  proxy/http2/Http2Stream.h
Labels: HTTP/2

#7129 Comment out a wrong assertion in QUIC Loss Detection logic
  iocore/net/quic/QUICLossDetector.cc
Labels: QUIC

#7126 Replaces "smart" quotes with ASCII equivalents
  CONTRIBUTING.md
  doc/admin-guide/configuration/hierarchical-caching.en.rst
  doc/admin-guide/configuration/redirecting-http-requests.en.rst
  doc/admin-guide/configuration/transparent-proxy/wccp-service-config.en.rst
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/introduction.en.rst
  doc/admin-guide/logging/examples.en.rst
  doc/admin-guide/plugins/collapsed_forwarding.en.rst
  doc/admin-guide/plugins/header_rewrite.en.rst
  doc/admin-guide/plugins/prefetch.en.rst
  doc/developer-guide/api/functions/TSContScheduleOnPool.en.rst
  doc/developer-guide/logging-architecture/architecture.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/configuration/cache-basics.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/configuration/hierachical-caching.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/configuration/redirecting-http-requests.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/configuration/transparent-proxy/wccp-service-config.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/files/records.config.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/introduction.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/monitoring/logging/log-formats.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/plugins/collapsed_forwarding.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/plugins/header_rewrite.en.po
  doc/locale/ja/LC_MESSAGES/admin-guide/transparent-proxy/wccp-service-config.en.po
  include/tscore/ink_queue.h
  iocore/net/quic/QUICStreamState.cc
  plugins/experimental/access_control/plugin.cc
  src/tscore/EventNotify.cc
  tools/package/trafficserver.spec
Labels: Cleanup

#7125 SSLConfig mem leak fix
  iocore/net/SSLConfig.cc
Labels: ASAN, SSL

#7133 Updated gdb mutex script to get process file for Fedora 32
  tools/gdb_mutex_contention.pl
Labels: Tools

#7137 Removes duplicated listing of files in same Makefile target
  configs/body_factory/default/Makefile.am
  iocore/net/Makefile.am
  iocore/net/quic/Makefile.am
  lib/records/Makefile.am
  mgmt/Makefile.am
Labels: Cleanup

#7140 Fixes garbled logs when using %<vbn> log tag
  proxy/logging/LogAccess.cc
Labels: Logging

#7123 Accept NAT rebinding on a QUIC connection
  iocore/net/QUICNetVConnection.cc
Labels: QUIC

#7120 Check VIO availability before checking whether the VIO has data
  iocore/net/quic/QUICBidirectionalStream.cc
  iocore/net/quic/QUICUnidirectionalStream.cc
  iocore/net/quic/test/test_QUICStream.cc
Labels: QUIC

#7128 Protect TSActionCancel from null INKContInternal actions
  src/traffic_server/InkAPI.cc
Labels: Crash

#7138 Remove useless shortopt
  plugins/cache_promote/configs.cc
Labels: Cleanup

#7144 Fix typo in cache docs
  doc/developer-guide/plugins/io/cache-api.en.rst
  doc/locale/ja/LC_MESSAGES/developer-guide/plugins/io/cache-api.en.po
Labels: Documentation

#7130 Allow override of CA certs for cert from client based on SNI server name sent by client.
  doc/admin-guide/files/sni.yaml.en.rst
  iocore/net/P_SNIActionPerformer.h
  iocore/net/P_SSLUtils.h
  iocore/net/SSLSNIConfig.cc
  iocore/net/SSLUtils.cc
  iocore/net/YamlSNIConfig.cc
  iocore/net/YamlSNIConfig.h
  tests/gold_tests/tls/ssl/aaa-ca.key
  tests/gold_tests/tls/ssl/aaa-ca.pem
  tests/gold_tests/tls/ssl/aaa-signed.key
  tests/gold_tests/tls/ssl/aaa-signed.pem
  tests/gold_tests/tls/ssl/bbb-ca.key
  tests/gold_tests/tls/ssl/bbb-ca.pem
  tests/gold_tests/tls/ssl/bbb-signed.key
  tests/gold_tests/tls/ssl/bbb-signed.pem
  tests/gold_tests/tls/ssl/ccc-ca.key
  tests/gold_tests/tls/ssl/ccc-ca.pem
  tests/gold_tests/tls/ssl/ccc-signed.key
  tests/gold_tests/tls/ssl/ccc-signed.pem
  tests/gold_tests/tls/ssl/gen_client_certs.sh
  tests/gold_tests/tls/ssl/openssl.cnf
  tests/gold_tests/tls/tls_client_verify3.test.py
Labels: Core, TLS

#7117 Fix #7116, skip the insertion of the same continuation to pending dns
  iocore/hostdb/HostDB.cc
Labels: HostDB

#7145 Check VIO availability before acquiring a lock for it
  iocore/net/quic/QUICBidirectionalStream.cc
  iocore/net/quic/QUICUnidirectionalStream.cc
  iocore/net/quic/test/test_QUICStream.cc
Labels: OnDocs, QUIC

#7121 Don't return QUIC frame if the size exceeds maximum frame size
  iocore/net/quic/QUICBidirectionalStream.cc
  iocore/net/quic/QUICFlowController.cc
  iocore/net/quic/QUICUnidirectionalStream.cc
  iocore/net/quic/test/test_QUICFlowController.cc
  iocore/net/quic/test/test_QUICStream.cc
Labels: OnDocs, QUIC

#7143 Deprecate cqhv field
  doc/admin-guide/logging/formatting.en.rst
Labels: Documentation

#7147 slice: check if vio is still valid before calling TSVIODone* on shutdown
  plugins/experimental/slice/Stage.h
Labels: Crash, Plugins

#7148 Fix stale pointer due to SSL config reload
  iocore/net/I_NetVConnection.h
  iocore/net/P_UnixNetVConnection.h
  iocore/net/SSLNetVConnection.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpSessionManager.cc
Labels: Crash, TLS
