Repository apache/trafficserver, pull requests merged in 2021-03, with the labels that each got.

#7557 Remove reference to CoreUtils
  include/tscore/Ptr.h
  proxy/hdrs/HdrHeap.h
  proxy/http/HttpSM.h
  proxy/http/HttpTunnel.h
Labels: Cleanup

#7572 FQ pacing plugin memory leak fix
  plugins/experimental/fq_pacing/fq_pacing.c
Labels: Bug, Plugins

#7537 Enable origin server session cache by default
  doc/admin-guide/files/records.config.en.rst
  iocore/net/SSLConfig.cc
  mgmt/RecordsConfig.cc
Labels: Origin Session

#7570 Cleanup: Remove unused member of Http2ClientSession
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ClientSession.h
Labels: Cleanup, HTTP/2

#6241 Make Allocator.h less silly (no creepy "proto" object).
  include/tscore/Allocator.h
  iocore/cache/P_CacheInternal.h
  iocore/eventsystem/I_ProxyAllocator.h
Labels: Cleanup

#7566 Updates the STATUS file with all recent releases
  STATUS
Labels: Build

#7564 Fix compress issues with 304s, only looks at 304 headers
  plugins/compress/compress.cc
Labels: Bug, Plugins

#7569 Cleanup: Rename IOBufferReader of Http2ClientSession
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ClientSession.h
Labels: Cleanup, HTTP/2

#7556 Introduce TLSBasicSupport interface
  iocore/net/Makefile.am
  iocore/net/P_SSLNetVConnection.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLUtils.cc
  iocore/net/TLSBasicSupport.cc
  iocore/net/TLSBasicSupport.h
  proxy/http/HttpSM.cc
  src/traffic_server/InkAPI.cc
Labels: Cleanup, TLS

#7567 Remove ProxyTransaction::set_proxy_ssn
  proxy/ProxyTransaction.cc
  proxy/ProxyTransaction.h
  proxy/http/Http1ClientSession.cc
  proxy/http/Http1Transaction.h
  proxy/http/HttpSM.cc
  proxy/http/HttpSessionAccept.cc
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2SessionAccept.cc
  proxy/http2/Http2Stream.cc
  proxy/http2/Http2Stream.h
  proxy/http3/Http3Transaction.cc
Labels: Cleanup

#7571 Tidy up session/transaction destruction process
  proxy/ProxySession.cc
  proxy/ProxySession.h
  proxy/ProxyTransaction.cc
  proxy/ProxyTransaction.h
  proxy/http/Http1ClientSession.cc
  proxy/http/Http1ClientSession.h
  proxy/http/Http1ServerSession.cc
  proxy/http/Http1ServerSession.h
  proxy/http/Http1Transaction.cc
  proxy/http/Http1Transaction.h
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2Stream.cc
  proxy/http2/Http2Stream.h
  proxy/http3/Http3Session.cc
  proxy/http3/Http3Session.h
  proxy/http3/Http3Transaction.cc
  proxy/http3/Http3Transaction.h
Labels: Cleanup, Core

#7408 Reactivate accept_no_activity_timeout
  proxy/ProtocolProbeSessionAccept.cc
  proxy/http/HttpSM.cc
  tests/gold_tests/timeout/accept_timeout.test.py
  tests/gold_tests/timeout/create_request.sh
  tests/gold_tests/timeout/time_client.sh
Labels: Connection Timeouts

#7577 Fix the final consumer write size from unchunked to chunked tunnel
  proxy/http/HttpTunnel.cc
Labels: HTTP

#7588 Build the test library for tls_engine consistently
  tests/gold_tests/tls/tls_engine.test.py
  tests/tools/plugins/Makefile.inc
  tests/tools/plugins/async_engine.c
Labels: AuTest, Cleanup

#7587 Change the default value for verify.server.policy
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  tests/gold_tests/tls/tls_verify_base.test.py
  tests/gold_tests/tls/tls_verify_override_base.test.py
Labels: Configuration, Incompatible

#7589 Add gold test for remap config .include directive.
  tests/gold_tests/traffic_ctl/remap_inc/remap_inc.test.py
  tests/gold_tests/traffic_ctl/remap_inc/wait_reload.sh
Labels: AuTest

#7582 Add pointer/reference downcast function that is checked in debug builds.
  include/tscore/ink_assert.h
Labels: Debug

#7600 Fix double destuct on Http2Stream termination
  proxy/http2/Http2Stream.cc
Labels: Crash

#7591 Use return values to fix ubuntu release build error
  contrib/openssl/async_engine.c
  tests/gold_tests/tls/tls_engine.test.py
  tests/tools/plugins/async_engine.c
Labels: Tests

#7596 Remove UnixNetVConnection::startEvent - not actually called.
  iocore/net/P_QUICNetVConnection.h
  iocore/net/P_UnixNetVConnection.h
  iocore/net/QUICNetProcessor.cc
  iocore/net/QUICNetVConnection.cc
  iocore/net/SSLNetVConnection.cc
  iocore/net/UnixNetVConnection.cc
Labels: Cleanup, clang-analyzer

#7592 Remove inline for detail::cache::CacheData::idAddr
  src/wccp/WccpEndPoint.cc
Labels: Build

#7604 Fix the connection limit crash while using parents
  proxy/http/HttpSM.cc
Labels: HTTP

#7602 Fix the connection limit crash while using parents
  proxy/http/HttpSM.cc
Labels: HTTP

#7609 Remove UnixNetVConnection::startEvent - not actually called.
  iocore/net/P_UnixNetVConnection.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/UnixNetVConnection.cc
Labels: Backport, Cleanup, clang-analyzer

#7608 Set pcre_malloc/free function pointers in core main() only.
  plugins/experimental/cookie_remap/cookie_remap.cc
  plugins/regex_remap/regex_remap.cc
  plugins/regex_revalidate/regex_revalidate.c
Labels: Cleanup

#7616 Increase Proxy Verifier caching delay.
  tests/gold_tests/cache/replay/cache-control-max-age.replay.yaml
  tests/gold_tests/cache/replay/negative-caching-300-second-timeout.replay.yaml
  tests/gold_tests/cache/replay/negative-caching-customized.replay.yaml
  tests/gold_tests/cache/replay/negative-caching-default.replay.yaml
  tests/gold_tests/cache/replay/negative-caching-disabled.replay.yaml
  tests/gold_tests/cache/replay/negative-caching-no-timeout.replay.yaml
  tests/gold_tests/cache/replay/negative-caching-timeout.replay.yaml
Labels: AuTest

#7279 Add throttled log functions
  doc/admin-guide/files/records.config.en.rst
  include/tscore/Diags.h
  include/tscore/DiagsTypes.h
  include/tscore/LogMessage.h
  include/tscore/Ptr.h
  include/tscore/Throttler.h
  iocore/dns/DNS.cc
  mgmt/RecordsConfig.cc
  proxy/logging/Log.cc
  proxy/logging/Log.h
  proxy/logging/LogBuffer.cc
  proxy/logging/LogConfig.cc
  proxy/logging/LogFile.cc
  proxy/logging/LogObject.cc
  proxy/logging/LogStandalone.cc
  proxy/shared/DiagsConfig.cc
  proxy/shared/DiagsConfig.h
  src/traffic_manager/traffic_manager.cc
  src/traffic_server/traffic_server.cc
  src/tscore/LogMessage.cc
  src/tscore/Makefile.am
  src/tscore/Throttler.cc
  src/tscore/unit_tests/test_Throttler.cc
Labels: Logging

#7617 Typo in output when forcing kqueue for configure
  configure.ac
Labels: Cleanup

#7619 Use standard isdigit library function
  proxy/hdrs/HTTP.cc
Labels: Cleanup

#7291 Add failed state to hostdb to better track failing origins
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
Labels: Connection Timeouts, Server Session

#7620 Adding negative revalidating AuTests.
  tests/gold_tests/cache/negative-revalidating.test.py
  tests/gold_tests/cache/replay/negative-revalidating-disabled.replay.yaml
  tests/gold_tests/cache/replay/negative-revalidating-enabled.replay.yaml
Labels: AuTest

#7626 Remove unused variables
  proxy/ProxySession.h
  proxy/http/Http1ClientSession.cc
Labels: Cleanup

#7634 statichit: misc. fixes
  plugins/experimental/statichit/statichit.cc
Labels: Plugins

#7625 Add proxy.process.http.background_fill_total_count
  doc/admin-guide/monitoring/statistics/core/cache.en.rst
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpSM.cc
Labels: Cache, HTTP, Metrics

#7576 Add thread yield to avoid busy waiting in LogObject::_checkout_write().
  proxy/logging/LogObject.cc
Labels: Logging, Performance

#7630 Add default implementation for allow_half_open
  proxy/ProxyTransaction.cc
  proxy/ProxyTransaction.h
  proxy/http2/Http2Stream.h
  proxy/http3/Http3Transaction.cc
  proxy/http3/Http3Transaction.h
Labels: HTTP

#7628 Expose URL element methods through HTTPHdr
  proxy/hdrs/HTTP.h
Labels: HTTP

#7627 Add pooled_server_connections metric
  doc/admin-guide/monitoring/statistics/core/http-connection.en.rst
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpSessionManager.cc
Labels: Metrics

#7645 Fix tls_client_versions and tls_hooks18 tests
  tests/gold_tests/tls/tls_client_versions.test.py
  tests/gold_tests/tls_hooks/tls_hooks18.test.py
Labels: AuTest

#7631 Fix HttpSessionManager::acquireSession from previous rebase error
  proxy/http/HttpSessionManager.cc
Labels: HTTP, Server Session

#7629 Add proxy.config.cache.log.alternate.eviction
  configs/records.config.default.in
  doc/admin-guide/configuration/cache-basics.en.rst
  doc/admin-guide/files/records.config.en.rst
  iocore/cache/Cache.cc
  iocore/cache/CacheWrite.cc
  iocore/cache/P_CacheInternal.h
  lib/perl/lib/Apache/TS/AdminClient.pm
  mgmt/RecordsConfig.cc
  tests/gold_tests/cache/gold/two_alternates_evicted.gold
  tests/gold_tests/cache/replay/varied_transactions.replay.yaml
  tests/gold_tests/cache/vary-handling.test.py
Labels: Cache, Logging

#7612 Document http.default_buffer_water_mark
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#7614 Change ROUNDUP from function-like macro to function template.
  include/tscore/ink_defs.h
  iocore/dns/DNSConnection.cc
  iocore/net/Connection.cc
  iocore/net/UnixConnection.cc
  iocore/net/UnixNetAccept.cc
Labels: Cleanup

#7646 Remove erroneous manager.log mesg with remap include file reload
  mgmt/ConfigManager.cc
  tests/gold_tests/traffic_ctl/remap_inc/remap_inc.test.py
Labels: Configuration, Logging

#7621 Update server_response_body_bytes when background fill worked
  proxy/http/HttpSM.cc
Labels: Cache, HTTP, Metrics

#7601 Update -with-profile and add some profiling documentation
  configure.ac
  doc/developer-guide/debugging/profiling.en.rst
Labels: Configuration, Documentation

#7648 Comment why log eviction isn't implemented via a log field.
  iocore/cache/CacheWrite.cc
Labels: Logging

#7655 Remove inline for detail::cache::CacheData::idAddr
  src/wccp/WccpEndPoint.cc
Labels: Build

#7654 Updating documentation for negative_revalidating_lifetime
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#7662 Refine Inline.cc carveout for arm64 darwin builds
  iocore/aio/Inline.cc
  iocore/cache/Inline.cc
  iocore/dns/Inline.cc
  iocore/eventsystem/Inline.cc
  iocore/hostdb/Inline.cc
  iocore/net/Inline.cc
Labels: macOS
