Repository apache/trafficserver, pull requests merged in 2022-06, with the labels that each got.

#8875 Expose setting some HTTP/2 tunables via sni.yaml (#8818)
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/files/sni.yaml.en.rst
  iocore/net/I_NetVConnection.h
  iocore/net/P_SNIActionPerformer.h
  iocore/net/SSLSNIConfig.cc
  iocore/net/TLSSNISupport.h
  iocore/net/YamlSNIConfig.cc
  iocore/net/YamlSNIConfig.h
  proxy/http2/Http2ClientSession.cc
Labels: Backport

#8880 8.1.x Backport: Move has_request_body to ProxyTransaction (#7499)
  proxy/ProxyClientTransaction.cc
  proxy/ProxyClientTransaction.h
  proxy/hdrs/HdrToken.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2Stream.cc
  proxy/http2/Http2Stream.h
  tests/gold_tests/h2/http2.test.py
Labels: Backport, v8.1.2

#8884 Upgrade to Proxy Verifier 2.4.0.
  tests/prepare_proxy_verifier.sh
  tests/proxy-verifier-version.txt
Labels: AuTest

#8885 Update to libswoc 1.3.8
  ci/rat-regex.txt
  lib/swoc/Makefile.am
  lib/swoc/include/swoc/MemSpan.h
  lib/swoc/include/swoc/TextView.h
  lib/swoc/include/swoc/Vectray.h
  lib/swoc/include/swoc/swoc_ip.h
  lib/swoc/include/swoc/swoc_version.h
Labels: Tools

#8864 Update the GitHub stale action to use the new version
  .github/workflows/stale.yml
Labels: GitHub

#8873 Add proxy.process.hostdb.total_serve_stale
  doc/admin-guide/monitoring/statistics/core/hostdb.en.rst
  doc/appendices/command-line/traffic_top.en.rst
  iocore/hostdb/HostDB.cc
  iocore/hostdb/P_HostDBProcessor.h
  src/traffic_top/stats.h
Labels: HostDB

#8855 Allow for long Http* error.log lines
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
Labels: Logging

#8889 remap_reload test: Spacing out file modification and reload
  tests/gold_tests/remap/remap_reload.test.py
Labels: AuTest, remap

#8897 Removed references to the throttle option from the slice plugin. (#8373)
  doc/admin-guide/plugins/slice.en.rst
  plugins/experimental/slice/Config.cc
Labels: Backport

#8898 slice and cache_range_requests: allow header override (#8666)
  doc/admin-guide/plugins/cache_range_requests.en.rst
  doc/admin-guide/plugins/slice.en.rst
  plugins/cache_range_requests/cache_range_requests.cc
  plugins/experimental/slice/Config.cc
  plugins/experimental/slice/Config.h
  plugins/experimental/slice/HttpHeader.h
  plugins/experimental/slice/client.cc
  plugins/experimental/slice/server.cc
  plugins/experimental/slice/slice.cc
  plugins/experimental/slice/slice.h
  plugins/experimental/slice/util.cc
  tests/gold_tests/pluginTest/cache_range_requests/cache_range_requests_ims.test.py
  tests/gold_tests/pluginTest/slice/slice.test.py
  tests/gold_tests/pluginTest/slice/slice_selfhealing.test.py
Labels: Backport

#8892 Cleanup SNIConfig
  iocore/net/P_SSLSNI.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLSNIConfig.cc
  proxy/http/HttpSM.cc
  proxy/http/PreWarmManager.cc
Labels: Cleanup

#8888 Make FileManager ctor private.
  mgmt2/config/FileManager.h
Labels: Cleanup, JSONRPC

#8886 Add escape json for logging
  doc/admin-guide/logging/formatting.en.rst
  proxy/logging/LogAccess.cc
  proxy/logging/LogAccess.h
  proxy/logging/LogBuffer.cc
  proxy/logging/LogBuffer.h
  proxy/logging/LogField.cc
  proxy/logging/LogField.h
  proxy/logging/LogFile.cc
  proxy/logging/LogFile.h
  proxy/logging/LogFormat.cc
  proxy/logging/LogFormat.h
  proxy/logging/LogObject.cc
  proxy/logging/YamlLogConfigDecoders.cc
  tests/gold_tests/logging/gold/field-json-test.gold
  tests/gold_tests/logging/log-field-json.test.py
Labels: Logging

#8891 Cleanup: Get rid of afterpoll net stats
  doc/admin-guide/monitoring/statistics/core/network-io.en.rst
  iocore/net/Net.cc
  iocore/net/P_Net.h
  iocore/net/UnixNetVConnection.cc
  src/traffic_server/traffic_server.cc
Labels: Network, Metrics, Incompatible

#8814 9.1.x: Unit test compiler and library run time fixes
  iocore/net/quic/test/test_QUICPacket.cc
  src/tscore/Makefile.am
Labels: Build, Tests

#8842 Fixes leak of sni config filename on load (#8821)
  iocore/net/P_SSLSNI.h
  iocore/net/SSLSNIConfig.cc
  iocore/net/YamlSNIConfig.cc
  iocore/net/YamlSNIConfig.h
Labels: Backport

#8843 Fix leaks in ConfigManager::configName (#8269)
  mgmt/ConfigManager.cc
  mgmt/ConfigManager.h
  src/traffic_manager/AddConfigFilesHere.cc
Labels: Leak

#8906 Fix autest uses of File exists parameter
  tests/gold_tests/autest-site/trafficserver.test.ext
  tests/gold_tests/pluginTest/cookie_remap/bucketcookie.test.py
  tests/gold_tests/pluginTest/cookie_remap/collapseslashes.test.py
  tests/gold_tests/pluginTest/cookie_remap/connector.test.py
  tests/gold_tests/pluginTest/cookie_remap/existscookie.test.py
  tests/gold_tests/pluginTest/cookie_remap/matchcookie.test.py
  tests/gold_tests/pluginTest/cookie_remap/matchuri.test.py
  tests/gold_tests/pluginTest/cookie_remap/matrixparams.test.py
  tests/gold_tests/pluginTest/cookie_remap/notexistscookie.test.py
  tests/gold_tests/pluginTest/cookie_remap/pcollapseslashes.test.py
  tests/gold_tests/pluginTest/cookie_remap/psubstitute.test.py
  tests/gold_tests/pluginTest/cookie_remap/regexcookie.test.py
  tests/gold_tests/pluginTest/cookie_remap/setstatus.test.py
  tests/gold_tests/pluginTest/cookie_remap/subcookie.test.py
  tests/gold_tests/pluginTest/cookie_remap/substitute.test.py
Labels: AuTest

#8904 iocore/cache test_Alternate: up timeout to allow vc to write out
  iocore/cache/test/test_Alternate_S_to_L_remove_L.cc
  iocore/cache/test/test_Alternate_S_to_L_remove_S.cc
Labels: Tests, Crash

#8899 Do not modify Transfer-Encoding header on retry
  proxy/http/HttpSM.cc
Labels: HTTP

#8901 uri_signing plugin: Fix missing payload validation for the iss field.
  plugins/experimental/uri_signing/jwt.c
  plugins/experimental/uri_signing/parse.c
  tests/gold_tests/pluginTest/uri_signing/uri_signing.test.py
Labels: Plugins, Bug

#8910 Pin Jinja2 for doc builds (#8773)
  doc/Pipfile
Labels: v8.1.2

#8911 Override LogField constructor to avoid reinterpret_cast at call site
  proxy/logging/Log.cc
  proxy/logging/LogField.cc
  proxy/logging/LogField.h
Labels: Logging, Cleanup

#8916 JSONRPC: replace std::string with std::string_view when registring a new endpoint.
  mgmt2/rpc/jsonrpc/JsonRPC.h
  mgmt2/rpc/jsonrpc/JsonRPCManager.cc
  mgmt2/rpc/jsonrpc/JsonRPCManager.h
  mgmt2/rpc/server/unit_tests/test_rpcserver.cc
Labels: JSONRPC

#8921 stek_share test: compare output with the correct Process
  tests/gold_tests/pluginTest/stek_share/stek_share.test.py
Labels: AuTest

#8925 Cleanup. Remove unnecessary use of a memory arena when logging.
  proxy/http2/HPACK.cc
Labels: HTTP/2, Cleanup, Debug

#8923 JSONRPC: Deal with an empty id as an id error.
  doc/developer-guide/jsonrpc/jsonrpc-handler-development.en.rst
  doc/developer-guide/jsonrpc/jsonrpc-node-errors.en.rst
  mgmt2/rpc/jsonrpc/error/RPCError.cc
  mgmt2/rpc/jsonrpc/error/RPCError.h
  mgmt2/rpc/jsonrpc/json/YAMLCodec.h
  mgmt2/rpc/jsonrpc/unit_tests/test_basic_protocol.cc
Labels: JSONRPC

#8922 Use std::variant to clean up handling of unmarshal functions.
  proxy/logging/LogAccess.cc
  proxy/logging/LogAccess.h
  proxy/logging/LogField.cc
  proxy/logging/LogField.h
  proxy/logging/Makefile.am
Labels: Logging, Cleanup

#8928 proxy_serve_stale: Test updates
  tests/gold_tests/proxy_protocol/gold/proxy_serve_stale.gold
  tests/gold_tests/proxy_protocol/proxy_serve_stale.test.py
  tests/gold_tests/proxy_protocol/replay/proxy_serve_stale.replay.yaml
Labels: AuTest

#8935 Make clang-format not modify ink_autoconf.h.in and ink_autoconf.h
  tools/clang-format.sh
Labels: Build, Tools
