Repository apache/trafficserver, pull requests merged in 2022-11, with the labels that each got.

#9166 Cleanup: Remove unused functions of cache
  iocore/cache/Cache.cc
  iocore/cache/I_Cache.h
  iocore/cache/P_CacheDir.h
  iocore/cache/P_CacheVol.h
Labels: Cache, Cleanup

#9163 reconfigure should not apply a bad config even if exit_on_load_fail i…
  iocore/net/SSLConfig.cc
  tests/gold_tests/tls/ssl_multicert_loader.test.py
Labels: Bug

#9175 s3_auth_parsing.gold: Make Age Less Specified
  tests/gold_tests/pluginTest/s3_auth/gold/s3_auth_parsing.gold
Labels: AuTest

#9180 update autest version
  tests/Pipfile
Labels: AuTest

#9169 TSan: Fix data race of RecMutex::thread_holding
  include/records/I_RecMutex.h
  src/records/RecMutex.cc
Labels: TSan

#9170 TSan: Fix data race of g_num_records
  src/records/P_RecCore.cc
  src/records/RecUtils.cc
Labels: TSan

#9171 Add ThreadSanitizer suppressions file to ignore data race of freelist
  .tsan_suppressions
Labels: TSan

#9172 TSan: Fix data race of hostdb_current_timestamp
  iocore/hostdb/HostDB.cc
  iocore/hostdb/I_HostDBProcessor.h
Labels: TSan

#9178 Asynchronously refresh OCSP
  iocore/net/SSLNetProcessor.cc
Labels: 9.2.0

#9182 per_server.connection.max: CONNECT requests
  proxy/http/HttpTransact.h
  tests/gold_tests/origin_connection/gold/two_503_congested.gold
  tests/gold_tests/origin_connection/per_server_connection_max.test.py
Labels: HostDB

#9177 Fix the Loading of Client Certificate Chains
  iocore/net/SSLConfig.cc
Labels: TLS

#9164 Output diags to stderr before reconfig
  proxy/shared/DiagsConfig.cc
  src/tscore/ink_cap.cc
Labels: Debug

#9190 Fix missing virtual destructor in JSON RPC request.
  include/shared/rpc/RPCRequests.h
Labels: Cleanup, JSONRPC

#9191 Add include path for libswoc to base CMake file.
  CMakeLists.txt
Labels: Build, Cleanup

#9114 Add event loop timing histogram data.
  doc/admin-guide/monitoring/statistics/core/eventloop.en.rst
  include/tscpp/util/Histogram.h
  iocore/eventsystem/I_EThread.h
  iocore/eventsystem/UnixEThread.cc
  iocore/eventsystem/UnixEventProcessor.cc
  proxy/http/HttpSM.cc
  src/tscore/Makefile.am
  src/tscore/unit_tests/test_Histogram.cc
Labels: Metrics, Event System

#9194 Update .gitignore for overridable_txn_vars.cc in mgmt/
  .gitignore
Labels: Build, Tools

#9181 Adding back set_connect_fail for generic I/O error
  proxy/http/HttpSM.cc
  tests/gold_tests/dns/dns_host_down.test.py
  tests/gold_tests/dns/hosts_file
  tests/gold_tests/dns/replay/server_down.replay.yaml
Labels: HTTP

#9195 AuTest: make MakeATSProcess accessible for TestRuns
  tests/gold_tests/autest-site/trafficserver.test.ext
Labels: AuTest

#9185 Don't abort for inactivity timeout during tunneling.
  proxy/http/HttpSM.cc
Labels: Core, Bug

#9196 Delete .lgtm.yml
  .lgtm.yml
Labels: lgtm

#9186 Traffic Dump: Allow unlimited disk utilization
  doc/admin-guide/plugins/traffic_dump.en.rst
  plugins/experimental/traffic_dump/session_data.cc
  plugins/experimental/traffic_dump/session_data.h
  plugins/experimental/traffic_dump/traffic_dump.cc
  tests/gold_tests/pluginTest/traffic_dump/traffic_dump.test.py
  tests/gold_tests/pluginTest/traffic_dump/traffic_dump_http3.test.py
  tests/gold_tests/pluginTest/traffic_dump/traffic_dump_sni_filter.test.py
Labels: Plugins

#9198 Update README.md for C++17.
  README.md
Labels: Cleanup

#9202 Update codeql.yml
  .github/workflows/codeql.yml
Labels: CodeQL

#9200 libswoc: update to 1.4.0
  lib/swoc/Makefile.am
  lib/swoc/include/swoc/DiscreteRange.h
  lib/swoc/include/swoc/IPAddr.h
  lib/swoc/include/swoc/IPEndpoint.h
  lib/swoc/include/swoc/IPRange.h
  lib/swoc/include/swoc/IPSrv.h
  lib/swoc/include/swoc/TextView.h
  lib/swoc/include/swoc/Vectray.h
  lib/swoc/include/swoc/bwf_fwd.h
  lib/swoc/include/swoc/swoc_ip.h
  lib/swoc/include/swoc/swoc_version.h
  lib/swoc/src/bw_format.cc
  lib/swoc/src/bw_ip_format.cc
  lib/swoc/src/swoc_ip.cc
Labels: CPP Util

#9107 Adds support for serving statichit content out of a directory
  plugins/experimental/statichit/statichit.cc
Labels: Plugins, Feature

#9205 Add CMake build directories to .gitignore.
  .gitignore
Labels: Build, Cleanup

#9206 libswoc: Replace ts::Scalar with swoc::Scalar
  include/tscore/MemArena.h
  include/tscore/Scalar.h
  iocore/hostdb/HostDB.cc
  iocore/hostdb/test_HostFile.cc
  proxy/hdrs/HTTP.cc
  proxy/hdrs/HdrHeap.cc
  proxy/hdrs/HdrHeap.h
  src/traffic_cache_tool/CacheDefs.cc
  src/traffic_cache_tool/CacheDefs.h
  src/traffic_cache_tool/CacheScan.cc
  src/tscore/Makefile.am
  src/tscore/MemArena.cc
  src/tscore/unit_tests/test_Scalar.cc
Labels: Cleanup, CPP Util

#9211 libswoc: Fix "string_view_util.h" export duplication
  lib/swoc/Makefile.am
Labels: Build, Cleanup, CPP Util

#9210 libswoc: Export "ts_diag_levels.h".
  include/tscpp/util/Makefile.am
Labels: Plugins, CPP Util

#9213 strategy.yaml loading: give remap rule context in debug for troubleshooting
  proxy/http/remap/NextHopStrategyFactory.cc
Labels: Debug

#9212 traffic_ctl - Fix number of mandatory arguments when sending a plugin msg.
  src/traffic_ctl/traffic_ctl.cc
Labels: Tools

#9209 libswoc: Add ATS IP address utitilies on top of libswoc.
  include/tscpp/util/Makefile.am
  include/tscpp/util/ts_ip.h
  src/tscpp/util/Makefile.am
  src/tscpp/util/ts_ip.cc
Labels: Network, Cleanup, CPP Util

#9208 libswoc: update maxmind plugin to IPSpace.
  include/tscpp/util/ts_ip.h
  lib/swoc/include/swoc/IPRange.h
  plugins/experimental/maxmind_acl/mmdb.cc
  plugins/experimental/maxmind_acl/mmdb.h
Labels: Plugins, Cleanup, CPP Util

#9215 Traffic Dump AuTest Update: remove unneeded extra param
  tests/gold_tests/pluginTest/traffic_dump/traffic_dump.test.py
Labels: Plugins, AuTest

#9219 Removes unused no_data_in_fragment
  src/traffic_cache_tool/CacheDefs.h
Labels: Cleanup

#9189 Removed most sprintf and ignore sprintf warnings in bind code
  iocore/cache/CachePagesInternal.cc
  mgmt/WebMgmtUtils.cc
  mgmt/WebMgmtUtils.h
  mgmt/utils/MgmtUtils.cc
  plugins/certifier/certifier.cc
  plugins/compress/misc.cc
  plugins/experimental/access_control/plugin.cc
  plugins/experimental/access_control/utils.cc
  plugins/experimental/icap/icap_plugin.cc
  plugins/experimental/ja3_fingerprint/ja3_fingerprint.cc
  plugins/experimental/mp4/mp4.cc
  plugins/experimental/traffic_dump/transaction_data.cc
  plugins/prefetch/plugin.cc
  proxy/http/HttpBodyFactory.cc
  proxy/http/HttpSM.cc
  proxy/http/remap/unit-tests/plugin_testing_common.cc
  proxy/logging/Log.cc
  src/traffic_top/stats.h
  src/tscore/ink_res_mkquery.cc
  tools/jtest/jtest.cc
Labels: Cleanup

#9216 Fix codeql finding
  plugins/lua/ts_lua.c
Labels: Plugins, Lua

#9221 AuTest: Update to Proxy Verifier v2.5.0
  tests/prepare_proxy_verifier.sh
  tests/proxy-verifier-version.txt
Labels: AuTest

#9207 Upgrade stats over http to use libswoc.
  plugins/stats_over_http/stats_over_http.cc
  tests/gold_tests/pluginTest/stats_over_http/stats_over_http.test.py
Labels: Plugins, Cleanup, CPP Util

#9223 AuTest: Update to Proxy Verifier 2.5.2
  tests/prepare_proxy_verifier.sh
  tests/proxy-verifier-version.txt
Labels: AuTest
