Repository apache/trafficserver, pull requests merged in 2022-07, with the labels that each got.

#8931 Fix clang-format installation with multiple threads
  Makefile.am
  tools/clang-format.sh
Labels: Build

#8937 Add nullptr check of HTTPInfo
  proxy/http/HttpSM.cc
Labels: Crash

#8893 Fix %<chi> with PROXY Protocol
  doc/admin-guide/logging/formatting.en.rst
  iocore/net/P_NetVConnection.h
  iocore/net/SSLNetVConnection.cc
  proxy/ProtocolProbeSessionAccept.cc
  proxy/http/HttpTransactHeaders.cc
  tests/gold_tests/proxy_protocol/gold/access.gold
  tests/gold_tests/proxy_protocol/gold/test_case_0_stdout.gold
  tests/gold_tests/proxy_protocol/gold/test_case_1_stdout.gold
  tests/gold_tests/proxy_protocol/gold/test_case_2_stdout.gold
  tests/gold_tests/proxy_protocol/proxy_protocol.test.py
Labels: Logging, Proxy Protocol

#8932 Initialize TLSTunnelSupport on startup
  iocore/net/SSLUtils.cc
Labels: TLS

#8940 Fix the body_buffer AuTest for 10-Dev
  tests/gold_tests/pluginTest/test_hooks/body_buffer.test.py
Labels: AuTest

#8945 Grants some karma to active contributors which are not committers
  .asf.yaml
Labels: CI

#8944 Make the autopep8 clang-format targets quieter
  tools/autopep8.sh
  tools/clang-format.sh
Labels: Build

#8950 .fit/fmt/.clang-format-installed prerequisite
  Makefile.am
  tools/clang-format.sh
Labels: Build

#8946 Remove use of sbrk()
  src/traffic_server/traffic_server.cc
Labels: Cleanup, Metrics

#8947 Enable warning for deprecated declarations on macOS
  configure.ac
Labels: Build

#8954 Use std::unique_ptr for X509 and BIO scoped heap objects.
  iocore/net/OCSPStapling.cc
  iocore/net/P_SSLUtils.h
  iocore/net/SSLUtils.cc
Labels: Cleanup

#8957 Remove unneccessary const qualifiers
  configure.ac
  iocore/net/quic/QUICFrame.cc
  iocore/net/quic/QUICFrame.h
  iocore/net/quic/QUICPacket.cc
  iocore/net/quic/QUICPacket.h
  plugins/regex_revalidate/regex_revalidate.c
Labels: Cleanup

#8953 Hostdb Restructure
  configs/body_factory/default/Makefile.am
  configs/body_factory/default/connect#all_dead
  doc/developer-guide/core-architecture/HostDB-Data-Layout.svg
  doc/developer-guide/core-architecture/hostdb.en.rst
  doc/developer-guide/core-architecture/index.en.rst
  doc/uml/host-resolve.plantuml
  example/plugins/c-api/protocol/TxnSM.c
  include/ts/ts.h
  include/tscore/BufferWriter.h
  include/tscore/BufferWriterForward.h
  include/tscore/Diags.h
  include/tscore/bwf_std_format.h
  include/tscore/ink_time.h
  include/tscore/ts_file.h
  iocore/dns/P_SplitDNSProcessor.h
  iocore/dns/SRV.h
  iocore/dns/SplitDNS.cc
  iocore/hostdb/HostDB.cc
  iocore/hostdb/I_HostDBProcessor.h
  iocore/hostdb/P_HostDBProcessor.h
  plugins/lua/ts_lua_misc.c
  proxy/ControlMatcher.h
  proxy/ParentSelection.cc
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpConnectionCount.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpSM.h
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  proxy/http/PreWarmManager.cc
  proxy/http/PreWarmManager.h
  proxy/http/remap/unit-tests/nexthop_test_stubs.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/InkAPITest.cc
  src/tscore/unit_tests/test_BufferWriterFormat.cc
  tests/gold_tests/next_hop/strategies_ch2/strategies_ch2.test.py
  tests/gold_tests/proxy_protocol/proxy_serve_stale.test.py
  tests/gold_tests/tls/tls_verify_override_base.test.py
Labels: HostDB, Feature

#8971 Fixes issue with file size calculation for existing logs
  src/tscore/BaseLogFile.cc
Labels: Bug

#8975 Fix reverting PR#7302
  proxy/http/HttpSM.cc
Labels: HTTP, Crash

#8970 add a metric to track how often the range seek bug is detected
  iocore/cache/Cache.cc
  iocore/cache/CacheRead.cc
  iocore/cache/P_CacheInternal.h
Labels: Cache, Metrics

#8949 Do NOT setup internal transfer if ua_entry is nullptr
  proxy/http/HttpSM.cc
Labels: HTTP

#8977 Update roadmap doc with latest releases
  doc/release-notes/roadmap.en.rst
Labels: Documentation

#8985 Fix autest: Add missing config value for origin's dead policy.
  tests/gold_tests/tls/tls_verify_override_base.test.py
Labels: AuTest

#8890 Update slice to only prefetch when first block is miss/hit-stale
  doc/admin-guide/plugins/slice.en.rst
  plugins/cache_range_requests/cache_range_requests.cc
  plugins/experimental/slice/Data.h
  plugins/experimental/slice/HttpHeader.h
  plugins/experimental/slice/prefetch.cc
  plugins/experimental/slice/prefetch.h
  plugins/experimental/slice/server.cc
  plugins/experimental/slice/util.cc
  tests/gold_tests/pluginTest/slice/gold/slice_prefetch.gold
  tests/gold_tests/pluginTest/slice/slice_prefetch.test.py
Labels: Plugins

#8982 Add anonymous mmdb support
  doc/admin-guide/plugins/maxmind_acl.en.rst
  plugins/experimental/maxmind_acl/mmdb.cc
  plugins/experimental/maxmind_acl/mmdb.h
Labels: Plugins
