Repository apache/trafficserver, pull requests merged in 2022-05, with the labels that each got.

#8747 Add http2.default_buffer_water_mark config to tune latency
  doc/admin-guide/files/records.config.en.rst
  iocore/net/UnixNetVConnection.cc
  mgmt/RecordsConfig.cc
  proxy/http2/HTTP2.cc
  proxy/http2/HTTP2.h
  proxy/http2/Http2ClientSession.cc
  proxy/http2/Http2CommonSession.cc
  proxy/http2/Http2CommonSession.h
  proxy/http2/Http2ConnectionState.cc
Labels: HTTP/2, Performance

#8819 build: use non-deprecated form of autoconf macro
  build/nuraft.m4
Labels: Build

#8821 Fixes leak of SNI config filename on load
  iocore/net/P_SSLSNI.h
  iocore/net/SSLSNIConfig.cc
  iocore/net/YamlSNIConfig.cc
  iocore/net/YamlSNIConfig.h
Labels: Leak

#8802 Change remap loading to be fatal during startup.
  doc/admin-guide/files/records.config.en.rst
  doc/admin-guide/files/remap.config.en.rst
  mgmt/RecordsConfig.cc
  proxy/ReverseProxy.cc
  proxy/http/remap/RemapConfig.cc
  proxy/http/remap/UrlRewrite.cc
  proxy/http/remap/UrlRewrite.h
  tests/gold_tests/remap/reload_1.replay.yaml
  tests/gold_tests/remap/reload_2.replay.yaml
  tests/gold_tests/remap/reload_3.replay.yaml
  tests/gold_tests/remap/reload_4.replay.yaml
  tests/gold_tests/remap/reload_server.replay.yaml
  tests/gold_tests/remap/remap_load_empty_failure.test.py
  tests/gold_tests/remap/remap_load_empty_success.test.py
  tests/gold_tests/remap/remap_load_missing_failure.test.py
  tests/gold_tests/remap/remap_load_missing_success.test.py
  tests/gold_tests/remap/remap_reload.test.py
Labels: remap

#8815 Fedora/RHEL path layout for config.layout
  config.layout
Labels: Build

#8829 Fix a compile error
  iocore/cache/CacheWrite.cc
Labels: Build

#8827 Fixes leak in SNIAction name globbing
  iocore/net/P_SSLSNI.h
  iocore/net/SSLSNIConfig.cc
Labels: Leak

#8834 Handle opentelemetry-cpp v1.3.0 upgrade for otel_tracer plugin
  configure.ac
  doc/admin-guide/plugins/otel_tracer.en.rst
Labels: Plugins

#8804 Add support for request body transaction data sink
  doc/developer-guide/api/types/TSHttpHookID.en.rst
  doc/developer-guide/plugins/http-transformations/index.en.rst
  example/plugins/c-api/txn_data_sink/txn_data_sink.cc
  include/ts/apidefs.h.in
  include/tscpp/api/TransformationPlugin.h
  proxy/ProxySession.cc
  proxy/http/HttpDebugNames.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpSM.h
  src/traffic_server/InkAPITest.cc
  src/tscpp/api/TransformationPlugin.cc
  src/tscpp/api/utils_internal.cc
  tests/gold_tests/pluginTest/transform/transaction-with-body.replays.yaml
  tests/gold_tests/pluginTest/transform/transaction_data_sink.test.py
Labels: Plugins

#8830 Change ip-allow debug tag to ip_allow.
  proxy/IPAllow.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  tests/gold_tests/ip_allow/ip_allow.test.py
Labels: Cleanup, Debug

#8660 Fix overflow conditions in prefetch plugin
  doc/admin-guide/plugins/prefetch.en.rst
  plugins/prefetch/Makefile.inc
  plugins/prefetch/evaluate.cc
  plugins/prefetch/evaluate.h
  plugins/prefetch/plugin.cc
  plugins/prefetch/test/test_evaluate.cc
Labels: Plugins

#8835 Remove incorrect comment from base64 functions
  include/tscore/ink_base64.h
Labels: Cleanup

#8779 Add autest to cover updates to cache with alternates
  iocore/cache/Cache.cc
  tests/gold_tests/cache/alternate-caching.test.py
  tests/gold_tests/cache/replay/alternate-caching-update-size.yaml
Labels: Cache, AuTest

#8837 Add compatibility define when building with OpenSSL3
  build/crypto.m4
  configure.ac
Labels: Build, SSL

#8840 Remove CODEOWNERS file
  CODEOWNERS
Labels: GitHub

#8846 Add `#pragma once` for PendingAction.h
  include/tscore/PendingAction.h
Labels: Build

#8839 gcc 12.1.1 fix warning about reading larger than the buffer
  src/tscore/unit_tests/test_CryptoHash.cc
Labels: Tests

#8831 Fix parent_select optional scheme
  plugins/experimental/parent_select/strategy.cc
  proxy/http/remap/NextHopSelectionStrategy.cc
  tests/gold_tests/pluginTest/parent_select/parent_select_optional_scheme_matching.test.py
Labels: Plugins, Bug, 9.2.0

#8817 Fix `COMPRESSION_ERROR` on valid HPACK input
  proxy/hdrs/HuffmanCodec.cc
  proxy/hdrs/test_Huffmancode.cc
  proxy/hdrs/unit_tests/test_XPACK.cc
Labels: HTTP/2, Bug

#8847 Restore down nameservers after they come back online
  iocore/dns/DNS.cc
  iocore/dns/P_DNSProcessor.h
  tests/gold_tests/dns/dns_down_nameserver.test.py
  tests/gold_tests/dns/replay/multiple_host_requests.replay.yaml
Labels: DNS, Bug

#8852 traffic_ctl - JSONRPC: make sure we display the error regardless of the formatting type.
  include/shared/rpc/RPCRequests.h
  src/traffic_ctl_jsonrpc/CtrlPrinters.cc
Labels: JSONRPC

#8838 mkdfa.c is not being used and doesn't compile with gcc 12.1.1
  src/tscore/Makefile.am
  src/tscore/mkdfa.c
Labels: Core, Build

#8850 Fix Rocky Linux 8 arm64 GCC Compiler Warnings
  iocore/eventsystem/I_Continuation.h
  iocore/net/quic/QUICStreamVCAdapter.cc
  iocore/net/quic/QUICStreamVCAdapter.h
  lib/fastlz/fastlz.cc
  plugins/experimental/traffic_dump/json_utils.cc
  plugins/header_rewrite/conditions.cc
  proxy/http3/Http3HeaderVIOAdaptor.h
Labels: Build

#8810 Add Au test for prefetch plugin in simple mode.
  tests/gold_tests/pluginTest/prefetch_simple/prefetch_simple.gold
  tests/gold_tests/pluginTest/prefetch_simple/prefetch_simple.test.py
Labels: Plugins, AuTest, needs +1 review

#8859 Re-introduce import to get man_pages list available for sphinx.
  doc/conf.py
Labels: Documentation

#8853 Change parent_select Init func to constructor
  plugins/experimental/parent_select/consistenthash.cc
  plugins/experimental/parent_select/consistenthash.h
  plugins/experimental/parent_select/consistenthash_config.cc
  plugins/experimental/parent_select/strategy.cc
  plugins/experimental/parent_select/strategy.h
  proxy/http/remap/NextHopConsistentHash.cc
  proxy/http/remap/NextHopConsistentHash.h
  proxy/http/remap/NextHopRoundRobin.h
  proxy/http/remap/NextHopSelectionStrategy.cc
  proxy/http/remap/NextHopSelectionStrategy.h
  proxy/http/remap/NextHopStrategyFactory.cc
Labels: Plugins

#8861 Add missing configuration files man pages
  doc/manpages.py
Labels: Documentation

#8866 Fix "is is" typos.
  plugins/compress/compress.cc
  src/wccp/WccpLocal.h
Labels: Cleanup

#8856 Fix traffic_ctl server drain(undo) jsonrpc api call.
  src/traffic_ctl_jsonrpc/jsonrpc/CtrlRPCRequests.h
Labels: JSONRPC

#8868 Update to Proxy Verifier v2.3.3
  tests/gold_tests/chunked_encoding/bad_chunked_encoding.test.py
  tests/prepare_proxy_verifier.sh
  tests/proxy-verifier-version.txt
Labels: AuTest

#8872 remap_reload AuTest: await config reload messages
  tests/gold_tests/remap/remap_reload.test.py
Labels: AuTest
