Repository apache/trafficserver, pull requests merged in 2022-03, with the labels that each got.

#8677 Update iocore/cache/test to fix the build
  iocore/cache/Makefile.am
  iocore/cache/test/stub.cc
Labels: Build, Tests, cache-tests

#8695 traffic_ctl - Add rpc invoke option.
  doc/appendices/command-line/traffic_ctl_jsonrpc.en.rst
  doc/developer-guide/jsonrpc/jsonrpc-architecture.en.rst
  include/shared/rpc/RPCRequests.h
  src/traffic_ctl_jsonrpc/CtrlCommands.cc
  src/traffic_ctl_jsonrpc/CtrlCommands.h
  src/traffic_ctl_jsonrpc/jsonrpc/CtrlRPCRequests.h
  src/traffic_ctl_jsonrpc/traffic_ctl.cc
Labels: JSONRPC

#8696 MGMT - Improve invalid rpc param error description and some cleanup.
  mgmt2/rpc/jsonrpc/error/RPCError.cc
  mgmt2/rpc/jsonrpc/unit_tests/test_basic_protocol.cc
Labels: JSONRPC

#8706 Provide libquic.a definition to VIO::VIO()
  src/traffic_server/Makefile.inc
Labels: Build

#8692 Add docs for parent.config defaults
  doc/admin-guide/files/parent.config.en.rst
Labels: Documentation

#8707 cache-request-method autest: Extending IO delay
  tests/gold_tests/cache/replay/post_with_post_caching_enabled.replay.yaml
Labels: AuTest

#8700 Change api TSSslTicketKeyUpdate to return TSReturnCode
  include/ts/ts.h
  iocore/net/P_SSLConfig.h
  iocore/net/SSLConfig.cc
  src/traffic_server/InkAPI.cc
Labels: TS API

#8704 traffic_ctl - Use better format output options.
  doc/appendices/command-line/traffic_ctl_jsonrpc.en.rst
  doc/developer-guide/jsonrpc/jsonrpc-handler-development.en.rst
  src/traffic_ctl_jsonrpc/CtrlCommands.cc
  src/traffic_ctl_jsonrpc/CtrlPrinters.h
  src/traffic_ctl_jsonrpc/traffic_ctl.cc
Labels: JSONRPC

#8711 Move hwloc-based functions into it's own header/compilation unit
  include/tscore/ink_defs.h
  include/tscore/ink_hw.h
  iocore/aio/AIO.cc
  iocore/aio/test_AIO.cc
  iocore/eventsystem/UnixEventProcessor.cc
  iocore/net/test_I_Net.cc
  src/traffic_layout/info.cc
  src/traffic_server/traffic_server.cc
  src/tscore/Makefile.am
  src/tscore/ink_defs.cc
  src/tscore/ink_hw.cc
  src/tscore/unit_tests/freelist_benchmark.cc
Labels: Cleanup

#8688 update FREELIST macros for AArch64
  include/tscore/ink_queue.h
Labels: Core

#8715 Fixes build when hwloc is not installed
  src/tscore/ink_hw.cc
Labels: Cleanup

#8719 Fixed memory leaks with CryptoContext
  include/tscore/CryptoHash.h
  include/tscore/MD5.h
  include/tscore/SHA256.h
  src/traffic_server/traffic_server.cc
  src/tscore/CryptoHash.cc
  src/tscore/Makefile.am
  src/tscore/unit_tests/test_CryptoHash.cc
Labels: Core, Incompatible, Leak

#8724 Change DNS retries to be a static (requires restart) config value
  mgmt/RecordsConfig.cc
Labels: DNS, Bug

#8716 Check bounds before accessing Vol::evacuate array
  iocore/cache/CacheWrite.cc
  iocore/cache/P_CacheVol.h
Labels: Cache

#8703 8.1.x: docs: Add option to mostly strictly check URL characters (#8012)
  doc/admin-guide/files/records.config.en.rst
Labels: HTTP, Documentation, Backport

#8701 8.1.x: Add option to mostly strictly check URL characters (#8012)
  mgmt/RecordsConfig.cc
  proxy/hdrs/HTTP.cc
  proxy/hdrs/HTTP.h
  proxy/hdrs/HdrTSOnly.cc
  proxy/hdrs/URL.cc
  proxy/hdrs/URL.h
  proxy/http/HttpConfig.cc
  tests/gold_tests/headers/gold/bad_good_request.gold
  tests/gold_tests/headers/gold/bad_good_request_header.gold
  tests/gold_tests/headers/gold/bad_good_request_http1.gold
  tests/gold_tests/headers/gold/bad_method.gold
  tests/gold_tests/headers/gold/bad_protocol_number.gold
  tests/gold_tests/headers/gold/bad_te_value.gold
  tests/gold_tests/headers/good_request_after_bad.test.py
Labels: HTTP, Backport

#8732 Default proxy.config.http.strict_uri_parsing to "2" (#8632)
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  proxy/http/HttpConfig.h
Labels: Configuration

#8731 Bug fix in origin connection handling
  iocore/net/SSLNetVConnection.cc
  iocore/net/YamlSNIConfig.h
Labels: Bug, SSL

#8722 Adds user-agent to OCSP requests
  iocore/net/OCSPStapling.cc
  iocore/net/P_SSLConfig.h
  iocore/net/SSLConfig.cc
Labels: SSL

#8733 libswoc: Make libswoc implementation overridable, header export optional
  build/libswoc.m4
  configure.ac
  lib/Makefile.am
Labels: CPP Util

#8729 Address issues with python 3.10
  tests/Pipfile
  tests/gold_tests/autest-site/ordered_set_queue.py
Labels: AuTest

#8737 Require use of 'override' keyword when valid.
  configure.ac
  include/tscore/PluginUserArgs.h
  iocore/cache/CacheTest.cc
  iocore/cache/P_CacheTest.h
  iocore/net/P_QUICNextProtocolAccept.h
  iocore/net/quic/Mock.h
  plugins/esi/esi.cc
  plugins/esi/test/StubIncludeHandler.h
  plugins/esi/test/TestHttpDataFetcher.h
  plugins/experimental/parent_select/strategy.h
  plugins/experimental/webp_transform/ImageTransform.cc
  plugins/s3_auth/unit_tests/test_aws_auth_v4.h
  proxy/http/remap/PluginDso.h
  proxy/http/remap/unit-tests/test_PluginDso.cc
  proxy/http/remap/unit-tests/test_PluginFactory.cc
  proxy/http3/Http3SessionAccept.h
  src/wccp/WccpLocal.h
Labels: Cleanup

#8738 ts_lua: change type in stats struct from 'int' to 'TSMgmtInt' to avoid overflow
  plugins/lua/ts_lua.c
Labels: Plugins, Lua

#8725 Update THREAD_FREE macro to only evaluate the _t parameter once.
  iocore/eventsystem/I_ProxyAllocator.h
  iocore/eventsystem/Makefile.am
  iocore/eventsystem/unit_tests/benchmark_ProxyAllocator.cc
  proxy/http/HttpSM.cc
Labels: Core, Performance

#8657 Support transforming range requests when origin returns full resource.
  doc/admin-guide/files/records.config.en.rst
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  tests/gold_tests/cache/cache-range-response.test.py
  tests/gold_tests/cache/replay/cache-range-response.replay.yaml
Labels: Cache

#8718 Enable all iocore/cache tests
  iocore/cache/Makefile.am
  iocore/cache/test/main.cc
  iocore/cache/test/test_RWW.cc
Labels: Tests

#8744 Remove null check before ats_free calls
  iocore/cache/CacheHosting.cc
  iocore/cache/P_CacheInternal.h
  iocore/net/ALPNSupport.cc
  iocore/net/OCSPStapling.cc
  iocore/net/SSLNextProtocolSet.cc
  iocore/net/TLSTunnelSupport.cc
  iocore/net/UnixUDPNet.cc
  lib/records/RecCore.cc
  lib/records/RecUtils.cc
  lib/records/test_RecProcess.i
  plugins/experimental/memcache/tsmemcache.cc
  proxy/http/HttpSM.cc
  proxy/http/remap/RemapConfig.cc
  proxy/http/remap/UrlMapping.h
  proxy/http/remap/UrlRewrite.cc
  proxy/http/remap/unit-tests/nexthop_test_stubs.cc
  proxy/http2/Http2Stream.cc
  proxy/http3/QPACK.cc
  proxy/logging/LogFormat.cc
  src/traffic_server/InkAPI.cc
Labels: Cleanup

#8655 money_trace: allow custom header, change span-id gen, opt to create if none
  doc/admin-guide/plugins/money_trace.en.rst
  plugins/experimental/money_trace/README
  plugins/experimental/money_trace/money_trace.cc
  plugins/experimental/money_trace/money_trace.h
  tests/gold_tests/pluginTest/money_trace/gold/global-log.gold
  tests/gold_tests/pluginTest/money_trace/gold/remap-log.gold
  tests/gold_tests/pluginTest/money_trace/money_trace.test.py
  tests/gold_tests/pluginTest/money_trace/money_trace_global.test.py
Labels: Plugins

#8742 Fixes Issue #7824 - The strategies.yaml parser can incorrectly interpret
  plugins/experimental/parent_select/strategy.cc
  proxy/http/remap/NextHopSelectionStrategy.cc
Labels: Bug, 9.2.0

#8689 Hoststatus remove stats creation.
  doc/appendices/command-line/traffic_ctl_jsonrpc.en.rst
  doc/developer-guide/jsonrpc/jsonrpc-api.en.rst
  include/shared/rpc/yaml_codecs.h
  include/tscore/Filenames.h
  proxy/HostStatus.h
  src/traffic_ctl_jsonrpc/CtrlCommands.cc
  src/traffic_ctl_jsonrpc/CtrlPrinters.cc
  src/traffic_ctl_jsonrpc/jsonrpc/CtrlRPCRequests.h
  src/traffic_ctl_jsonrpc/jsonrpc/ctrl_yaml_codecs.h
  src/traffic_ctl_jsonrpc/traffic_ctl.cc
  src/traffic_server/HostStatus.cc
  src/traffic_server/RpcAdminPubHandlers.cc
  src/traffic_server/traffic_server.cc
Labels: Commands, JSONRPC

#8745 Add log format for whether origin TLS connection resumed an existing TLS session
  doc/admin-guide/logging/formatting.en.rst
  iocore/net/TLSSessionResumptionSupport.cc
  iocore/net/TLSSessionResumptionSupport.h
  proxy/http/HttpSM.cc
  proxy/http/HttpSM.h
  proxy/logging/Log.cc
  proxy/logging/LogAccess.cc
  proxy/logging/LogAccess.h
Labels: Logging, TLS, Origin Session

#8740 Require use of 'override' keyword when valid. (#8737)
  configure.ac
  include/shared/rpc/RPCRequests.h
  include/tscore/PluginUserArgs.h
  iocore/cache/CacheTest.cc
  iocore/cache/P_CacheTest.h
  iocore/net/P_QUICNextProtocolAccept.h
  iocore/net/quic/Mock.h
  plugins/esi/esi.cc
  plugins/esi/test/StubIncludeHandler.h
  plugins/esi/test/TestHttpDataFetcher.h
  plugins/experimental/parent_select/strategy.h
  plugins/experimental/webp_transform/ImageTransform.cc
  plugins/s3_auth/unit_tests/test_aws_auth_v4.h
  proxy/http/remap/PluginDso.h
  proxy/http/remap/unit-tests/test_PluginDso.cc
  proxy/http/remap/unit-tests/test_PluginFactory.cc
  proxy/http3/Http3SessionAccept.h
  src/traffic_ctl_jsonrpc/CtrlCommands.h
  src/traffic_ctl_jsonrpc/jsonrpc/CtrlRPCRequests.h
  src/wccp/WccpLocal.h
Labels: Cleanup, needs +1 review

#8710 Move Sterror class from TsSharedMutex.h to its own include file.
  include/tscpp/util/Makefile.am
  include/tscpp/util/Strerror.h
  include/tscpp/util/TsSharedMutex.h
Labels: Cleanup, CPP Util

#8749 marks the HostStatusGetRequest::get_method as an override.
  src/traffic_ctl_jsonrpc/jsonrpc/CtrlRPCRequests.h
Labels: Cleanup

#8750 Use Sphinx 4.x
  doc/Pipfile
  doc/developer-guide/api/types/TSSslSession.en.rst
Labels: Documentation

#8752 docs: add some obvious units to some http2 overridables
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#8754 Revert "Use Sphinx 4.x"
  doc/Pipfile
  doc/developer-guide/api/types/TSSslSession.en.rst
Labels: Documentation

#8753 Update to proxy-verifier-v2.3.1
  tests/prepare_proxy_verifier.sh
  tests/proxy-verifier-version.txt
Labels: AuTest

#8757 Use Sphinx 4.x (second attempt)
  doc/Pipfile
  doc/conf.py
  doc/developer-guide/api/types/TSSslSession.en.rst
Labels: Documentation

#8736 [ink_base64] Fix buffer size computation
  include/tscore/ink_base64.h
  plugins/experimental/access_control/unit_tests/test_utils.cc
  plugins/experimental/access_control/utils.cc
  plugins/experimental/metalink/metalink.cc
  src/tscore/ink_base64.cc
Labels: Core, Bug

#8765 Fixing the httpbin AuTests by pinning Werkzeug
  tests/Pipfile
Labels: AuTest

#8763 Fix error handling in SSL cert/key load failures
  iocore/net/SSLUtils.cc
Labels: TLS, Bug

#8762 Avoid allocation when matching hosts for vol lookup
  iocore/cache/CacheHosting.cc
  iocore/cache/P_CacheHosting.h
Labels: Cache, Performance

#8770 Remove null check before ats_free calls (#8744)
  iocore/cache/CacheHosting.cc
  iocore/cache/P_CacheInternal.h
  iocore/net/ALPNSupport.cc
  iocore/net/OCSPStapling.cc
  iocore/net/SSLNextProtocolSet.cc
  iocore/net/UnixUDPNet.cc
  lib/records/RecCore.cc
  lib/records/RecUtils.cc
  lib/records/test_RecProcess.i
  plugins/experimental/memcache/tsmemcache.cc
  proxy/http/HttpSM.cc
  proxy/http/remap/RemapConfig.cc
  proxy/http/remap/UrlMapping.h
  proxy/http/remap/UrlRewrite.cc
  proxy/http/remap/unit-tests/nexthop_test_stubs.cc
  proxy/http2/Http2Stream.cc
  proxy/http3/QPACK.cc
  proxy/logging/LogFormat.cc
  src/traffic_server/InkAPI.cc
Labels: Cleanup, Backport

#8773 Pin Jinja2 for doc builds
  doc/Pipfile
Labels: Documentation

#8764 Lua plugin memory leak on remap configuration reloads
  doc/admin-guide/plugins/lua.en.rst
  plugins/lua/ts_lua.c
  plugins/lua/ts_lua_common.h
  plugins/lua/ts_lua_util.c
Labels: Lua, Bug, Leak

#8772 Add metrics for loop detection.
  doc/admin-guide/monitoring/statistics/core/http-connection.en.rst
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpTransact.cc
Labels: Metrics
