Repository apache/trafficserver, pull requests merged in 2023-05, with the labels that each got.

#9656 Prefer the __linux__ macro over linux.
  include/tscore/ink_platform.h
  include/tscore/ink_rwlock.h
  include/tscpp/util/TsSharedMutex.h
  iocore/cache/Store.cc
  iocore/eventsystem/I_SocketManager.h
  iocore/net/P_UnixNet.h
  iocore/net/UnixNetAccept.cc
  mgmt/utils/MgmtSocket.cc
  proxy/logging/LogBuffer.h
  proxy/logging/LogFormat.cc
  src/traffic_server/traffic_server.cc
  src/tscore/ink_file.cc
  src/tscore/ink_memory.cc
  src/tscore/ink_res_mkquery.cc
  tools/http_load/port.h
Labels: Build

#9659 Remove obsolete signals check.
  include/tscore/signals.h
  src/tscore/signals.cc
Labels: Cleanup

#9650 Replace deprecated Debug() macro with Dbg() in cache_scan.cc.
  example/plugins/c-api/cache_scan/cache_scan.cc
Labels: Debug

#9616 Add support for CONNECT method on HTTP/2 connection
  proxy/hdrs/VersionConverter.cc
  proxy/http2/HTTP2.cc
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2Stream.cc
  proxy/http2/Http2Stream.h
Labels: HTTP/2

#9662 OCSP: Fix unitialized variable error.
  iocore/net/OCSPStapling.cc
Labels: Cleanup

#9655 rename attempts to retry_attempts
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  proxy/logging/LogAccess.cc
Labels: Cleanup

#9648 cmake build, fixed warning using older openssl APIs
  plugins/certifier/CMakeLists.txt
Labels: Build, certifier

#9660 Try to do less work in hot function HttpHookState::getNext
  proxy/InkAPIInternal.h
  src/traffic_server/InkAPI.cc
Labels: Performance

#9620 Return current parent max retry count for parent proxy
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
Labels: Tests

#9669 setup pre-commit hook at cmake generation time
  CMakeLists.txt
Labels: Build

#9664 Cleanup: remove ts::Buffer from ControlBase.
  proxy/ControlBase.cc
Labels: Cleanup

#9661 Cleanup: remove TsBuffer.h from MIME.cc
  proxy/hdrs/MIME.cc
Labels: Cleanup

#9675 Fix leak in MultiTextMod in ControlBase.
  proxy/ControlBase.cc
Labels: Leak

#9677 Cleanup: remove ts::buffer from HostDB.
  iocore/hostdb/P_HostDBProcessor.h
Labels: Cleanup

#9671 Stabilize autest tls_hooks17
  tests/gold_tests/tls_hooks/tls_hooks17.test.py
Labels: AuTest

#9670 Don't build native QUIC implementation
  build/quiche.m4
  configure.ac
  iocore/net/Makefile.am
  iocore/net/quic/Makefile.am
  src/traffic_quic/Makefile.inc
  src/traffic_server/Makefile.inc
Labels: QUIC

#9685 Added Zhengxi to the asf contributors
  .asf.yaml
Labels: GitHub

#9654 Doc: Add example of --enable-lto build option with LLVM
  doc/admin-guide/installation/index.en.rst
Labels: Documentation

#9688 Remove flask from tests/Pipfile
  tests/Pipfile
Labels: AuTest

#9674 Add error log for invalid OCSP response
  iocore/net/OCSPStapling.cc
Labels: TLS

#9672 Fixes crashes around OCSP with FetchSM
  iocore/net/OCSPStapling.cc
  src/traffic_server/FetchSM.cc
Labels: TLS, Crash

#9692 Fix event queue corruption on PreWarmManager::reconfigure
  proxy/http/PreWarmManager.cc
Labels: Threads

#9684 Replace curl with proxy verifier in proxy protocol tests
  tests/gold_tests/proxy_protocol/gold/access.gold
  tests/gold_tests/proxy_protocol/gold/test_case_0_stderr.gold
  tests/gold_tests/proxy_protocol/gold/test_case_0_stdout.gold
  tests/gold_tests/proxy_protocol/gold/test_case_1_stderr.gold
  tests/gold_tests/proxy_protocol/gold/test_case_1_stdout.gold
  tests/gold_tests/proxy_protocol/gold/test_case_2_stdout.gold
  tests/gold_tests/proxy_protocol/gold/test_case_3_stderr.gold
  tests/gold_tests/proxy_protocol/gold/test_case_3_stdout.gold
  tests/gold_tests/proxy_protocol/gold/test_case_4_stderr.gold
  tests/gold_tests/proxy_protocol/gold/test_case_4_stdout.gold
  tests/gold_tests/proxy_protocol/proxy_protocol.test.py
  tests/gold_tests/proxy_protocol/proxy_protocol_server.py
  tests/gold_tests/proxy_protocol/replay/proxy_protocol_in.replay.yaml
  tests/gold_tests/proxy_protocol/replay/proxy_protocol_out.replay.yaml
Labels: AuTest

#9630 Make io_uring or thread AIO modes a startup time decision (vs compile time)
  CMakeLists.txt
  doc/admin-guide/files/records.yaml.en.rst
  include/tscore/ink_config.h.cmake.in
  iocore/aio/AIO.cc
  iocore/aio/I_AIO.h
  iocore/aio/P_AIO.h
  iocore/aio/sample.cfg
  iocore/aio/test_AIO.cc
  iocore/io_uring/I_IO_URING.h
  iocore/io_uring/io_uring.cc
  iocore/net/UnixNet.cc
  src/records/RecordsConfig.cc
  src/traffic_server/CMakeLists.txt
  src/traffic_server/traffic_server.cc
Labels: AIO

#9701 Changes for C++20
  include/tscore/List.h
  include/tscore/Ptr.h
  iocore/eventsystem/I_IOBuffer.h
  plugins/s3_auth/aws_auth_v4_wrap.h
  proxy/hdrs/MIME.h
Labels: Build

#9699 Reload hosting.config on TASK thread
  iocore/cache/CacheHosting.cc
Labels: Configuration

#9700 libswoc: Update to 1.4.10
  iocore/eventsystem/IOBuffer.cc
  lib/swoc/CMakeLists.txt
  lib/swoc/Makefile.am
  lib/swoc/include/swoc/BufferWriter.h
  lib/swoc/include/swoc/IPAddr.h
  lib/swoc/include/swoc/IPRange.h
  lib/swoc/include/swoc/Lexicon.h
  lib/swoc/include/swoc/MemArena.h
  lib/swoc/include/swoc/MemSpan.h
  lib/swoc/include/swoc/TextView.h
  lib/swoc/include/swoc/bwf_base.h
  lib/swoc/include/swoc/bwf_fwd.h
  lib/swoc/include/swoc/bwf_std.h
  lib/swoc/include/swoc/swoc_version.h
  lib/swoc/src/MemArena.cc
  lib/swoc/src/bw_format.cc
  lib/swoc/src/bw_ip_format.cc
  lib/swoc/src/swoc_ip.cc
Labels: CPP Util

#9703 Changes for C++23
  proxy/http/HttpSM.cc
  src/traffic_server/InkAPITest.cc
Labels: Build

#9676 Remove deprecated debug output functions from 13 source files.
  include/tscore/Diags.h
  iocore/eventsystem/ConfigProcessor.cc
  iocore/eventsystem/ConfigProcessor.h
  iocore/eventsystem/RecProcess.cc
  iocore/eventsystem/RecRawStatsImpl.cc
  iocore/hostdb/HostDB.cc
  iocore/hostdb/HostFile.cc
  iocore/hostdb/P_RefCountCache.h
  iocore/hostdb/P_RefCountCacheSerializer.h
  iocore/hostdb/test_HostFile.cc
  iocore/net/P_SSLUtils.h
  iocore/net/SSLSecret.cc
  iocore/net/SSLUtils.cc
  iocore/net/Socks.cc
Labels: Debug

#9679 autoconf: Add lib flags for the quiche build test.
  build/quiche.m4
  tools/build_h3_tools.sh
Labels: QUIC

#9710 build_h3_tools.sh: Remove an unneeded dir check
  tools/build_h3_tools.sh
Labels: Tools, QUIC

#9691 Check the calling thread of Ethread::schedule_local
  iocore/eventsystem/P_UnixEThread.h
Labels: Threads

#9665 Cleanup: remove ts::Buffer from LogField.
  proxy/logging/LogField.cc
  proxy/logging/LogField.h
Labels: Cleanup

#9711 Only need to include eventfd for native mode.
  iocore/aio/AIO.cc
Labels: Cleanup

#9714 Fix H3 transaction leak
  proxy/http3/Http3App.cc
  proxy/http3/Http3Transaction.cc
  proxy/http3/Http3Transaction.h
Labels: HTTP/3

#9721 Add CentOS to the required builds
  .asf.yaml
Labels: CI

#9722 Fix ttmsh log field
  proxy/logging/Log.cc
Labels: Logging

#9720 Add automatic detection of ccache for cmake
  CMakeLists.txt
  cmake/find_ccache.cmake
Labels: Build

#9698 Fix PROXY protocol out with tls
  proxy/http/ConnectingEntry.cc
  tests/gold_tests/post_slow_server/gold/post_slow_server_max_requests_in_0_stderr.gold
  tests/gold_tests/proxy_protocol/proxy_protocol.test.py
Labels: Bug, PROXY Protocol

#9724 Fix TS_HTTP_REQUEST_TRANSFORM_HOOK Tunnel Processing
  proxy/http/HttpSM.cc
  tests/gold_tests/pluginTest/multiplexer/multiplexer.test.py
Labels: Transform

#9716 Fix protocol version in request Via header
  iocore/net/QUICNetVConnection_quiche.cc
  proxy/http/HttpTransactHeaders.cc
  tests/gold_tests/headers/via.test.py
  tests/gold_tests/headers/via_h3.gold
Labels: HTTP/3

#9726 Don't build traffic_quic command
  src/Makefile.am
Labels: Build, QUIC

#9725 Cleanup: Fix format of doc corruption message
  iocore/cache/CacheRead.cc
Labels: Cache, Cleanup

#9394 Add BRAVO Reader-Writer Lock
  .gitignore
  NOTICE
  include/tscpp/util/Bravo.h
  include/tscpp/util/DenseThreadId.h
  src/tscore/Makefile.am
  src/tscore/unit_tests/benchmark_shared_mutex.cc
  src/tscore/unit_tests/test_Bravo.cc
  src/tscpp/util/Makefile.am
Labels: Performance

#9713 Doc: Clarify that connect ports can have multiple values
  doc/admin-guide/files/records.yaml.en.rst
Labels: Documentation

#9715 Fix a potential crash due to use-after-free on QUIC connections
  iocore/net/P_QUICNetVConnection_quiche.h
  iocore/net/QUICNetVConnection_quiche.cc
Labels: QUIC

#9728 Make config.proxy.http.no_dns_just_forward_to_parent overridable
  doc/admin-guide/files/records.yaml.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  include/ts/apidefs.h.in
  plugins/header_rewrite/operators.cc
  plugins/lua/ts_lua_http_config.c
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  src/shared/overridable_txn_vars.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/InkAPITest.cc
Labels: Configuration, DNS

#9735 Updates to cmake install to get a running ATS from a fresh install
  CMakeLists.txt
  configs/CMakeLists.txt
  lib/CMakeLists.txt
Labels: Build

#9737 Fix quic_no_activity_timeout test
  tests/gold_tests/timeout/quic_no_activity_timeout.test.py
Labels: QUIC

#9738 Fix a crash caused by a HTTP/2 GET request with a body
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2Stream.cc
  tests/gold_tests/cache/background_fill.test.py
  tests/gold_tests/cache/gold/background_fill_3_stdout.gold
  tests/gold_tests/cache/replay/bg_fill.yaml
  tests/gold_tests/h2/gold/server_after_headers.gold
  tests/gold_tests/h2/h2get_with_body.test.py
  tests/gold_tests/h2/h2get_with_body.yaml
  tests/gold_tests/h2/http2_rst_stream.test.py
  tests/prepare_proxy_verifier.sh
  tests/proxy-verifier-version.txt
Labels: HTTP/2

#9582 Term standardization: dead/down server -> down server
  configs/body_factory/default/Makefile.am
  configs/body_factory/default/connect#all_down
  configs/records.yaml.default.in
  doc/admin-guide/files/records.yaml.en.rst
  doc/admin-guide/monitoring/statistics/core/http-connection.en.rst
  doc/admin-guide/plugins/lua.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  doc/developer-guide/core-architecture/hostdb.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/files/records.config.en.po
  doc/locale/ja/LC_MESSAGES/developer-guide/api/functions/TSHttpOverridableConfig.en.po
  doc/release-notes/upgrading.en.rst
  include/ts/apidefs.h.in
  iocore/hostdb/HostDB.cc
  iocore/hostdb/I_HostDBProcessor.h
  plugins/lua/ts_lua_http_config.c
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  src/records/RecordsConfig.cc
  src/shared/overridable_txn_vars.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/InkAPITest.cc
  tests/gold_tests/records/gold/full_records.yaml
  tests/gold_tests/records/legacy_config/full_records.config
  tests/gold_tests/tls/tls_verify_override_base.test.py
Labels: Incompatible

#9694 Add ssrc and surc log fields for server simple/unavail retry counts.
  doc/admin-guide/logging/formatting.en.rst
  proxy/logging/Log.cc
  proxy/logging/LogAccess.cc
  proxy/logging/LogAccess.h
Labels: Logging

#9758 Fix Via header on H3 connections
  proxy/http3/Http3Session.cc
Labels: HTTP/3

#9759 Fix records config to yaml autest for out of tree build
  tests/gold_tests/autest-site/setup.cli.ext
  tests/gold_tests/records/records_config_to_yaml.test.py
Labels: YAML, AuTest

#9729 Fix a crash when H3 transaction ends early
  proxy/http3/Http3Transaction.cc
  proxy/http3/Http3Transaction.h
Labels: HTTP/3
