Repository apache/trafficserver, pull requests merged in 2023-03, with the labels that each got.

#9433 Ethread::process_event(): make sure event mutex is unlocked before freeing event.
  doc/developer-guide/api/functions/TSContCreate.en.rst
  doc/developer-guide/api/functions/TSMutexDestroy.en.rst
  iocore/eventsystem/UnixEThread.cc
Labels: Core, Documentation

#9477 QUIC: Make sure the some of the quic configs get set into the quiche impl.
  doc/admin-guide/files/records.yaml.en.rst
  iocore/net/QUICNetProcessor_quiche.cc
Labels: QUIC

#9472 records.yaml: NULL strings should explicitly be set to null.
  src/records/RecUtils.cc
  src/records/RecYAMLDecoder.cc
  tests/gold_tests/records/records_yaml.test.py
Labels: Configuration, YAML

#9183 TSAN fix for fake_global_for_ink_queue.
  src/tscore/ink_queue.cc
Labels: Cleanup, TSan

#9471 traffic_ctl - Remove legacy/pretty format output options.
  doc/appendices/command-line/traffic_ctl.en.rst
  src/traffic_ctl/CtrlCommands.cc
  src/traffic_ctl/CtrlPrinters.cc
  src/traffic_ctl/CtrlPrinters.h
  src/traffic_ctl/traffic_ctl.cc
Labels: Tools

#9440 Human readable timestamp for traffic_ctl config status
  src/traffic_ctl/CtrlCommands.cc
  src/traffic_ctl/CtrlPrinters.cc
  src/traffic_ctl/CtrlPrinters.h
Labels: Tools

#9492 Fix pre-warm std::string parameter
  proxy/http/PreWarmManager.h
Labels: Cleanup

#9473 Use deprecated OpenSSL APIs for MD5 and SHA256 if available (#9469)
  configure.ac
  include/tscore/SHA256.h
Labels: TLS, Performance

#9484 QUIC: Avoid crash when IO is disabled by the caller.
  proxy/http3/Http3Transaction.cc
Labels: QUIC, HTTP/3

#9498 traffic_ctl: config set/get --cold tidy.
  src/traffic_ctl/FileConfigCommand.cc
Labels: Cleanup

#9495 libswoc: update to 1.4.4
  lib/swoc/CMakeLists.txt
  lib/swoc/Makefile.am
  lib/swoc/include/swoc/DiscreteRange.h
  lib/swoc/include/swoc/Errata.h
  lib/swoc/include/swoc/IPAddr.h
  lib/swoc/include/swoc/IPEndpoint.h
  lib/swoc/include/swoc/IPRange.h
  lib/swoc/include/swoc/Lexicon.h
  lib/swoc/include/swoc/MemArena.h
  lib/swoc/include/swoc/MemSpan.h
  lib/swoc/include/swoc/TextView.h
  lib/swoc/include/swoc/bwf_base.h
  lib/swoc/include/swoc/bwf_ip.h
  lib/swoc/include/swoc/swoc_meta.h
  lib/swoc/include/swoc/swoc_version.h
  lib/swoc/src/Errata.cc
  lib/swoc/src/bw_format.cc
  lib/swoc/src/bw_ip_format.cc
  src/records/RecHttp.cc
Labels: CPP Util

#9493 TLS tunnel destination parse fix
  iocore/net/TLSTunnelSupport.cc
  iocore/net/TLSTunnelSupport.h
  proxy/http/HttpSM.cc
Labels: Cleanup

#9490 Minor cleanup, prioritize HTTP/1.1
  iocore/cache/P_CacheInternal.h
  proxy/http/HttpSM.cc
  proxy/http/HttpTransactHeaders.cc
Labels: Cleanup

#9499 libswoc: Replace IpMap in ControlMatcher.
  proxy/ControlMatcher.cc
  proxy/ControlMatcher.h
Labels: Cleanup, CPP Util

#9494 Properly support multiple instantiation in plugins.config
  plugins/experimental/rate_limit/rate_limit.cc
  plugins/experimental/rate_limit/sni_selector.cc
Labels: rate_limit

#9491 Adds a new percentage option, cleans up pressure calculations
  doc/admin-guide/plugins/rate_limit.en.rst
  plugins/experimental/rate_limit/sni_limiter.cc
  plugins/experimental/rate_limit/sni_limiter.h
Labels: rate_limit

#9442 Replace exclusive locks with rwlocks in hostdb
  iocore/hostdb/HostDB.cc
  iocore/hostdb/P_HostDB.h
  iocore/hostdb/P_HostDBProcessor.h
  iocore/hostdb/P_RefCountCache.h
  iocore/hostdb/P_RefCountCacheSerializer.h
Labels: HostDB, Performance

#9507 libswoc: Replace ts::IpAddrSet with swoc::IPRangeSet
  include/tscpp/util/ts_ip.h
  plugins/experimental/maxmind_acl/mmdb.h
  plugins/stats_over_http/stats_over_http.cc
Labels: Cleanup, CPP Util

#9323 Support config reloading using plugin msg for STEK Share Plugin
  plugins/experimental/stek_share/common.h
  plugins/experimental/stek_share/log_store.h
  plugins/experimental/stek_share/state_machine.h
  plugins/experimental/stek_share/state_manager.h
  plugins/experimental/stek_share/stek_share.cc
  plugins/experimental/stek_share/stek_share.h
  plugins/experimental/stek_share/stek_utils.h
Labels: Plugins

#9502 Cleanup: More const-crrectness of cache read
  iocore/cache/Cache.cc
  iocore/cache/CacheDir.cc
  iocore/cache/P_CacheDir.h
  iocore/cache/P_CacheVol.h
Labels: Cache, Cleanup

#9508 9.2.x: http2_flow_control.test.py: Correctly enable debug logs
  tests/gold_tests/h2/http2_flow_control.test.py
Labels: AuTest

#9505 records.yaml - Allow the records.yaml parser to keep reading further docs even when an error is detected
  src/records/RecConfigParse.cc
  tests/gold_tests/records/records_yaml.test.py
Labels: Configuration, YAML

#9504 records.yaml - Fix record name comparison logic.
  src/records/RecordsConfig.cc
  tests/gold_tests/records/records_yaml.test.py
Labels: Configuration, Bug, YAML

#9510 CMake: Update src/tscpp/util.
  src/tscpp/util/CMakeLists.txt
Labels: Build

#9487 Cleanup: Remove RecModeT from the code.
  doc/developer-guide/api/types/TSRecordModeType.en.rst
  doc/locale/ja/LC_MESSAGES/developer-guide/api/types/TSRecordModeType.en.po
  include/records/I_RecDefs.h
  include/records/I_RecProcess.h
  include/records/P_RecCore.h
  include/ts/apidefs.h.in
  iocore/aio/test_AIO.cc
  iocore/cache/test/main.cc
  iocore/eventsystem/unit_tests/test_EventSystem.cc
  iocore/eventsystem/unit_tests/test_IOBuffer.cc
  iocore/hostdb/test_RefCountCache.cc
  iocore/net/quic/test/event_processor_main.cc
  iocore/net/quic/test/main.cc
  iocore/net/test_I_Net.cc
  iocore/net/test_I_UDPNet.cc
  mgmt/rpc/server/unit_tests/test_rpcserver.cc
  proxy/http/remap/unit-tests/test_PluginFactory.cc
  proxy/http2/unit_tests/main.cc
  proxy/http3/test/main.cc
  proxy/http3/test/main_qpack.cc
  proxy/logging/LogStandalone.cc
  proxy/logging/unit-tests/benchmark_LogObject.cc
  src/records/P_RecCore.cc
  src/records/RecCore.cc
  src/records/RecProcess.cc
  src/records/test_RecProcess.i
  src/records/unit_tests/unit_test_main_on_eventsystem.cc
  src/traffic_crashlog/traffic_crashlog.cc
  src/traffic_layout/engine.cc
  src/traffic_layout/info.cc
  src/traffic_quic/traffic_quic.cc
  src/traffic_server/traffic_server.cc
Labels: Cleanup

#9501 Enable external file loading for sni.yaml.
  doc/admin-guide/files/sni.yaml.en.rst
  iocore/net/CMakeLists.txt
  iocore/net/Makefile.am
  iocore/net/P_SNIActionPerformer.h
  iocore/net/SNIActionPerformer.cc
Labels: TLS

#9481 Eliminates padding from some common structs
  include/records/P_RecDefs.h
  include/ts/apidefs.h.in
  include/tscore/MatcherUtils.h
  include/tscore/ink_string++.h
  iocore/eventsystem/I_EventProcessor.h
  iocore/eventsystem/I_VIO.h
  iocore/net/I_NetVConnection.h
  proxy/InkAPIInternal.h
  proxy/PoolableSession.h
  proxy/hdrs/HTTP.h
  proxy/hdrs/HdrHeap.h
  proxy/http/HttpSM.h
  proxy/http/HttpTransact.h
Labels: Cleanup, Performance

#9232 Add support for CMCD-Request header nor field to prefetch plugin
  doc/admin-guide/plugins/prefetch.en.rst
  plugins/prefetch/common.h
  plugins/prefetch/configs.cc
  plugins/prefetch/configs.h
  plugins/prefetch/fetch.cc
  plugins/prefetch/fetch.h
  plugins/prefetch/plugin.cc
  tests/gold_tests/pluginTest/prefetch/header_rewrite.conf
  tests/gold_tests/pluginTest/prefetch/prefetch_cmcd.test.py
  tests/gold_tests/pluginTest/prefetch/prefetch_cmcd0.gold
  tests/gold_tests/pluginTest/prefetch/prefetch_cmcd1.gold
  tests/gold_tests/pluginTest/prefetch/prefetch_simple.gold
  tests/gold_tests/pluginTest/prefetch/prefetch_simple.test.py
Labels: Plugins

#9509 Reduce the size of the APIHooks, eliminating enum gap
  include/ts/apidefs.h.in
  src/traffic_server/InkAPITest.cc
Labels: TS API, Performance, Incompatible

#9486 QUIC: Add support to configure UDP max payload limit.
  doc/admin-guide/files/records.yaml.en.rst
  iocore/net/QUICNetProcessor_quiche.cc
  iocore/net/quic/QUICConfig.cc
  iocore/net/quic/QUICConfig.h
  src/records/RecordsConfig.cc
Labels: Configuration, QUIC, UDP

#9517 autest - Minor fix on the verifier_client test ext to allow setting only the http3 ports.
  tests/gold_tests/autest-site/verifier_client.test.ext
Labels: QUIC, HTTP/3, AuTest

#9485 Unit parser
  include/tscpp/util/Makefile.am
  include/tscpp/util/ts_time_parser.h
  include/tscpp/util/ts_unit_parser.h
  src/tscpp/util/CMakeLists.txt
  src/tscpp/util/Makefile.am
  src/tscpp/util/ts_unit_parser.cc
  src/tscpp/util/unit_tests/test_time_parser.cc
Labels: Configuration

#9474 Avoid memory allocation in CryptoHash
  include/tscore/CryptoHash.h
  src/tscore/CryptoHash.cc
Labels: Core, Performance

#9479 Hugepage config cleanup
  doc/admin-guide/files/records.yaml.en.rst
  iocore/cache/Cache.cc
  iocore/cache/CacheDir.cc
  iocore/cache/P_CacheInternal.h
  iocore/eventsystem/EventSystem.cc
  iocore/eventsystem/IOBuffer.cc
  iocore/eventsystem/I_IOBuffer.h
  iocore/eventsystem/unit_tests/test_IOBuffer.cc
  iocore/hostdb/Makefile.am
  proxy/logging/Makefile.am
  src/records/RecordsConfig.cc
  src/traffic_quic/Makefile.inc
Labels: Cleanup

#9515 Adds the AR env variable to config.nice
  build/common.m4
  configure.ac
Labels: Build

#9322 Add TLSCertSwitchSupport
  iocore/net/Makefile.am
  iocore/net/P_SSLNetVConnection.h
  iocore/net/SSLNetVConnection.cc
  iocore/net/SSLUtils.cc
  iocore/net/TLSCertSwitchSupport.cc
  iocore/net/TLSCertSwitchSupport.h
Labels: TLS

#9521 CryptoContext: Clean up to avoid compiler problem.
  include/tscore/CryptoHash.h
  include/tscore/MD5.h
  include/tscore/MMH.h
  include/tscore/SHA256.h
Labels: Cleanup

#9522 Update to libswoc 1.4.5
  lib/swoc/include/swoc/IPAddr.h
  lib/swoc/include/swoc/IPEndpoint.h
  lib/swoc/include/swoc/IPRange.h
  lib/swoc/include/swoc/bwf_base.h
  lib/swoc/src/swoc_ip.cc
Labels: CPP Util

#9480 Slight performance improvements before calling APIHooks::clear
  proxy/InkAPIInternal.h
Labels: Performance

#9358 tunnel_route: Support local inbound and proxy protocol ports
  doc/admin-guide/files/sni.yaml.en.rst
  iocore/net/P_SNIActionPerformer.h
  iocore/net/TLSTunnelSupport.cc
  iocore/net/TLSTunnelSupport.h
  iocore/net/YamlSNIConfig.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  tests/gold_tests/tls/proxy_protocol_client.py
  tests/gold_tests/tls/tls_tunnel.test.py
Labels: TLS

#9523 Refresh SOCKs logic, remove IpMapConf
  include/tscore/IpMapConf.h
  iocore/net/P_Socks.h
  iocore/net/Socks.cc
  iocore/net/UnixNetProcessor.cc
  src/tscore/IpMapConf.cc
  src/tscore/Makefile.am
Labels: Cleanup

#9524 Link boringocsp lib to unit tests
  iocore/cache/Makefile.am
  iocore/net/Makefile.am
Labels: Build, Tests

#9530 libswoc: Update to 1.4.6
  lib/swoc/CMakeLists.txt
  lib/swoc/Makefile.am
  lib/swoc/include/swoc/DiscreteRange.h
  lib/swoc/include/swoc/Errata.h
  lib/swoc/include/swoc/IPAddr.h
  lib/swoc/include/swoc/IPRange.h
  lib/swoc/include/swoc/swoc_version.h
  lib/swoc/src/Errata.cc
  lib/swoc/src/bw_format.cc
  lib/swoc/src/swoc_ip.cc
Labels: CPP Util

#9532 Remove unused IpMap include.
  iocore/net/I_NetVConnection.h
Labels: Cleanup

#9538 CMake: clean up dead references to IpMapConf
  src/tscore/CMakeLists.txt
Labels: Cleanup

#9540 Add files generated by "make check" to ignore list.
  .gitignore
Labels: Cleanup

#9542 Doc: fix typo in SNI YAML.
  doc/admin-guide/files/sni.yaml.en.rst
Labels: Documentation

#9514 Change RecHttpLoadIp to use ts::AddrPair
  include/records/I_RecHttp.h
  include/tscpp/util/ts_ip.h
  proxy/ProxyTransaction.cc
  proxy/ProxyTransaction.h
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpProxyServerMain.cc
  proxy/http/HttpSessionAccept.h
  proxy/http/Makefile.am
  src/records/RecHttp.cc
  src/records/unit_tests/test_RecHttp.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/traffic_server.cc
  src/tscpp/util/ts_ip.cc
Labels: Cleanup, CPP Util

#9531 Update logfilter to remove use of IpMap
  include/tscore/ink_inet.h
  proxy/logging/LogFilter.cc
  proxy/logging/LogFilter.h
  src/tscore/unit_tests/test_ink_inet.cc
Labels: Cleanup, CPP Util

#9541 Remove IpMap dependency from NetVConnection infrastructure.
  include/records/I_RecHttp.h
  iocore/net/I_NetProcessor.h
  iocore/net/P_SNIActionPerformer.h
  iocore/net/P_SSLConfig.h
  iocore/net/SNIActionPerformer.cc
  iocore/net/SSLConfig.cc
  iocore/net/SSLNetVConnection.cc
  proxy/ProtocolProbeSessionAccept.cc
  proxy/ProtocolProbeSessionAccept.h
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpProxyServerMain.cc
  src/records/RecHttp.cc
Labels: Cleanup, CPP Util

#9549 libswoc: Remove ts::MemArena.
  include/records/I_RecHttp.h
  include/tscore/MemArena.h
  src/tscore/CMakeLists.txt
  src/tscore/Makefile.am
  src/tscore/MemArena.cc
  src/tscore/unit_tests/test_MemArena.cc
Labels: Cleanup, CPP Util

#9546 Fix a build issue with the latest BoringSSL
  iocore/net/SSLUtils.cc
  iocore/net/TLSSessionResumptionSupport.cc
Labels: Build, TLS

#9527 Fixes silent header duplication that occurs upon successful revalidation when duplicate headers are present
  proxy/http/HttpTransact.cc
  proxy/http/Makefile.am
  proxy/http/unit_tests/main.cc
  proxy/http/unit_tests/test_HttpTransact.cc
Labels: Bug

#9357 Add dockerfile for building h3 tools for testing
  tools/build_h3_tools.sh
  tools/http3/Dockerfile
Labels: Tools

#9443 cleanup cache inlines to avoid duplicate symbol definitions
  iocore/cache/CMakeLists.txt
  iocore/cache/I_CacheDefs.h
  iocore/cache/Inline.cc
  iocore/cache/Makefile.am
  iocore/cache/P_CacheArray.h
  iocore/cache/P_CacheDir.h
  iocore/cache/P_CacheHttp.h
  iocore/cache/P_CacheInternal.h
  iocore/cache/P_CacheVol.h
Labels: Build

#9543 QUIC: Test basic scenarios around the ts.quic.no_activity_timeout_in config
  iocore/net/QUICNetVConnection_quiche.cc
  tests/gold_tests/timeout/gold/quic_no_activity_timeout.gold
  tests/gold_tests/timeout/quic_no_activity_timeout.test.py
  tests/gold_tests/timeout/replay/quic_no_activity_timeout.replay.yaml
  tests/gold_tests/timeout/ssl/cert.crt
  tests/gold_tests/timeout/ssl/private-key.key
Labels: QUIC

#9547 Add TS_HAS_QUICHE feature variable.
  configure.ac
  doc/developer-guide/testing/blackbox-testing.en.rst
  include/tscore/ink_config.h.in
  iocore/net/P_QUICNet.h
  iocore/net/P_QUICNetProcessor.h
  iocore/net/P_QUICNetVConnection.h
  iocore/net/P_QUICNextProtocolAccept.h
  iocore/net/P_QUICPacketHandler.h
  iocore/net/QUICNet.cc
  iocore/net/quic/Mock.h
  iocore/net/quic/QUICContext.cc
  iocore/net/quic/QUICContext.h
  iocore/net/quic/QUICGlobals.cc
  proxy/http3/test/test_QPACK.cc
  src/traffic_layout/info.cc
  tests/README.md
Labels: QUIC, AuTest

#9483 Add support for multiple yaml config files for wasm plugin
  doc/admin-guide/plugins/wasm.en.rst
  plugins/experimental/wasm/wasm_main.cc
Labels: Plugins

#9556 coverity 1497413: Use of 32-bit time_t
  iocore/cache/CacheWrite.cc
  iocore/cache/P_CacheInternal.h
  iocore/cache/P_CacheVol.h
Labels: Cleanup, Coverity

#9560 Update codeql.yml
  .github/workflows/codeql.yml
Labels: CodeQL

#9424 combine UDPPacket and UDPPacketInternal
  iocore/net/I_UDPConnection.h
  iocore/net/I_UDPPacket.h
  iocore/net/Makefile.am
  iocore/net/P_QUICNet.h
  iocore/net/P_UDPConnection.h
  iocore/net/P_UDPNet.h
  iocore/net/P_UDPPacket.h
  iocore/net/P_UnixUDPConnection.h
  iocore/net/QUICNet.cc
  iocore/net/QUICPacketHandler.cc
  iocore/net/QUICPacketHandler_quiche.cc
  iocore/net/UnixUDPConnection.cc
  iocore/net/UnixUDPNet.cc
  iocore/net/quic/QUICPacketReceiveQueue.cc
Labels: Cleanup

#9564 QUIC: Ignore default_inactivity_timeout in favour of proxy.config.quic.no_activity_timeout_in.
  doc/admin-guide/files/records.yaml.en.rst
  iocore/net/QUICNetVConnection_quiche.cc
  tests/gold_tests/timeout/quic_no_activity_timeout.test.py
Labels: QUIC

#9561 Drop support for old quiche
  build/quiche.m4
  iocore/net/QUICNetVConnection_quiche.cc
  iocore/net/QUICPacketHandler_quiche.cc
Labels: QUIC

#9566 Cleanup: Use swoc::meta instead of ts::meta.
  mgmt/rpc/jsonrpc/JsonRPCManager.cc
  mgmt/rpc/jsonrpc/JsonRPCManager.h
  src/traffic_ctl/CtrlPrinters.cc
Labels: Cleanup

#9571 fixup cmake build for master and add conditional for io_uring support
  CMakeLists.txt
  include/tscore/ink_config.h.cmake.in
  include/tscore/ink_ssl.h
  iocore/CMakeLists.txt
  proxy/http/CMakeLists.txt
  proxy/http2/CMakeLists.txt
  src/tscpp/util/unit_tests/test_IntrusiveDList.cc
Labels: Build

#9575 Add CMake to the required PR CI builds
  .asf.yaml
Labels: GitHub
