Repository apache/trafficserver, pull requests merged in 2023-02, with the labels that each got.

#9350 Cleanup of legacy, makes newer clang-format crash right now
  plugins/experimental/sslheaders/expand.cc
Labels: Cleanup

#9336 Fixed some memory leaks with http/3
  proxy/http3/Http3HeaderFramer.cc
  proxy/http3/Http3HeaderFramer.h
  proxy/http3/Http3Session.cc
Labels: HTTP/3, Leak

#9334 Fix an error on SSL config reload (plus some cleanup).
  doc/developer-guide/api/functions/TSSslSecret.en.rst
  include/ts/ts.h
  iocore/cache/test/stub.cc
  iocore/net/P_SSLConfig.h
  iocore/net/P_SSLSecret.h
  iocore/net/SSLConfig.cc
  iocore/net/SSLSecret.cc
  iocore/net/SSLUtils.cc
  iocore/net/libinknet_stub.cc
  proxy/InkAPIInternal.h
  src/traffic_quic/traffic_quic.cc
  src/traffic_server/InkAPI.cc
Labels: TLS, TS API, Incompatible, Bug

#9353 Enable merging for 10-Dev merge
  .asf.yaml
Labels: CI

#9356 Clang-format 15.0.7 is finicky, does not like old school array inits
  plugins/experimental/slice/unit-tests/test_config.cc
Labels: Cleanup

#9354 Disable merging on GitHub
  .asf.yaml
Labels: CI

#9360 Updates the release roadmap, adjusting for delays
  doc/release-notes/images/roadmap.png
Labels: Documentation

#9339 Revert PRs 7667 and 7807
  proxy/http/HttpCacheSM.cc
  proxy/http/HttpCacheSM.h
  proxy/http/HttpSM.cc
  proxy/http/HttpSM.h
Labels: Revert

#9368 Fix clang-format error ... array
  src/records/RecYAMLDecoder.cc
Labels: Cleanup

#9372 Fix autest flakiness
  tests/gold_tests/remap/remap_load_empty_failure.test.py
  tests/gold_tests/shutdown/emergency.test.py
  tests/gold_tests/shutdown/fatal.test.py
Labels: AuTest

#9364 Fixes type qualifier warning
  iocore/net/SSLSecret.cc
Labels: Cleanup

#9365 Fix the autest Proxy Verifier version check
  tests/gold_tests/autest-site/conditions.test.ext
Labels: AuTest

#9361 Add FreeBSD and OSX to the list of required CI tests to pass
  .asf.yaml
Labels: CI

#9349 Roadmap typo fix: striaght -> straight
  doc/release-notes/roadmap.en.rst
Labels: Documentation

#9367 [Docs] - Records config to records.yaml documentation(migration guide).
  doc/admin-guide/files/records.yaml.en.rst
  doc/admin-guide/index.en.rst
  doc/admin-guide/tools/converting-records-to-yaml.en.rst
  doc/admin-guide/tools/index.en.rst
  doc/ext/traffic-server.py
  tools/records/convert2yaml.py
Labels: Configuration, Documentation, YAML

#9363 Fixes spelling across the tree
  configure.ac
  doc/admin-guide/files/records.yaml.en.rst
  doc/admin-guide/plugins/header_rewrite.en.rst
  doc/conf.py
  doc/developer-guide/api/functions/TSSslSecret.en.rst
  doc/developer-guide/core-architecture/hostdb.en.rst
  doc/developer-guide/jsonrpc/jsonrpc-api.en.rst
  doc/developer-guide/plugins/example-plugins/denylist/setting-a-global-hook.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/plugins/ts_lua.en.po
  doc/locale/ja/LC_MESSAGES/developer-guide/architecture/architecture.en.po
  doc/locale/ja/LC_MESSAGES/developer-guide/documentation/conventions.en.po
  doc/locale/ja/LC_MESSAGES/developer-guide/plugins/example-plugins/blacklist/setting-a-global-hook.en.po
  include/records/I_RecHttp.h
  include/shared/rpc/RPCRequests.h
  include/ts/ts.h
  include/tscore/Diags.h
  include/tscore/Regex.h
  include/tscpp/util/TsSharedMutex.h
  iocore/eventsystem/I_Continuation.h
  iocore/eventsystem/I_EThread.h
  iocore/hostdb/HostDB.cc
  iocore/hostdb/HostFile.cc
  iocore/hostdb/I_HostDBProcessor.h
  iocore/net/TLSEarlyDataSupport.cc
  mgmt/rpc/handlers/common/RecordsUtils.h
  mgmt/rpc/handlers/config/Configuration.cc
  mgmt/rpc/handlers/records/Records.cc
  mgmt/rpc/jsonrpc/unit_tests/test_basic_protocol.cc
  mgmt/rpc/server/CommBase.cc
  mgmt/rpc/server/IPCSocketServer.cc
  mgmt/rpc/server/unit_tests/test_rpcserver.cc
  plugins/experimental/fastcgi/src/Readme
  plugins/experimental/otel_tracer/tracer_common.h
  plugins/experimental/parent_select/consistenthash.cc
  plugins/experimental/rate_limit/ip_reputation.h
  plugins/experimental/rate_limit/sni_limiter.h
  plugins/experimental/wasm/wasm_main.cc
  proxy/ControlMatcher.h
  proxy/IPAllow.h
  proxy/InkAPIInternal.h
  proxy/hdrs/VersionConverter.cc
  proxy/http/HttpSM.cc
  proxy/http/HttpSessionManager.h
  proxy/http/stats.memo
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2ConnectionState.h
  proxy/http3/Http3App.cc
  tests/README.md
  tests/gold_tests/jsonrpc/jsonrpc_api_schema.test.py
  tests/gold_tests/pluginTest/TSVConnFd/TSVConnFd.cc
  tests/gold_tests/proxy_protocol/proxy_protocol_server.py
  tools/http_load/timers.h
  tools/jtest/jtest.cc
Labels: Cleanup

#9375 Fixed some memory leaks with http/3 (#9336)
  proxy/http3/Http3HeaderFramer.cc
  proxy/http3/Http3HeaderFramer.h
  proxy/http3/Http3Session.cc
Labels: HTTP/3, Leak

#9378 Make sure we let the user know we are about to perform an invalid conversion.
  tests/gold_tests/records/legacy_config/override_map.config
  tests/gold_tests/records/legacy_config/override_value.config
  tests/gold_tests/records/records_config_to_yaml.test.py
  tools/records/convert2yaml.py
Labels: Tools

#9379 Added memory info to system_stats plugin
  doc/admin-guide/plugins/system_stats.en.rst
  plugins/experimental/system_stats/system_stats.c
Labels: Plugins

#9380 Try shasum with algo option if sha256sum is unavailable
  tools/clang-format.sh
Labels: Tools

#9382 Use snprintf
  iocore/cache/test/main.cc
  iocore/net/QUICPacketHandler_quiche.cc
  mgmt/rpc/server/unit_tests/test_rpcserver.cc
Labels: Cleanup

#9387 Update h2disable tests for new curl output
  tests/gold_tests/h2/h2disable.test.py
  tests/gold_tests/h2/h2disable_no_accept_threads.test.py
Labels: AuTest

#9342 Fixed memory leaks with http/3
  iocore/net/QUICNet.cc
  iocore/net/QUICNetVConnection.cc
  iocore/net/quic/QUICApplicationMap.h
  iocore/net/quic/test/test_QUICStreamManager.cc
  proxy/http3/QPACK.cc
Labels: HTTP/3, Leak

#9381 Fix stack overflow on sending UDP packets
  iocore/net/UnixUDPNet.cc
Labels: QUIC, UDP

#9386 Enable UDP GSO by default
  doc/admin-guide/files/records.yaml.en.rst
  mgmt/RecordsConfig.cc
Labels: QUIC, UDP

#9383 Proxy Protocol: Allow for no Proxy Protocol header
  doc/admin-guide/configuration/proxy-protocol.en.rst
  iocore/net/ProxyProtocol.cc
  iocore/net/SSLNetVConnection.cc
  proxy/ProtocolProbeSessionAccept.cc
  tests/gold_tests/proxy_protocol/gold/access.gold
  tests/gold_tests/proxy_protocol/gold/test_case_3_stderr.gold
  tests/gold_tests/proxy_protocol/gold/test_case_3_stdout.gold
  tests/gold_tests/proxy_protocol/gold/test_case_4_stderr.gold
  tests/gold_tests/proxy_protocol/gold/test_case_4_stdout.gold
  tests/gold_tests/proxy_protocol/proxy_protocol.test.py
Labels: PROXY Protocol

#9385 Use IOBufferBlock instead of alloc to avoid stackoverflow
  iocore/net/UnixUDPNet.cc
Labels: QUIC

#9390 Add support for WasmEdge for Wasm Plugin
  configure.ac
  doc/admin-guide/plugins/wasm.en.rst
  plugins/Makefile.am
  plugins/experimental/wasm/Makefile.inc
  plugins/experimental/wasm/examples/cpp/myproject.yaml
  plugins/experimental/wasm/examples/rust/myfilter.yaml
  plugins/experimental/wasm/examples/tinygo/plugin.yaml
  plugins/experimental/wasm/wasm_main.cc
Labels: Plugins

#9391 Make autest ts shutdown tests more reliable
  tests/gold_tests/remap/remap_load_empty_failure.test.py
  tests/gold_tests/shutdown/emergency.test.py
  tests/gold_tests/shutdown/fatal.test.py
Labels: AuTest

#9290 improve cmake support
  CMakeLists.txt
  cmake/FindPCRE.cmake
  include/tscore/ink_config.h.cmake.in
  iocore/CMakeLists.txt
  iocore/aio/CMakeLists.txt
  iocore/cache/CMakeLists.txt
  iocore/dns/CMakeLists.txt
  iocore/eventsystem/CMakeLists.txt
  iocore/eventsystem/I_MIOBufferWriter.h
  iocore/hostdb/CMakeLists.txt
  iocore/net/CMakeLists.txt
  iocore/utils/CMakeLists.txt
  lib/CMakeLists.txt
  lib/fastlz/CMakeLists.txt
  lib/yamlcpp/CMakeLists.txt
  mgmt/CMakeLists.txt
  mgmt/utils/CMakeLists.txt
  proxy/CMakeLists.txt
  proxy/hdrs/CMakeLists.txt
  proxy/http/CMakeLists.txt
  proxy/http/remap/CMakeLists.txt
  proxy/http2/CMakeLists.txt
  proxy/logging/CMakeLists.txt
  proxy/shared/CMakeLists.txt
  src/records/CMakeLists.txt
  src/traffic_server/CMakeLists.txt
  src/tscore/CMakeLists.txt
  src/tscore/unit_tests/test_Extendible.cc
  src/tscpp/util/CMakeLists.txt
Labels: Build

#9398 CMake: Update for post 10-Dev merge.
  CMakeLists.txt
  mgmt/CMakeLists.txt
  mgmt/utils/CMakeLists.txt
  src/records/CMakeLists.txt
  src/tscore/CMakeLists.txt
  src/tscpp/util/CMakeLists.txt
Labels: Build

#9407 Added a log message when individual plugin is loaded
  proxy/Plugin.cc
Labels: Logging

#9406 Honor the BASE for Quiche builds
  tools/build_h3_tools.sh
Labels: Tools, QUIC

#9402 This removes the support for Solaris
  INSTALL
  build/network.m4
  config.layout
  configure.ac
  doc/admin-guide/files/records.yaml.en.rst
  doc/admin-guide/files/storage.config.en.rst
  doc/appendices/faq.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/files/storage.config.en.po
  doc/locale/ja/LC_MESSAGES/appendices/faq.en.po
  include/ts/ts.h
  iocore/aio/test_AIO.cc
  iocore/eventsystem/UnixEThread.cc
  iocore/net/UnixNet.cc
  mgmt/utils/MgmtUtils.cc
  plugins/authproxy/authproxy.cc
  proxy/http/HttpSessionAccept.cc
  proxy/logging/LogFile.cc
  proxy/logging/LogStandalone.cc
  proxy/logging/LogUtils.cc
  proxy/shared/UglyLogStubs.cc
  rc/solaris.txt
  rc/trafficserver.xml.in
  src/traffic_logstats/logstats.cc
  src/traffic_server/InkAPITest.cc
  src/traffic_server/InkIOCoreAPI.cc
  src/tscore/ink_file.cc
  src/tscore/ink_res_init.cc
  src/tscore/ink_thread.cc
  src/wccp/WccpStatic.cc
  tools/http_load/port.h
  tools/tsxs.in
Labels: Build, Cleanup

#9393 Fix missing semi-colon
  include/tscore/ink_memory.h
Labels: Build

#9184 TSan: Make Thread::cur_time thread local
  iocore/eventsystem/I_Thread.h
  iocore/eventsystem/Thread.cc
  proxy/logging/Log.cc
Labels: TSan, Threads

#9410 Fixes the compile to work with LLVM15
  iocore/eventsystem/UnixEventProcessor.cc
Labels: Build

#9412 QUIC: Remove hardcoded quiche set_initial_max_streams and use config values instead.
  iocore/net/QUICNetProcessor_quiche.cc
Labels: QUIC

#9397 Build: improve libswoc building.
  build/libswoc.m4
  configure.ac
  proxy/logging/Makefile.am
  src/records/Makefile.am
Labels: Build, CPP API

#9414 P_SSLUtils.h include updates
  iocore/net/P_SSLUtils.h
Labels: Build

#9416 FileManager string update
  mgmt/config/FileManager.cc
  mgmt/config/FileManager.h
Labels: Build

#9417 Histogram: rename members because Zwoop.
  include/tscpp/util/Histogram.h
  iocore/eventsystem/UnixEventProcessor.cc
  src/tscore/unit_tests/test_Histogram.cc
Labels: CPP Util

#9415 Make jsonrcp restricted_api false by default.
  configs/jsonrpc.yaml.default
  doc/admin-guide/files/jsonrpc.yaml.en.rst
  mgmt/rpc/server/IPCSocketServer.h
Labels: JSONRPC

#9413 Remove UDP_stubs.h
  include/tscore/UDP_stubs.h
  iocore/aio/test_AIO.cc
  iocore/net/I_UDPPacket.h
  iocore/net/P_UDPNet.h
  iocore/net/P_UDPPacket.h
  iocore/net/QUICPacketHandler.cc
  iocore/net/QUICPacketHandler_quiche.cc
  iocore/net/UnixUDPNet.cc
  iocore/net/quic/test/test_QUICAddrVerifyState.cc
  iocore/net/quic/test/test_QUICFlowController.cc
  iocore/net/quic/test/test_QUICFrame.cc
  iocore/net/quic/test/test_QUICFrameDispatcher.cc
  iocore/net/quic/test/test_QUICHandshakeProtocol.cc
  iocore/net/quic/test/test_QUICLossDetector.cc
  iocore/net/quic/test/test_QUICPacketFactory.cc
  iocore/net/quic/test/test_QUICPacketHeaderProtector.cc
  iocore/net/quic/test/test_QUICPathValidator.cc
  iocore/net/quic/test/test_QUICStream.cc
  iocore/net/quic/test/test_QUICStreamManager.cc
  iocore/net/quic/test/test_QUICStreamState.cc
  iocore/net/quic/test/test_QUICVersionNegotiator.cc
  proxy/http/remap/unit-tests/nexthop_test_stubs.cc
  proxy/http/unit_tests/unit_test_main.cc
  proxy/http3/test/main_qpack.cc
  proxy/logging/LogStandalone.cc
  src/traffic_logcat/logcat.cc
  src/traffic_logstats/logstats.cc
  src/traffic_server/InkIOCoreAPI.cc
Labels: Cleanup

#9429 tscore: Remove unneeded and mispelled libswoc reference.
  src/tscore/Makefile.am
Labels: Tests, Cleanup

#9430 On arm64 macOS, do not use pagezero linker flag when using luajit
  build/luajit.m4
  src/traffic_server/Makefile.inc
Labels: Build, macOS

#9441 Fixes comparison with the wrong type
  iocore/eventsystem/EventSystem.cc
Labels: Bug

#9436 quic: make sure we create a stream if none available.
  iocore/net/QUICNetVConnection_quiche.cc
Labels: QUIC

#9439 Use TSDbg in webp_transform plugin
  plugins/experimental/webp_transform/ImageTransform.cc
Labels: Plugins, Logging

#9435 records.yaml: Make sure we fail if we found a legacy records.config file.
  doc/admin-guide/tools/converting-records-to-yaml.en.rst
  src/records/RecCore.cc
  tests/gold_tests/records/old_config_fail.test.py
Labels: Configuration

#9447 QUIC: Use configured disable_active_migration param at quiche transport configuration.
  iocore/net/QUICNetProcessor_quiche.cc
Labels: QUIC

#9404 records.yaml - Add support to load multiple YAML docs from the same file and let traffic_ctl to modify a records.yaml file
  doc/admin-guide/files/records.yaml.en.rst
  doc/appendices/command-line/traffic_ctl.en.rst
  src/records/RecConfigParse.cc
  src/traffic_ctl/CtrlCommands.cc
  src/traffic_ctl/CtrlCommands.h
  src/traffic_ctl/FileConfigCommand.cc
  src/traffic_ctl/FileConfigCommand.h
  src/traffic_ctl/Makefile.inc
  src/traffic_ctl/traffic_ctl.cc
  src/traffic_ctl/utils/yaml_utils.h
  tests/gold_tests/autest-site/trafficserver.test.ext
  tests/gold_tests/records/gold/records.yaml.cold_test0.gold
  tests/gold_tests/records/gold/records.yaml.cold_test2.gold
  tests/gold_tests/records/gold/records.yaml.cold_test4.gold
  tests/gold_tests/records/gold/records.yaml.cold_test5.gold
  tests/gold_tests/records/records_yaml.test.py
  tests/gold_tests/records/traffic_ctl_cold_config.test.py
Labels: Configuration, Tools, YAML

#9425 Cleanup: removing some traffic_manager leftovers.
  doc/admin-guide/files/records.yaml.en.rst
  doc/admin-guide/monitoring/statistics/core/general.en.rst
  doc/appendices/command-line/traffic_manager.en.rst
  doc/uml/RPC-sequence-diagram.uml
  doc/uml/RPC-states.uml
  include/records/DynamicStats.h
  include/tscore/ink_error.h
  src/records/RecordsConfig.cc
  src/traffic_ctl/jsonrpc/CtrlRPCRequests.h
  src/traffic_server/traffic_server.cc
  tests/gold_tests/logging/ts_process_handler.py
  tests/gold_tests/records/gold/full_records.yaml
  tests/gold_tests/records/legacy_config/full_records.config
Labels: Cleanup

#9445 Stabilize autest for traffic_dump
  tests/gold_tests/pluginTest/traffic_dump/traffic_dump.test.py
Labels: AuTest

#9450 Stabilize autest for tls_check_cert_selection_reload
  tests/gold_tests/tls/tls_check_cert_selection_reload.test.py
Labels: AuTest

#9449 QUIC: Support active_connection_id_limit for quche impl.
  doc/admin-guide/files/records.yaml.en.rst
  iocore/net/QUICNetProcessor_quiche.cc
  src/records/RecordsConfig.cc
Labels: QUIC

#9452 Eliminates the anonymous struct, which is not standard C++
  include/tscore/ink_uuid.h
  src/tscore/ink_uuid.cc
Labels: Cleanup

#9465 Make header prefix matching case-insensitive in authProxy
  plugins/authproxy/tests/authproxy_test.cc
  plugins/authproxy/utils.h
Labels: authproxy

#9460 Use SSL_get1_peer_certificate on OpenSSL3 build
  example/plugins/c-api/verify_cert/verify_cert.cc
  iocore/net/P_SSLNetVConnection.h
  iocore/net/SSLNetVConnection.cc
  plugins/experimental/sslheaders/sslheaders.cc
  plugins/experimental/wasm/ats_context.cc
Labels: TLS

#9453 Fix parameter parser in ssl_hook_test plugin
  tests/tools/plugins/ssl_hook_test.cc
Labels: AuTest

#9454 Stabilize autest tls_hook18
  tests/gold_tests/tls_hooks/tls_hooks18.test.py
  tests/tools/plugins/ssl_hook_test.cc
Labels: AuTest

#9455 Run autest tls_hooks17 and tls_hooks18 on BoringSSL build
  tests/gold_tests/tls_hooks/tls_hooks17.test.py
  tests/gold_tests/tls_hooks/tls_hooks18.test.py
Labels: AuTest

#9444 Fix SSLSessionDup for old OpenSSL and BoringSSL
  iocore/net/SSLUtils.cc
Labels: TLS

#9463 Build: remove configure check for sys/mount.h, use C++17 builtin.
  configure.ac
  include/tscore/ink_file.h
  src/tscore/ink_file.cc
Labels: Build

#9468 Fixed documentation issue with xdebug plugin to be a literal block
  doc/admin-guide/plugins/xdebug.en.rst
Labels: Documentation, xdebug

#9467 Added more debugging output for the xdebug plugin
  doc/admin-guide/plugins/xdebug.en.rst
  plugins/xdebug/xdebug.cc
Labels: Plugins, Documentation, xdebug

#9461 QUIC: Make some adjustment to the qlog configuration
  doc/admin-guide/files/records.yaml.en.rst
  iocore/net/QUICNetVConnection.cc
  iocore/net/QUICPacketHandler_quiche.cc
  iocore/net/quic/QUICConfig.cc
  iocore/net/quic/QUICConfig.h
  iocore/net/quic/qlog/QLogListener.h
  src/records/RecordsConfig.cc
  tests/gold_tests/pluginTest/traffic_dump/traffic_dump_http3.test.py
  tests/gold_tests/records/gold/full_records.yaml
  tests/gold_tests/records/legacy_config/full_records.config
Labels: Configuration, QUIC

#9423 traffic_ctl: Add support to monitor metrics.
  doc/appendices/command-line/traffic_ctl.en.rst
  src/traffic_ctl/CtrlCommands.cc
  src/traffic_ctl/CtrlCommands.h
  src/traffic_ctl/traffic_ctl.cc
Labels: Tools

#9464 Adds a --enable-lto option (Link Time Optimization)
  build/common.m4
  configure.ac
Labels: Build, Performance

#9469 Use deprecated OpenSSL APIs for MD5 and SHA256 if available
  configure.ac
  include/tscore/MD5.h
  include/tscore/SHA256.h
Labels: Performance, SSL
