Repository apache/trafficserver, pull requests merged in 2023-01, with the labels that each got.

#9273 Remove deprecated TS API
  doc/developer-guide/api/functions/TSHttpArgs.en.rst
  doc/developer-guide/api/functions/TSVConnArgs.en.rst
  doc/release-notes/upgrading.en.rst
  include/ts/ts.h
  src/traffic_server/InkAPI.cc
  tests/tools/plugins/user_args.cc
Labels: Cleanup

#9278 Make redundant HttpTransact::State::state_machine_id variable into function.
  proxy/http/HttpSM.cc
  proxy/http/HttpSM.h
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
Labels: Cleanup

#9285 Do not track config file periodically
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  src/records/RecLocal.cc
Labels: 9.2.0

#9282 Updated documentation and added test coverage for some caching behavior
  doc/admin-guide/configuration/cache-basics.en.rst
  doc/admin-guide/files/records.config.en.rst
  tests/gold_tests/cache/cache-auth.test.py
  tests/gold_tests/cache/cache-control.test.py
  tests/gold_tests/cache/cache-cookie.test.py
  tests/gold_tests/cache/replay/auth-default.replay.yaml
  tests/gold_tests/cache/replay/auth-ignored.replay.yaml
  tests/gold_tests/cache/replay/cache-control-pragma.replay.yaml
  tests/gold_tests/cache/replay/cookie-all-but-text-with-excp.replay.yaml
  tests/gold_tests/cache/replay/cookie-all-but-text.replay.yaml
  tests/gold_tests/cache/replay/cookie-bypass-cache.replay.yaml
  tests/gold_tests/cache/replay/cookie-cache-img-only.replay.yaml
  tests/gold_tests/cache/replay/cookie-default.replay.yaml
  tests/gold_tests/cache/replay/request-cache-control-default.replay.yaml
  tests/gold_tests/cache/replay/request-cache-control-honor-client.replay.yaml
  tests/gold_tests/cache/replay/response-cache-control-default.replay.yaml
  tests/gold_tests/cache/replay/response-cache-control-ignored.replay.yaml
Labels: Cache, HTTP, Tests, Documentation

#9287 Fix a crash from a server early abort
  proxy/http/HttpSM.cc
  tests/gold_tests/slow_post/__init__.py
  tests/gold_tests/slow_post/http_utils.py
  tests/gold_tests/slow_post/quick_server.py
  tests/gold_tests/slow_post/quick_server.test.py
  tests/gold_tests/slow_post/slow_post.test.py
  tests/gold_tests/slow_post/slow_post_client.py
  tests/gold_tests/slow_post/slow_post_clients.py
Labels: Crash

#9281 Remove doc about disable_h2
  doc/admin-guide/files/sni.yaml.en.rst
Labels: Cleanup, Documentation

#9239 Fix ordering Via response header values
  proxy/http/HttpTransact.cc
  proxy/http/HttpTransact.h
  proxy/http/HttpTransactHeaders.cc
Labels: HTTP

#9291 Documentation-only changes from #9282 for 9.2.x
  doc/admin-guide/configuration/cache-basics.en.rst
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#9292 Drop autoconf checking for readline/libedit
  build/ax_lib_readline.m4
  configure.ac
Labels: Build

#9295 Fix test_jsonrpcserver library ordering link issue
  mgmt/rpc/Makefile.am
Labels: Build

#9238 Add slice config to strip Range header for HEAD requests
  doc/admin-guide/plugins/slice.en.rst
  plugins/experimental/slice/Config.cc
  plugins/experimental/slice/Config.h
  plugins/experimental/slice/server.cc
  plugins/experimental/slice/util.cc
  tests/gold_tests/pluginTest/slice/replay/slice_range.replay.yaml
  tests/gold_tests/pluginTest/slice/slice_rm_range.test.py
Labels: Plugins

#9300 Fixed issue with SDK_API_HttpParentProxySet_Fail regression test
  proxy/http/HttpTransact.cc
Labels: Tests, Regression

#9304 Fix build issues in H3 unit tests
  iocore/net/quic/Mock.h
  proxy/http3/test/test_QPACK.cc
Labels: Build, Tests, HTTP/3

#9305 Updates to the h3 tool build script
  tools/build_h3_tools.sh
Labels: QUIC, HTTP/3

#9306 Updated warning message for adding duplicated remap entries
  proxy/http/remap/UrlRewrite.cc
Labels: Configuration

#9307 AuTests: update to Proxy Verifier v2.6.0
  tests/prepare_proxy_verifier.sh
  tests/proxy-verifier-version.txt
Labels: Tests

#9311 Docs: Unpin Sphinx
  doc/Pipfile
  doc/conf.py
  doc/ext/traffic-server.py
Labels: Documentation

#9263 This adds a simple (static) metric for counting cache stripes
  iocore/cache/Cache.cc
  iocore/cache/P_CacheInternal.h
Labels: Cache, Metrics

#9312 Adds 9.2.x to the list of docs versions
  doc/static/languages.json
Labels: Documentation

#9313 Don't pass invalid cert file paths to Quiche
  iocore/net/QUICNetProcessor_quiche.cc
Labels: QUIC

#9308 Change to WAMR for wasm runtime
  build/wavm.m4
  configure.ac
  doc/admin-guide/plugins/wasm.en.rst
  plugins/Makefile.am
  plugins/experimental/wasm/Makefile.inc
  plugins/experimental/wasm/ats_wasm.cc
  plugins/experimental/wasm/ats_wasm.h
  plugins/experimental/wasm/examples/cpp/myproject.yaml
  plugins/experimental/wasm/examples/rust/myfilter.yaml
  plugins/experimental/wasm/examples/tinygo/README.md
  plugins/experimental/wasm/examples/tinygo/plugin.yaml
  plugins/experimental/wasm/lib/include/proxy-wasm/exports.h
  plugins/experimental/wasm/lib/include/proxy-wasm/limits.h
  plugins/experimental/wasm/lib/include/proxy-wasm/null_vm.h
  plugins/experimental/wasm/lib/include/proxy-wasm/pairs_util.h
  plugins/experimental/wasm/lib/include/proxy-wasm/wasm.h
  plugins/experimental/wasm/lib/include/proxy-wasm/wasm_vm.h
  plugins/experimental/wasm/lib/include/proxy-wasm/word.h
  plugins/experimental/wasm/lib/src/bytecode_util.cc
  plugins/experimental/wasm/lib/src/exports.cc
  plugins/experimental/wasm/lib/src/pairs_util.cc
  plugins/experimental/wasm/lib/src/signature_util.cc
  plugins/experimental/wasm/lib/src/v8/v8.cc
  plugins/experimental/wasm/lib/src/wamr/types.h
  plugins/experimental/wasm/lib/src/wamr/wamr.cc
  plugins/experimental/wasm/lib/src/wasm.cc
  plugins/experimental/wasm/lib/src/wasmedge/wasmedge.cc
  plugins/experimental/wasm/lib/src/wasmtime/wasmtime.cc
  plugins/experimental/wasm/lib/src/wavm/wavm.cc
  plugins/experimental/wasm/wasm_main.cc
Labels: Plugins

#9316 Update rtd-theme to the latest version
  doc/Pipfile
  doc/conf.py
Labels: Documentation

#9294 Don't initialize the member variables of HistoryEntry and SourceLocation
  include/tscore/History.h
  include/tscore/SourceLocation.h
Labels: Performance

#9297 Optimize HPACK string comparison
  proxy/http2/HPACK.cc
Labels: HTTP/2, Performance

#9321 Fix return types of equality operators
  include/tscore/Ptr.h
Labels: Cleanup

#9301 Updated certifier plugin to generate certificate with SAN extension
  doc/admin-guide/plugins/certifier.en.rst
  plugins/certifier/certifier.cc
  tests/gold_tests/pluginTest/certifier/certifier.test.py
  tests/gold_tests/pluginTest/certifier/certs/ca-serial.txt
  tests/gold_tests/pluginTest/certifier/certs/ca.cert
  tests/gold_tests/pluginTest/certifier/certs/ca.key
  tests/gold_tests/pluginTest/certifier/replays/https-two-sessions.replay.yaml
  tests/gold_tests/pluginTest/certifier/replays/https.replay.yaml
Labels: Plugins, TLS

#9268 Make net.default_inactivity_timeout overridable
  doc/admin-guide/files/records.config.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  include/ts/apidefs.h.in
  iocore/net/I_NetVConnection.h
  iocore/net/NetEvent.h
  iocore/net/QUICNetVConnection.cc
  iocore/net/UnixNet.cc
  iocore/net/UnixNetVConnection.cc
  plugins/lua/ts_lua_http_config.c
  proxy/ProxySession.cc
  proxy/ProxySession.h
  proxy/ProxyTransaction.h
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpTransact.cc
  src/shared/overridable_txn_vars.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/InkAPITest.cc
  tests/gold_tests/timeout/default_inactivity_timeout.test.py
  tests/gold_tests/timeout/gold/client_default_inactivity_timeout.gold
  tests/gold_tests/timeout/replay/default_inactivity_timeout.replay.yaml
Labels: Configuration

#9325 glibc 2.37 requires additional explicit includes
  include/tscpp/util/TextView.h
  plugins/experimental/slice/Config.h
Labels: Build

#9326 ppc64 stack grows down, so it can be re-enabled as a supported arch
  iocore/eventsystem/UnixEventProcessor.cc
Labels: Build

#9298 Limit the serching range of static table by the first letter of header name
  proxy/http2/HPACK.cc
Labels: HTTP/2, Performance

#9330 Don't send response body on status 204 No Content
  proxy/http/HttpSM.cc
Labels: HTTP

#9314 Register ET_UDP thread type even if no UDP threads are requested
  iocore/net/I_UDPNet.h
  iocore/net/P_UDPNet.h
  iocore/net/UnixUDPNet.cc
  proxy/shared/UglyLogStubs.cc
  src/traffic_server/traffic_server.cc
Labels: QUIC, UDP

#9328 s3_auth: Schedule reloading config event on TASK thread
  plugins/s3_auth/s3_auth.cc
Labels: Plugins

#9315 Added http connect Autest with proxy verifier
  tests/gold_tests/connect/connect.test.py
  tests/gold_tests/connect/replays/connect.replay.yaml
Labels: HTTP, AuTest

#9329 s3_auth: Fix assertion failure of TSActionCancel
  plugins/s3_auth/s3_auth.cc
Labels: Plugins

#9271 Add param to forward headers from the auth server to the origin
  doc/admin-guide/plugins/authproxy.en.rst
  plugins/authproxy/Makefile.inc
  plugins/authproxy/authproxy.cc
  plugins/authproxy/tests/authproxy_test.cc
  plugins/authproxy/utils.cc
  plugins/authproxy/utils.h
Labels: Plugins

#9333 Make 204 cacheable again
  iocore/cache/Cache.cc
Labels: Cache

#9324 Memory leaks with storing configuration filenames
  mgmt/config/AddConfigFilesHere.cc
  mgmt/config/FileManager.cc
Labels: Leak

#9341 Proxy protocol out fixes
  iocore/net/ProxyProtocol.cc
  proxy/http/HttpSM.cc
  tests/gold_tests/autest-site/trafficserver.test.ext
  tests/gold_tests/proxy_protocol/proxy_protocol.test.py
  tests/gold_tests/proxy_protocol/proxy_protocol_server.py
Labels: Proxy Protocol

#9340 Update the roadmap / branch management doc page
  doc/release-notes/images/branch_mgmt.png
  doc/release-notes/roadmap.en.rst
Labels: Documentation
