Repository apache/trafficserver, pull requests merged in 2023-12, with the labels that each got.

#10883 Reenable management control for TS logging
  src/traffic_server/traffic_server.cc
Labels: Configuration, Logging

#10890 Coverity 1523673: Resource leak in test_MMH
  src/tscore/unit_tests/test_MMH.cc
Labels: Coverity

#10888 Add new config option to support CUBIC
  doc/admin-guide/files/records.yaml.en.rst
  include/iocore/net/quic/QUICConfig.h
  src/iocore/net/QUICNetProcessor.cc
  src/iocore/net/quic/QUICConfig.cc
  src/records/RecordsConfig.cc
Labels: Configuration, QUIC

#10894 Minor an/a replacement in strategies.yaml
  doc/admin-guide/files/strategies.yaml.en.rst
Labels: Documentation

#10865 Update links in records.yaml to be valid
  configs/records.yaml.default.in
Labels: Configuration

#10879 Coverity 1497350: Wrapper object use after free in GzipDeflateTransformation
  src/tscpp/api/GzipDeflateTransformation.cc
Labels: Coverity

#10898 Coverity 1508836: Uninitialized pointer field in JsonRPCManager
  include/mgmt/rpc/jsonrpc/JsonRPCManager.h
Labels: Coverity

#10902 Coverity 1523647: No virtual destructor
  include/proxy/http/HttpBodyFactory.h
Labels: Coverity

#10911 Coverity 1529710: Resource leak in object in CacheScan
  src/traffic_cache_tool/CacheScan.h
Labels: Coverity

#10912 Coverity 1528674: Uncaught exception in test_MIOBufferWriter's _ink_assert
  src/iocore/eventsystem/unit_tests/test_MIOBufferWriter.cc
Labels: Coverity

#10915 Coverity 1497388: Dereference after null check
  plugins/stats_over_http/stats_over_http.cc
Labels: Coverity

#10882 Coverity 1497456: Time of check time of use in LogFile::trim_rolled
  src/proxy/logging/LogFile.cc
Labels: Coverity

#10906 Coverity 1497426: Unintentional integer overflow
  src/proxy/hdrs/XPACK.cc
Labels: Coverity

#10858 Updates / cleanup of the vscode directory paths
  .vscode/c_cpp_properties.json
Labels: Tools

#10920 Remove deprecated debug output functions from 17 proxy source files.
  include/proxy/ParentSelection.h
  include/proxy/http/HttpTransact.h
  include/proxy/http/remap/NextHopSelectionStrategy.h
  src/proxy/ControlMatcher.cc
  src/proxy/IPAllow.cc
  src/proxy/ParentConsistentHash.cc
  src/proxy/ParentRoundRobin.cc
  src/proxy/ParentSelection.cc
  src/proxy/PluginVC.cc
  src/proxy/http/HttpSM.cc
  src/proxy/http/HttpTransact.cc
  src/proxy/http/remap/NextHopConsistentHash.cc
  src/proxy/http/remap/NextHopHealthStatus.cc
  src/proxy/http/remap/NextHopRoundRobin.cc
  src/proxy/http/remap/NextHopSelectionStrategy.cc
  src/proxy/http/remap/NextHopStrategyFactory.cc
  src/proxy/http/remap/unit-tests/nexthop_test_stubs.h
Labels: Debug

#10926 [Fuzzing] Add http2 response parser and http3 request/response parser to fuzzing
  tests/fuzzing/fuzz_http.cc
Labels: Tests

#10924 In VIA header, cW means a fresh Read While Write cache hit
  src/traffic_via/traffic_via.cc
  tools/traffic_via/traffic_via.pl
Labels: Cache

#10917 header_freq: Fix msg lock issues
  doc/admin-guide/plugins/header_freq.en.rst
  plugins/experimental/header_freq/header_freq.cc
Labels: header_freq

#10929 Change volatile to atomic in EThread.h.
  include/iocore/eventsystem/EThread.h
  src/iocore/eventsystem/UnixEThread.cc
Labels: Core, Threads

#10933 IP: Adjust ats_force_order_by_family parameters for less type dependency
  include/tscore/ink_resolver.h
  src/proxy/http/HttpTransact.cc
  src/tscore/ink_res_mkquery.cc
Labels: Cleanup

#10932 KIWF: remove ink_res_getservers
  src/tscore/ink_res_init.cc
Labels: Cleanup

#10931 UDP: Set the "Don't Fragment" (DF) bit at IP layer for QUIC.
  src/iocore/net/UnixUDPNet.cc
Labels: QUIC, UDP

#10848 Cripts: Adds txn counts for outbound conns & cleanup
  example/CMakeLists.txt
  example/cripts/CMakeLists.txt
  include/cripts/Connections.hpp
  include/cripts/Error.hpp
  include/cripts/Headers.hpp
  include/cripts/Instance.hpp
  include/cripts/Lulu.hpp
  src/cripts/Connections.cc
  src/cripts/Crypto.cc
  src/cripts/Error.cc
  src/cripts/Headers.cc
  src/cripts/Lulu.cc
  src/cripts/Matcher.cc
  src/cripts/Urls.cc
Labels: Cripts

#10795 Cleanup Cript includes, and metrics
  example/cripts/example1.cc
  include/cripts/Bundles/Common.hpp
  include/cripts/Bundles/LogsMetrics.hpp
  include/cripts/Connections.hpp
  include/cripts/Context.hpp
  include/cripts/Crypto.hpp
  include/cripts/Epilogue.hpp
  include/cripts/Error.hpp
  include/cripts/Files.hpp
  include/cripts/Headers.hpp
  include/cripts/Instance.hpp
  include/cripts/Lulu.hpp
  include/cripts/Matcher.hpp
  include/cripts/Metrics.hpp
  include/cripts/Preamble.hpp
  include/cripts/Time.hpp
  include/cripts/Transaction.hpp
  include/cripts/UUID.hpp
  include/cripts/Urls.hpp
  include/tsutil/Metrics.h
  src/cripts/Bundles/LogsMetrics.cc
  src/cripts/Geo.cc
  src/cripts/Instance.cc
  src/cripts/Metrics.cc
Labels: Cripts

#10938 Update cmake for cleaner install with static vs shared
  lib/swoc/CMakeLists.txt
  src/api/CMakeLists.txt
  src/proxy/FetchSM.cc
  src/proxy/Plugin.cc
  src/proxy/logging/CMakeLists.txt
  src/traffic_logstats/CMakeLists.txt
  src/traffic_server/traffic_server.cc
  src/tscore/CMakeLists.txt
  src/tsutil/CMakeLists.txt
Labels: Cleanup, CMake

#10935 cmake: Add tsutil/Assert.h to public headers
  src/tsutil/CMakeLists.txt
Labels: CMake

#10925 Use slice req method type in Data obj
  plugins/slice/Config.h
  plugins/slice/Data.h
  plugins/slice/server.cc
  plugins/slice/slice.cc
  plugins/slice/util.cc
Labels: Plugins

#10940 Arena; avoid use of temporary.
  src/proxy/http/HttpSM.cc
Labels: Cleanup

#10941 Arena: Avoid use of temporary.
  src/proxy/http/HttpTransact.cc
Labels: Cleanup

#10942 clear up plugin string usage ambiguities reported by gcc
  plugins/cachekey/cachekey.cc
  plugins/experimental/rate_limit/limiter.h
  plugins/experimental/rate_limit/utilities.cc
  plugins/prefetch/evaluate.cc
  plugins/traffic_dump/json_utils.cc
  plugins/traffic_dump/session_data.cc
  plugins/traffic_dump/transaction_data.cc
Labels: Plugins, Build

#10943 add branch- presets into CMakePresets.json
  CMakePresets.json
Labels: CMake

#10946 KIWF: Remove useless declaration in IpAllow
  include/proxy/IPAllow.h
Labels: Cleanup

#10945 cmake: small fixes to install
  .gitignore
  CMakeLists.txt
  cmake/post_install.cmake
  lib/CMakeLists.txt
  src/api/CMakeLists.txt
Labels: CMake

#10953 Cleanup: Rename gvol to gstripes
  src/iocore/cache/Cache.cc
  src/iocore/cache/CacheDir.cc
  src/iocore/cache/P_CacheDir.h
  src/iocore/cache/P_CacheVol.h
  src/iocore/cache/Stripe.cc
  src/iocore/cache/unit_tests/test_CacheDir.cc
  src/iocore/cache/unit_tests/test_CacheVol.cc
Labels: Cache, Cleanup
