Repository apache/trafficserver, pull requests merged in 2023-08, with the labels that each got.

#10124 Fix DbgCtl reference that got cherry-picked into 9.2.x
  iocore/net/SSLUtils.cc
Labels: Logging

#10128 8.1.x: Correctly handle encoding for cache hash generation
  proxy/hdrs/URL.cc
  proxy/hdrs/unit_tests/test_URL.cc
Labels: Cache, HTTP

#10132 Updates to 8.1.x to compile on newer OSes
  example/cppapi/websocket/WSBuffer.h
  include/tscpp/util/TextView.h
  plugins/experimental/slice/Config.h
Labels: Build

#10134 8.1.x: Fix a crash triggered by invalid range header
  proxy/http/HttpTransact.cc
Labels: Cache, HTTP

#10133 Remove duplicate slashes at the beginning of the incoming URL
  proxy/hdrs/URL.cc
  proxy/hdrs/unit_tests/test_URL.cc
Labels: HTTP

#10125 Remove duplicate slashes at the beginning of the incoming URL
  proxy/hdrs/URL.cc
  proxy/hdrs/unit_tests/test_URL.cc
Labels: HTTP

#10127 9.2.x: Correctly handle encoding for cache hash generation
  proxy/hdrs/URL.cc
  proxy/hdrs/unit_tests/test_URL.cc
  tests/gold_tests/url/uri.replay.yaml
  tests/gold_tests/url/uri.test.py
Labels: Cache, HTTP

#10131 9.2.x: Fix a crash triggered by invalid range header
  proxy/http/HttpTransact.cc
  tests/gold_tests/headers/invalid_range_header.test.py
  tests/gold_tests/headers/replays/invalid_range_request.replay.yaml
Labels: Cache, HTTP

#10096 Tools: Update common.m4 TS_ADDTO_RPATH function to use a generic rpath setting
  m4/common.m4
Labels: Tools

#10140 81x mcx16 build fix
  configure.ac
Labels: Build, Backport

#10135 TXN var config string set. Add nullptr check for non-specific variable string handling.
  src/traffic_server/InkAPI.cc
Labels: Bug

#10118 Remove version check when setting early data related config
  iocore/net/SSLNetVConnection.cc
Labels: Bug, SSL

#10139 Extracted pseudo header validation logic to use in both h2 and h3
  proxy/hdrs/CMakeLists.txt
  proxy/hdrs/HeaderValidator.cc
  proxy/hdrs/HeaderValidator.h
  proxy/hdrs/Makefile.am
  proxy/hdrs/unit_tests/test_HeaderValidator.cc
  proxy/http2/HTTP2.cc
  proxy/http3/Http3HeaderVIOAdaptor.cc
Labels: HTTP/3

#10122 Remove unused cache Store code.
  iocore/cache/I_Store.h
  iocore/cache/Store.cc
Labels: Cache, Cleanup

#10147 Wasm plugin: Upgrade to the latest proxy-wasm-cpp-host and remove reference to WAVM
  configure.ac
  doc/admin-guide/plugins/wasm.en.rst
  plugins/experimental/wasm/Makefile.inc
  plugins/experimental/wasm/lib/include/proxy-wasm/context.h
  plugins/experimental/wasm/lib/include/proxy-wasm/wasm.h
  plugins/experimental/wasm/lib/src/context.cc
  plugins/experimental/wasm/lib/src/hash.cc
  plugins/experimental/wasm/lib/src/hash.h
  plugins/experimental/wasm/lib/src/wamr/wamr.cc
  plugins/experimental/wasm/lib/src/wasm.cc
Labels: Plugins, Wasm

#10149 Fix the libloader plugin makefile.
  plugins/libloader/Makefile.inc
Labels: Build

#10121 Remove global symbols for zero hashes.
  include/tscore/CryptoHash.h
  iocore/cache/Cache.cc
  iocore/cache/CacheHttp.cc
  iocore/cache/CacheRead.cc
  iocore/cache/CacheVol.cc
  iocore/cache/CacheWrite.cc
  iocore/cache/I_Store.h
  iocore/cache/P_CacheInternal.h
  iocore/cache/test/main.cc
  proxy/PoolableSession.h
  proxy/http/HttpTransactCache.cc
  src/tscore/CryptoHash.cc
Labels: Cache, Cleanup

#10144 Strictly follow Content-Length header ABNF rule
  proxy/hdrs/HTTP.cc
  proxy/hdrs/unit_tests/test_Hdrs.cc
Labels: HTTP

#10145 Clean up some leftovers from the alarms removal.
  doc/admin-guide/files/records.yaml.en.rst
  proxy/example_alarm_bin.sh
  src/records/RecordsConfig.cc
  tests/gold_tests/records/gold/full_records.yaml
  tests/gold_tests/records/legacy_config/full_records.config
Labels: Cleanup

#10108 Add test of transaction logging to ip_allow Au test.
  tests/gold_tests/ip_allow/gold/log.gold
  tests/gold_tests/ip_allow/ip_allow.test.py
  tests/gold_tests/ip_allow/run_sed.sh
Labels: AuTest

#10150 Eliminate function-scope thread_local in Regex.cc.
  src/tscore/Regex.cc
Labels: Debug

#10157 Fix KeyEqual param for ConnectingIpPool declaration
  proxy/http/ConnectingEntry.h
Labels: HTTP

#10159 Add comment about thread_local variables in Regex.cc.
  src/tscore/Regex.cc
Labels: Core

#10130 Fix a crash triggered by invalid range header
  proxy/http/HttpTransact.cc
  tests/gold_tests/headers/invalid_range_header.test.py
  tests/gold_tests/headers/replays/invalid_range_request.replay.yaml
Labels: Cache, HTTP

#10162 Fix incorrect indentation in sni.yaml Sphinx docs
  doc/admin-guide/files/sni.yaml.en.rst
Labels: Documentation

#9942 records.yaml - conf_remap update to use records.yaml as input files.
  doc/admin-guide/plugins/conf_remap.en.rst
  plugins/conf_remap/conf_remap.cc
  tests/gold_tests/remap/basic_conf_remap_yaml.test.py
  tests/gold_tests/remap/conf_remap_float.test.py
  tests/gold_tests/remap/gold/200OK_test.gold
Labels: Plugins, YAML, conf_remap

#10167 Fixed h3 crash in accept() triggered by ip_allow rejection
  iocore/net/QUICNetVConnection_quiche.cc
  tests/gold_tests/ip_allow/ip_allow.test.py
  tests/gold_tests/ip_allow/replays/h3.replay.yaml
Labels: HTTP/3

#10154 Fix Throttler initialization.
  include/tscore/Throttler.h
Labels: Core

#10165 Remove Http3NoError allocations
  proxy/http3/Http3App.cc
  proxy/http3/Http3FrameCollector.cc
  proxy/http3/Http3FrameDispatcher.cc
  proxy/http3/Http3HeaderVIOAdaptor.cc
  proxy/http3/Http3ProtocolEnforcer.cc
  proxy/http3/Http3StreamDataVIOAdaptor.cc
  proxy/http3/Http3Types.h
  proxy/http3/test/Mock.h
  proxy/http3/test/test_Http3FrameDispatcher.cc
Labels: HTTP/3

#10169 cmake: add check for clock_gettime
  CMakeLists.txt
  include/tscore/ink_config.h.cmake.in
Labels: CMake

#9975 Clean up certifier plugin debug messages.
  plugins/certifier/certifier.cc
  tests/gold_tests/pluginTest/certifier/certifier.test.py
Labels: Cleanup, certifier

#10170 cache_range test performance improvement
  tests/gold_tests/pluginTest/cache_range_requests/cache_range_requests_cache_complete_responses.test.py
Labels: AuTest

#10146 Unrequire remap rules for OCSP
  include/ts/experimental.h
  iocore/net/I_NetVConnection.h
  iocore/net/OCSPStapling.cc
  proxy/http/HttpSM.cc
  src/traffic_server/FetchSM.cc
Labels: TLS, TS API

#10181 mgmt: make libconfigmanager a true static library
  mgmt/config/Makefile.am
  mgmt/rpc/Makefile.am
  src/traffic_server/Makefile.inc
Labels: Build

#10182 ink_ink_get_hrtime -> ink_get_hrtime
  iocore/aio/P_AIO.h
  src/records/test_RecProcess.i
Labels: Cleanup

#10185 test_QUICLossDetector.cc: Add back get_hrtime()
  iocore/net/quic/test/test_QUICLossDetector.cc
Labels: Core, Cleanup

#10180 clang-analyzer fixes for clang14 (#10055)
  iocore/net/NetEvent.h
  iocore/net/P_QUICNetVConnection.h
  iocore/net/P_SSLNetVConnection.h
  iocore/net/P_UnixNetVConnection.h
  iocore/net/QUICNetProcessor.cc
  iocore/net/QUICNetVConnection.cc
  iocore/net/SSLNetVConnection.cc
  iocore/net/UnixNet.cc
  iocore/net/UnixNetVConnection.cc
  proxy/http/HttpSM.cc
  src/tscore/ArgParser.cc
  src/tscore/Layout.cc
Labels: Backport

#10176 Strictly follow Content-Length header ABNF rule (#10144)
  proxy/hdrs/HTTP.cc
  proxy/hdrs/unit_tests/test_Hdrs.cc
Labels: Backport

#10173 Remove autoconf headers during CMake configuration
  CMakeLists.txt
Labels: Build, CMake

#10184 Check SNI in h3
  proxy/http3/Http3SessionAccept.cc
  tests/gold_tests/h3/h3_sni_check.test.py
  tests/gold_tests/h3/replays/h3_sni.replay.yaml
Labels: HTTP/3

#10172 Makes cmake build again, on macOS
  tests/tools/plugins/CMakeLists.txt
Labels: Tests, CMake

#10155 libswoc: Update to 1.5.4
  lib/swoc/CMakeLists.txt
  lib/swoc/Makefile.am
  lib/swoc/include/swoc/BufferWriter.h
  lib/swoc/include/swoc/bwf_base.h
  lib/swoc/include/swoc/bwf_ex.h
  lib/swoc/include/swoc/bwf_std.h
  lib/swoc/include/swoc/swoc_meta.h
  lib/swoc/include/swoc/swoc_version.h
  lib/swoc/src/Errata.cc
  lib/swoc/src/bw_format.cc
Labels: CPP API, CPP Util

#10111 Remove cqtx log field
  configs/logging.yaml.default
  doc/admin-guide/files/logging.yaml.en.rst
  doc/admin-guide/logging/examples.en.rst
  doc/admin-guide/logging/formatting.en.rst
  doc/appendices/faq.en.rst
  doc/locale/ja/LC_MESSAGES/admin-guide/monitoring/logging/log-formats.en.po
  doc/locale/ja/LC_MESSAGES/appendices/faq.en.po
  doc/release-notes/upgrading.en.rst
  proxy/logging/Log.cc
  tests/gold_tests/connect/connect.test.py
  tests/gold_tests/connect/gold/connect_access.gold
  tests/gold_tests/h2/gold/httpbin_access.gold
  tests/gold_tests/h2/httpbin.test.py
Labels: Documentation, Incompatible, Deprecated

#10161 LSan: Fix memory leak of test_X509HostnameValidator
  src/tscore/unit_tests/test_X509HostnameValidator.cc
Labels: ASan

#10178 LSan: Fix memory leak of test_EventSystem
  iocore/eventsystem/unit_tests/test_EventSystem.cc
Labels: ASan

#10179 LSan: Fix leak of test_Metrics
  include/api/Metrics.h
Labels: ASan

#10126 Correctly handle encoding for cache hash generation
  proxy/hdrs/URL.cc
  proxy/hdrs/unit_tests/test_URL.cc
  tests/gold_tests/url/uri.replay.yaml
  tests/gold_tests/url/uri.test.py
Labels: Cache, HTTP

#10190 Fix editor config for makefiles.
  .editorconfig
Labels: Tools

#10188 Fixes a problem which can decrement milestone metrics unintentionally
  proxy/Milestones.h
  proxy/http/HttpTransact.cc
Labels: Metrics

#10237 Make OSX and FreeBSD not required temporarily
  .asf.yaml
Labels: CI

#10189 Fixing TSHttpTxnServerAddrSet
  proxy/http/HttpSM.cc
  proxy/http/HttpTransact.cc
  tests/gold_tests/pluginTest/tsapi/CMakeLists.txt
  tests/gold_tests/pluginTest/tsapi/Makefile.inc
  tests/gold_tests/pluginTest/tsapi/test_TSHttpTxnServerAddrSet.cc
  tests/gold_tests/pluginTest/tsapi/test_TSHttpTxnServerAddrSet.replay.yaml
  tests/gold_tests/pluginTest/tsapi/test_TSHttpTxnServerAddrSet.test.py
Labels: HostDB, TS API

#10115 TLS early data: logging updates
  iocore/net/P_SNIActionPerformer.h
  iocore/net/P_SSLNetVConnection.h
  iocore/net/SSLNetVConnection.cc
Labels: TLS

#10236 fall back to configure file for older cmake versions
  cmake/install_configs.cmake
Labels: CMake

#10245 Coverity 1508984: Dereference null return value
  tests/tools/plugins/async_engine.c
Labels: Coverity

#10247 Python 3.12: microserver.test.ext wrap_socket update
  tests/gold_tests/autest-site/microserver.test.ext
Labels: AuTest

#10248 Revert "Make OSX and FreeBSD not required temporarily (#10237)"
  .asf.yaml
Labels: Build

#10250 This dependency is not needed, cmake did it right
  src/traffic_crashlog/Makefile.inc
Labels: Build, Cleanup

#10249 Upgrade yaml-cpp version to 0.8.0
  doc/developer-guide/api/functions/TSRPCRegister.en.rst
  doc/developer-guide/jsonrpc/jsonrpc-handler-development.en.rst
  lib/yamlcpp/BUILD.bazel
  lib/yamlcpp/CMakeLists.txt
  lib/yamlcpp/CONTRIBUTING.md
  lib/yamlcpp/README.md
  lib/yamlcpp/SECURITY.md
  lib/yamlcpp/appveyor.yml
  lib/yamlcpp/cmake_uninstall.cmake.in
  lib/yamlcpp/include/yaml-cpp/dll.h
  lib/yamlcpp/include/yaml-cpp/exceptions.h
  lib/yamlcpp/include/yaml-cpp/node/convert.h
  lib/yamlcpp/include/yaml-cpp/node/detail/node.h
  lib/yamlcpp/include/yaml-cpp/node/impl.h
  lib/yamlcpp/include/yaml-cpp/node/iterator.h
  lib/yamlcpp/include/yaml-cpp/node/ptr.h
  lib/yamlcpp/include/yaml-cpp/traits.h
  lib/yamlcpp/src/binary.cpp
  lib/yamlcpp/src/contrib/graphbuilderadapter.h
  lib/yamlcpp/src/directives.cpp
  lib/yamlcpp/src/directives.h
  lib/yamlcpp/src/emitter.cpp
  lib/yamlcpp/src/emitterutils.cpp
  lib/yamlcpp/src/exp.h
  lib/yamlcpp/src/node_data.cpp
  lib/yamlcpp/src/scanner.h
  lib/yamlcpp/src/singledocparser.cpp
  lib/yamlcpp/src/tag.cpp
  lib/yamlcpp/src/tag.h
  lib/yamlcpp/test/CMakeLists.txt
  lib/yamlcpp/test/binary_test.cpp
  lib/yamlcpp/test/create-emitter-tests.py
  lib/yamlcpp/test/integration/emitter_test.cpp
  lib/yamlcpp/test/integration/error_messages_test.cpp
  lib/yamlcpp/test/integration/load_node_test.cpp
  lib/yamlcpp/test/node/node_test.cpp
  lib/yamlcpp/util/parse.cpp
  lib/yamlcpp/yaml-cpp-config.cmake.in
  lib/yamlcpp/yaml-cpp.pc.in
  m4/yaml-cpp.m4
  tests/gold_tests/jsonrpc/plugins/jsonrpc_plugin_handler_test.cc
  tools/git/pre-commit
Labels: YAML

#10211 Add example subdir to cmake enabled with 'ENABLE_EXAMPLE' cmake option
  CMakeLists.txt
  cmake/add_atsplugin.cmake
  example/CMakeLists.txt
  example/plugins/CMakeLists.txt
  example/plugins/c-api/CMakeLists.txt
  plugins/CMakeLists.txt
Labels: CMake

#10212 Coverity 1518060: Uninitialized scalar variable
  iocore/net/UnixUDPNet.cc
Labels: Coverity

#10252 cmake out of source doc build support
  CMakeLists.txt
  doc/CMakeLists.txt
  doc/conf.cmake.in.py
  doc/ext/local-config.cmake.in.py
  doc/ext/traffic-server.cmake.in.py
  doc/manpages.cmake.in.py
Labels: CMake

#10262 CID 1216305/1497374 regex_revalidate file stat fixes
  plugins/regex_revalidate/regex_revalidate.cc
Labels: Coverity

#10265 CID 1518143: String not null terminated money_trace plugin
  plugins/experimental/money_trace/money_trace.cc
Labels: Coverity

#10266 Python 3.12: add charset-nomalizer to tests/Pipfile
  tests/Pipfile
Labels: AuTest

#10256 Python 3.12: add h2 dependencies to autest Pipfile
  tests/Pipfile
Labels: AuTest

#10272 Check return value of stat()
  plugins/experimental/ssl_session_reuse/src/config.cc
Labels: Plugins

#10270 Update the HTTP/3 library dependencies
  tools/build_h3_tools.sh
Labels: Tools

#10235 remove example/plugins/cpp-api
  configure.ac
  example/plugins/Makefile.am
  example/plugins/cpp-api/Makefile.am
  example/plugins/cpp-api/async_http_fetch/AsyncHttpFetch.cc
  example/plugins/cpp-api/async_http_fetch_streaming/AsyncHttpFetchStreaming.cc
  example/plugins/cpp-api/async_timer/AsyncTimer.cc
  example/plugins/cpp-api/boom/README.txt
  example/plugins/cpp-api/boom/boom.cc
  example/plugins/cpp-api/clientredirect/ClientRedirect.cc
  example/plugins/cpp-api/clientrequest/ClientRequest.cc
  example/plugins/cpp-api/custom_error_remap_plugin/CustomErrorRemapPlugin.cc
  example/plugins/cpp-api/customresponse/CustomResponse.cc
  example/plugins/cpp-api/delay_transformation_plugin/DelayTransformationPlugin.cc
  example/plugins/cpp-api/globalhook/GlobalHookPlugin.cc
  example/plugins/cpp-api/gzip_transformation/GzipTransformationPlugin.cc
  example/plugins/cpp-api/helloworld/HelloWorldPlugin.cc
  example/plugins/cpp-api/intercept/intercept.cc
  example/plugins/cpp-api/internal_transaction_handling/InternalTransactionHandling.cc
  example/plugins/cpp-api/logger_example/LoggerExample.cc
  example/plugins/cpp-api/multiple_transaction_hooks/MultipleTransactionHookPlugins.cc
  example/plugins/cpp-api/null_transformation_plugin/NullTransformationPlugin.cc
  example/plugins/cpp-api/post_buffer/PostBuffer.cc
  example/plugins/cpp-api/remap_plugin/RemapPlugin.cc
  example/plugins/cpp-api/serverresponse/ServerResponse.cc
  example/plugins/cpp-api/stat_example/StatExample.cc
  example/plugins/cpp-api/timeout_example/TimeoutExamplePlugin.cc
  example/plugins/cpp-api/transactionhook/TransactionHookPlugin.cc
  example/plugins/cpp-api/websocket/README.txt
  example/plugins/cpp-api/websocket/WSBuffer.cc
  example/plugins/cpp-api/websocket/WSBuffer.h
  example/plugins/cpp-api/websocket/WebSocket.cc
  example/plugins/cpp-api/websocket/WebSocket.h
Labels: Cleanup

#10275 Fix CID 1508992, 1508976, 1508972: uninitialized scalar variables
  plugins/lua/ts_lua_crypto.cc
Labels: Plugins, Lua, Coverity

#10282 Fix CID 1508970: Uninitialized scalar variable
  plugins/lua/ts_lua.cc
Labels: Plugins, Lua, Coverity

#10281 Fix CID 1508979: unchecked return value
  plugins/lua/ts_lua_util.cc
Labels: Plugins, Lua, Coverity

#10274 build_h3_tools: explicitly chmod the destination directory
  tools/build_h3_tools.sh
Labels: Tools

#10292 tools/jtest: use @SWOC_LIBS@
  tools/Makefile.am
Labels: Build

#10293 Fix missing virtual destructor.
  include/records/I_RecDefs.h
Labels: Cleanup

#10267 Check the inet_pton return value for IP reputations
  plugins/experimental/rate_limit/ip_reputation.cc
Labels: Coverity

#10277 Initialize variable
  plugins/experimental/ssl_session_reuse/src/publish.cc
Labels: Plugins, Coverity

#10278 Suppress coverity false positive on race condition
  plugins/experimental/ssl_session_reuse/src/publish.cc
Labels: Plugins, Coverity

#10289 replace net_config_poll_timeout with EThread::default_wait_interval_ms
  iocore/aio/AIO.cc
  iocore/aio/test_AIO.cc
  iocore/eventsystem/I_EThread.h
  iocore/eventsystem/I_SocketManager.h
  iocore/eventsystem/UnixEThread.cc
  iocore/net/I_Net.h
  iocore/net/Net.cc
  iocore/net/PollCont.cc
  iocore/net/PollCont.h
  iocore/net/UnixUDPNet.cc
  iocore/net/test_I_UDPNet.cc
  src/traffic_quic/traffic_quic.cc
  src/traffic_server/traffic_server.cc
Labels: Cleanup

#10288 untangle fds_limit global
  include/tscore/ink_sys_control.h
  iocore/net/P_UnixNet.h
  iocore/net/UnixNet.cc
  proxy/logging/LogStandalone.cc
  src/records/CMakeLists.txt
  src/traffic_server/traffic_server.cc
  src/tscore/ink_sys_control.cc
Labels: Cleanup

#10259 Add version range up to CMake 3.27
  CMakeLists.txt
Labels: CMake

#10294 Fix connect failure count
  proxy/http/HttpSM.cc
Labels: Core

#10269 remove deprecated 'NATIVE' AIO mode
  CMakeLists.txt
  configure.ac
  doc/developer-guide/testing/blackbox-testing.en.rst
  include/tscore/ink_config.h.cmake.in
  include/tscore/ink_config.h.in
  iocore/aio/AIO.cc
  iocore/aio/I_AIO.h
  iocore/aio/P_AIO.h
  iocore/aio/test_AIO.cc
  iocore/cache/Cache.cc
  src/traffic_layout/info.cc
  src/traffic_server/CMakeLists.txt
  src/traffic_server/InkAPI.cc
  tests/README.md
Labels: Cleanup

#10253 Make remap API compatibility checks consistent.
  example/plugins/c-api/remap/remap.cc
  include/ts/Makefile.am
  include/ts/remap_version.h
  plugins/background_fetch/background_fetch.cc
  plugins/cache_promote/cache_promote.cc
  plugins/cache_range_requests/cache_range_requests.cc
  plugins/compress/compress.cc
  plugins/experimental/cache_fill/cache_fill.cc
  plugins/experimental/fq_pacing/fq_pacing.cc
  plugins/experimental/geoip_acl/geoip_acl.cc
  plugins/experimental/maxmind_acl/maxmind_acl.cc
  plugins/experimental/money_trace/money_trace.cc
  plugins/experimental/parent_select/parent_select.cc
  plugins/experimental/rate_limit/rate_limit.cc
  plugins/experimental/uri_signing/uri_signing.cc
  plugins/experimental/url_sig/url_sig.cc
  plugins/header_rewrite/header_rewrite.cc
  plugins/regex_remap/regex_remap.cc
  plugins/s3_auth/s3_auth.cc
  tests/gold_tests/pluginTest/tsapi/test_tsapi.cc
  tests/tools/plugins/user_args.cc
Labels: Plugins, Coverity

#10260 CID 1508887 fix parent_select plugin stat Time of check.
  plugins/experimental/parent_select/consistenthash_config.cc
Labels: Cleanup, Coverity

#10287 Fix a crash due to bad disks
  iocore/cache/CacheRead.cc
Labels: Cache, Crash

#10309 Remove in_addr forward declaration from experimental.h.
  include/ts/experimental.h
Labels: TS API

#9732 Use Dbg() for debug output in both core and plugins.
  example/plugins/c-api/cache_scan/cache_scan.cc
  include/ts/DbgCtl.h
  include/ts/Makefile.am
  include/ts/apidefs.h.in
  include/ts/ts.h
  include/tscore/DbgCtl.h
  include/tscore/Diags.h
  include/tscore/DiagsTypes.h
  include/tscore/Trie.h
  include/tscpp/api/Cleanup.h
  iocore/cache/Cache.cc
  iocore/cache/CacheDir.cc
  iocore/cache/CacheHosting.cc
  iocore/cache/CacheRead.cc
  iocore/cache/CacheWrite.cc
  iocore/dns/DNS.cc
  iocore/dns/P_DNSProcessor.h
  iocore/dns/SplitDNS.cc
  iocore/net/SSLDiags.cc
  iocore/net/SSLUtils.cc
  iocore/net/TLSSessionResumptionSupport.cc
  iocore/net/UnixUDPNet.cc
  plugins/experimental/webp_transform/ImageTransform.cc
  src/traffic_server/InkAPI.cc
  src/tscore/DbgCtl.cc
  src/tscore/Diags.cc
  tests/gold_tests/pluginTest/TSVConnFd/TSVConnFd.cc
  tests/gold_tests/pluginTest/polite_hook_wait/polite_hook_wait.cc
  tests/gold_tests/pluginTest/tsapi/test_tsapi.cc
Labels: Debug

#10246 Fix ip_allow optional methods specification
  proxy/IPAllow.cc
  tests/gold_tests/ip_allow/ip_allow.test.py
  tests/gold_tests/ip_allow/replays/https_multiple_methods.replay.yaml
Labels: YAML

#10283 cmake: add tests for proxy/hdrs
  CMakeLists.txt
  proxy/hdrs/CMakeLists.txt
  proxy/hdrs/Makefile.am
  proxy/hdrs/unit_tests/test_Huffmancode.cc
  proxy/hdrs/unit_tests/unit_test_main.cc
  src/api/CMakeLists.txt
  src/tests/CMakeLists.txt
  src/tscore/CMakeLists.txt
  src/tscpp/util/CMakeLists.txt
Labels: CMake

#10299 setup default install path, runtime user and group
  CMakeLists.txt
  include/tscore/ink_config.h.cmake.in
Labels: CMake

#10301 cmake: add unit tests for proxy/logging
  proxy/logging/CMakeLists.txt
Labels: CMake

#10302 add tests for src/records
  src/records/CMakeLists.txt
Labels: CMake

#10305 Cmake: Add tests in proxy/http proxy/http2
  proxy/http/CMakeLists.txt
  proxy/http2/CMakeLists.txt
  src/tests/CMakeLists.txt
Labels: CMake

#10310 cmake: add tests for proxy/http3
  proxy/http3/CMakeLists.txt
Labels: CMake

#10316 cmake: Add support for building benchmarks
  CMakeLists.txt
  tools/benchmark/CMakeLists.txt
Labels: CMake

#10319 Fix lua plugin build
  plugins/lua/ts_lua_log.cc
Labels: Build

#10322 Update Proxy Verifier to v2.10.1
  tests/prepare_proxy_verifier.sh
  tests/proxy-verifier-version.txt
Labels: AuTest

#10317 Make bad disk detection more robust
  iocore/aio/AIO.cc
  iocore/aio/I_AIO.h
  iocore/aio/P_AIO.h
  iocore/cache/Cache.cc
  iocore/cache/CacheDir.cc
  iocore/cache/CacheDisk.cc
  iocore/cache/CacheVol.cc
  iocore/cache/P_CacheVol.h
Labels: Cache

#10325 Remove test references to DelayTransformation.so
  tests/README.md
  tests/gold_tests/pluginTest/CppDelayTransformation/CppDelayTransformation.test.py
  tests/gold_tests/pluginTest/CppDelayTransformation/body.gold
Labels: Cleanup, AuTest
