Repository apache/trafficserver, pull requests merged in 2024-11, with the labels that each got.

#11837 Enable TLS 1.0 and 1.1 internally
  src/iocore/net/SSLUtils.cc
Labels: TLS

#11815 jsonrpc: Wait for the socket to be ready to read.
  include/shared/rpc/IPCSocketClient.h
  include/shared/rpc/RPCClient.h
  src/shared/rpc/IPCSocketClient.cc
Labels: Bug, JSONRPC Client

#11843 chunked body autests: avoid UUID colision
  tests/gold_tests/chunked_encoding/bad_chunked_encoding.test.py
  tests/gold_tests/chunked_encoding/replays/chunked_trailer_dropped.replay.yaml
  tests/gold_tests/chunked_encoding/replays/chunked_trailer_proxied.replay.yaml
  tests/gold_tests/chunked_encoding/replays/malformed_chunked_header.replay.yaml
Labels: AuTest

#11825 Implement RAII for `PreservationTable`
  src/iocore/cache/PreservationTable.cc
  src/iocore/cache/PreservationTable.h
  src/iocore/cache/StripeSM.cc
  src/iocore/cache/unit_tests/test_Stripe.cc
Labels: Cache, Cleanup

#11856 Add matrix params to the cachekey in the cachekey plugin
  plugins/cachekey/cachekey.cc
  plugins/cachekey/cachekey.h
  plugins/cachekey/configs.cc
  plugins/cachekey/configs.h
  plugins/cachekey/plugin.cc
Labels: cachekey

#11833 Update references in configuration variable implementation
  doc/developer-guide/config-vars.en.rst
Labels: Documentation

#11838 Add a dir-entry setting to volumes.config
  doc/admin-guide/files/volume.config.en.rst
  src/iocore/cache/Cache.cc
  src/iocore/cache/CacheHosting.cc
  src/iocore/cache/CacheProcessor.cc
  src/iocore/cache/P_CacheHosting.h
  src/iocore/cache/Stripe.cc
  src/iocore/cache/Stripe.h
  src/iocore/cache/StripeSM.cc
  src/iocore/cache/StripeSM.h
Labels: Cache, Configuration

#11862 Make proxy.config.http.cache.post_method overridable
  doc/admin-guide/plugins/lua.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  include/proxy/http/HttpConfig.h
  include/proxy/http/HttpTransactHeaders.h
  include/ts/apidefs.h.in
  plugins/lua/ts_lua_http_config.cc
  src/api/InkAPI.cc
  src/api/InkAPITest.cc
  src/proxy/http/HttpConfig.cc
  src/proxy/http/HttpTransact.cc
  src/proxy/http/HttpTransactHeaders.cc
  src/shared/overridable_txn_vars.cc
  tests/gold_tests/cache/cache-request-method.test.py
Labels: Configuration, HTTP

#11863 Adds a HTTP-CNTL condition to header_rewrite
  doc/admin-guide/plugins/header_rewrite.en.rst
  plugins/header_rewrite/conditions.cc
  plugins/header_rewrite/conditions.h
  plugins/header_rewrite/factory.cc
  plugins/header_rewrite/operators.cc
  plugins/header_rewrite/statement.cc
  plugins/header_rewrite/statement.h
Labels: header_rewrite

#11860 Coverity: fix for CID-1550449
  src/tscore/lockfile.cc
Labels: Coverity

#11849 [BoringSSL] Add TLS 1.3 cipher metrics
  src/iocore/net/SSLStats.cc
Labels: TLS, Metrics

#11866 Change the interpretation of cache fragment size
  src/iocore/cache/Cache.cc
  src/iocore/cache/StripeSM.h
Labels: Cache

#11853 Revert "First cut at header heap genIDs and new API (#11780)"
  include/proxy/hdrs/HdrHeap.h
  include/ts/ts.h
  src/api/InkAPI.cc
  src/proxy/hdrs/HdrHeap.cc
Labels: Cache

#11865 Adds a fragment-size= option to volume.config
  doc/admin-guide/files/volume.config.en.rst
  src/iocore/cache/Cache.cc
  src/iocore/cache/CacheHosting.cc
  src/iocore/cache/CacheProcessor.cc
  src/iocore/cache/CacheWrite.cc
  src/iocore/cache/P_CacheHosting.h
  src/iocore/cache/Stripe.cc
  src/iocore/cache/Stripe.h
  src/iocore/cache/StripeSM.cc
  src/iocore/cache/StripeSM.h
Labels: Cache, Configuration

#11840 Fix setting TLS groups with BoringSSL
  src/iocore/net/SSLUtils.cc
Labels: TLS

#11864 s3_auth does not retry after a file read error
  doc/admin-guide/plugins/origin_server_auth.en.rst
  plugins/origin_server_auth/origin_server_auth.cc
Labels: s3_auth, origin_server_auth

#11867 Coverity: Fix for CID-1550441
  src/iocore/net/SNIActionPerformer.cc
Labels: Coverity

#11877 Coverity: Fix for CID-1523671
  plugins/esi/test/utils_test.cc
Labels: Coverity

#11876 Coverity: Fix for CID-1528689
  src/traffic_ctl/CtrlPrinters.cc
Labels: Coverity, traffic_ctl

#11870 Coverity: Fixes for CID-1544449, CID-1497428 and CID-1497258
  src/proxy/http/remap/unit-tests/nexthop_test_stubs.cc
  src/tscore/Diags.cc
Labels: Coverity

#11848 Have dummy_forced_read only if it's used
  src/tscore/ink_queue.cc
Labels: Build

#11850 Don't call getsockname on every packet
  src/iocore/net/UnixUDPNet.cc
Labels: UDP

#11879 Coverity: Several Overflowed integer argument fixes
  src/proxy/logging/Log.cc
  src/traffic_logcat/logcat.cc
  src/tscore/MatcherUtils.cc
Labels: Coverity

#11868 Coverity: Fix fox CID-1550411
  include/tscore/ink_file.h
  src/tscore/ink_file.cc
Labels: Coverity
