Repository apache/trafficserver, pull requests merged in 2024-08, with the labels that each got.

#11583 remap_action_to_add: helper script for new ACL actions
  tests/tools_tests/test_convert_remap_actions_to_10x
  tools/remap/convert_remap_actions_to_10x
Labels: Tools, Remap

#11637 Reduce the number of checks for BoringSSL
  CMakeLists.txt
  include/tscore/ink_config.h.cmake.in
  src/iocore/net/OCSPStapling.cc
  src/iocore/net/P_OCSPStapling.h
  src/iocore/net/SSLUtils.cc
Labels: TLS, Cleanup

#11584 Allow `UnixNetVConnection` to be closed anytime
  src/iocore/net/CMakeLists.txt
  src/iocore/net/UnixNetVConnection.cc
  src/iocore/net/unit_tests/test_Net.cc
Labels: Network, Tests, Cleanup

#11628 Extract `PreservationTable` from `StripeSM`
  doc/developer-guide/cache-architecture/architecture.en.rst
  doc/developer-guide/cache-architecture/data-structures.en.rst
  src/iocore/cache/CMakeLists.txt
  src/iocore/cache/CacheDir.cc
  src/iocore/cache/CacheEvacuateDocVC.cc
  src/iocore/cache/P_CacheDir.h
  src/iocore/cache/P_CacheVol.h
  src/iocore/cache/PreservationTable.cc
  src/iocore/cache/PreservationTable.h
  src/iocore/cache/Stripe.h
  src/iocore/cache/StripeSM.cc
Labels: Cache, Cleanup, Documentation

#11612 prefetch autests: await log file content
  tests/gold_tests/autest-site/when.test.ext
  tests/gold_tests/pluginTest/prefetch/prefetch_bignum.test.py
  tests/gold_tests/pluginTest/prefetch/prefetch_cmcd.test.py
  tests/gold_tests/pluginTest/prefetch/prefetch_overflow.test.py
  tests/gold_tests/pluginTest/prefetch/prefetch_simple.test.py
Labels: AuTest, prefetch

#11635 ACL filter action documentation updates
  configs/records.yaml.default.in
  doc/admin-guide/files/ip_allow.yaml.en.rst
  doc/admin-guide/files/records.yaml.en.rst
  doc/admin-guide/files/remap.config.en.rst
  include/proxy/http/remap/RemapConfig.h
  include/proxy/http/remap/UrlRewrite.h
  src/proxy/IPAllow.cc
  src/proxy/http/remap/RemapConfig.cc
  src/proxy/http/remap/UrlRewrite.cc
  src/records/RecordsConfig.cc
  tests/gold_tests/ip_allow/ip_category.test.py
  tests/gold_tests/remap/all_acl_combinations.py
  tests/gold_tests/remap/deactivate_ip_allow.py
  tests/gold_tests/remap/remap_acl.test.py
Labels: Documentation

#11551 Cleanup of header_rewrite redirect operator when invoked globally.
  doc/admin-guide/plugins/header_rewrite.en.rst
  plugins/header_rewrite/operators.cc
  plugins/header_rewrite/operators.h
  tests/gold_tests/pluginTest/header_rewrite/gold/set-redirect-glob.gold
  tests/gold_tests/pluginTest/header_rewrite/header_rewrite_url_glob.test.py
  tests/gold_tests/pluginTest/header_rewrite/rules/glob_set_redirect.conf
Labels: Cleanup, header_rewrite

#11624 Remove TSUrlHttpParamsGet/Set and their internal implementation
  include/proxy/hdrs/HTTP.h
  include/proxy/hdrs/URL.h
  include/ts/ts.h
  src/api/InkAPI.cc
  src/api/InkAPITest.cc
  src/proxy/hdrs/URL.cc
  src/proxy/hdrs/VersionConverter.cc
  src/proxy/hdrs/unit_tests/test_URL.cc
  src/proxy/http/HttpTransact.cc
Labels: Cleanup, TS API, Incompatible

#11644 Add upgrade notes for connection_attempts_timeout changes
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11638 Fix check_build problem with Fuzz tests
  tests/fuzzing/CMakeLists.txt
  tests/fuzzing/fuzz_hpack.cc
  tests/fuzzing/oss-fuzz.sh
Labels: Tests

#11645 Reduce dup code
  include/iocore/net/SSLTypes.h
  include/iocore/net/TLSSNISupport.h
  src/iocore/net/SSLUtils.cc
  src/iocore/net/TLSSNISupport.cc
Labels: TLS, Cleanup

#11643 Reduce the number of checks for BoringSSL
  CMakeLists.txt
  doc/admin-guide/files/records.yaml.en.rst
  include/iocore/net/SSLTypes.h
  include/tscore/ink_config.h.cmake.in
  src/iocore/net/BIO_fastopen.cc
  src/iocore/net/SSLUtils.cc
Labels: TLS, Cleanup

#11648 Docs: Make sure we use the right YAML root name when building records.yaml docs. `ts` -> `records`
  doc/ext/traffic-server.cmake.in.py
Labels: Documentation

#11647 9.2.x: Document 0 for max_conections_in disables it
  doc/admin-guide/files/records.config.en.rst
Labels: Documentation

#11646 Document 0 for max_conections_in disables it
  doc/admin-guide/files/records.yaml.en.rst
Labels: Documentation

#11656 Remove rest of cache inspector references
  doc/admin-guide/interaction/index.en.rst
  doc/admin-guide/storage/index.en.rst
  doc/developer-guide/cache-architecture/consistency.en.rst
  doc/locale/ja/LC_MESSAGES/developer-guide/architecture/consistency.en.po
Labels: Cache, Documentation

#11655 cleanup: Change legacy function name to actually reflect the logic.
  src/proxy/logging/LogStandalone.cc
  src/traffic_server/traffic_server.cc
Labels: Cleanup, easy_review

#11606 Run regression tests for InkAPI
  src/api/CMakeLists.txt
  src/api/InkAPITest.cc
Labels: Build, Tests

#11657 Fixed crash in XPACK when making space for a new entry
  src/proxy/hdrs/XPACK.cc
  src/proxy/hdrs/unit_tests/test_XPACK.cc
Labels: HTTP/2, Crash, QUIC

#11499 multiplexer: fix consume of too many bytes
  plugins/multiplexer/fetcher.h
  src/iocore/eventsystem/P_IOBuffer.h
Labels: Core, multiplexer

#11662 Fix CID 1559183 from Coverity
  src/iocore/cache/StripeSM.cc
Labels: Cache, Coverity

#11661 Fix CID 1559182 from Coverity
  src/iocore/cache/StripeSM.cc
Labels: Cache, Coverity

#11618 Conditional Slicing
  doc/admin-guide/plugins/slice.en.rst
  plugins/cache_range_requests/cache_range_requests.cc
  plugins/slice/CMakeLists.txt
  plugins/slice/Config.cc
  plugins/slice/Config.h
  plugins/slice/ObjectSizeCache.cc
  plugins/slice/ObjectSizeCache.h
  plugins/slice/server.cc
  plugins/slice/slice.cc
  plugins/slice/unit-tests/CMakeLists.txt
  plugins/slice/unit-tests/test_cache.cc
  tests/gold_tests/pluginTest/slice/slice_conditional.test.py
Labels: Plugins, slice

#11669 Fix Fuzz test issue
  tests/fuzzing/fuzz_http3frame.cc
Labels: Tests

#11639 Remove `SocketManager`
  include/iocore/eventsystem/EventSystem.h
  include/iocore/eventsystem/SocketManager.h
  include/iocore/eventsystem/UnixSocket.h
  src/iocore/eventsystem/CMakeLists.txt
  src/iocore/eventsystem/P_EventSystem.h
  src/iocore/eventsystem/P_UnixSocketManager.h
  src/iocore/eventsystem/SocketManager.cc
  src/iocore/eventsystem/unit_tests/test_EventSystem.cc
  src/iocore/hostdb/P_RefCountCache.h
  src/iocore/net/BIO_fastopen.cc
  src/iocore/net/Connection.cc
  src/iocore/net/NetAcceptEventIO.cc
  src/iocore/net/P_Connection.h
  src/iocore/net/P_UDPConnection.h
  src/iocore/net/P_UnixNetVConnection.h
  src/iocore/net/P_UnixUDPConnection.h
  src/iocore/net/QUICNetProcessor.cc
  src/iocore/net/SSLNetVConnection.cc
  src/iocore/net/UDPEventIO.cc
  src/iocore/net/UnixConnection.cc
  src/iocore/net/UnixNetAccept.cc
  src/iocore/net/UnixNetProcessor.cc
  src/iocore/net/UnixNetVConnection.cc
  src/iocore/net/UnixUDPConnection.cc
  src/iocore/net/UnixUDPNet.cc
  src/proxy/http/HttpSessionManager.cc
Labels: Network, Cleanup, Event System

#11665 Fix CID 1523641 - unchecked error return
  src/proxy/http2/unit_tests/test_Http2Frame.cc
Labels: Coverity

#11658 header_rewrite: Allow Txn reenable to be deferred.
  plugins/header_rewrite/header_rewrite.cc
  plugins/header_rewrite/operator.h
  plugins/header_rewrite/operators.cc
  plugins/header_rewrite/operators.h
  plugins/header_rewrite/ruleset.h
Labels: header_rewrite

#11674 Update InkAPITest.cc for new con.sock field
  include/iocore/eventsystem/UnixSocket.h
  src/api/InkAPITest.cc
Labels: Tests, Event System

#11664 Suppress CID 1523641 - dead code in XPACK
  src/proxy/hdrs/XPACK.cc
Labels: Coverity

#11666 CID-1559185: Mute coverity.
  include/shared/rpc/IPCSocketClient.h
  src/shared/rpc/IPCSocketClient.cc
Labels: Coverity

#11650 traffic_ctl: Display `YAML` format when `--records` option is set (instead of the legacy `records.config` style)
  doc/appendices/command-line/traffic_ctl.en.rst
  include/records/RecYAMLDecoder.h
  src/traffic_ctl/CMakeLists.txt
  src/traffic_ctl/CtrlPrinters.cc
  src/traffic_ctl/PrintUtils.cc
  src/traffic_ctl/PrintUtils.h
  src/traffic_ctl/traffic_ctl.cc
Labels: Tools, traffic_ctl

#11636 Create `CacheProcessor.cc` source file
  src/iocore/cache/CMakeLists.txt
  src/iocore/cache/Cache.cc
  src/iocore/cache/CacheProcessor.cc
Labels: Cache, Cleanup

#11672 Add ASF release targets
  CMakeLists.txt
Labels: Build

#11668 Fix a bunch of COPY_INSTEAD_OF_MOVE Coverity CIDs
  plugins/esi/test/vars_test.cc
  plugins/experimental/magick/magick.cc
  plugins/experimental/stek_share/log_store.cc
  plugins/experimental/stek_share/state_machine.h
  plugins/experimental/stek_share/stek_share.cc
  plugins/s3_auth/aws_auth_v4.cc
  plugins/statichit/statichit.cc
  src/iocore/hostdb/P_HostDBProcessor.h
  src/iocore/net/P_SSLCertLookup.h
  src/iocore/net/SSLSNIConfig.cc
  src/iocore/net/SSLSessionCache.cc
  src/iocore/net/SSLSessionCache.h
  src/iocore/net/SSLUtils.cc
  src/iocore/net/YamlSNIConfig.cc
  src/mgmt/rpc/handlers/common/RecordsUtils.cc
  src/proxy/ControlBase.cc
  src/proxy/HostStatus.cc
  src/proxy/http/PreWarmManager.cc
  src/proxy/http/remap/PluginDso.cc
  src/traffic_layout/engine.cc
Labels: Coverity

#11671 Add algorithm to calculate a JA4 fingerprint
  cmake/ExperimentalPlugins.cmake
  plugins/experimental/CMakeLists.txt
  plugins/experimental/ja4_fingerprint/CMakeLists.txt
  plugins/experimental/ja4_fingerprint/ja4.cc
  plugins/experimental/ja4_fingerprint/ja4.h
  plugins/experimental/ja4_fingerprint/test_ja4.cc
  plugins/experimental/ja4_fingerprint/tls_client_hello_summary.cc
Labels: Plugins, ja4_fingerprint

#11678 Fix JA4 TLS version encoding
  plugins/experimental/ja4_fingerprint/ja4.cc
  plugins/experimental/ja4_fingerprint/ja4.h
  plugins/experimental/ja4_fingerprint/test_ja4.cc
Labels: ja4_fingerprint

#11683 Documenting the removal of mysql_remap plugin in upgrading
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11686 Update ATS 10 upgrading documentation
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11679 Upgrade notes: per_server.connection.queue removal
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11681 Update ATS 10 upgrading documentation
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11687 Update ATS 10 upgrading documentation
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11682 Update release docs
  CMakeLists.txt
  doc/developer-guide/release-process/index.en.rst
Labels: Documentation

#11680 Upgrade notes: removal of disable_h2 sni.yaml
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11695 Reduce the default size for http.header_field_max_size
  doc/admin-guide/files/records.yaml.en.rst
  doc/release-notes/upgrading.en.rst
  src/records/RecordsConfig.cc
Labels: Configuration

#11685 add max_open_write_retry_timeout to recordsconfig
  src/records/RecordsConfig.cc
Labels: Configuration

#11696 Upgrade doc additions
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11701 Document JSON-RPC changes.
  doc/release-notes/upgrading.en.rst
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11699 Documentation: Update release notes
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11697 Upgrade Docs: IP Category and filter action docs
  doc/release-notes/upgrading.en.rst
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11706 Revert cache redirect following fix for ATS 10 release
  include/proxy/http/HttpTransact.h
  src/proxy/http/HttpSM.cc
  src/proxy/http/HttpTransact.cc
  tests/gold_tests/redirect/redirect_to_same_origin_on_cache.replay.yaml
  tests/gold_tests/redirect/redirect_to_same_origin_on_cache.test.py
Labels: HttpSM

#11698 Update ATS 10 upgrading documentation
  doc/release-notes/upgrading.en.rst
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11708 Move lua function removal into the plugin section
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11694 Upgrade doc for keepalive_internal_vc setting
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11693 Document upgrade for verify.server.policy default
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11704 Document TSContSchedule related API changes
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11692 Document traffic_ctl monitor command
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11684 Upgrade notes: Removal of mgmt libraries
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11689 Upgrade notes: Document new configs related to hugepages
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11691 Update ATS 10 new features (plugins)
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11702 Document records.yaml changes
  doc/admin-guide/files/records.yaml.en.rst
  doc/admin-guide/files/sni.yaml.en.rst
  doc/admin-guide/performance/index.en.rst
  doc/developer-guide/api/functions/TSSslSession.en.rst
  doc/developer-guide/plugins/hooks-and-transactions/ssl-session-api.en.rst
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11709 Update ATS 10 upgrading documentation
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11711 Documentation updates
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11710 Update ATS 10 new features (http2)
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11707 Fix whats-new links and remove redundant timeout
  doc/release-notes/upgrading.en.rst
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11712 Documentation: updates
  doc/release-notes/upgrading.en.rst
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11715 Document changes for sni.yaml:fqdn:tunnel_route
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11717 Update documentation - hostdb, rate plugin, slice plugin
  doc/release-notes/upgrading.en.rst
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11663 coverity #1550451: Don't invalidate internal data
  include/tsutil/StringConvert.h
Labels: Coverity

#11716 Fix JA4 SNI type determination
  plugins/experimental/ja4_fingerprint/ja4.cc
  plugins/experimental/ja4_fingerprint/ja4.h
  plugins/experimental/ja4_fingerprint/test_ja4.cc
  plugins/experimental/ja4_fingerprint/tls_client_hello_summary.cc
Labels: ja4_fingerprint

#11703 Remove dead private method from `HttpSM`
  include/proxy/http/HttpSM.h
  src/proxy/http/HttpSM.cc
Labels: Cleanup, HttpSM

#11651 Disable mptcp if proper header files are not available
  src/records/RecHttp.cc
Labels: Network, TCP

#11690 Document proxy.config.system_clock setting
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11659 NetHandler - Use the right type to hold `additional_accepts` config value.
  include/iocore/net/NetHandler.h
  src/iocore/net/NetHandler.cc
  src/records/RecordsConfig.cc
Labels: Network, Bug, Records

#11721 Document change of fqdn field (sni.yaml)
  doc/admin-guide/files/sni.yaml.en.rst
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11688 Update ATS 10 upgrading documentation
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11727 release target: Fix tarball so it contains the distribution name
  CMakeLists.txt
Labels: Build

#11626 traffic_ctl: Support command options to enable/disable debug logs at runtime in a single command.
  doc/admin-guide/files/records.yaml.en.rst
  doc/appendices/command-line/traffic_ctl.en.rst
  src/traffic_ctl/CtrlCommands.cc
  src/traffic_ctl/CtrlCommands.h
  src/traffic_ctl/jsonrpc/CtrlRPCRequests.h
  src/traffic_ctl/traffic_ctl.cc
Labels: Configuration, Logging, Tools, Documentation, JSONRPC, traffic_ctl, Records

#11723 QUIC: Fix a bug that ssl_multicert.config is not reloaded for QUIC
  src/iocore/net/SSLClientCoordinator.cc
  src/iocore/net/SSLUtils.cc
Labels: QUIC

#11729 Add `VAR_DEPENDS` feature to auto options
  cmake/AutoOptionHelpers.cmake
Labels: CMake

#11730 RPC: Make sure any internal(not handlers) error gets properly set.
  include/mgmt/rpc/jsonrpc/Defs.h
  src/mgmt/rpc/jsonrpc/JsonRPCManager.cc
Labels: Bug, JSONRPC

#11722 Move `Cache::` methods to Cache.cc
  src/iocore/cache/CMakeLists.txt
  src/iocore/cache/Cache.cc
  src/iocore/cache/CacheRead.cc
  src/iocore/cache/CacheVol.cc
  src/iocore/cache/CacheWrite.cc
Labels: Cache, Cleanup

#11726 Update ATS 10 documenation
  doc/release-notes/whats-new.en.rst
Labels: Documentation

#11728 Update ATS 10 documentation
  doc/release-notes/upgrading.en.rst
Labels: Documentation

#11731 Sever `PreservationTable` inheritance and add utility methods
  src/iocore/cache/CacheEvacuateDocVC.cc
  src/iocore/cache/P_CacheVol.h
  src/iocore/cache/PreservationTable.cc
  src/iocore/cache/PreservationTable.h
  src/iocore/cache/StripeSM.cc
  src/iocore/cache/unit_tests/test_Stripe.cc
Labels: Cache, Cleanup

#11732 Cleanup: StripeSM
  doc/developer-guide/cache-architecture/data-structures.en.rst
  src/iocore/cache/CacheDisk.cc
  src/iocore/cache/CacheEvacuateDocVC.cc
  src/iocore/cache/CacheProcessor.cc
  src/iocore/cache/P_Cache.h
  src/iocore/cache/P_CacheInternal.h
  src/iocore/cache/Stripe.cc
  src/iocore/cache/Stripe.h
  src/iocore/cache/StripeSM.cc
  src/iocore/cache/StripeSM.h
Labels: Cache, Cleanup

#11739 Cleanup: Remove unused dir_ functions
  src/iocore/cache/CacheDir.cc
  src/iocore/cache/P_CacheDir.h
  src/iocore/cache/P_CacheInternal.h
Labels: Cache, Cleanup

#11741 cleanup - remove unused buffer.
  src/mgmt/rpc/server/IPCSocketServer.cc
Labels: Cleanup

#11675 Separate `Server` from `Connection`
  src/iocore/net/CMakeLists.txt
  src/iocore/net/Connection.cc
  src/iocore/net/P_Connection.h
  src/iocore/net/P_NetAccept.h
  src/iocore/net/Server.cc
  src/iocore/net/Server.h
Labels: Network, Cleanup

#11719 Add JA4 plugin
  cmake/ExperimentalPlugins.cmake
  plugins/experimental/ja4_fingerprint/CMakeLists.txt
  plugins/experimental/ja4_fingerprint/README.md
  plugins/experimental/ja4_fingerprint/ja4.h
  plugins/experimental/ja4_fingerprint/plugin.cc
  plugins/experimental/ja4_fingerprint/tls_client_hello_summary.cc
  tests/gold_tests/pluginTest/ja4_fingerprint/ja4_fingerprint.replay.yaml
  tests/gold_tests/pluginTest/ja4_fingerprint/ja4_fingerprint.test.py
Labels: Plugins, ja4_fingerprint

#11735 Cleanup: Move dir_valid macros to Stripe
  src/iocore/cache/CacheDir.cc
  src/iocore/cache/CacheEvacuateDocVC.cc
  src/iocore/cache/CacheRead.cc
  src/iocore/cache/CacheVC.cc
  src/iocore/cache/CacheWrite.cc
  src/iocore/cache/P_CacheDir.h
  src/iocore/cache/Stripe.cc
  src/iocore/cache/Stripe.h
Labels: Cache, Cleanup

#11733 Fix C-style cast in Cache subsystem
  include/iocore/cache/Cache.h
  src/iocore/cache/AggregateWriteBuffer.cc
  src/iocore/cache/Cache.cc
  src/iocore/cache/CacheDir.cc
  src/iocore/cache/CacheDisk.cc
  src/iocore/cache/CacheEvacuateDocVC.cc
  src/iocore/cache/CacheHosting.cc
  src/iocore/cache/CacheHttp.cc
  src/iocore/cache/CacheProcessor.cc
  src/iocore/cache/CacheRead.cc
  src/iocore/cache/CacheTest.cc
  src/iocore/cache/CacheVC.cc
  src/iocore/cache/CacheWrite.cc
  src/iocore/cache/P_CacheDir.h
  src/iocore/cache/P_CacheHosting.h
  src/iocore/cache/P_CacheInternal.h
  src/iocore/cache/P_CacheTest.h
  src/iocore/cache/PreservationTable.cc
  src/iocore/cache/RamCacheCLFUS.cc
  src/iocore/cache/Store.cc
  src/iocore/cache/Stripe.h
  src/iocore/cache/StripeSM.cc
  src/iocore/cache/unit_tests/test_CacheDir.cc
  src/iocore/cache/unit_tests/test_CacheVol.cc
Labels: Cache, Cleanup

#11734 Changes all of Cripts to be in cripts:: namespace
  doc/developer-guide/cripts/cripts-bundles.en.rst
  doc/developer-guide/cripts/cripts-connections.en.rst
  doc/developer-guide/cripts/cripts-crypto.en.rst
  doc/developer-guide/cripts/cripts-headers.en.rst
  doc/developer-guide/cripts/cripts-matcher.en.rst
  doc/developer-guide/cripts/cripts-misc.en.rst
  doc/developer-guide/cripts/cripts-overview.en.rst
  doc/developer-guide/cripts/cripts-urls.en.rst
  doc/developer-guide/cripts/cripts-variables.en.rst
  example/cripts/example1.cc
  include/cripts/Bundle.hpp
  include/cripts/Bundles/Caching.hpp
  include/cripts/Bundles/Common.hpp
  include/cripts/Bundles/Headers.hpp
  include/cripts/Bundles/LogsMetrics.hpp
  include/cripts/Configs.hpp
  include/cripts/ConfigsBase.hpp
  include/cripts/Connections.hpp
  include/cripts/Context.hpp
  include/cripts/Crypto.hpp
  include/cripts/Epilogue.hpp
  include/cripts/Error.hpp
  include/cripts/Files.hpp
  include/cripts/Headers.hpp
  include/cripts/Instance.hpp
  include/cripts/Lulu.hpp
  include/cripts/Matcher.hpp
  include/cripts/Metrics.hpp
  include/cripts/Plugins.hpp
  include/cripts/Preamble.hpp
  include/cripts/Time.hpp
  include/cripts/Transaction.hpp
  include/cripts/UUID.hpp
  include/cripts/Urls.hpp
  src/cripts/Bundles/Caching.cc
  src/cripts/Bundles/Common.cc
  src/cripts/Bundles/HRWBridge.cc
  src/cripts/Bundles/Headers.cc
  src/cripts/Bundles/LogsMetrics.cc
  src/cripts/Configs.cc
  src/cripts/Connections.cc
  src/cripts/Context.cc
  src/cripts/Crypto.cc
  src/cripts/Error.cc
  src/cripts/Files.cc
  src/cripts/Geo.cc
  src/cripts/Headers.cc
  src/cripts/Instance.cc
  src/cripts/Lulu.cc
  src/cripts/Matcher.cc
  src/cripts/Plugins.cc
  src/cripts/UUID.cc
  src/cripts/Urls.cc
  tools/cripts/genconfig.py
Labels: Cripts

#11748 Fix performance issues in cripts::Random
  include/cripts/Lulu.hpp
  src/cripts/Lulu.cc
Labels: Cripts

#11742 Cleanup: Move Stripe initialization to Stripe::_init_data
  src/iocore/cache/Stripe.cc
  src/iocore/cache/Stripe.h
  src/iocore/cache/StripeSM.cc
Labels: Cache, Cleanup

#11752 Fix an infinite loop in Histogram
  include/tsutil/Histogram.h
  src/tscore/unit_tests/test_Histogram.cc
Labels: Metrics, Bug

#11746 Update official release docs
  doc/developer-guide/release-process/index.en.rst
Labels: Documentation
