Repository apache/trafficserver, pull requests merged in 2025-01, with the labels that each got.

#11933 Remove reference to traffic_manager from trafficserver rc file
  rc/trafficserver.in
Labels: Cleanup

#11936 Do not allow extra CRs in chunks
  src/proxy/http/HttpTunnel.cc
  tests/gold_tests/chunked_encoding/bad_chunked_encoding.test.py
  tests/gold_tests/chunked_encoding/replays/malformed_chunked_header.replay.yaml
Labels: HTTP

#11925 [10.0.x] Make warning if remap ACL has more than one @action (#11911)
  src/proxy/http/remap/RemapConfig.cc
Labels: Configuration, remap_acl

#11919 Deduplicate StripeSM evacuate hit window computation
  src/iocore/cache/CacheDir.cc
  src/iocore/cache/Stripe.h
  src/iocore/cache/StripeSM.cc
  src/iocore/cache/StripeSM.h
Labels: Cache, Cleanup

#11939 Turn off ccache for coverity build
  CMakePresets.json
Labels: CMake

#11938 [9.2.x] Backport AuTest fixes for Fedora 40
  build/crypto.m4
  include/tscore/ink_config.h.in
  tests/gold_tests/h2/gold/http2_8_stderr.gold
  tests/gold_tests/h2/gold/http2_8_stdout.gold
  tests/gold_tests/h2/http2.test.py
  tests/gold_tests/pluginTest/compress/compress.gold
  tests/gold_tests/tls/h2_early_decode.py
  tests/gold_tests/tls/ssl_key_dialog.test.py
  tests/gold_tests/tls/test-0rtt-s_client.py
  tests/gold_tests/tls/tls_check_dual_cert_selection.test.py
  tests/gold_tests/tls/tls_check_dual_cert_selection2.test.py
  tests/gold_tests/tls/tls_verify_override_base.test.py
Labels: Build, Backport, AuTest

#11932 Remove Vagrant related files
  Vagrantfile
  contrib/vagrant-setup.sh
  doc/.tx/config
  doc/developer-guide/index.en.rst
  doc/developer-guide/testing-with-vagrant/index.en.rst
  doc/locale/ja/LC_MESSAGES/developer-guide/documentation/building.en.po
  doc/locale/ja/LC_MESSAGES/developer-guide/testing-with-vagrant/index.en.po
Labels: Cleanup

#11924 [9.2.x] Make warning if remap ACL has more than one @action (#11911)
  proxy/http/remap/RemapConfig.cc
Labels: Configuration, remap_acl

#11941 Configure autests to use microserver 1.0.8
  tests/Pipfile
  tests/gold_tests/autest-site/init.cli.ext
Labels: AuTest

#11926 Group directory related `Stripe` fields into struct
  src/iocore/cache/CacheDir.cc
  src/iocore/cache/CacheProcessor.cc
  src/iocore/cache/CacheRead.cc
  src/iocore/cache/CacheVC.cc
  src/iocore/cache/CacheWrite.cc
  src/iocore/cache/P_CacheDir.h
  src/iocore/cache/PreservationTable.cc
  src/iocore/cache/Stripe.cc
  src/iocore/cache/Stripe.h
  src/iocore/cache/StripeSM.cc
  src/iocore/cache/StripeSM.h
  src/iocore/cache/unit_tests/test_CacheDir.cc
  src/iocore/cache/unit_tests/test_Stripe.cc
  src/iocore/cache/unit_tests/test_doubles.h
Labels: Cache, Cleanup

#11944 Cleanup: Remove C-style cast from RemapConfig.cc
  include/proxy/http/remap/RemapConfig.h
  src/proxy/http/remap/RemapConfig.cc
Labels: Cleanup, Remap

#11947 Coverity: Fix several new issues.
  src/traffic_ctl/CtrlPrinters.cc
  src/traffic_ctl/PrintUtils.cc
  src/traffic_ctl/jsonrpc/CtrlRPCRequests.h
Labels: Coverity, traffic_ctl

#11946 Adding more ssl user agent error stats
  doc/admin-guide/monitoring/statistics/core/ssl.en.rst
  src/iocore/net/SSLDiags.cc
  src/iocore/net/SSLStats.cc
  src/iocore/net/SSLStats.h
Labels: Metrics

#11937 Clean up some linter warnings in SSLNetVConnection
  src/api/InkAPI.cc
  src/iocore/net/P_SSLNetVConnection.h
  src/iocore/net/SSLNetVConnection.cc
Labels: Cleanup

#11949 [traffic_crashlog] Log full version info
  src/traffic_crashlog/traffic_crashlog.cc
Labels: traffic_crashlog

#11950 Coverity: Fix for CID-1587277
  plugins/experimental/ja4_fingerprint/ja4.h
Labels: Coverity, ja4_fingerprint

#11955 ci-ubuntu preset: use clang
  CMakePresets.json
Labels: Build, Tools, CMake

#11951 Add unit tests for remap rules. Fix release-assert crasher
  include/proxy/http/remap/RemapConfig.h
  include/proxy/http/remap/UrlRewrite.h
  src/iocore/cache/CMakeLists.txt
  src/iocore/cache/CacheTest.cc
  src/iocore/cache/P_CacheTest.h
  src/iocore/cache/RegressionSM.cc
  src/iocore/cache/RegressionSM.h
  src/proxy/CMakeLists.txt
  src/proxy/http/remap/RemapConfig.cc
  src/proxy/http/remap/unit-tests/CMakeLists.txt
  src/proxy/http/remap/unit-tests/test_RemapRules.cc
Labels: Tests, Crash

#11953 Zero-initialize struct variables in JA4 plugin
  plugins/experimental/ja4_fingerprint/plugin.cc
Labels: ja4_fingerprint

#11908 Coverity. `swoc` Make Name Binding global variables a singleton.
  lib/swoc/include/swoc/bwf_base.h
  lib/swoc/src/bw_format.cc
  lib/swoc/unit_tests/ex_bw_format.cc
  src/proxy/http/HttpProxyServerMain.cc
Labels: Coverity, libswoc

#11956 Fix a test case for malformed chunk header
  tests/gold_tests/chunked_encoding/replays/malformed_chunked_header.replay.yaml
Labels: Tests

#11954 Coverity: Fix for CID 1587263.
  src/iocore/hostdb/test_RefCountCache.cc
Labels: Tests, Coverity

#11959 Fix memory leak when loading remap config
  proxy/http/remap/RemapConfig.cc
Labels: Backport

#11957 Add unit tests for remap rules. Fix release-assert crasher (#11951)
  include/proxy/http/remap/RemapConfig.h
  include/proxy/http/remap/UrlRewrite.h
  src/iocore/cache/CMakeLists.txt
  src/iocore/cache/CacheTest.cc
  src/iocore/cache/P_CacheTest.h
  src/iocore/cache/RegressionSM.cc
  src/iocore/cache/RegressionSM.h
  src/proxy/CMakeLists.txt
  src/proxy/http/remap/RemapConfig.cc
  src/proxy/http/remap/unit-tests/CMakeLists.txt
  src/proxy/http/remap/unit-tests/test_RemapRules.cc
Labels: Backport

#11942 Do not allow extra CRs in chunks (#11936)
  proxy/http/HttpTunnel.cc
  tests/gold_tests/chunked_encoding/bad_chunked_encoding.test.py
  tests/gold_tests/chunked_encoding/replays/malformed_chunked_header.replay.yaml
Labels: HTTP

#11958 libswoc version update: 1.5.13
  lib/swoc/include/swoc/swoc_version.h
Labels: libswoc

#11962 Configure autests to use microserver 1.0.8 (#11941) Update proxy-verifier to 2.12.0 via (#11534)
  tests/Pipfile
  tests/gold_tests/autest-site/init.cli.ext
  tests/prepare_proxy_verifier.sh
  tests/proxy-verifier-version.txt
Labels: Backport, AuTest

#11964 Handle VC_EVENT_EOS in more places (#11368)
  iocore/net/QUICNextProtocolAccept.cc
  iocore/net/SSLNextProtocolAccept.cc
  proxy/http/HttpSM.cc
Labels: Backport

#11966 9.2.x backport autests (#11601) and (#11512)
  tests/gold_tests/cache/cache-control.test.py
  tests/gold_tests/cache/replay/cache-control-s-maxage.replay.yaml
  tests/gold_tests/slow_post/quick_server.py
  tests/gold_tests/slow_post/quick_server.test.py
Labels: Backport, AuTest

#11968 9.2.x backport: chunked body autests: avoid UUID colision (#11843)
  tests/gold_tests/chunked_encoding/bad_chunked_encoding.test.py
  tests/gold_tests/chunked_encoding/replays/chunked_trailer_dropped.replay.yaml
  tests/gold_tests/chunked_encoding/replays/chunked_trailer_proxied.replay.yaml
  tests/gold_tests/chunked_encoding/replays/malformed_chunked_header.replay.yaml
Labels: Backport

#11969 9.2.x backport: tslua.so: handle unrecognized status codes (#11272)
  plugins/lua/ts_lua_client_response.c
  tests/gold_tests/pluginTest/lua/lua_set_error_response.test.py
  tests/gold_tests/pluginTest/lua/set_error_response.lua
  tests/gold_tests/pluginTest/lua/set_error_response.replay.yaml
Labels: Backport

#11971 Use the specified `length` characters of the key in `Headers::count` (#11405)
  src/tscpp/api/Headers.cc
Labels: Backport

#11961 Add nullptr check in PluginVC read and write
  src/proxy/PluginVC.cc
Labels: Crash

#11965 multiplexer: fix consume of too many bytes (#11499)
  iocore/eventsystem/P_IOBuffer.h
  plugins/multiplexer/fetcher.h
Labels: Backport, multiplexer

#11970 handle EOS events during server open (#11346)
  proxy/http/HttpSM.cc
Labels: Backport

#11972 Add nullptr check in PluginVC read and write (#11961)
  proxy/PluginVC.cc
Labels: Backport

#11973 [9.2.x] Add http2.incomplete_header_timeout_in (#11354)
  doc/admin-guide/files/records.config.en.rst
  mgmt/RecordsConfig.cc
  proxy/http2/HTTP2.cc
  proxy/http2/HTTP2.h
  proxy/http2/Http2CommonSession.h
  proxy/http2/Http2ConnectionState.cc
  proxy/http2/Http2Stream.cc
Labels: Backport

#11963 Add support to retrieve request header block to lua plugin (#11893)
  doc/admin-guide/plugins/lua.en.rst
  plugins/lua/ts_lua_client_request.c
Labels: Plugins, Lua, Backport

#11976 Don't assume LogAccess::m_client_req_unmapped_url_canon_str is null t…
  proxy/logging/LogAccess.cc
Labels: Backport

#11978 Codeql updates
  .github/workflows/codeql.yml
Labels: CodeQL

#11979 Add Sphinx documentation for statichit plugin. (#11389)
  doc/admin-guide/plugins/index.en.rst
  doc/admin-guide/plugins/statichit.en.rst
  plugins/experimental/statichit/README.md
  tests/gold_tests/pluginTest/statichit/empty.txt
  tests/gold_tests/pluginTest/statichit/small_body.txt
  tests/gold_tests/pluginTest/statichit/statichit.replay.yaml
  tests/gold_tests/pluginTest/statichit/statichit.test.py
  tests/gold_tests/pluginTest/statichit/story_16.json
Labels: Backport

#11940 Add micro benchmark of EventSystem
  tools/benchmark/CMakeLists.txt
  tools/benchmark/benchmark_EventSystem.cc
Labels: Performance

#11980 Fix linter warnings in InkAPI.cc
  src/api/InkAPI.cc
Labels: Cleanup

#11982 Coverity: Some fixes.
  src/proxy/http/remap/unit-tests/test_NextHopRoundRobin.cc
  src/proxy/http/remap/unit-tests/test_PluginFactory.cc
  src/tscore/unit_tests/test_Ptr.cc
Labels: Coverity

#11986 [compress] Make warning if compress plugin has cache and range-request config
  plugins/compress/configuration.cc
Labels: Configuration, compress

#11996 remove unprotected optional deref Errata::severity
  lib/swoc/include/swoc/Errata.h
Labels: Crash, Bug

#11983 Disable h2 prior knowledge on tls (#11881)
  iocore/net/SSLNetVConnection.cc
  proxy/ProtocolProbeSessionAccept.cc
  tests/gold_tests/tls/test-0rtt-s_client.py
  tests/gold_tests/tls/tls_0rtt_server.test.py
Labels: Backport

#11997 Fix crash by including remap files with named filters
  include/proxy/http/remap/RemapConfig.h
  src/proxy/http/remap/RemapConfig.cc
  src/proxy/http/remap/unit-tests/test_RemapRules.cc
Labels: Configuration, Crash

#11998 Fix crash by including remap files with named filters (#11997)
  proxy/http/remap/RemapConfig.cc
  proxy/http/remap/RemapConfig.h
Labels: Backport

#11999 Add support for parsing Proxy protocol v2 TLV fields
  include/iocore/net/ProxyProtocol.h
  src/iocore/net/ProxyProtocol.cc
  src/iocore/net/unit_tests/test_ProxyProtocol.cc
Labels: PROXY Protocol

#12005 [docs] fix note about updating the ats website
  doc/developer-guide/release-process/index.en.rst
Labels: Documentation
