Repository apache/trafficserver, pull requests merged in 2025-04, with the labels that each got.

#12145 Couple of coverity fixes.
  plugins/compress/configuration.h
  src/iocore/net/Server.cc
Labels: Coverity

#12151 9.2.x: Sphinx 8.x and sphinx-rtd-theme 3.x
  doc/Pipfile
  doc/conf.py
  doc/developer-guide/cache-architecture/architecture.en.rst
Labels: Documentation

#12148 Require the use of CRLF in chunked message body
  doc/admin-guide/files/records.yaml.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  include/proxy/http/HttpConfig.h
  include/proxy/http/HttpTunnel.h
  include/ts/apidefs.h.in
  plugins/lua/ts_lua_http_config.cc
  src/api/InkAPI.cc
  src/api/InkAPITest.cc
  src/proxy/FetchSM.cc
  src/proxy/http/HttpConfig.cc
  src/proxy/http/HttpSM.cc
  src/proxy/http/HttpTunnel.cc
  src/records/RecordsConfig.cc
  src/shared/overridable_txn_vars.cc
  tests/gold_tests/chunked_encoding/replays/malformed_chunked_header.replay.yaml
Labels: HTTP

#12149 Require the use of CRLF in chunked message body
  doc/admin-guide/files/records.yaml.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  include/proxy/http/HttpConfig.h
  include/proxy/http/HttpTunnel.h
  include/ts/apidefs.h.in
  plugins/lua/ts_lua_http_config.cc
  src/api/InkAPI.cc
  src/api/InkAPITest.cc
  src/proxy/FetchSM.cc
  src/proxy/http/HttpConfig.cc
  src/proxy/http/HttpSM.cc
  src/proxy/http/HttpTunnel.cc
  src/records/RecordsConfig.cc
  src/shared/overridable_txn_vars.cc
  tests/gold_tests/chunked_encoding/replays/malformed_chunked_header.replay.yaml
Labels: HTTP

#12150 Require the use of CRLF in chunked message body
  doc/admin-guide/files/records.config.en.rst
  doc/developer-guide/api/functions/TSHttpOverridableConfig.en.rst
  doc/developer-guide/api/types/TSOverridableConfigKey.en.rst
  include/ts/apidefs.h.in
  mgmt/RecordsConfig.cc
  plugins/lua/ts_lua_http_config.c
  proxy/http/HttpConfig.cc
  proxy/http/HttpConfig.h
  proxy/http/HttpSM.cc
  proxy/http/HttpTunnel.cc
  proxy/http/HttpTunnel.h
  src/shared/overridable_txn_vars.cc
  src/traffic_server/FetchSM.cc
  src/traffic_server/InkAPI.cc
  src/traffic_server/InkAPITest.cc
  tests/gold_tests/chunked_encoding/replays/malformed_chunked_header.replay.yaml
Labels: HTTP

#12152 tidy - Fix redundant cast
  src/api/InkAPI.cc
  src/proxy/http/remap/RemapConfig.cc
Labels: Cleanup

#12153 Cleanup - Use C++ style cast instead of the C style. Part 1.
  src/iocore/cache/CacheDir.cc
  src/iocore/cache/CacheWrite.cc
  src/iocore/cache/unit_tests/test_RWW.cc
  src/iocore/dns/DNS.cc
  src/iocore/eventsystem/UnixSocket.cc
  src/iocore/hostdb/HostDB.cc
  src/iocore/net/SSLConfig.cc
  src/iocore/net/SSLNetVConnection.cc
  src/iocore/net/Socks.cc
  src/proxy/hdrs/HdrToken.cc
  src/proxy/http/remap/RemapConfig.cc
Labels: Cleanup

#12160 Update the expired certs for autest ssl_key_dialog
  tests/gold_tests/tls/ssl/passphrase.key
  tests/gold_tests/tls/ssl/passphrase.pem
  tests/gold_tests/tls/ssl/passphrase2.key
  tests/gold_tests/tls/ssl/passphrase2.pem
Labels: AuTest

#12163 GCC 15: Address mismatched-new-delete in MemArena::Block
  lib/swoc/include/swoc/MemArena.h
  lib/swoc/src/MemArena.cc
Labels: Build, libswoc

#12117 Adds a %{LAST-CAPTURE} condition to HRW
  doc/admin-guide/plugins/header_rewrite.en.rst
  plugins/header_rewrite/conditions.cc
  plugins/header_rewrite/conditions.h
  plugins/header_rewrite/factory.cc
  plugins/header_rewrite/lulu.h
  plugins/header_rewrite/matcher.h
  plugins/header_rewrite/regex_helper.cc
  plugins/header_rewrite/regex_helper.h
  plugins/header_rewrite/resources.cc
  plugins/header_rewrite/resources.h
Labels: New Feature, header_rewrite

#12161 build_h3_tools version updates
  tools/build_boringssl_h3_tools.sh
  tools/build_openssl_h3_tools.sh
Labels: Tools

#12165 autest updates for recent curl and nghttp2 versions
  tests/gold_tests/chunked_encoding/chunked_encoding_h2.test.py
  tests/gold_tests/connect/connect.test.py
  tests/gold_tests/connect/gold/connect_0_stderr.gold
  tests/gold_tests/cripts/cripts.test.py
  tests/gold_tests/pluginTest/compress/compress.test.py
  tests/gold_tests/pluginTest/compress/greplog.sh
  tests/gold_tests/pluginTest/polite_hook_wait/polite_hook_wait.test.py
  tests/gold_tests/pluginTest/tsapi/test_TSHttpSsnInfo.test.py
  tests/gold_tests/pluginTest/tsapi/test_TSHttpSsnInfo_nghttp0.gold
  tests/gold_tests/redirect/number_of_redirects.test.py
Labels: AuTest

#12164 -std=c++20: Remove TextView space before _sv/_tv literal
  lib/swoc/include/swoc/TextView.h
Labels: Build

#12146 docs: Update documentation about PPv2 TLV support
  doc/admin-guide/configuration/proxy-protocol.en.rst
Labels: Documentation, PROXY Protocol

#12169 9.2.x: fix libyaml for gcc 15, and cherry-pick fedora:42 updates
  lib/yamlcpp/src/emitterutils.cpp
  tests/gold_tests/chunked_encoding/chunked_encoding_h2.test.py
  tests/gold_tests/connect/connect.test.py
  tests/gold_tests/connect/gold/connect_0_stderr.gold
  tests/gold_tests/pluginTest/compress/compress.test.py
  tests/gold_tests/pluginTest/compress/greplog.sh
  tests/gold_tests/redirect/number_of_redirects.test.py
  tests/gold_tests/tls/ssl/passphrase.key
  tests/gold_tests/tls/ssl/passphrase.pem
  tests/gold_tests/tls/ssl/passphrase2.key
  tests/gold_tests/tls/ssl/passphrase2.pem
Labels: Build, AuTest

#12159 Cleanup - Use C++ style cast instead of the C style. Part 2
  src/api/InkAPITest.cc
  src/api/InkIOCoreAPI.cc
  src/iocore/aio/test_AIO.cc
  src/iocore/cache/CacheHosting.cc
  src/iocore/cache/CacheProcessor.cc
  src/iocore/net/Socks.cc
  src/proxy/Plugin.cc
  src/proxy/hdrs/URL.cc
  src/proxy/hdrs/unit_tests/test_Huffmancode.cc
  src/records/RecConfigParse.cc
Labels: Cleanup

#12156 Support UDS path for prefetch and esi plugin
  plugins/esi/fetcher/HttpDataFetcherImpl.cc
  plugins/esi/fetcher/HttpDataFetcherImpl.h
  plugins/prefetch/fetch.cc
Labels: Plugins, esi, prefetch

#12116 [compress] Fix compressible-status-code config
  plugins/compress/configuration.cc
Labels: compress

#12172 Cleanup - some more clang-tidy recommendation.
  src/iocore/net/P_UnixNet.h
  src/iocore/net/SSLUtils.cc
  src/proxy/http/remap/unit-tests/test_PluginDso.cc
  src/traffic_server/traffic_server.cc
Labels: Cleanup

#12185 OCSP: FetchSM initialization check
  include/proxy/FetchSM.h
  include/proxy/PluginHttpConnect.h
  src/iocore/cache/unit_tests/stub.cc
  src/iocore/net/OCSPStapling.cc
  src/iocore/net/P_OCSPStapling.h
  src/iocore/net/SSLNetProcessor.cc
  src/iocore/net/libinknet_stub.cc
  src/proxy/FetchSM.cc
  src/proxy/PluginHttpConnect.cc
  src/traffic_quic/traffic_quic.cc
Labels: TLS

#12162 Remove misleading log statement
  doc/admin-guide/logging/formatting.en.rst
Labels: Documentation

#12186 Remove unused VIO.op values
  include/iocore/eventsystem/VIO.h
  include/iocore/net/NetVConnection.h
Labels: Cleanup

#12182 Reset HttpCacheSM on following redirect
  include/proxy/http/HttpCacheSM.h
  src/proxy/http/HttpCacheSM.cc
  src/proxy/http/HttpSM.cc
Labels: Cache, Redirect

#12181 Cleanup: Remove unused args from open_read and open_write
  include/iocore/cache/Cache.h
  src/iocore/cache/Cache.cc
  src/iocore/cache/CacheProcessor.cc
  src/iocore/cache/P_CacheInternal.h
  src/iocore/cache/unit_tests/main.cc
  src/proxy/http/HttpCacheSM.cc
Labels: Cache, Cleanup

#12187 Make chunk size parsing more strict
  src/proxy/http/HttpTunnel.cc
  tests/gold_tests/chunked_encoding/replays/malformed_chunked_header.replay.yaml
Labels: HTTP

#12188 remove -k parameter and clear_hostdb command
  include/iocore/hostdb/HostDBProcessor.h
  src/iocore/hostdb/HostDB.cc
  src/traffic_server/traffic_server.cc
Labels: Cleanup

#12189 Cleanup HttpCacheSM & HttpCacheAction
  include/proxy/http/HttpCacheSM.h
  src/proxy/http/HttpCacheSM.cc
  src/proxy/http/remap/unit-tests/nexthop_test_stubs.cc
Labels: Cleanup

#12190 doc: ssl.client.alpn_protocol h22o update
  doc/admin-guide/files/records.yaml.en.rst
Labels: HTTP/2, Documentation

#12194 Remove accept_fn from NetAccept
  src/iocore/net/P_NetAccept.h
  src/iocore/net/QUICNetProcessor.cc
  src/iocore/net/UnixNetAccept.cc
  src/iocore/net/UnixNetProcessor.cc
Labels: Cleanup

#12205 Fix openDirEntry leak
  src/proxy/http/HttpCacheSM.cc
Labels: Cache, HTTP, Leak

#12203 Update dependency comments for building boringssl and openssl for HTTP/3 on Debian
  tools/build_boringssl_h3_tools.sh
  tools/build_openssl_h3_tools.sh
Labels: Tools, HTTP/3

#12147 Take string view arguments in cache processor
  include/iocore/cache/Cache.h
  src/api/InkAPI.cc
  src/iocore/cache/Cache.cc
  src/iocore/cache/CacheHosting.cc
  src/iocore/cache/CacheProcessor.cc
  src/iocore/cache/CacheTest.cc
  src/iocore/cache/CacheVC.cc
  src/iocore/cache/CacheVC.h
  src/iocore/cache/P_CacheHosting.h
  src/iocore/cache/P_CacheInternal.h
  src/mgmt/rpc/handlers/storage/Storage.cc
Labels: Cache, Cleanup

#12183 traffic_ctl - Implement `server status` command option.
  doc/appendices/command-line/traffic_ctl.en.rst
  include/mgmt/rpc/handlers/server/Server.h
  src/mgmt/rpc/handlers/server/Server.cc
  src/traffic_ctl/CtrlCommands.cc
  src/traffic_ctl/CtrlCommands.h
  src/traffic_ctl/CtrlPrinters.cc
  src/traffic_ctl/CtrlPrinters.h
  src/traffic_ctl/jsonrpc/CtrlRPCRequests.h
  src/traffic_ctl/traffic_ctl.cc
  src/traffic_server/RpcAdminPubHandlers.cc
  tests/gold_tests/traffic_ctl/traffic_ctl_config_output.test.py
  tests/gold_tests/traffic_ctl/traffic_ctl_server_output.test.py
  tests/gold_tests/traffic_ctl/traffic_ctl_test_utils.py
Labels: traffic_ctl

#12202 Fix build for clang 20
  include/tscore/CryptoHash.h
  lib/swoc/src/swoc_ip.cc
  src/proxy/HostStatus.cc
Labels: Build

#12200 Fix FreeBSD Raw Cache Disk Support
  src/tscore/ink_file.cc
Labels: Cache, FreeBSD

#12209 Fixes a crash related to connection tracker config callbacks
  src/records/RecCore.cc
Labels: Crash, Bug

#12180 otel build update for GCC 15
  cmake/Findopentelemetry.cmake
Labels: Build, otel_tracer

#12213 Adds new partial string matching to header_rewrite
  doc/admin-guide/plugins/header_rewrite.en.rst
  plugins/header_rewrite/condition.cc
  plugins/header_rewrite/condition.h
  plugins/header_rewrite/matcher.cc
  plugins/header_rewrite/matcher.h
Labels: New Feature, header_rewrite

#12212 Add proxy.config.http.negative_revalidating_list
  doc/admin-guide/files/records.yaml.en.rst
  include/proxy/http/HttpConfig.h
  src/proxy/http/HttpConfig.cc
  src/proxy/http/HttpTransact.cc
  src/records/RecordsConfig.cc
  tests/gold_tests/cache/negative-revalidating.test.py
  tests/gold_tests/cache/replay/negative-revalidating-list.replay.yaml
Labels: Configuration, HTTP, New Feature
